Update tdot.md
w3f/Grants-Program pull request #1079
Opened 2022-07-19 23:34 UTC by shengda

https://github.com/w3f/Grants-Program/pull/872

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

We propose amendment to tDOT grant because we enhance our original architecture design.
* During the implementation, we find it more robust and flexible to introduce the concept of local LP which is generated by individual stable asset pool and aggregate LP which is generated by local LP. tDOT is an aggregate LP. Therefore, we add a milestone for implement stable asset XCM pallet to manages both LPs;
* Minting and redeeming tDOT on host chains requires changes to the stable asset pallet due to change in milestone 1. Therefore, we expand the scope of milestone 2 and 3;
* We remove cross-chain swap from the grant since a cross-chain swap can be seen as a combination of cross-chain mint + redeem. We are going to implement such swap in DApp instead of on pallet;
* We remove cross-chain fee and yield handling from the grant since we have implemented an off-chain fee and yield handing solution. Since this solution is offchain and we have run it successfully on Kusama and Polkadot, we decide to remove them from the grant.

2022-07-19 23:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1079) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1079) it.</sub>

2022-07-25 18:58 UTC, cruikshankss commented
Good day @shengda, thank you for your application. I will look into it as soon as possible.

2022-07-27 08:59 UTC, semuelle requested changes
Thanks for the amendment, @shengda. It sounds as if you are now planning to implement everything in one pallet, instead of several. Is that correct?

2022-07-27 08:59 UTC, semuelle commented on applications/tdot.md
>  - **Total Costs:** 16,000 DAI
If I'm counting correctly, this should now be

```suggestion
- **Total Costs:** 14,000 DAI
```

2022-07-27 12:29 UTC, Noc2 requested changes
I’m happy to approve it, once the total costs are updated.

2022-07-28 07:59 UTC, shengda commented
> 

We will implement it in two pallets.
* Stable asset pallet is the upgraded version from our previous grant. It will be deployed on each parachain that supports stable asset and mints local LP;
* Stable asset XCM pallet manages all cross-chain minting and redemption. It will be deployed on the host chain of the aggregate LP.

2022-07-28 08:27 UTC, semuelle approved these changes
Thanks for the update. Happy to proceed.

2022-07-28 08:58 UTC, Noc2 approved these changes

2022-08-03 17:59 UTC, alxs approved these changes

2022-08-03 19:31 UTC, merged