Add IPFS Utilities application
w3f/Grants-Program pull request #1127
Opened 2022-08-18 08:17 UTC by dobschal

#### Project Abstract

This application is about the utilities of Substrate within IPFS.

Main part of the project is the implementation of a pallet to integrate IPFS into Substrate.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [X] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [X] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-08-18 12:49 UTC, Noc2 requested changes
Thanks for the application. Are you also aware of the following project that worked/work on this?: 

- https://github.com/WunderbarNetwork/substrate/tree/ipfs-ocw 
- https://github.com/dappforce/subsocial-offchain 

And do you have an incentive to maintain it? I would still be happy to jump on a call. See my email.

2022-08-26 11:02 UTC, Noc2 commented
Thanks again for the nice call. Feel free to ping me here, once you updated the application.

2022-08-28 16:28 UTC, dobschal commented
Hey @Noc2, 
thanks for the call. I updated the application. Could you please have a look?

2022-08-29 07:32 UTC, Noc2 submitted a review, later dismissed
Thanks for the update. I’m generally happy to go ahead with it and mark it as ready for review. But maybe you can also add a little bit more technical details to the specification of the deliveries, like the programming language. Also, a medium article or something similar as an additional delivery of milestone 2 would be nice.

2022-08-29 10:20 UTC, alxs commented
Hey @dobschal. Thank you for the application. It's true that `offchain::ipfs` is no longer maintained and I'm not sure there's a fork that currently is. However, your application currently lacks significant details and it's unclear what functionality you will implement. In milestone 1 you describe a "pallet implementation, that allow bytes to uploads"? I suppose you don't mean uploading the files on-chain, so what's the purpose of this pallet? You mention in the overview that "it will need much more affairs to the validation process on the chain side, if the developer wants to make sure and trust the input CID will point to the corresponding file on the chain", but then you don't describe any such functionality. I would ask you to please be much more explicit with the specification, i.e. please describe what API the pallet and OCW will provide, what IPFS functionality the latter will support and any additional features. Here's the original `offchain::ipfs` grant, for comparison: https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/offchain_ipfs.md

I'm also concerned by your labelling of this as a POC. For the amount you're requesting, I would certainly expect a feature-complete implementation. Besides, I'm curious to hear why you don't want to base your project on Equilibrium's original `offchain::ipfs` work. They did great work and the only problem with it that you mention is that it is unmaintained. Substrate has changed a lot since then, so this is probably still a decent amount of effort, but I don't see why you wouldn't want to reuse it or update it rather than starting from scratch.

Lastly, could you add deliverables 0d-e back to the application? These are mandatory as per [the application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#development-roadmap-nut_and_bolt).

2022-08-29 10:21 UTC, alxs requested changes
Hey @dobschal. Thank you for the application. It's true that `offchain::ipfs` is no longer maintained and I'm not sure there's a fork that currently is. However, your application currently lacks significant details and it's unclear what functionality you will implement. In milestone 1 you describe a "pallet implementation, that allow bytes to uploads"? I suppose you don't mean uploading the files on-chain, so what's the purpose of this pallet? You mention in the overview that "it will need much more affairs to the validation process on the chain side, if the developer wants to make sure and trust the input CID will point to the corresponding file on the chain", but then you don't describe any such functionality. I would ask you to please be much more explicit with the specification, i.e. please describe what API the pallet and OCW will provide, what IPFS functionality the latter will support and any additional features. Here's the original `offchain::ipfs` grant, for comparison: https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/offchain_ipfs.md

I'm also concerned by your labelling of this as a POC. For the amount you're requesting, I would certainly expect a feature-complete implementation. Besides, I'm curious to hear why you don't want to base your project on Equilibrium's original `offchain::ipfs` work. They did great work and the only problem with it that you mention is that it is unmaintained. Substrate has changed a lot since then, so this is probably still a decent amount of effort, but I don't see why you wouldn't want to reuse it or update it rather than starting from scratch.

Lastly, could you add deliverables 0d-e back to the application? These are mandatory as per [the application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#development-roadmap-nut_and_bolt).

2022-09-06 09:18 UTC, dobschal commented
Hey @alxs,
thanks for your feedback. We updated the application to contain more details about the features we want to implement. Also added the deliverables 0d-e section. I hope everything looks fine now, if not please let me know :) 

Looking forward to your answer.

2022-09-06 13:41 UTC, Noc2 approved these changes

2022-09-23 16:18 UTC, alxs commented
@dobschal since your proposal has now been in the review state for 2 weeks without any comments from other members of the committee, I'll go ahead and close it. This application may not have succeeded in swaying the committee, but don't be discouraged—you're always welcome to apply again with a revised application or for a different project. Alternatively, you may want to check out other [sources of funding](https://github.com/w3f/Grants-Program#rocket-alternative-funding-sources) in the ecosystem.

2022-09-23 16:18 UTC, closed without merging

2022-09-27 08:44 UTC, dobschal commented
Hey @alxs, 
thanks for your messages. 
We took some more time to check the existing `offchain::ipfs` project and adjusted our application accordingly:
https://github.com/w3f/Grants-Program/pull/1187