Change payment preference for wasm-opt-for-rust
w3f/Grants-Program pull request #1134
Opened 2022-08-21 21:06 UTC by brson

This is a request to change our payment method from aUSD to DOT. We will be submitting a milestone soon, and with the current unresolved aUSD issues would prefer DOT for now.

2022-08-22 07:27 UTC, Noc2 requested changes
Thanks for the PR. However, we don’t pay teams in DOT. Could you alternatively provide an ethereum (DAI, USDT, or ETH) or bitcoin address?

2022-08-22 23:53 UTC, brson commented
@Noc2 I've changed it to DAI on Ethereum.

2022-08-23 12:02 UTC, Noc2 approved these changes
Perfect. Thanks. I will share the amendment with the rest of the committee.

2022-08-23 12:27 UTC, takahser approved these changes

2022-08-23 12:32 UTC, alxs approved these changes

2022-08-23 12:57 UTC, merged