Epirus Substrate Explorer phase 2 application
w3f/Grants-Program pull request #1159
Opened 2022-09-02 17:11 UTC by conor10

#### Project Abstract

This is an application for phase 2 of the Epirus Substrate Explorer grant which was successfully delivered.

The previous grand application is available [here](https://github.com/w3f/Grants-Program/pull/965).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x ] The software delivered for this grant will be released under an open-source license specified in the application.
- [x ] The initial PR contains only one commit (squash and force-push if needed).
- [x ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-09-02 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1159) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1159) it.</sub>

2022-09-03 01:02 UTC, Micassa93 approved these changes

2022-09-05 06:52 UTC, Noc2 requested changes
Thanks for the application. Could you sign the latest version of our terms and conditions? Do you already have some mock-ups for the planned changes to the UI? I will also share your application already internally.

2022-09-05 08:34 UTC, conor10 commented
Hi @Noc2, I've signed the updated CLA.

We haven't designed mockups for this next phase - we were keen to get the application in to keep things moving. We can create mockups, however it will take us a day or two to do.

2022-09-06 13:46 UTC, Noc2 requested changes
Thanks for the quick reply. Given the size of the grant it would be great to have some initial mock-ups or other drafts/designs, doesn’t need to be perfect. Let me know in case this would be difficult for you.

2022-09-07 14:52 UTC, conor10 commented
@Noc2 we've just added mockups and some details on the security front.

2022-09-09 06:29 UTC, Noc2 submitted a review, later dismissed
Thanks for the update. I’m happy to go ahead with it and will share it with the rest of the team.

2022-09-12 12:09 UTC, alxs submitted a review, later dismissed
I missed your first grant and wasn't aware of the project - great work!

2022-09-13 23:03 UTC, gautamdhameja submitted a review, later dismissed

2022-09-20 08:07 UTC, conor10 commented
Hi, are other reviewers looking at this application? There haven't been any updates in the past 6 days — we're ready to get going once we have approval. 🙂

2022-09-20 08:13 UTC, alxs commented
Thanks for pinging us @conor10. I'll share it with the committee again.

2022-09-20 11:36 UTC, laboon submitted a review, later dismissed

2022-09-20 20:36 UTC, takahser requested changes

2022-09-20 20:36 UTC, takahser commented on applications/epirus_substrate_phase_2.md
> +The Metadata Registry is a public service that allows users to upload compressed archives to reproduce the build of their smart contracts.
What compression algorithm are you planning to support here?

2022-09-21 08:02 UTC, mfornos commented
Hi @takahser, 
we just updated the application document in response to your questions.

Summary: 
* We plan to support zip and tgz archive formats
* The public instance is the same but with the added functionality of each milestone

Thank you!

PS: we have noticed that the force push dismissed the previous reviews, hoping it is not a problem. :smile_cat:

2022-09-21 08:40 UTC, takahser approved these changes
Thanks for the update, happy to go ahead with it.

2022-09-21 09:02 UTC, alxs approved these changes

2022-09-21 16:52 UTC, conor10 commented
@Noc2 and @laboon may we request your re-approval following the updates we've made? We're ready to mobilise once we have those approvals through!

2022-09-23 06:42 UTC, laboon approved these changes

2022-09-25 07:47 UTC, Noc2 approved these changes

2022-09-25 07:47 UTC, merged