add polkdadot snap grant application
w3f/Grants-Program pull request #1166
Opened 2022-09-07 06:55 UTC by aaronisme

#### Project Abstract
“Polkadot Snap” will help the Dapp applications open up one of the biggest WEB3.O entrances - MetaMask, where users could continue exploring the Polkadot ecosystem with their familiar MetaMask Wallet.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-09-07 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1166) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1166) it.</sub>

2022-09-07 11:13 UTC, Noc2 requested changes
Thanks a lot for the application. In general, this sounds really interesting, but I have a few comments: 

- Level 2 grants are only up to 30k. Would you be willing to reduce the price accordingly? 
- Deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are usually mandatory for all milestones, and deliverable 0e at least for the last one. 
- Could you reintegrate the table of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) for the milestones and structure it accordingly?

2022-09-09 03:17 UTC, aaronisme commented
@Noc2 Hi David, I have updated the application as you requested

2022-09-09 06:23 UTC, Noc2 requested changes
Thanks for the update. Could you also integrate the list of estimated duration,
FTE and Costs for each milestone? See [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality). Just to make sure we don’t forget anything. And usually the deliveries with a zero are the default deliveries and number 1, etc are the actual technical deliveries of your project. Feel free to integrate things like: “Building the snap application Provider and js sdk which wrap the snap application which provide injected object for the Dapp developer. Writing the documentation for the Dapp developer.” into the deliverable table.

2022-09-13 15:01 UTC, takahser commented on applications/PolkadotSnap.md
> +We will use React, Mobx and Typescript for building this application.Considering Polkadot Snap is not completed yet, we put some samples of our BTCSnap for your reference.
```suggestion
We will use React, Mobx, and Typescript for building this application. Considering Polkadot Snap is not completed yet, we put some samples of our BTCSnap for your reference.
```

2022-09-16 08:01 UTC, takahser commented on applications/PolkadotSnap.md
> +	- FIrst Polkadot Snap: Keystone aims to be the first Polkadot Snap developer and build the first open source Polkadot Snap for the Polkadot ecosystem.
```suggestion
	- First Polkadot Snap: Keystone aims to be the first Polkadot Snap developer and build the first open-source Polkadot Snap for the Polkadot ecosystem.
```

2022-09-16 08:04 UTC, takahser requested changes
@aaronisme thanks for submitting your grant application.
As David [already mentioned](https://github.com/w3f/Grants-Program/pull/1166#pullrequestreview-1101755525), there are some details missing in your deliveries. Could you update them? Let me know if you have any questions.

2022-09-21 10:06 UTC, aaronisme commented
@Noc2 @takahser I have updated the application for all the comments. Please check it.

2022-09-26 08:55 UTC, Noc2 approved these changes
Thanks for the update. Given the background of your team and your previous deliveries, I’m happy to already go ahead with it. But it still would be nice if you could add more technical details to the milestones and specifically the tables of the milestones. For example, what does “ Staking etc.” mean? Could you be more specific?

2022-09-28 03:51 UTC, aaronisme commented
@Noc2 Thanks for the feedback. @juntao Do you think this application is ready to go?

2022-09-28 06:16 UTC, juntao commented
@aaronisme I do not think you meant to tag me in your comment? 😅

2022-09-29 12:23 UTC, Noc2 commented
@aaronisme it would still be nice if you could fix my comments. Afterward, I will ping the rest of the committee again.

2022-10-06 11:23 UTC, Noc2 commented
@aaronisme Btw. let us know if you have any questions. We are still highly interested in this project.

2022-10-10 06:51 UTC, aaronisme commented
@Noc2 @takahser I have updated the application to fix all the comments. Free to let me know if you have any questions. And btw we have already started the work of the milestone one :)

2022-10-10 07:14 UTC, Noc2 submitted a review, later dismissed
Thanks for the update. I'm happy to go ahead with it and share it with the rest of the team.

2022-10-10 10:42 UTC, takahser approved these changes
@aaronisme thanks for the update, happy to go ahead with it as well.

2022-10-11 16:03 UTC, semuelle requested changes
Thanks for the application. I am generally happy to support this. Just two small requests:

2022-10-12 01:19 UTC, aaronisme commented on applications/PolkadotSnap.md
> +* **Project:** Polkadot Snap Made by Keystone Wallet Team
Done

2022-10-12 01:22 UTC, aaronisme commented on applications/PolkadotSnap.md
> +1. Users can use this wallet to manage their assets like DOT/KSM.
In the first release of the application, included in this grant scope, we will only support Polkadot and Kusama. But for future releases, we will support other parachain.

2022-10-12 01:24 UTC, aaronisme commented
@semuelle I have updated the application for your comments and for questions. Free to ping me if any questions.

2022-10-12 12:29 UTC, takahser approved these changes
Re-approving this.

2022-10-12 14:00 UTC, merged

2023-01-12 22:09 UTC, keeganquigley commented
Hi @aaronisme just curious if you have any updates on the milestone progress? Thanks!

2023-02-16 23:44 UTC, keeganquigley commented
Hi @aaronisme friendly reminder, are you still working on this grant?

2023-03-06 03:56 UTC, aaronisme commented
> 
Yes, we are building the snap for the Milestone 1 currently

2023-03-09 22:09 UTC, keeganquigley commented
Thanks @aaronisme if you think it will be significantly delayed, please consider filing an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to extend the timeline. Since milestone 2 will likely be delayed as well. Thanks!

2023-04-17 16:48 UTC, keeganquigley commented
Hi @aaronisme are you able to give us an update on M1?

2023-05-11 19:47 UTC, keeganquigley commented
pinging @aaronisme for a reminder.

2023-05-28 12:10 UTC, Noc2 commented
@aaronisme, any update here, if we don't hear anything from you within the next week, we will probably terminate the grant and try to find another team for the metamask snap integration.

2023-05-30 06:26 UTC, aaronisme commented
@Noc2 @keeganquigley Sorry for the late response. Currently our engineering team are absorb in the firmware of our next gen hardware wallet. We are planning to move this snap into Q4 this year. Hope we can start on Oct.

2023-05-30 07:35 UTC, Noc2 commented
Thanks for the update @aaronisme. In this case, we will cancel the grant for now, and you can potentially reapply at the end of the year.