Add NEFTME to Grants Application
w3f/Grants-Program pull request #1167
Opened 2022-09-08 15:57 UTC by LuisNeves05

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [ ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-09-08 15:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1167) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1167) it.</sub>

2022-09-09 06:34 UTC, Noc2 requested changes
Thanks for your interest in our grants program, but could you take another look at our template as well as [the accepted application](https://github.com/w3f/Grants-Program/tree/master/applications) and update the application accordingly?

2022-09-09 10:21 UTC, LuisNeves05 commented
Hey @Noc2! Just updated the md file! Added some architecture files! Hope you find some clarification! If that is not enough, please let me know!

2022-09-22 10:25 UTC, takahser requested changes
@LuisNeves05 your application still doesn't adhere to the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). Feel free to also have a look at my inline comments I made.

2022-09-22 10:25 UTC, takahser commented on applications/NEFTME.md
> +- **[Level](https://github.com/w3f/Grants-Program/tree/master#level_slider-levels):** 1, 2 or 3
@LuisNeves05 you're supposed to pick one of the levels here (1, 2 or 3)

2022-09-22 10:25 UTC, takahser commented on applications/NEFTME.md
> +![img](https://neftme-test-bucket.s3.eu-west-2.amazonaws.com/Vista_fisica_n2.jpg)
I have a couple of points here:

- I think you meant to write "http" where you wrote "htpp" in the diagram.
- Is there a reason to use http for the integrations between the frontend and publicly accessible APIs (e.g. Instagram API)? I think these should strictly be secured (https) for security reasons.
- I don't really understand what "localhost" indicates here. Is it your server? Or is it the users local machine? Are there multiple localhosts (e.g. for each user) in the overall architecture or just one)?

2022-09-22 10:25 UTC, takahser commented on applications/NEFTME.md
> +Currently, we are EVM based (smart contracts). However, this technical constraint was due to a time urgency and is not final. We simply wanted to deploy our dApp and show the world what we can do!
We currently do not support EVM-based grants, since we're no solidity experts nor do we know their ecosystem well enough to make well-founded decisions, on what would be useful to the community.

2022-09-22 10:25 UTC, takahser commented on applications/NEFTME.md
> +- **Costs:** 65K USD
Please update the milestones to adhere to the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). So mainly you're supposed to copy over the tables and fill them with your own deliverables and additional information, as appropriate.

2022-09-22 13:06 UTC, LuisNeves05 commented on applications/NEFTME.md
> +![img](https://neftme-test-bucket.s3.eu-west-2.amazonaws.com/Vista_fisica_n2.jpg)
The use of http/s was just a standard i learned in university when making these diagrams. But of course we only use http/s, there is no reason to sacrifice safety

2022-09-22 13:07 UTC, LuisNeves05 commented on applications/NEFTME.md
> +![img](https://neftme-test-bucket.s3.eu-west-2.amazonaws.com/Vista_fisica_n2.jpg)
The localhost is just the user's phone

2022-09-22 13:22 UTC, LuisNeves05 commented on applications/NEFTME.md
> +Currently, we are EVM based (smart contracts). However, this technical constraint was due to a time urgency and is not final. We simply wanted to deploy our dApp and show the world what we can do!
As far as i can see, Polkadot supports our smartcontracts, however, that´s not a problem since we look for a chain to support us both technically and financially, so we could be fully integrated on Polkadot if we get a grant

2022-10-05 06:25 UTC, takahser commented on applications/NEFTME.md
> +![img](https://neftme-test-bucket.s3.eu-west-2.amazonaws.com/Vista_fisica_n2.jpg)
> whether in mobile apps or web browser

In that case, it doesn't make sense to me to name it `<<component>> App`, because there are obviously different frontends (web, native app), right?

2022-10-05 06:29 UTC, takahser commented on applications/NEFTME.md
> +- **Total Costs:** Requested amount in USD for the whole project (e.g. 12,000 USD). Note that the acceptance criteria and additional benefits vary depending on the [level](../README.md#level_slider-l
Can you update the **Total Costs** field please?

2022-10-05 06:29 UTC, takahser commented on applications/NEFTME.md
> +We want to integrate with a chain that allows us to grow by giving us technical and financial support. As said above, the EVM integration is not final and can/will be changed.
```suggestion
We want to integrate with a chain that allows us to grow by giving us technical and financial support. As said above, the EVM integration is not final and can/will be changed.
```

In that case, what smart contract language are you planning to use instead?

2022-10-05 06:29 UTC, takahser commented on applications/NEFTME.md
> +Currently, we are EVM based (smart contracts). However, this technical constraint was due to a time urgency and is not final. We simply wanted to deploy our dApp and show the world what we can do!
> to support us both technically

keep in mind that the W3F grants program [doesn't provide hands-on support](https://github.com/w3f/Grants-Program#support), just something to be aware of.

2022-10-05 06:34 UTC, takahser requested changes
@LuisNeves05 I added some more comments, feel free to take a look.

2022-10-05 06:34 UTC, takahser commented on applications/NEFTME.md
> +| 6. | Smart contracts fixes | Fix smart contract bugs and update staking model |
@LuisNeves05 you're still missing the mandatory deliverables, so feel free to add these as well to M1 and M2. Keep in mind that deliverables 0a-0d are [mandatory](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#development-roadmap-nut_and_bolt) for all milestones, and deliverable 0e at least for the last one.

2022-10-08 17:38 UTC, LuisNeves05 commented on applications/NEFTME.md
> +We want to integrate with a chain that allows us to grow by giving us technical and financial support. As said above, the EVM integration is not final and can/will be changed.
Since we outsource our contracts, the language we're going to use will not be a problem. The one thing left to do is to decide, definitely, what blockchain to use and, consequently, what language to use.

2022-10-08 17:41 UTC, LuisNeves05 commented on applications/NEFTME.md
> +![img](https://neftme-test-bucket.s3.eu-west-2.amazonaws.com/Vista_fisica_n2.jpg)
I think i understand where you're coming from. That was just to ilustrate the different apps a user has to have installed on their phone (our app and the external wallet). Going to fix that diagram, thanks

2022-10-10 11:04 UTC, LuisNeves05 commented on applications/NEFTME.md
> +![img](https://neftme-test-bucket.s3.eu-west-2.amazonaws.com/Vista_fisica_n2.jpg)
Also, just to be clear, we're 100% mobile. There are plans to make a web version but that is not in the near future

2022-10-10 11:06 UTC, LuisNeves05 commented
Just read the comments and made some changes @takahser

2022-10-17 13:29 UTC, Noc2 requested changes
Thanks for the update. I have a few additional comments/questions: 

- Your explainer video is no longer available on youtube. 
- Will the entire app (that you can use to create NFTs) be open source? 
- What kind of technology/framework are you using for this? 
- What kind of NFTs will you support? (pallet, ink!, etc.) We usually don’t support evm based projects via our grants program, since it’s not specific to our ecosystem. 
- Could you still add more technical details to the deliverables?
- Deliverables like “Smart contracts fixes” is not something that we support, since it basically could mean anything.

2022-10-17 14:17 UTC, LuisNeves05 commented
> Thanks for the update. I have a few additional comments/questions:
> 
> * Your explainer video is no longer available on youtube.
> * Will the entire app (that you can use to create NFTs) be open source?
> * What kind of technology/framework are you using for this?
> * What kind of NFTs will you support? (pallet, ink!, etc.) We usually don’t support evm based projects via our grants program, since it’s not specific to our ecosystem.
> * Could you still add more technical details to the deliverables?
> * Deliverables like “Smart contracts fixes” is not something that we support, since it basically could mean anything.

2022-10-17 14:43 UTC, LuisNeves05 commented
Hey @Noc2! Accidentally closed the PR, sorry 😅! I answered some of your questions and will be commiting changes to the NEFTME.md file to answer the rest!

> * Your explainer video is no longer available on youtube. 

We had a problem with our youtube account. This is the new link:
https://www.youtube.com/watch?v=tRfG_GCBOyU&t=1s&ab_channel=Jo%C3%A3oDomingos

> * Will the entire app (that you can use to create NFTs) be open source?

Yes, it will be open source

> * What kind of technology/framework are you using for this?

We're using React Native with Expo GO for the frontend and Ruby on Rails for our REST API. That's the main tech stack.

> * What kind of NFTs will you support? (pallet, ink!, etc.) We usually don’t support evm based projects via our grants program, since it’s not specific to our ecosystem.

Following our research, ink! would be the best fit for us, as our NFT smart contracts have specific business rules. 
This is also the part where we are looking for guidance from people in the ecosystem, we want to make a good and user friendly dApp and technical assistance will be crucial to make the best decisions possible

> * Could you still add more technical details to the deliverables?

Will do! 
> * Deliverables like “Smart contracts fixes” is not something that we support, since it basically could mean anything.

Ok, I understand your point! That generalized point is due to the fact that we're revamping our NFT business model (staking) and adding some other features. I'll add them in detail do the deliverables.



Also, if you have not already seen it, we're going to be present in this year's Web Summit! We were selected as an Alpha Startup (program that only accepts 75 aplicants worldwide) and will be pitching and presenting at the event! If someone in your team is planning on going, they should stop by our booth and say hi! We would love to meet in person!

2022-10-20 12:40 UTC, Noc2 requested changes
Thanks again for the update. Could you integrate the technical details into the specification of the deliveries? Also, the kind of NFTs that you are going to support should probably be specified as part of the specification of the deliverables. Once this is done, I will mark the application as ready for review. But be aware, that I’m not sure we should support your app at the moment. Especially your current setup, which we would support with this application, looks like a centralized app with a clear business model.

2022-10-25 15:55 UTC, LuisNeves05 commented
Hey @Noc2! Any news on the process of the application? 
Thanks in advance for you response! :)

2022-10-31 09:13 UTC, Noc2 requested changes
Sorry for the delay here. I have one additional comment before I mark the application as ready for review. The costs of your milestones (35k +65k) currently don’t add up to your total costs (150k).

2022-11-01 18:17 UTC, LuisNeves05 commented
Just updated the NEFTME.md with some details about the values @Noc2

2022-11-02 14:55 UTC, Noc2 requested changes
Thanks for the update. I will mark the application as ready for review. But you should be aware that we usually don’t do any upfront payments. Also, as pointed out before, I personally won’t approve the application, given that you seem to have a clear business model and the application is rather centralized.

2022-11-02 15:01 UTC, LuisNeves05 commented
Hi @Noc2! 
Thanks for the honesty. I get where you're coming from, but once again, I'm asking you to try to see this from an MVP point of view. We built a proof of concept that our testers liked and found easy to use. What we're doing from now on is decentralizing the app as much as we can (as you can see in our milestones) in order to fully give controll to our userbase.
Thank you for your time

2022-11-15 23:55 UTC, LuisNeves05 commented
Hey @Noc2, any news on the application progress? Would love to get some feedback :)

2022-11-16 12:17 UTC, alxs commented
@LuisNeves05 personally, I agree with David's impression and it also looks to me like a lot of the deliverables represent features of your website, and not necessarily work that could be reused by others in the ecosystem.

Since the application has now been in the review state for 2 weeks with no approvals or further comments from other members of the committee, I'll go ahead and close it. This application may not have succeeded in swaying the committee, but don't be discouraged—you're always welcome to apply again with another project, or you can check out other [sources of funding](https://github.com/w3f/Grants-Program#rocket-alternative-funding-sources) in the ecosystem.

2022-11-16 12:17 UTC, closed without merging