leetcoin application
w3f/Grants-Program pull request #1182
Opened 2022-09-23 14:27 UTC by NoirKomBatman

#### Project Abstract

> LeetCoin is the LeetCode for Web3, centered on leveling up dev’s skills.
> We are creating a platform to help enhance technical skills in a gamified and fun way, expand Web3 technical literacy through highly visual smart contract analysis, create online judge engine for Solidity and Vyper contract solutions and create a standard for Web3 technical interviews

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-09-23 14:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1182) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1182) before we can accept your contribution.<br/><hr/>**Bolat** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1182) it.</sub>

2022-09-26 09:38 UTC, Noc2 requested changes
Thanks for the application. Looks like an interesting project. Could you add the default deliverables of the template 0a.- 0d. to the second and third milestones as well? Also, it would be nice if you could mainly focus on the support of ink! Instead of solidity with this grant application. For example regarding: “Implement Solidity Problem Builder, Solution and Compiler”. And feel free to add the programming language/framework also to the specification of the deliverables. This makes it usually easier to understand.

2022-09-29 08:04 UTC, NoirKomBatman commented
hi @Noc2 ,
I have updated the application to focus solely on Ink! contracts. Please let me know if you have any other questions!

2022-09-29 11:46 UTC, Noc2 requested changes
Thanks for the update. I only have two small comments, otherwise, it looks good.

2022-09-29 11:46 UTC, Noc2 commented on applications/leetcoin.md
> +| 7. | First Solidity Problem Set | Develop first 10 Ink! problems working with core teams of popular DeFi protocols
Could you also update this to ink!?

2022-09-29 11:46 UTC, Noc2 commented on applications/leetcoin.md
> +| 3. | Expand Online Judge | Allow for problems written in Solidity, Vyper, Rust and Go by extending compiler                                                                          |
And maybe add ink! here

2022-10-01 12:33 UTC, NoirKomBatman commented
@Noc2 done!

2022-10-03 17:30 UTC, Noc2 approved these changes
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the team.

2022-10-10 16:40 UTC, NoirKomBatman commented
hi @Noc2 ! Any updates from the rest of the team?

2022-10-11 12:48 UTC, Noc2 commented
Sorry for the delay here. I just pinged the rest of the team again.

2022-10-12 13:02 UTC, takahser requested changes
@NoirKomBatman looks mostly good to me, I added a few questions. Feel free to have a look at them.

2022-10-12 17:07 UTC, NoirKomBatman commented on applications/leetcoin.md
> +- **Team Name:** LeetCoin
We took inspiration from GitCoin.co which is a public good platform. Coins and tokens are the first things that come to mind when people think about Web3 and Blockchain and we find the name very sticky :)

2022-10-12 17:08 UTC, NoirKomBatman commented
hey @takahser 
I have done the edits! Please let me know if you need anything else!

2022-10-12 17:11 UTC, NoirKomBatman commented on applications/leetcoin.md
> +LeetCoin is the LeetCode for Web3, centered on leveling up dev’s skills. We are creating a platform to help enhance technical skills in a gamified and fun way, expand Web3 technical literacy through
Smart contract

2022-10-13 13:10 UTC, Noc2 approved these changes

2022-10-13 13:28 UTC, semuelle reviewed
Thanks for the application, @NoirKomBatman. I think this is a useful project, but I have some questions about the setup.

- How are you planning to fund the maintenance of the challenge pool? Will this be funded by ads, or paying customers? Given that Substrate and ink! are currently evolving quite fast, I can see this being quite a lot of work to maintain. 
- Since you mention AWS: will I be able to evaluate (and someone else use) your milestone locally, or will it include a manual on how to set up AWS to host everything (especially the online judge) that's required?

2022-10-13 17:16 UTC, NoirKomBatman commented
> 

Hi @semuelle 
What do you mean by challenge pool? If you mean the problem sets we want to rely on the community similar to how LeetCode does it. We also plan in the future to partner with companies who have a need to hire and vet Web3 talent and they will be able to contribute to the problem sets.

We plan to deploy it on AWS but we are going to provide the documentation on how to set it up on your own. AWS Amplify is very simple and works like Vercel (e.g you connect the Github repo and it deploys the Frontend automatically for you)

2022-10-14 17:51 UTC, semuelle approved these changes
Thanks. Happy to proceed.

2022-10-16 04:22 UTC, NoirKomBatman commented
hi @Noc2 ! Do you have any other questions?

2022-10-16 12:20 UTC, Noc2 commented
@NoirKomBatman No, I already approved it. The application needs one more approval from somebody else. I will ping the rest of the team again.

2022-10-16 22:58 UTC, takahser commented on applications/leetcoin.md
> +- **Team Name:** LeetCoin
Fair enough, thanks for explaining.

2022-10-16 22:58 UTC, takahser approved these changes

2022-10-16 22:59 UTC, merged

2023-01-02 03:07 UTC, NoirKomBatman commented
@Noc2 @semuelle @takahser 

Unfortunately, due to unforeseen circumstances, we have had to postpone the start of the project to January 2023. We understand that this delay may cause some inconvenience and we apologize for any issues this may cause. All the original milestones, as well as their durations and scope, will remain the same. The revised timeline is as follows:
Milestone 1: Complete by Feb 28th, 2023
Milestone 2: Complete by April 15th, 2023
Milestone 3: Complete by  May 31st, 2023

Please rest assured that we are still very excited about this project and are fully committed to seeing it through to completion. We have been working hard to ensure that everything is in place and that we are ready to hit the ground running these next several months. Please let us know if this new timeline still works.

Thank you for your understanding and support. We look forward to getting started on this project and making a positive impact on the ecosystem and helping enable builders.

Sincerely,
LeetCoin Core Team

2023-01-02 09:41 UTC, Noc2 commented
@NoirKomBatman Thanks for the update. Could you create a PR to amend the contract and update the timeline?

2023-01-12 22:26 UTC, keeganquigley commented
Thanks @NoirKomBatman this new timeline shouldn't be a problem, we know that plans can change, but as @Noc2 mentioned we would ask that you submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to change the timeline. It should be relatively easy to get approved by the committee. Then there will be no pressure. Thanks!

2023-02-02 23:14 UTC, keeganquigley commented
Hi @NoirKomBatman I see you are still working on the project which is great, but if you could create an amendment to include the updated timelines that would be great. Then I can update for our records. Thanks!

2023-02-17 00:00 UTC, keeganquigley commented
Hi @NoirKomBatman it's great to see the estimation for milestone 1 completed by the end of Feb. , however could you still submit an amendment for the remaining 2 milestones? Seeing as they will most likely be delayed as well.

2023-02-20 05:00 UTC, NoirKomBatman commented
hi @keeganquigley !

Sorry for the delay! I have submitted an amendment https://github.com/w3f/Grants-Program/pull/1550 with revised completion dates, updated repo URLs, and some minor deliverable changes. I have commented on where the changes are made.

2023-05-11 20:08 UTC, keeganquigley commented
Hi @NoirKomBatman is it possible to get an update on M1?

2023-05-25 21:39 UTC, keeganquigley commented
Hi @NoirKomBatman friendly reminder.

2023-05-26 23:48 UTC, NoirKomBatman commented
Here @keeganquigley 

We have done most of the things for milestone one: 
https://github.com/LeetCoinCo/leetcoin-backend
https://github.com/LeetCoinCo/leetcoin-frontend
https://aliserag.medium.com/introducing-leetcore-leveling-up-web3-hiring-509c92d7ba3

Last things that remain is integration of test suites that we encountered performance issues with.

Because the community wanted to try it out ASAP and we encountered the performance issues with compiling and running test suites in real time on demand, we made another version of the product that utilizes ChatGPT to compile the Rust contracts and receive the feedback from community on it https://app.leetcore.co

https://twitter.com/leetcore_?lang=en

2023-06-27 21:29 UTC, keeganquigley commented
Hi @NoirKomBatman do you plan to submit the delivery soon? If not, I think it might be best to file an amendment PR in order to extend the timeline. Let us know, thanks!

2023-07-13 20:11 UTC, keeganquigley commented
pinging @NoirKomBatman for an update.

2023-07-27 22:25 UTC, keeganquigley commented
Hi @NoirKomBatman are you still working on the grant? I will try emailing you as well.

2023-08-11 19:28 UTC, keeganquigley commented
Hi @NoirKomBatman I think it's best to cancel this grant for now, and it can potentially be re-opened should you wish to continue working on it. If I don't hear from you after two weeks we will go ahead and file a PR for the committee to review. Thanks.