Removing the BTC faucet functionality because BlueWallet does not support the Bitcoin testnet
w3f/Grants-Program pull request #1223
Opened 2022-10-18 17:13 UTC by 3yekn

We need to remove the BTC testnet faucet because of the signer configuration. We provided BTC secrets to the evaluator for use in testing.

2022-10-18 17:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1223) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1223) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1223) it.</sub>

2022-10-19 06:36 UTC, Noc2 approved these changes
Thanks for the update. Sounds good to me. For reference: https://github.com/w3f/Grant-Milestone-Delivery/pull/605

2022-10-19 07:14 UTC, takahser approved these changes

2022-10-19 08:21 UTC, alxs commented
Application PR: https://github.com/w3f/Grants-Program/pull/868

2022-10-19 08:22 UTC, alxs approved these changes

2022-10-19 08:22 UTC, alxs requested changes
This breaks the formatting

2022-10-19 08:22 UTC, alxs commented on applications/native-bitcoin-vaults.md
> +
```suggestion
```

2022-10-19 08:23 UTC, alxs approved these changes

2022-10-19 09:10 UTC, Noc2 approved these changes

2022-10-19 17:01 UTC, semuelle approved these changes

2022-10-19 21:28 UTC, takahser approved these changes

2022-10-24 15:36 UTC, keeganquigley approved these changes

2022-10-24 15:43 UTC, merged