updating team lead and timeline
w3f/Grants-Program pull request #1251
Opened 2022-11-02 21:43 UTC by cwilker

Amending the timeline and team lead for the project. I will be leading the final milestone of this grant and expect to take about 3 months to complete the work. Work will start in December and end in March of 2023.

2022-11-02 21:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1251) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1251) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1251) it.</sub>

2022-11-03 09:24 UTC, Noc2 requested changes
Thanks for the update. Could you also sign the latest version of our Terms and Conditions? (see message above)

2022-11-04 08:49 UTC, Noc2 approved these changes
Thanks for the update.

2022-11-04 09:19 UTC, alxs submitted a review, later dismissed

2022-11-04 10:24 UTC, takahser approved these changes

2022-11-04 10:30 UTC, takahser requested changes
@cwilker could you also add the following information to your application:

- the [level](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md?plain=1#L9) (this seems to have been overlooked when you applied)
- the [name of your project](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md?plain=1#L1) on L1

2022-11-07 09:32 UTC, alxs approved these changes

2022-11-08 08:05 UTC, Noc2 approved these changes

2022-11-08 13:16 UTC, takahser approved these changes

2022-11-08 13:16 UTC, merged