New Grant Proposal: Xcavate - the future of real estate finance & pro…
w3f/Grants-Program pull request #1266
Opened 2022-11-08 13:48 UTC by xcavate2022

- **Project Name:** Xcavate
- **Team Name:** Xcavate
- **Payment Address:** 4pjePvJgUZAMKtnSmYJitGacxBRnsKe1GvCb1t6vgg2Kof8o 
- **Level:** 1 = $10000
- **Total Project Cost** $307200

## Project Overview

This is the initial grant application

### Overview

Xcavate will be a first-of-its-kind real-world land & property NFT that can be collateralized to finance development transactions. 
Xcavate facilitates digitizing land and/or property title deeds through minting and bundling of NFTs, which are then linked to verifiable digital identities (DIDs) approved by government entities.
Xcavate is an ecosystem that allows real-world property developers access to finance parcels of physical land with planning permission for development. Once the land is at the final development stage, the developer will create NFTs for the individual properties to be sold/managed by a peer-to-peer marketplace (property owners, investors, trusts etc.). 
The system will significantly reduce the time from real estate planning permission to build start. By simplifying the finance application process and speeding up the release of funds to the developer.. Xcavate not only provides real-world property developers with a way to build quicker but, as a result, enables a more significant number of much-needed houses to be delivered to market. It also provides liquidity to static real-world assets at every stage of the property development process in a fair and risk-averse way. It will enable the real estate to be onboarded cleanly and efficiently, opening up opportunities throughout the broader Dotsama ecosystem.

![](XCAV-WEB-3-Grant-Application-Image-1.jpg)

![](XCAV-WEB-3-Grant-Application-Image-2.jpg)

![](XCAV-WEB-3-Grant-Application-Image-3.jpg)

### Project Details

We expect the teams to already have a solid idea about your project's expected final state. Therefore, we ask the teams to submit (where relevant):

We will be using an agile methodology for the development of this project. We will use a design to development process to deliver the best user experience. Followed by an engineer's engagement based on approved designs. We will build an agile board open to W3F and partners for complete project transparency.  This will allow everyone involved to see all milestones, roadblocks and added scope in real-time. We will still have weekly updates internally, but this methodology will enable W3F to be in the know at all times. Our organizational goal is to achieve a simplistic way for everyone involved to be in the know at all times. In addition, we would like to set up and maintain the quality of code and delivery to production processes through GitHub that all involved will have access to review. We understand that in pursuit of these objectives, W3F has their standards, and we will always strive to exceed them as partners. We have chosen the below technology stack and already have a significant amount of experience to deliver this project in these technologies. We have also already spent a reasonable amount of time meeting and learning about our partners and their unique technologies.

Xcavate will develop multiple Pallets to execute the functionalities. We will use the substrate framework and primary language Rust to create the pallets on the Polkadot ecosystem.
Token Pallet
Decentralized Identity Document pallet
User Management pallet
Loan Management pallet
Transaction management pallet
Staking pallet
Verification pallet

This Architecture diagram shows the visual representation that maps out the physical implementation for components in the Polkadot ecosystem and how the scalability of the platform works. The diagram represents Microservices we are using to execute the functionality. API gateway will split the API calls to the respective microservices. We are using an s3 bucket to store the media files. We are using pallets to execute the functions on the Polkadot ecosystem.

![](XCAV-WEB-3-Grant-Application-Image-4.jpg)

Token:
XCAV - Platforms Native Token to launch a para chain and participate in a crowd loan/slot auction. XCAV tokens are used to stake within the platform. We will create these tokens with the Transfer, Mint, Burn, Approve, and Allowance functions.
Liquidity Pool:
Xcavate creates a liquidity pool to store staked tokens, staked tokens will be queued and utilized for each loan application. XCAV tokens are swapped as GBPT through XCM and deposited on the Central Loan pool.
Central Loan Pool:
Xcavate Creates a central loan pool to manage Loan amounts and Loan repayment. The central lending pool will act as the heart of the platform to map all the transactions.

### Technology Stack

React.js
Node.js
Express.js
Rust
Substrate Framework
Polkadot

### Third-Party

Kilt – SDK 			Statemint
Chainlink 			Property Data

### Ecosystem Fit

After many months of research, we initially met on a zoom with Ingo from Kilt, discussing our idea and talking through how the Kilt chain can be incorporated into the Xcavate system. A few weeks later, we contacted Acala and met with Robinson, who was very helpful and enthusiastic about us being involved in the ecosystem and our potential partnership. We also reached Centrifuge and spent many weeks looking through their docs with the initial idea of creating a dApp on their chain, but as there were some striking differences in how their chain operated, it was apparent that was not going to be the best fit for our project. Going forward, however, once the real estate has been built, there will be opportunities for us to introduce Centrifuge.

We feel this is a great way to bring land & Property assets into the digital ecosystem to interact with the following potential partners:

**Kilt (Identity & wallet)**
This is a crucial part of the initial process to verify; Real Estate Director, Company & Title Deed and create DID’s, which will be held in a Sporran Wallet and used throughout.
**Chainlink (Oracle)**
To accurately value and risk rate land and the completed real estate, we need to build Oracles that enable off-chain APIs to feed data into an algorithm which delivers the personalized loan APR. In the first phase, we will build a Chainlink Oracle that relies on https://propertydata.co.uk/ for its data.
**Statemint / Acala**
There are many stages of financing that will involve aUSD / USDT / GDPT… from the initial funding pool, a liquidity pool, as well as the need to exchange the locked loan value for each project in GBP stable coins (as our initial market is based in the UK).
**XCM (Crosschain)**
As our user base is only used to the web2.0 space, we will need a seamless front end that hides the complexities of the many transactions below the hood. XCM will be the enabler for this to happen.

## Team :busts_in_silhouette:

### Team members

Richard Houldsworth – CTO 
Alex Ward – COO
Akash Takyar - Management Sponsor
Deepak Shokeen - Chief Engineer
Kapil Saxena - Design Head

### Contact

Richard Houldsworth – +44 7798 666 710 
Alex Ward – +44 7779 885964 
xcavate.io

### Legal Structure

H & W Investments Limited 
17 College Road, Cheshunt EN8 9LS, United Kingdom

### Team's experience

Richard Houldsworth – 10 years in web 2.0 dev space – serial Entrepreneur
Alex Ward – 25 years in the global property market – serial Entrepreneur
Akash Takyar - Akash has a master’s in computer application with a deep understanding of IoT and Blockchain. Akash is a world-renowned expert, blockchain influencer, and technical architect.
Deepak Shokeen - With over 20 years of experience engineering and developing apps. He has a deep understanding of building Cloud, IoT, and Blockchain applications.
Kapil Saxena - Kapil is a design professional with 15+ years of experience in User Experience & User Interface design. Currently, he is leading
the design team at LeewayHertz designing UX and UI for Blockchain Applications, handheld devices, Artificial Intelligence Solutions, and IoT Products.

### Team Code Repos

https://github.com/xcavate2022
https://git [...]

2022-11-08 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1266) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1266) it.</sub>

2022-11-08 17:01 UTC, semuelle commented
Thanks for the application, @xcavate2022. Someone will look into it more closely soon. In the meantime, could you

- sign the CLA,
- host the images elsewhere? We prefer to keep the repo to the documents only. Easiest is to just paste the images into the Github editor.
- Can you remove the application text from the PR and replace it with our filled out [PR template](https://github.com/w3f/Grants-Program/blob/master/.github/pull_request_template.md)?
- What does "Level: 1 = $10000" mean? At 300k, this is a Level 3 grant application.

2022-11-08 17:37 UTC, xcavate2022 commented
Thanks for your comments Sebastian

Can you please clarify where the CLA is?
done
done
I was told that we can apply for the initial grant then reapply for more if required… or would you just recommend we adjust and go direct to level 3?

Best Regards,

Richard

> On 8 Nov 2022, at 17:01, Sebastian Müller ***@***.***> wrote:
> 
> 
> Thanks for the application, @xcavate2022 <https://github.com/xcavate2022>. Someone will look into it more closely soon. In the meantime, could you
> 
> sign the CLA,
> host the images elsewhere? We prefer to keep the repo to the documents only. Easiest is to just paste the images into the Github editor.
> Can you remove the application text from the PR and replace it with our filled out PR template <https://github.com/w3f/Grants-Program/blob/master/.github/pull_request_template.md>?
> What does "Level: 1 = $10000" mean? At 300k, this is a Level 3 grant application.
> —
> Reply to this email directly, view it on GitHub <https://github.com/w3f/Grants-Program/pull/1266#issuecomment-1307534754>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A2OSX7EN6EBDTCICZYWO7BTWHKBPNANCNFSM6AAAAAAR2K2Q6Q>.
> You are receiving this because you were mentioned.
>

2022-11-08 22:36 UTC, semuelle commented
> Can you please clarify where the CLA is? 

Follow [the link](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1266) posted by the CLAAssistant in the comment above. All commit authors need to sign it. 

> I was told that we can apply for the initial grant then reapply for more if required… or would you just recommend we adjust and go direct to level 3?

Absolutely. However, your application currently lists a total cost of USD 307,200 and milestones with higher cost than 10k. So it is not clear what work the 10k would go towards. If these are the total costs of your project but you only want to apply for a small part of it, please write the application so that it is clear what it is you want to deliver as part of the grant. 

Given the size of the project you are describing, please also keep in mind that all work funded by a W3F grant needs to be open source and useful for the ecosystem as a whole, so no proprietary dependencies.

2022-11-14 16:23 UTC, semuelle commented on Project_Xcavate.md
> +We will start with the user onboarding process to Xcavate parachain/parathread allowing the design team to create low-fi wireframe mockups using Figma that will then be approved by the team to be upd
> that will then be approved by the team

Which team? We usually expect at least low-fi designs or wireframes to exist for a UI grant.

2022-11-14 16:24 UTC, semuelle commented on Project_Xcavate.md
> +- **Level:** 1 = $10000
At the moment, M1 is stated to cost 36,000 USD, so it'd be a Level 3 grant.

2022-11-14 16:42 UTC, semuelle commented on Project_Xcavate.md
> +![](https://xcavate.io/wp-content/uploads/2022/11/XCAV-WEB-3-Grant-Application-Image-3.jpg)
Only two of these images load for me. Interestingly, all the xcavate.io URLs return 404 for me.

2022-11-14 16:42 UTC, semuelle commented on Project_Xcavate.md
> +![](https://xcavate.io/wp-content/uploads/2022/11/XCAV-WEB-3-Grant-Application-Image-4.jpg)
This image also doesn't load for me.

2022-12-02 08:53 UTC, Noc2 requested changes
Thanks for the update. Sorry for the delay here. I think @semuelle missed the update. In the future, feel free to ping us here. Regarding your current proposal, it looks like you only want to create wireframes and mock-ups as part of this grant. This is usually something we don’t support since it’s not necessarily useful for others and is very much focused on your product. My recommendation would be to do this work on your own and reapply later once you actually want to work on the open-source software implementation.

2022-12-12 13:40 UTC, Noc2 commented
I’m closing this for now. Let me know if you want to re-open it.

2022-12-12 13:40 UTC, closed without merging