Unified deployment for the validator node
w3f/Grants-Program pull request #1268
Opened 2022-11-09 19:34 UTC by markblaize

#### Project Abstract

The core goal is to provide production-ready deployment for the Polkadot validator node and update [Polkadot Validator Setup](https://github.com/w3f/polkadot-validator-setup) repository with up-to-date  scripts

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-11-09 19:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1268) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1268) it.</sub>

2022-11-10 11:12 UTC, alxs commented
Thanks for the application @markblaize! Could you please sign the CLA above containing our Terms and Conditions? Note that since @siexp made the commit, he'll also need to sign it.

Do you have any experience using the `polkadot-validator-setup` repo yourself? The issues you list are very old (up to 3 years) and I wonder if they really are the most pressing features you'd want to implement when picking this up again. It might make sense to wait with these, and also to break up the milestone into smaller ones so you get some feedback along the way and more regular payments.

2022-11-10 13:35 UTC, markblaize commented
> Thanks for the application @markblaize! Could you please sign the CLA above containing our Terms and Conditions? Note that since @siexp made the commit, he'll also need to sign it.
Sorry, little mess up with ssh keys, signed with the correct account.

Hi @alxs,

> Do you have any experience using the `polkadot-validator-setup` repo yourself? The issues you list are very old (up to 3 years) and I wonder if they really are the most pressing features you'd want to implement when picking this up again. 

Yes, that's why we want to update it. The main goal is not to fix mentioned issues, but to rework deployment so node infrastructure is maintained properly. At the current state, scripts from `polkadot-validator-setup` are outdated and don't work. Issues are mentioned because we will fix them in the scope of terrform deployment updates. 

>It might make sense to wait with these, and also to break up the milestone into smaller ones so you get some feedback along the way and more regular payments.

Let me review the roadmap if we could make changes more granular

2022-12-02 11:54 UTC, Noc2 requested changes
As just discussed, I'm closing this one. Feel free to reopen it later or ping me in the future.

2022-12-02 11:54 UTC, closed without merging