ZK-Snarks tutorial
w3f/Grants-Program pull request #1290
Opened 2022-11-21 22:17 UTC by bufta

ZK-Snarks tutorial grant proposal

#### Project Abstract

Main goal of this project is to popularise the ZK-Snarks concept within the Substrate community. We would like to create a series of blog posts with the tutorial codebase, which will help in better understanding the ZK-Snarks for the Substrate community.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-11-21 22:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1290) it.</sub>

2022-11-22 12:43 UTC, Noc2 requested changes
Thanks for the application. We usually don’t fund purely educational-focused milestones. Could you potentially combine milestones 2 and 3? Also could you the default deliverables to all milestones (0a. License, etc.)? And just to double-check, you want to essentially update https://github.com/zeropoolnetwork/zeropool-substrate-groth16-example, correct?

2022-11-23 08:20 UTC, bufta commented
Hi @Noc2  thank you for the feedback. Indeed, coding wise we would like to implement, from scratch, an updated version of the zeropool project. This experience will allow us to document and share the step-by-step guidance for Substrate community (blogposts & video). As for the milestones, we will rearrange the blog posts/video plans to combine the educational efforts with the development.

2022-11-24 14:23 UTC, Noc2 submitted a review, later dismissed
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the team.

2022-11-24 16:52 UTC, semuelle commented
Thanks for the application, @bufta. Just to make sure I understand correctly: you will build and publish a fully functioning zk-snarks pallet and demo (on, say, Github) and then accompanying material on your blog and YouTube?

2022-11-25 11:46 UTC, bufta commented
@semuelle as we described it in the proposal, the pallet will be used for the verification process. Based on the implementation part we'll prepare the tutorials (blog posts and video).

2022-11-28 16:46 UTC, semuelle requested changes
Thanks for the update. Could you also remove the boilerplate text from the `0` deliverables and replace it with more concrete specifications?

2022-11-29 11:28 UTC, bufta commented
@semuelle the requested change was applied in the latest commit, hope the 0 deliverables are more suitable now

2022-11-29 13:54 UTC, semuelle submitted a review, later dismissed
Thanks for the update. I approve.

2022-11-29 14:08 UTC, Noc2 submitted a review, later dismissed

2022-11-29 16:12 UTC, takahser requested changes
@bufta please make sure that your application adheres to our [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md).

2022-11-29 16:12 UTC, takahser commented on applications/ZK-Snarks tutorial.md
> +* **Proposer:** Bright Inventions
```suggestion
* **Team Name:** Bright Inventions
```

2022-11-29 16:12 UTC, takahser commented on applications/ZK-Snarks tutorial.md
> +* **Payment Address:** 0xDDcfd2a1D4Bcf058cf2828eb78dB59b300e80F8d
```suggestion
* **Payment Address:** 0xDDcfd2a1D4Bcf058cf2828eb78dB59b300e80F8d
- **[Level](https://github.com/w3f/Grants-Program/tree/master#level_slider-levels):** 2

```

2022-11-29 16:12 UTC, takahser commented on applications/ZK-Snarks tutorial.md
> +* **Projects you think this work could be useful for:** Community
```suggestion
```

2022-11-29 20:48 UTC, bufta commented
Thank you @takahser, I applied the suggested changes

2022-11-30 09:05 UTC, Noc2 approved these changes

2022-11-30 09:36 UTC, semuelle approved these changes

2022-11-30 13:44 UTC, takahser commented
@bufta thanks for the update.
@alxs could you have a look at this application, since it focuses on zero-knowledge-based tech?

2022-12-05 10:56 UTC, laboon approved these changes

2022-12-05 11:18 UTC, merged