Update verida_network.md
w3f/Grants-Program pull request #1306
Opened 2022-11-25 03:32 UTC by ysam21

Added expected delivery date of Milestone 1

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [ ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2022-11-25 03:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1306) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1306) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1306) it.</sub>

2022-11-25 08:24 UTC, Noc2 requested changes
Thanks for the update, but could you provide a recent estimate of the new delivery date and not something that is already in the past: " [Expected delivery June 2022]"

2022-11-25 08:25 UTC, Noc2 commented
Also, could you sign the latest version of our terms and conditions? See CLAassistant above

2022-11-29 07:54 UTC, ysam21 commented
Apologies @Noc2 , it was meant to say June 2023. I've updated the application.
 I've signed the CLA too.

2022-11-29 11:19 UTC, alxs commented on applications/verida_network.md
> +- **Estimated Duration:** 2 months [Expected delivery June 2022]
```suggestion
- **Estimated Duration:** 2 months [Expected delivery June 2023]
```

2022-11-29 11:29 UTC, alxs approved these changes

2022-11-29 11:32 UTC, takahser approved these changes

2022-11-29 12:14 UTC, Noc2 approved these changes

2022-11-29 12:14 UTC, Noc2 commented
Thanks for the update

2022-11-29 12:35 UTC, dsm-w3f approved these changes

2022-11-29 13:20 UTC, gautamdhameja approved these changes

2022-11-29 13:25 UTC, merged