RFP for User Account Access Graph
w3f/Grants-Program pull request #1417
Opened 2023-01-06 11:33 UTC by bhargavbh

Security analysis of the user account access and recovery mechanisms for Polkadot accounts.

2023-01-06 11:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1417) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1417) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1417) it.</sub>

2023-01-06 11:57 UTC, Noc2 approved these changes

2023-01-06 12:01 UTC, Noc2 requested changes
Could you merge this PR to fix the formating: https://github.com/bhargavbh/Grants-Program/pull/1/files

2023-01-06 12:26 UTC, Noc2 approved these changes

2023-01-06 12:52 UTC, dsm-w3f approved these changes

2023-01-06 21:43 UTC, keeganquigley approved these changes

2023-01-07 03:14 UTC, randombishop approved these changes
LG

2023-01-07 16:17 UTC, merged