Claps Health
w3f/Grants-Program pull request #1440
Opened 2023-01-15 10:13 UTC by jacobleegithub

#### Project Abstract

> Claps is the mobile app that integrates gaming with personal health tracking can be a fun and engaging way to encourage users to track their health on a daily basis and make healthy lifestyle choices. 

#### Grant [3]

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-01-15 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1440) it.</sub>

2023-01-16 07:53 UTC, Noc2 requested changes
Thanks for the application and your interest in our grants program. Some of the deliveries that you currently list already exist in our ecosystem (like, for example, the [pallet DID](https://github.com/substrate-developer-hub/pallet-did) or the [Uniques Module](https://github.com/paritytech/substrate/tree/master/frame/uniques) for NFTs). Could you either remove them or clarify what is unique about your solution? Also, in general, could you try to add more technical details to the specification of your deliverables (e.g., programming language)?

2023-01-16 09:19 UTC, jacobleegithub commented
Yes, we can remove the DID and NFT modules from our proposal development milestones and instead focus on improving the patient management platform development and adding more details about its architecture and technical details with specification. Additionally, we can leverage existing solutions such as the pallet DID or the Uniques Module if need. We will making some modifications in Claps Health proposal soon. Thank you for the advise!

2023-01-31 09:34 UTC, jacobleegithub commented
We've removed DID and NFT from milestone 1 and update all of milestone deliverables 1-4 with more technical details. Add use cases and architecture diagram.  Thank you!

2023-01-31 12:50 UTC, Noc2 requested changes
Thanks for the update. However, the formatting of the application, specifically the tables, seems to be off now. Could you please fix this? And I have one additional question: How do you ensure the privacy of the users and comply with health laws like HIPAA or GDPR, etc.? It looks at the moment like you want to put everything on the chain.

2023-01-31 14:05 UTC, jacobleegithub commented
Hi David, 

On chain:
1. User ID (anonymous ID)
2. Credential (User level, for example aggressive user produce high data quality)
3. User status (To be verify by system or suspend by user)
4. Data hash code (if required for some situration)  

So there are very limited and anonymous data on-chain.

Off-chain data on AWS S3 or IPFS:
User profile (Gender, Birth)
Health Diary (Result of questionnaire)
Dialog with Chatbot (Specific data by user required)

To answer your questions, it is very limited anonymous data on-chain, and all of health data will be encrypted and secured on AWS S3 or IPFS Cluster (Decentralized Storage), allow user to decrypted(access control), authorize, delete..etc. Compliance with HIPAA & GDPR.

We need to do more investigation to see if Substrate can support Decentralized Storage. IPFS and AWS S3 will be backup solution.

By the way, I've check milestone table, can't find the problem, preview mode seems ok, I've updated, can you please check again? Many Thanks!

2023-01-31 14:37 UTC, Noc2 commented
This is how the table of milestone shows up for me: 
<img width="1453" alt="Screenshot 2023-01-31 at 15 36 56" src="https://user-images.githubusercontent.com/24638510/215790023-0c62e134-1588-4ca8-834f-9d7bf39bea86.png">

2023-01-31 14:44 UTC, Noc2 requested changes
Could you clarify what you mentioned above as part of the application? It currently for example doesn’t mention ipfs. You can find a couple of ipfs related projects here: https://wiki.polkadot.network/docs/build-open-source Also could you specify which kind of encryption you are going to use? Also how is the anti-fraud mechanism going to work (I assume this is part of the substrate module) via twitter or email in an anonymous way?

2023-01-31 15:01 UTC, jacobleegithub commented
I've edit table and move function list column to the right, please check.
For example: all of the sub functions list are belong to no.1.  
![2023-01-31 下午10 56 51](https://user-images.githubusercontent.com/14127551/215795247-9d9775be-d56d-4e32-91e5-69a81aa39063.png)

Hope it will make much more clear.

2023-02-01 02:17 UTC, jacobleegithub commented
Could you clarify what you mentioned above as part of the application? It currently for example doesn’t mention ipfs.

Thanks for the resources, we are interested in Crust Network Storage on Polkadot Substrate. IPFS is an optional service and a future plan for Claps app users who want a more portable solution for their mood tracking data(or Real-word data). However, IPFS is a decentralized public storage solution and may have limitations in terms of accessibility and reliability, industry compliance compared to traditional centralized storage solutions such as AWS S3. So we will not integrate IPFS at this stage.

How is the anti-fraud mechanism going to work (I assume this is part of the substrate module) via twitter or email in an anonymous way?

We are planning to have multiple levels of verification on the Substrate module, such as signing a message and posting it to a social account, email verification, and SMS verification..etc, it can help increase the security of the user registration system and reduce the risk of fraud. (However, it's always possible for fraudsters to find ways to bypass security measures.) SMS depends on the local country service, it will be implemented on the next stage after Claps app product pilot program launch.

There will be user credential verification in an anonymous way (zero-knowledge proof) and “user account quality levels” design to improve anti-fraud mechanism, such as paid account will be level up, some data verified by health practitioners will be level up..etc.(credential by HP) 

Could you specify which kind of encryption you are going to use?

We are using Public-key ECIES cryptography to protect the user's data. When users upload their health diary, client side app will help users to perform the AES-256 GCM encryption process when saving the data.

When users share data with health practitioners or pharma on the web backend database, the system uses AES-256 encryption to individually transmit the shared decryption key, and does not disclose the user's public key information to avoid the risk of quantum computers doing brute force cracking.

2023-02-01 21:12 UTC, keeganquigley commented
Thanks for the application @jacobleegithub I have a few initial questions:

- I agree that the delivery tables still aren't formatted correctly. Can you get rid of the spaces? You can still make a list but it should be contained in one box. See [here](https://github.com/w3f/Grants-Program/blob/master/applications/ink-explorer.md) for a good example of what the tables should look like.
- Are you able to submit any initial mockups/wireframes of the UI? (For the Flutter and Vue front-ends you mentioned). Typically we ask for these for UI focused deliverables.
- We usually don't support Solidity development because we aren't experts in the field so it is hard to evaluate. Also in my opinion they don't directly benefit the substrate community. Would you be willing to create ink! smart contracts instead?
- As of now, ChatGPT occasionally generates incorrect information. I'm not sure how this would work with risk management within the health systems?
- SMS verification is susceptible to man-in-the-middle attacks and in my opinion should be phased out in favor of safer authentication methods. 
- Why not use existing substrate identity solutions instead of creating your own on-chain verification system?

2023-02-02 11:12 UTC, jacobleegithub commented
> I agree that the delivery tables still aren't formatted correctly. Can you get rid of the spaces? You can still make a list but it should be contained in one box. See here for a good example of what the tables should look like.

I’ve updated the delivery table, please check.

> Are you able to submit any initial mockups/wireframes of the UI? (For the Flutter and Vue front-ends you mentioned). Typically we ask for these for UI focused deliverables.

Yes we are able to submit initial mockups/wireframes of the UI, I will keep you updated in the next 2-3 weeks.

> We usually don't support Solidity development because we aren't experts in the field so it is hard to evaluate. Also in my opinion they don't directly benefit the substrate community. Would you be willing to create ink! smart contracts instead?

Yes we are able to code ink! smart contract, it will take some learning curve, it’s fine with us.

> As of now, ChatGPT occasionally generates incorrect information. I'm not sure how this would work with risk management within the health systems?

We are using structured indicators or questionnaires with AI only, that can help reduce the risk of providing incorrect information. There is no “free to speak” of AI in this stage.
ChatGPT will not be used to diagnose or treat medical conditions.

Here is an example:

HP design questionnaire for AI and patients:

On a scale of 0 to 3, how often have you been bothered by little interest or pleasure in doing things in the last 2 weeks?
On a scale of 0 to 3, how often have you been feeling down, depressed, or hopeless in the last 2 weeks?
On a scale of 0 to 3, how often have you had trouble falling or staying asleep, or sleeping too much in the last 2 weeks?

Patient answered:
0, 2, 0

ChatGPT respond and report to HP:
Thank you for your response. It is important to monitor your mental health and seek help if you are consistently experiencing symptoms. If your symptoms persist or worsen, it is recommended that you speak with a healthcare professional for further evaluation and treatment options.

HP confirmed message.
Patient received a response.

The idea of AI is to save time for health practitioners, ChatGPT function will be forced input and be monitored output by HP. There is no any personal information to ChatGPT.

In the future development, the AI content will be trained by HP (health education contents provided by HP), it will reduce risk of “google contents learning” for both patients and AI.

> SMS verification is susceptible to man-in-the-middle attacks and in my opinion should be phased out in favor of safer authentication methods.

Yes I agree with that. We will find safer authentication methods.

> Why not use existing substrate identity solutions instead of creating your own on-chain verification system?

After research of Substrate official website identity related project, we will consider to fork Substrate pallet DID and make it suitable for Claps Health system - both patients  and healthcare service providers.

Others identity project on Substrate website they all have different purpose, it will take too much time and resource for us to try. So pallet DID will be the basic solution for us. Simple is good.

2023-02-02 15:28 UTC, Noc2 requested changes
Thanks for the update. The application looks better now, and I will mark it as ready for review. However, I personally still have some concerns about it. First, your application currently doesn’t contain anything regarding zero-knowledge proofs. Directly using Twitter or email verification makes it probably very easy to extra personal data, even if you use a different address for the on-chain verification and the health-related data. Also, this on-chain data can not be deleted (GDPR).  Additionally, some of the deliveries, but especially the last milestone, seems currently to be unrelated to the polkadot ecosystem, and its current form could be implemented for any kind of project.

2023-02-02 17:37 UTC, keeganquigley commented
Thanks for the updates @jacobleegithub I appreciate the detailed encryption information and the application looks a lot better now. However I still won't approve the application at this time due to the aforementioned concerns. For example:

- I'm not sure that the smart contract modules would be re-used by other projects.
- all the various front-end apps would most likely only be useful only for your team and no one else.
- Creating a DAO is an endeavor that is not to be taken lightly. Have you looked at any of the DAO tooling [already available](https://wiki.polkadot.network/docs/build-open-source) in the ecosystem? I'm not sure that this should be condensed into one milestone.
- I don't know how a DAO would work regarding all the legal complexities that come with healthcare systems. You would likely have to deal with laws in every country the app is operated in.
- I agree that the last milestone essentially only benefits your app and isn't useful to the ecosystem.

In my opinion it also seems pretty ambitious to combine AI tech and a DAO into a survey app. Basically, I'm not convinced that this product would actually be used by healthcare companies.

2023-02-03 23:44 UTC, jacobleegithub commented
First of all, many thanks for great advice, make us introspection Claps Health project.

> I'm not sure that the smart contract modules would be re-used by other projects.
all the various front-end apps would most likely only be useful only for your team and no one else.

Healthcare market is huge, it may not develop smart contract and can be re-use by others project, but it may re-use in healthcare industry, for example:

Personal Health Records: A smart contract that can securely and manage patient health records and allow authorized access to medical professionals. (On chain data are very few but only trust DID list, informed consent, credential(zero-knowledge proof), data hash proof and times stamp..etc) 

Clinical Trials Management: A smart contract that can manage the administration of clinical trials, including patient recruitment, randomization, and data management. Connected to regulation & compliance protocols)

Drug Development: A smart contract that can track the progress of new drug development, from research and development to FDA approval. Such as IP sharing, Research & Publication..etc)

Medical Claims Processing: A smart contract that can automate the claims processing process, reducing administrative costs and improving the accuracy of payments.

Health Insurance: A smart contract that can manage the administration of health insurance plans, including claims processing, enrollment, and premium payments.

Patient Incentive Programs: A smart contract that can manage rewards programs for patients who participate in health and wellness programs, track their progress, and reward them for their efforts.

But develop such can widely use health protocols is very difficult, the whole system is now controlled by hospitals, government and pharma companies. There is no way to simply empower patients and get start with web3 based portable health records for every individual.

So Claps Health will be focused on last one, Patient Incentive Programs and Omni-Channels. I believe Patient Incentive Programs can be developed by smart contract and re-use in other utilities. For example the patient groups in every country can just re-use these smart contract to connected with patient in digital way, engage with others local resources and support program. Claps Health Incentive Programs for mental health can not cover all, they can just fork Health Incentive Programs to Oncology patients and others.

The front-end mobile app is for Claps Mental Health Patients, but Backend with Substrate nodes  will be Clients like Phama, Nutrition, Bio company..etc. (I will explain why pharma will be join soon)

> Creating a DAO is an endeavor that is not to be taken lightly. Have you looked at any of the DAO tooling already available in the ecosystem? I'm not sure that this should be condensed into one milestone.

We will reconsider removing DAO from milestone deliverables but keep it in Claps Health system. It’s because the Claps DAO functions as a controller(multi-signature) with other Claps Dapps. It’s not like DAO for community governance/voting/secure fund…etc, it’ not  like others defi project.

> I don't know how a DAO would work regarding all the legal complexities that come with healthcare systems. You would likely have to deal with laws in every country the app is operated in.

Good question! Clap DAO is a safeguard for other smart contracts. It won’t touch any health records or personal information or even funds. It is part of system security. To landing the local country should be a healthcare service company but not DAO.

I will discuss with team and add more details of Claps DAO function in this proposal.

> I agree that the last milestone essentially only benefits your app and isn't useful to the ecosystem.

I will discuss with team and see how we can do. We are sturdy and evaluate with KILT, DOCK and others Substrate DID projects.

To expand Substrate and widely use by healthcare business is hard. I believe Omini-Channels will be the key.

What I mean is we have confident to prove Claps Health Substrate will be use by pharma companies and others. And it can benefit to Substrate ecosystem in middle term.

The new evidence show they are using “WeChat, Line..etc” to manage HP and Patients on their Omni-Channels strategy, The use of messaging apps in the healthcare industry has grown due to strong market demand and the lack of a dedicated secure platform for healthcare communication. and there is an increasing demand for secure and compliant platforms in the healthcare industry. Claps Health Substrate will be the good solution for them. 

> In my opinion it also seems pretty ambitious to combine AI tech and a DAO into a survey app. Basically, I'm not convinced that this product would actually be used by healthcare companies.

Omini-Channel to mange HP and Patients will be the key to this business. But before that, we need patients. Until we have Claps Health patient group, they won’t talk with us.

I will do some modification about role of AI and DAO in this proposal. Try not to miss leading the core of Claps Health, at least in short to middle term. Thanks for advise.

2023-02-04 05:59 UTC, jacobleegithub commented
> Thanks for the update. The application looks better now, and I will mark it as ready for review. However, I personally still have some concerns about it. 

> First, your application currently doesn’t contain anything regarding zero-knowledge proofs. Directly using Twitter or email verification makes it probably very easy to extra personal data, even if you use a different address for the on-chain verification and the health-related data. 

Thanks for advice,  we will add zero-knowledge proofs to this proposal and explain how it works with a patient's anonymous ID with verifiable credentials issued by others and it can’t not be traced or connected with the patient's personal info.

Patients will need zero-knowledge proofs of their on-chain ID. We will add it into the proposal.

The alternative way is to use KILT or Dock or other DID solutions. But Claps DID require both individual and business multi ID environments. So we may decide to fork the pallet project and add more functions on it.

> Also, this on-chain data can not be deleted (GDPR).

Yes, on-chain data can not be deleted but there is only a public key type of random ID, in the smart contract of ID, there is only hash code, credential with timestamp. When a user chooses to delete personal data, it will delete related data on AWS S3. There is no personal data on-chain.

The on-chain ID can’t be recovered and traced to any person. If this can’t be applied with GDPR, I will say others DID can not too.

Our team already work with ISO27001/ISO27701 PIMS certificated association(TRPMA), we will ask a compliance officer to support this project, make sure we are on the right track.

We will add more data to this proposal about HIPAA/GDPR.

> Additionally, some of the deliveries, but especially the last milestone, seems currently to be unrelated to the polkadot ecosystem, and its current form could be implemented for any kind of project.

Thanks for reminding, we will do some modifications with the last milestone.

But please understand that the healthcare market is huge, if we can expand Substrate nodes to healthcare business to the industry, it will be another huge Substrate ecosystem. It also can benefit Polkadot in healthcare industry. And the strategy will be no doubt - patient group and omni-channels, start with Claps Mental Health Substrate.

2023-02-10 17:44 UTC, randombishop submitted a review, later dismissed
This application looks good to me, thanks for submitting, and I am happy to go forward.
(But you will still need 4 more approvals; so please try to respond to @keeganquigley and @Noc2 concerns with as much details as possible to convince them and the other committee members.)

2023-02-12 12:53 UTC, jacobleegithub reviewed
1. Overview updated

Move the position of AI from patient to health practitioners. For reference: “The Claps AI is designed to support health practitioners in tracking patients' data on a daily basis.”

2. Architecture updated

Add IPFS swam to substrate for health education content storage
Add Claps Health Data Sharing Protocol

3. Solution updated

Remove personal AI assistant
Add Health practitioners AI assistant
Add Ominichannel 

4. Technology updated

Add Substrate blockchain
Add SSI
Add Zero-knowledge proof for enhanced privacy protection 
Add Zero-knowledge proof model diagram

5. Milestone Deliverable

Add Enterprise Registration to M1
Replaced M3 with Data Sharing Protocol
Replaced M4 with Omnichannel

6. Add Regulation and Compliance with HIPAA/GDPR

2023-02-13 00:15 UTC, jacobleegithub commented
Dear committee members,

Thank you for considering our proposal for the Claps Health mood tracking app. We understand your concerns regarding the reusability of our smart contract modules, the limited usefulness of the front-end apps, the issues of creating a DAO, and the legal complexities of operating a healthcare system.

In response to your concerns, we have made several changes to our proposal to address these issues and make the Claps Health app a more valuable addition to the ecosystem. We have added Zero-knowledge proof for patient privacy protection, replaced the Claps DAO with a data sharing protocol that can be re-used by other projects, and replaced the web backend design with an omnichannel-ready platform design that we believe will be useful for other industries as well.

Our updated proposal includes an overview that moves the AI from the patient to health practitioners, an updated architecture that includes IPFS swarm for health education content storage and the Claps Health Data Sharing Protocol, a solution that includes a health practitioners AI assistant and omnichannel capabilities, technology that includes Substrate blockchain, SSI, and Zero-knowledge proof for enhanced privacy protection, and milestone deliverables that include Enterprise Registration and the Data Sharing Protocol. Additionally, we have added regulation and compliance with HIPAA/GDPR to ensure that our app is fully compliant with all relevant laws and regulations.

We hope that these changes demonstrate our commitment to making Claps Health a valuable addition to the Substrate ecosystem and we look forward to the opportunity to bring this app to the market. Thank you for your consideration.

P.S. Basic UI to be add by 1-2 weeks. thanks!

Sincerely,
Jacob

2023-02-13 13:47 UTC, randombishop submitted a review, later dismissed

2023-02-13 20:18 UTC, semuelle commented
While this application contains some interesting ideas, I cannot support it for the following reasons:

- It is very sparse on technical details (re zk proofs, end to end encryption plus a data sharing protocol on Substrate, and other things) while containing a ton of very complex topics,
- it uses imprecise or incorrect wording in several places (the "pallet" deliverables are specified as "backends" using smart contracts), and
- I am skeptical that individuals _and_ companies are willing to put their private and business data on-chain, encrypted or not,
- team has no apparent experience writing and maintaining open source software.

2023-02-15 13:32 UTC, jacobleegithub reviewed
Programing language on milestone deliverable M1-M4 Revised

2023-02-15 14:31 UTC, jacobleegithub commented
> While this application contains some interesting ideas, I cannot support it for the following reasons:
> 
> * It is very sparse on technical details (re zk proofs, end to end encryption plus a data sharing protocol on Substrate, and other things) while containing a ton of very complex topics,
> * it uses imprecise or incorrect wording in several places (the "pallet" deliverables are specified as "backends" using smart contracts), and
> * I am skeptical that individuals _and_ companies are willing to put their private and business data on-chain, encrypted or not,
> * team has no apparent experience writing and maintaining open source software.

Thank you for your feedback. I understand your concerns, and I agree that zk proofs and other technical details require more in-depth discussion, to make it clear in each one may require many proposals. However, I would like to clarify that this proposal is focused on healthcare applications, and it is based on our experience with blockchain technology from previous projects.

We are interested in Substrate and are hoping to learn and leverage the new technology on Polkadot Substrate. We understand the pallet project they mentioned in they proposal is for DID learning purposes only and not intended for business. At milestones, The backend is a web backend for healthcare businesses, and it will require both individual and multi-user organization decentralized identifiers (DIDs). The user interface will also require a backend to interact with DID smart contracts. I have made some changes to the milestone to hopefully make this clearer. 

We believe in the potential of healthcare on Web3, and we have executed many projects in the past few years based on Web3 technology. We have found that both individuals and businesses are looking for secure and useful applications.  Our important data is currently stored on AWS S3 for security reasons. To address your concerns, I would like to clarify that we do not put any data on chain, and we understand the importance of maintaining privacy and security when it comes to sensitive healthcare information.

As for our experience and qualifications, all of our experience is on Gitlab, but we are looking forward to moving to Github.

Anyway, thank you for your feedback, I hope I can provide a UI soon to demonstrate Claps Health potential.

2023-02-16 14:20 UTC, Noc2 requested changes
Thanks for the update. But to be honest, I’m now even more confused. For example, as part of the first milestone, you say, “Substrate Module (Developed in Rust):” and after this, I thought you would list all the functions of this substrate module. But part of this list is also ink! Smart contracts as well as “Zero-knowledge proof.” How can an ink smart contract be part of a substrate module? I also have to agree with Sebastian that it would be nice to have more details regarding the technology. For example, what kind of Zero-knowledge proofs are you talking about, and how are they implemented?

2023-02-17 11:26 UTC, jacobleegithub commented
@Noc2 
Thank for advise. About “How can an ink! smart contract be part of a substrate module?”

No, it’s separate! 

When I define the second column with “Deliverable”, at “Patient registration module”, it’s containing “Substrate API & Dapps”. Let me fix this by using a separate Row. The first Row is for Substrate Rust, the second Row by ink! Smart contract. So it will not mixed together.

Our solution is using a hybrid model, with anonymous on-chain ID and zero-knowledge proofs served by ink! smart contracts and personal profile data managed off-chain through Substrate APIs. This can help ensure the privacy and security of patient data, while still enabling efficient and secure access to healthcare services.

We can start working on details of technical specifications and provide POC on the main Github of Claps Health Official Account.

In the meantime, about spec of milestone 1 - Patients & Healthcare business registration, here is more details explanation for your reference.

For example, we can separate Patient data by:

Anonymous On-chain ID & zk Proof service
Personal profile data manage at off-chain world

The On-chain ID & zk Proof will be served by pure dapp, developed by ink! Smart contract.

Personal profile data will be managed off-chain using Substrate API (written in Rust). For example, the profile data will be stored on AWS S3 and encrypted by the ID holder (patient). The ID holder will hash the profile data and store the resulting hash code on the blockchain along with their ID. Let's jump over this part of profile management.

Here is sequence diagram:

Role play:

Claps Health (Issuer): An actor who makes a claim.
Claps Health Patient (ID Holder): An actor who receives a claim.
Healthcare Service Provider (Verifier): An actor who verifies if the content of a claim is issued by a specific identity and held by another specific identity.
Credential: Data that is needed to prove that a claim is issued by a specific identity and held by another specific identity. This data is composed of a claim and a proof.

Sequence flow:

(The process by client side)

1. ID Holder generate random ID (BIP39)

(The process with no zk-proof, credential issue by Claps Health trust party)

2. ID Holder call Substrate API Issuer to makes a claim
Substrate Issuer validate ID Holder and claim credential through dapp

(The process with zk-proof, on-chain)

3. Verifier challenge ID Holder
4. ID Holder answer challenge by credential
5. Verifier verified, allow ID Holder use the service

Our experience is based on EVM and Ethereum Parity, so please correct me if I am wrong. 
Substrate = Node = Blockchain SDK, can be customized by developing Rust language (Function as Substrate API).

ink! Smart Contract = Solidity, we can porting EVM smart contract by re-coding smart contract on ink! Deployed on Substrate virtual machine.

That’s why Claps Health Registration Module contains “Developed by Substrate Rust”, and some function list is developed by “ink! Smart Contract”. I will make it with two rows.

2023-02-21 15:54 UTC, jacobleegithub reviewed
Update milestone deliverable 1-4, add technical specifications.

2023-02-22 09:28 UTC, 0xCaso reviewed
Hi @jacobleegithub, could you please make the following changes to fix the application format?

2023-02-22 09:28 UTC, 0xCaso commented on applications/Claps.md
> +- **[Level 3]
```suggestion
- **[Level](https://github.com/w3f/Grants-Program/tree/master#level_slider-levels):** 3
```

2023-02-22 09:28 UTC, 0xCaso commented on applications/Claps.md
> +Milestone 1 - Prototyping & Registration
```suggestion
### Milestone 1 - Prototyping & Registration
```

2023-02-22 09:28 UTC, 0xCaso commented on applications/Claps.md
> +Milestone 2 - Challenge card & Health diary
```suggestion
### Milestone 2 - Challenge card & Health diary
```

2023-02-22 09:28 UTC, 0xCaso commented on applications/Claps.md
> +Milestone 3 - Data Sharing Protocol
```suggestion
### Milestone 3 - Data Sharing Protocol
```

2023-02-22 09:28 UTC, 0xCaso commented on applications/Claps.md
> +Millestone 4 - Omnichannel
```suggestion
### Milestone 4 - Omnichannel
```

2023-02-22 14:43 UTC, jacobleegithub reviewed
Format updated

2023-02-24 23:27 UTC, jacobleegithub commented
Claps Health will provide the following deliverables by March 8:

1. Basic wireframes for the Claps Health app/web interface.
2. A POC demo code for the Claps Health data sharing smart contract on Github.
3. A demo code for the Claps Health AES-256 ECM for health data encryption/decryption on Github.
p.s. The smart contract will initially be based on Solidity and will be ported to !ink as per the official roadmap schedule.

2023-02-28 13:00 UTC, Noc2 requested changes
Thanks for the update, and sorry for the late reply. I have a couple of additional questions/comments:

- Regarding BIP39, are you aware of https://github.com/paritytech/substrate-bip39 and https://wiki.polkadot.network/docs/learn-accounts#mnemonic-and-address-generation 
- It would be more useful if you support the polkadot.js extension and polkadot native solutions rather than metamask. I’m not sure you can use metamask to interact with the ink! Smart contracts at this stage. 
- What kind of Zero-Knowledge Proofs are you going to implement exactly? 
- How will the linking to Polkadot Name System work? Are you going to use XCM for it? 
- Feel free to ping me once you integrate the initial mockups/designs.

2023-03-03 04:01 UTC, jacobleegithub commented
>Regarding BIP39, are you aware of https://github.com/paritytech/substrate-bip39 and https://wiki.polkadot.network/docs/learn-accounts#mnemonic-and-address-generation

The Polkadot wiki page on mnemonic and address generation based on the BIP39 provides very good information on how mnemonic phrases can be used to generate a private key and address for a Polkadot account. Yes, we will double check that the algorithm is the same for user’s wallet generated, many thanks for the info.

>It would be more useful if you support the polkadot.js extension and polkadot native solutions rather than metamask. I’m not sure you can use metamask to interact with the ink! Smart contracts at this stage.

Definitely need to leverage polkadot.js but not Metamask in this stage. We know there is a limitation of Metamask to support polkadot ecosystem. And it’s pretty fine for us. We prefer to provide a one stop and all-in-one user experience but not rely on third party plug-in like MetaMask. Specially for patients and healthcare industry clients. In mobile devices and web backend.

>What kind of Zero-Knowledge Proofs are you going to implement exactly?
As of now, we prefer uses zkSNARKs Groth16, it is “non-interactive” and efficient for verification of Claps Health users. We will add this into tech spec in the next version of the proposal with UI update.

>How will the linking to Polkadot Name System work? Are you going to use XCM for it?

Using XCM to connect with the Polkadot Name System with parachain on the Substrate for the name service is a good solution for business clients, the main reason is we are offering a dedicated smart contract for enterprise (Replace smart contract address with meaningful name).  Yes we will use XCM for the future development, since all of Claps Health services are on the Substrate, it's not urgent at this stage. And XCM looks like a good solution for future compatibility.

>Feel free to ping me once you integrate the initial mockups/designs.

Yes I will. Many thanks.

2023-03-08 12:05 UTC, jacobleegithub reviewed
Add zk-proof spec
Add user interface mockup and figma link

2023-03-08 12:10 UTC, jacobleegithub commented
@Noc2 
Dear Committee Members,

We developed a Personal Health Records system based on Ethereum Parity technology and implemented a pilot program in the Medical Center in 2017. The system provided patient-owned and portable health records for the continued care of patients.

In 2023, my digital health team at the Taiwan Research-based Biopharmaceutical Manufacturers Association is committed to building an easy-to-use mobile app to support patients' lifestyle. This is also inspired by Pharma companies, the demand for AI and omni-channel solutions is strong, and more pharmaceutical companies and healthcare service providers are engaging in digital transformation strategies.

Unfortunately, healthcare service providers are currently relying on social media platforms and unsecured messaging tools. Our market approach is to start with the patient and provide an easy-to-manage lifestyle support on a secure mobile app. We aim to provide real-time data sharing, health education, and communication tools on the Polkadot Substrate for healthcare businesses.

The frontend application may be very specific for Claps Health, the core concept of data sharing and content publishing on the Polkadot web3 ecosystem can be applied to various industries and use cases beyond healthcare.

We have included basic UI in the Claps Health Proposal, which can be found [here](https://www.figma.com/file/Zlx3Qq4EoFtuV8AopAffVl/Claps-Health-Mobile-for-Patients?node-id=0%3A1&t=pUNA27WItIqVx5n8-1) and [here](https://www.figma.com/file/3uk14HULTZUcdAJeKmTkCM/Claps-Health-Web-Backend-for-Pharma?t=pUNA27WItIqVx5n8-1). Additionally, we have provided proof of concept for health data sharing through smart contract code on Claps Health Github Account [here](https://github.com/Claps-Health).

We are looking for resources to support this project and help us build it up on the Polkadot ecosystem based on Substrate technology, enabling patients to easily record and manage their real-world data and find resources for lifestyle support.

We hope you can see the potential of Claps Health as a simple and useful solution for citizens.

With best regards,
Jacob

2023-03-08 22:52 UTC, jacobleegithub commented
Please reload Figma link if you see only one page, I've put all ui on the same page.

2023-03-10 08:08 UTC, Noc2 approved these changes
Thanks for all the updates. I'm happy to go ahead with it and will share it with the rest of the team again. However, some committee members might not be willing to give you a level 3 grant immediately. In this case, it might make sense to initially only apply for a level 2 grant and potentially, after this, apply for a follow-up grant.

2023-03-10 14:07 UTC, randombishop approved these changes
I am a bit skeptical when I see too many challenges at once: healthcare network with ZKProofs and GPT-3 sounds really buzzy nowadays :)

But I am happy to move forward with this application given the credentials of the team and the ambition of the project, looking forward to seeing what you will build.

However, like @Noc2 said, it would help if you simplified the scope and reduced the first iteration to a level 2 grant

2023-03-10 15:39 UTC, keeganquigley requested changes
Thanks for the updates @jacobleegithub much appreciated.

- It sounds like an interesting app, but I do think the price is a bit high for a solution in which we aren't sure yet if it will work or not (and before we've had the chance to evaluate some of your work). Would you be willing to reduce the scope/cost for any of the milestones? 
- We only fund software development, therefore we don't pay for things like art design. Perhaps you could condense it down to 3 milestones and take out the costs for the art designer?
- Can you please fix the delivery tables to start with 0a - 0d for mandatory deliverables, and then start with 1, 2, etc. for the rest? That way the numbering will correctly match the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md).

2023-03-12 04:16 UTC, jacobleegithub commented
@Noc2 
Thank you for your feedback and for sharing the proposal with the rest of the team. We understand that some committee members might not be willing to give a level 3 grant immediately, and we are open to applying for a level 2 grant initially and potentially seeking a follow-up grant in the future. We appreciate your consideration and look forward to the next steps.

@randombishop 
Thank you for your feedback and for expressing interest in the project. We understand that there are multiple challenges involved in the proposal, and we are willing to simplify the scope and reduce the first iteration to a level 2 grant. We appreciate your support and look forward to building the app.

@keeganquigley 
Thank you for your feedback and for evaluating the proposal. We are willing to reduce the scope and cost for some of the milestones and remove the costs for art design, as we understand that the focus should be on software development. We will condense the proposal down to 3 milestones and adjust the delivery tables to match the template. We appreciate your consideration and look forward to the next steps.

Next step, I will reference with standard template and discuss with engineering team and revise the table of milestone in next two days.

Many Thanks!

2023-03-14 12:09 UTC, jacobleegithub reviewed
The revised product roadmap for Claps Health development.
We have also revised our grant application level to Level 2.

2023-03-14 12:10 UTC, jacobleegithub commented
Phase I - Minimum Viable Product (MVP) Development: (This proposal)

Patient registration
Fixed challenge card
Decentralized applications (dApps)
Health data sharing protocol
Incentive program for patients

Phase II - Full-featured Application Development: (Future Plan)

Enterprise registration
Dynamic challenge card
Health practitioner engagement
Patient groups
Health education content management
Omni-channel backend
Health data analysis backend

Note that the original roadmap has been modified from 4 milestones to 2 milestones for Phase I, as we prioritize the development of the MVP to provide the core functionality of our product as soon as possible.

2023-03-14 13:16 UTC, Noc2 approved these changes

2023-03-14 13:40 UTC, randombishop approved these changes

2023-03-14 15:31 UTC, keeganquigley approved these changes
Thanks for the changes, I'm happy to give you a chance and looking forward to the delivery.

2023-03-14 19:26 UTC, merged

2023-03-16 06:23 UTC, jacobleegithub commented
We are appreciate committee members's no-stop review and support, and thank you for sharing the great news! I'm thrilled to hear that the Claps Health proposal has been approved by the Web3 Foundation committee members. I'm excited to continue working on the Claps Health project and make a positive impact in the healthcare sector and Polkadot ecosystem.
Many Thanks!
With best regards,
Jacob Lee

2023-08-11 19:32 UTC, keeganquigley commented
Hi @jacobleegithub are you able to provide an update on Milestone 1?

2023-08-13 13:48 UTC, jacobleegithub commented
> Hi @jacobleegithub are you able to provide an update on Milestone 1?

Dear @keeganquigley 

**Claps Health Progress Report**

*Date:* Aug 13, 2023, Jacob Lee

---

**1. Executive Summary:**

Thank you for supporting Claps Health and granting us the opportunity to bring this vision to life. Since initiating the project in April 2023 (approved by middle of March), we've faced unforeseen challenges in the Rust and Substrate Technology learning curve, especially transitioning from a Solidity-based engineer. While we've onboarded experienced Substrate professionals to address this, the Item 3 related to zk-proof still to be develop.

We've achieved about 80% of the functionality in the mobile app frontend, and its progress now rely on Substrate / dapps development to catch thee timeline. And the major challenge is zk-proof.

We deeply regret the delay and sincerely hope for W3F's continued understanding and support. We're committed to navigating through these challenges and delivering on our promises.

Please reference the demo video in here:
https://youtu.be/naMzUGk9lQo

or you can download apk and install on Android phone here:
https://drive.google.com/file/d/11kxSy50M1YchAV8zD5kHuGJedQ5TZt6c/view?usp=sharing

Please find the detailed progress report attached for more insights.

- We have made significant progress towards Milestone 1, with delays in items in below:


| Number | Deliverable                                | Progress |
|--------|--------------------------------------------|----------|
| 0a.    | License                                    | Yes      |
| 0b.    | Documentation                              | 80%      |
| 0c.    | Testing and Testing Guide                  | 0%       |
| 0d.    | Docker                                     | 0%       |
| 0e.    | Article                                    | 0%       |
| 1.     | Patient ID creation                        | 100%     |
| 2.     | Patient profile management module          | 100%     |
| 3.     | Patient ID on-chain authentication         | 0%       |
| 4.     | Challenge card dapp module                 | 0%       |
| 5.     | Create database                            | 80%      |
| 6.     | Database encryption module                 | 0%       |
| 7.     | Android apk                                | Please reference download link |
| 8.     | Testing                                    | 40%      |





---

**2. Milestones Overview:**
- Milestone 1: Patient Identity and Security Framework
  - **Status:** Delayed due to zk-proof
  - **Estimated Completion Date:** Oct 2023
- Milestone 2: Patient Engagement and Data Sharing
  - **Status:** Delayed due to Milestone 1
  - **Estimated Completion Date:** Dec 2023

---

**3. Challenges and Delays:**
The Milestone 1, Item 3 - "Patient ID on-chain authentication" (specifically, zkSNARKs Groth16 based on Non-Interactive Zero-Knowledge Proof) is still under research. We are considering the use of Pallet or XCM to implement this function. Alternatively, we're exploring the possibility of using third-party zk-proof on Substrate, if available.

---

**4. Support Required:**
- Guidance on implementing zk-proof on Substrate if possiable.
- Introduction to potential partners of zk-proof if possiable.
- Introduction to Substrate developer/engineer if possiable (will share with grant).

---

**5. Conclusion and Forward Look:**
- **Conclusion:**

As of August 13, 2023, Claps Health has made significant strides in multiple areas, with the most notable progress in the creation of the Patient ID and the management module, both achieving a completion rate of 100%. However, the adoption and integration of zkSNARKs Groth16 for "Patient ID on-chain authentication" remain a prominent challenge, causing delays in the overall development trajectory.

While the mobile app's frontend boasts 80% functionality completion, its full operation hinges on the advancement of the Substrate / dapps component, particularly the integration of zk-proof. These challenges have, in turn, led to a rescheduling of the estimated completion dates for Milestone 1 and 2 to October and December 2023, respectively.

The team's commitment remains unwavering. We're tirelessly seeking solutions, considering various approaches, including leveraging Pallet, XCM, or third-party zk-proof on Substrate. However, guidance, particularly in zk-proof implementation, and introductions to potential partners for real-world data utilization, would greatly accelerate our progress.

We appreciate the patience, understanding, and continued support of the W3F and remain dedicated to turning the Claps Health vision into a reality.

---

2023-08-14 14:25 UTC, keeganquigley commented
Thanks for the detailed update @jacobleegithub much appreciated. No worries, we understand that delays and challenges can occur during development; this is normal. We just want to make sure it keeps being worked on.

If you aren't planning on submitting the delivery in the next four weeks or so, I'd recommend submitting an [amendment](https://github.com/w3f/Grants-Program#2-application-review) to extend the timeline. If you want to wait a couple weeks before submitting to better measure things, that's fine. Thanks!

2023-09-14 18:55 UTC, keeganquigley commented
Hi @jacobleegithub still planning on submitting an amendment?

2023-09-16 00:33 UTC, jacobleegithub commented
Dear @keeganquigley , Should I open a new pull request with new timeline of milestone delivery?
Yes and I will submit an amendment in next 2 days.

Many Thanks!
Jacob

2023-09-16 00:34 UTC, jacobleegithub commented
> Hi @jacobleegithub still planning on submitting an amendment?

Dear @keeganquigley , Should I open a new pull request with new timeline of milestone delivery?
Yes and I will submit an amendment in next 2 days.

Many Thanks!
Jacob

2023-09-18 14:05 UTC, keeganquigley commented
@jacobleegithub yep exactly, that's perfect. Thank you!

2023-10-05 18:23 UTC, keeganquigley commented
Hi @jacobleegithub are you still planning to submit this? Thanks!

2023-10-19 19:44 UTC, keeganquigley commented
Hi @jacobleegithub please note that if we don't hear from you or see an amendment in the next two weeks, the committee will go ahead and file an amendment to close the grant due to inactivity. Thank you.

2023-10-21 02:21 UTC, jacobleegithub commented
@keeganquigley 

Hi Web3 Foundation committee members,

First and foremost, I would like to express my deep appreciation for your continued patience and support throughout our project's journey. The Web3 Foundation's commitment to fostering innovation and collaboration in the blockchain space has always been an inspiration to us.

I sincerely apologize for the delays we've experienced and for not being able to meet the milestones as originally planned. As we communicated in our last update, we encountered unforeseen technical challenges, and unfortunately, constraints in engineering resources have further exacerbated the situation.

We understand the importance of accountability and transparency, especially when it comes to community and grant-driven projects. As such, if the committee feels it's in the best interest to close the grant due to our inability to meet the commitments timely, we accept that decision. While we are deeply saddened by the circumstances, we remain committed to the blockchain space and hope for opportunities to collaborate in the future.

Thank you for your understanding, and we are truly grateful for the opportunity you provided us.

With best regards,

Jacob Lee

2023-10-26 21:56 UTC, keeganquigley commented
Thanks @jacobleegithub for the sentiments.

I completely understand that times are hard for everyone at the moment. I appreciate the update and thank you for your efforts and work thus far. In this case, it's probably best to go ahead and close the grant for now, and you can potentially pick it back up in the future should you choose to continue to work on it. I will go ahead and file the PR.