add ventur-dapps application
w3f/Grants-Program pull request #1507
Opened 2023-02-05 19:32 UTC by Gryczka

# Request for Proposals

## Abstract

This application is a follow-up grant to the [Ventur grant application](https://github.com/w3f/Grants-Program/blob/master/applications/ventur.md) which was [pr #1126](https://github.com/w3f/Grants-Program/pull/1126).

Under the previous [Ventur grant](https://github.com/w3f/Grants-Program/blob/master/applications/ventur.md), our team developed an MVP of Ventur, creating Substrate modules for RFP, Scheduled Payment, Escrow, and Non-Transferable NFT (NT-NFT) functionality.

This grant builds on top of that work, implementing Proof of Concept User Interfaces for 2 core use cases of the NT-NFT pallet.

The 2 dApps we are targeting for this grant are:

* Ventur Verified - A dApp for creating, accepting, and managing credentials and certifications.

* Ventur Subscribed - A dApp for creating subscriptions with an interface for subscribing.

Each dApp will be developed as a React application using the substrate frontend template as a starting point.

For the Ventur Subscribed dApp, we will build out an additional subscription substrate pallet which will be coupled with the existing NT-NFT pallet.

These UIs will initially run against the Substrate based Ventur testnet, with the goal to have Ventur secure parachain slots on Kusama (AdVentur) and Polkadot (Ventur).

Our Team is interested in developing these dApps because we believe they are effective use cases for the core Ventur substrate pallets we developed in our first grant. These dApps will serve as both demos of the use cases that Ventur supports, but also as open source templates for any developers interested in building dApps on Ventur. We believe that both dApps showcase a category of apps that developers can customize to create market-specific offerings.

To further facilitate developer adoption and use, we want to create a developer hub for Ventur as part of this grant.  The developer hub will serve as a central portal for linking to resources like the Ventur pallet documentation, our Ventur node repository on GitHub, and to sample UI implementations for Ventur like the Credentialing and Subscription dApps.

In addition to the UI deliverables, this grant will provide an opportunity for our team to further refine the Ventur Substrate pallets, as we find opportunities to improve their usability based on dApp usage.

## Background

Described in the application.

## Checklist

- [x] I have checked the [RFPs](https://github.com/w3f/Grants-Program/tree/master/docs/rfps) to make sure this is not a duplicate.
- [x] I have read and followed the [RFP Suggestion instructions](https://github.com/w3f/Grants-Program#mailbox_with_mail-suggest-a-project).

2023-02-05 19:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1507) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1507) it.</sub>

2023-02-07 11:28 UTC, 0xCaso reviewed
Hi @Gryczka, thanks a lot for the new application!

What you propose seems more than reasonable, as the previous grant was about the "backend" of your idea, and now it's time for the frontend.

I haven't a lot of comments:
- The main one is: why did you choose to make two different dApps, and not making everything in one (and creating more sections in this one)?
- The second one is: as you wrote about extending the dApps in the **Future Plans**, I imagine you will add an interface to interact, for example, with the `RFP` pallet. In this case, you would make another dApp, or integrating this in one of the two proposed?

Thinking about UX, it would be good to make the interaction as easier as possible for the users. Maybe a great way to do it is one dApp per pallet? So one for the `NT-NFT`, one for the `RFP`...  or otherwise making one unique dApp with different sections. What do you think about it? I guess you already thought about this, so I'd like to know this better :)

2023-02-07 15:52 UTC, dsm-w3f requested changes
Could you please inform if in the parachain slot that you plan to get you will have your own token?

2023-02-07 23:57 UTC, Gryczka commented
Hi @0xCaso ,

For this grant work we wanted to break out the functionality across what we saw as use cases.  We believe these examples should be more directly accessible and consumable by developers if packaged as single purpose modules.  Developers should be able to take the Credential example and repurpose it for their market of choice, whether that's a technical certification, a video game achievement, or even a community badge like FourSquare Swarm.  Likewise, we believe the Subscription example should be directly adaptable too, whether that's a subscription functionality for a single site, or as the basis for a subscription market like Patreon.

So really, we're striving to hit on a format that's most directly and easily consumable.  

I think as a base, one example per pallet makes sense, but we would also want to model the combined use cases we see as directly repurposable.  For our future RFP frontend, our current thinking is that we would want to package both RFP + Credentials within a professional engagement dApp, as we believe that the RFP example will directly benefit from Credential functionality.

For our own purposes, we plan to present these together in flagship example dApps, but our current plan is to have the front ends broken up by functionality as microservices.

2023-02-07 23:59 UTC, Gryczka commented
Hi @dsm-w3f ,

This is an important question, but not one I have a satisfying answer for yet.  We're still putting a great deal of thought into the incentives around the chain.  We see using dot or ksm depending on the relay chain as a potential enabler for adoption removing the barrier of users needing to secure a new token to pay for transaction fees on the network, but we haven't been able to model a good incentive structure for collators and crowdloan contributors before adoption and usage reach a certain threshold without a native token.  We'd certainly welcome further conversations around this topic and would love to hear W3F members' insights.  At the moment, our mention of the intent to pursue a parachain slot is more forward looking and for the purpose of positioning the project within the application's ecosystem positioning.

2023-02-08 19:52 UTC, dsm-w3f commented
@Gryczka let me explain the situation. We generally don't support parachain creations and development of assets that only bring benefits for the creators. We fund common goods for Polkadot/Kusama ecosystem. These Dapps seems to be very specific and tied to Ventur Network don't being "reusable" by the ecosystem. For projects like this, we would recommend Treasury funding, but they don't support projects that has or intend to have your own token. Another option are venture capitalists, which generally doesn't have this kind of restriction. Let's try to figure out what is the best path for this project.

2023-02-23 09:59 UTC, 0xCaso commented
@Gryczka any updates?

2023-03-05 07:24 UTC, Noc2 commented
I'm closing the application for now due to inactivity. Let me know if I should reopen it or if you want to jump on a call to discuss future funding possibilities.

2023-03-05 07:24 UTC, closed without merging