Xcavate 2023 W3F grant application
w3f/Grants-Program pull request #1519
Opened 2023-02-07 16:12 UTC by xcavate2022

- **Project Name:** Xcavate
- **Team Name:** Xcavate
- **Payment Address:** 4pjePvJgUZAMKtnSmYJitGacxBRnsKe1GvCb1t6vgg2Kof8o 
- **Level:** 3 = $319200
- **Total Project Cost** $319200

## Project Overview

Xcavate will become a completely decentralised lending and NFT protocol to help fund the building of real world real estate assets as well as transact and manage fractions of each property in a permissionless environment. Our goal is to create a full framework and SDK that can be used by dApp developers to enable the onboarding of assets from a globally inclusive market, bringing together a community of real estate developers, investors and blockchain developers.

![](https://www.youtube.com/watch?v=rEex6M9620U&t=1s)

### Overview

Xcavate will be a first-of-its-kind real-world land & property NFT platform that collateralizes real world parcels of land to finance real estate development. 
Xcavate facilitates digitizing land and/or property title deeds through minting and bundling of NFTs, which are then linked to verifiable digital identities (DIDs) approved by government entities.
Xcavate is an ecosystem that allows real-world property developers access to finance parcels of physical land with planning permission for development. Once the land is at the final development stage, the developer will create NFTs for the individual properties to be sold/managed by a peer-to-peer marketplace (property owners, investors, trusts etc.). 
The system will significantly reduce the time from real estate planning permission to build start. By simplifying the finance application process and speeding up the release of funds to the developer. Xcavate not only provides real-world property developers with a way to build quicker but, as a result, enables a more significant number of much-needed houses to be delivered to market. It also provides liquidity to static real-world assets at every stage of the property development process in a fair and risk-averse way. It will enable the real estate to be onboarded cleanly and efficiently, opening up opportunities throughout the broader Dotsama ecosystem.

![](https://www.youtube.com/watch?v=YjVfwjt_m3g)

![](https://www.youtube.com/watch?v=7pD8NVHUBwE)

### Project Details

We will be using an agile methodology for the development of this project. We will use a design to development process to deliver the best user experience. Followed by an engineer's engagement based on approved designs. We will build an agile board open to W3F and partners for complete project transparency.  This will allow everyone involved to see all milestones, roadblocks and added scope in real-time. We will still have weekly updates internally, but this methodology will enable W3F to be in the know at all times. Our organizational goal is to achieve a simplistic way for everyone involved to monitor progress and to be in the know at all times. In addition, we would like to set up and maintain the quality of code and delivery to production processes through GitHub that all involved will have access to review. We understand that in pursuit of these objectives, W3F has their standards, and we will always strive to exceed them as partners. We have chosen the below technology stack and already have a significant amount of experience to deliver this project in these technologies. We have also already spent a reasonable amount of time meeting and learning about our partners and their unique technologies.

Xcavate will develop multiple Pallets to execute the functionalities. We will use the substrate framework and primary language Rust to create the pallets on the Polkadot ecosystem.

Token Pallet
Decentralized Identity Document pallet
User Management pallet
Loan Management pallet
Transaction management pallet
Staking pallet
Verification pallet

This Architecture diagram shows the visual representation that maps out the physical implementation for components in the Polkadot ecosystem and how the scalability of the platform works. The diagram represents Microservices we are using to execute the functionality. API gateway will split the API calls to the respective microservices. We are using an s3 bucket to store the media files. We are using pallets to execute the functions on the Polkadot ecosystem.

![](https://xcavate.io//W3F/XCAV-WEB-3-Grant-Application-Image-4.jpg)

Token:
XCAV - Platforms Native Token to launch a para chain and participate in a crowd loan/slot auction. XCAV tokens are used to stake within the platform. We will create these tokens with the Transfer, Mint, Burn, Approve, and Allowance functions.
Liquidity Pool:
Xcavate creates a liquidity pool to store staked tokens, staked tokens will be queued and utilized for each loan application. XCAV tokens are swapped as GBPT through XCM and deposited on the Central Loan pool.
Central Loan Pool:
Xcavate Creates a central loan pool to manage Loan amounts and Loan repayment. The central lending pool will act as the heart of the platform to map all the transactions.

### Technology Stack

React.js
Node.js
Express.js
Rust
Substrate Framework
Polkadot

### Third-Party

Kilt – SDK 			Statemint
Chainlink 			Property Data
Crust

### Ecosystem Fit

After many months of research, we initially met on a zoom with Ingo from Kilt, discussing our idea and talking through how the Kilt chain can be incorporated into the Xcavate system. A few weeks later, we contacted Acala and met with Robinson, who was very helpful and enthusiastic about us being involved in the ecosystem and our potential partnership. We also reached Centrifuge and spent many weeks looking through their docs with the initial idea of creating a dApp on their chain, but as there were some striking differences in how their chain operated, it was apparent that was not going to be the best fit for our project. Going forward, however, once the real estate has been built, there will be opportunities for us to introduce Centrifuge.

We feel this is a great way to bring land & Property assets into the digital ecosystem to interact with the following potential partners:

**Kilt (Identity & wallet)**
This is a crucial part of the initial process to verify; Real Estate Director, Company & Title Deed and create DID’s, which will be held in a Sporran Wallet and used throughout.
**Chainlink (Oracle)**
To accurately value and risk rate land and the completed real estate, we need to build Oracles that enable off-chain APIs to feed data into an algorithm which delivers the personalized loan APR. In the first phase, we will build a Chainlink Oracle that relies on https://propertydata.co.uk/ for its data.
**Statemint / Acala**
There are many stages of financing that will involve aUSD / USDT / GDPT… from the initial funding pool, a liquidity pool, as well as the need to exchange the locked loan value for each project in GBP stable coins (as our initial market is based in the UK).
**XCM (Crosschain)**
As our user base is only used to the web2.0 space, we will need a seamless front end that hides the complexities of the many transactions below the hood. XCM will be the enabler for this to happen.

## Team :busts_in_silhouette:

### Team members

Richard Houldsworth – CTO 
Alex Ward – COO
Akash Takyar - Management Sponsor
Deepak Shokeen - Chief Engineer
Kapil Saxena - Design Head

### Contact

Richard Houldsworth – +44 7798 666 710 
Alex Ward – +44 7779 885964 
xcavate.io

### Legal Structure

H & W Investments Limited 
17 College Road, Cheshunt EN8 9LS, United Kingdom

### Team's experience

Richard Houldsworth – 10 years in web 2.0 dev space – serial Entrepreneur
Alex Ward – 25 years in the global property market – serial Entrepreneur
Akash Takyar - Akash has a master’s in computer application with a deep understanding of IoT and Blockchain. Akash is a world-renowned expert, blockchain influencer, and technical architect.
Deepak Shokeen - With over 20 years of experience engineering and developing apps. He has a deep understanding of building Cloud, IoT, and Blockc [...]

2023-02-07 16:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1519) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1519) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1519) it.</sub>

2023-02-08 20:53 UTC, xcavate2022 commented
Apologies David… the other file was left over from a previous grant application last year… I’ve deleted that file so only the current one remains

Best Regards,

Richard

> On 8 Feb 2023, at 16:36, David Hawig ***@***.***> wrote:
> 
> 
> @Noc2 requested changes on this pull request.
> 
> Thanks for your interest in the grants program. I have one quick initial comment: You are currently adding two files as part of this PR (= two grant applications). Could you only apply for one grant at a time? We usually also like to start with one grant per team to get a better impression of the team.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/w3f/Grants-Program/pull/1519#pullrequestreview-1289570757>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A2OSX7D6ON3LY7DB4JPPPXLWWPDQRANCNFSM6AAAAAAUUFGC44>.
> You are receiving this because you authored the thread.
>

2023-02-10 08:29 UTC, Noc2 requested changes
Thanks for the update. For future reference, here is a link to your previous application:  https://github.com/w3f/Grants-Program/pull/1266 

I have a couple of comments/questions regarding your application: 

- All milestones need to have a milestone table with concrete technical deliverables that we can evaluate, and these are the requirements of our contracts (open source license of the deliveries, etc.). See also the default deliverables of the template 
- There seems to be an issue with the formatting of your first milestone table, see 8 Substrate
- You don’t need to include in the milestone table things that you don’t deliver, regarding “Smart contracts”  
- We don’t support the deployment of software in production. 
- Each deliverable should be unique and provide something new. For example, how is your NFT module different from existing solutions?

2023-02-10 08:31 UTC, xcavate2022 commented
No problem… I’ll speak to our development team and amend the grant application asapAll the bestRichardSent from my iPhoneOn 10 Feb 2023, at 08:29, David Hawig ***@***.***> wrote:﻿
@Noc2 requested changes on this pull request.

Thanks for the update. For future reference, here is a link to your previous application:  #1266
I have a couple of comments/questions regarding your application:

All milestones need to have a milestone table with concrete technical deliverables that we can evaluate, and these are the requirements of our contracts (open source license of the deliveries, etc.). See also the default deliverables of the template
There seems to be an issue with the formatting of your first milestone table, see 8 Substrate
You don’t need to include in the milestone table things that you don’t deliver, regarding “Smart contracts”
We don’t support the deployment of software in production.
Each deliverable should be unique and provide something new. For example, how is your NFT module different from existing solutions?


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-02-21 12:45 UTC, Noc2 commented
I'm closing the application for now due to inactivity. Let me know if I should reopen it.

2023-02-21 12:45 UTC, closed without merging

2023-03-31 07:44 UTC, Noc2 commented
@xcavate2022 in general, it's usually better to apply for a small part of the project or a PoC and provide as many technical details as possible for it. So feel free to apply.

2023-03-31 07:49 UTC, xcavate2022 commented
thank you very much David… I’ll revise the grant application accordingly :)

Richard J Houldsworth
m 07798 666 710
www.xcavate.io


CONFIDENTIALITY: This email and its attachments are confidential to the intended recipient only. They may not be used by, disclosed to or copied in any way to anyone other than the intended recipient. If this email is received in error, please contact ***@***.***
 
Disclaimer STRICTLY CONFIDENTIAL The contents of this email and any attachments are confidential and intended solely for the organisation or individual to whom it is addressed. If you are not the intended recipient, you must not copy, print, forward, distribute or disseminate the information, or take any action in reliance of it. If you have received this message in error, do not open any attachment but please notify the sender above and delete this email from your system.






> On 31 Mar 2023, at 08:44, David Hawig ***@***.***> wrote:
> 
> 
> @xcavate2022 <https://github.com/xcavate2022> in general, it's usually better to apply for a small part of the project or a PoC and provide as many technical details as possible for it. So feel free to apply.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/w3f/Grants-Program/pull/1519#issuecomment-1491457862>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A2OSX7CRFE4APM54CO45OATW62DNJANCNFSM6AAAAAAUUFGC44>.
> You are receiving this because you were mentioned.
>

2023-04-03 16:29 UTC, xcavate2022 commented
Hi David,

I have revised the W3F Grant application to only focus on the PoC of the lending protocol aspect of the dApp

https://github.com/xcavate2022/Grants-Program/blob/master/applications/Xcavate.md <https://github.com/xcavate2022/Grants-Program/blob/master/applications/Xcavate.md>

I look forward to your feedback

All the best

Richard

Richard J Houldsworth
m 07798 666 710
www.xcavate.io


CONFIDENTIALITY: This email and its attachments are confidential to the intended recipient only. They may not be used by, disclosed to or copied in any way to anyone other than the intended recipient. If this email is received in error, please contact ***@***.***
 
Disclaimer STRICTLY CONFIDENTIAL The contents of this email and any attachments are confidential and intended solely for the organisation or individual to whom it is addressed. If you are not the intended recipient, you must not copy, print, forward, distribute or disseminate the information, or take any action in reliance of it. If you have received this message in error, do not open any attachment but please notify the sender above and delete this email from your system.


> On 31 Mar 2023, at 08:44, David Hawig ***@***.***> wrote:
> 
> 
> @xcavate2022 <https://github.com/xcavate2022> in general, it's usually better to apply for a small part of the project or a PoC and provide as many technical details as possible for it. So feel free to apply.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/w3f/Grants-Program/pull/1519#issuecomment-1491457862>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A2OSX7CRFE4APM54CO45OATW62DNJANCNFSM6AAAAAAUUFGC44>.
> You are receiving this because you were mentioned.
>

2023-04-03 18:49 UTC, semuelle commented
Could you submit a new pull request for the new application, @xcavate2022 ? This one still contains all the information from the original one, so it might be too confusing to continue here.

2023-04-03 19:36 UTC, xcavate2022 commented
ok now?

Richard J Houldsworth
m 07798 666 710
www.xcavate.io


CONFIDENTIALITY: This email and its attachments are confidential to the intended recipient only. They may not be used by, disclosed to or copied in any way to anyone other than the intended recipient. If this email is received in error, please contact ***@***.***
 
Disclaimer STRICTLY CONFIDENTIAL The contents of this email and any attachments are confidential and intended solely for the organisation or individual to whom it is addressed. If you are not the intended recipient, you must not copy, print, forward, distribute or disseminate the information, or take any action in reliance of it. If you have received this message in error, do not open any attachment but please notify the sender above and delete this email from your system.






> On 3 Apr 2023, at 19:49, Sebastian Müller ***@***.***> wrote:
> 
> 
> Could you submit a new pull request for the new application, @xcavate2022 <https://github.com/xcavate2022> ? This one still contains all the information from the original one, so it might be too confusing to continue here.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/w3f/Grants-Program/pull/1519#issuecomment-1494809727>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A2OSX7D5IRJC7DCOAUCLPIDW7MLT3ANCNFSM6AAAAAAUUFGC44>.
> You are receiving this because you were mentioned.
>

2023-04-04 11:50 UTC, semuelle commented
Looks good. Thanks, @xcavate2022. Let's continue the conversation [there](https://github.com/w3f/Grants-Program/pull/1649).