feat(rfp): alternative javascript console for polkadot js API
w3f/Grants-Program pull request #1545
Opened 2023-02-16 17:35 UTC by muddlebee

wrt #1235 
@0xCaso

2023-02-16 17:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1545) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1545) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1545) it.</sub>

2023-02-16 17:55 UTC, muddlebee commented
wrt #1235 
@0xCaso

2023-02-17 09:18 UTC, 0xCaso reviewed
Thanks for the re-submission @muddlebee.

As I wrote in the original issue, could you please re-format the document following the [RFP template](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/suggestion-template.md)?

2023-02-18 16:32 UTC, muddlebee commented
@0xCaso apologies. missed it. 
I have fixed it now according to the format. Any suggestions/improvements to this RFP please let me know 🥂

2023-02-20 11:59 UTC, Noc2 requested changes
Thanks a lot for creating the RFP. I have one question/comment: Would you be interested in using this new javascript console personally or as part of a project, and if so, why? Maybe this will help to show the usefulness of the RFPs also to others.

2023-02-21 08:26 UTC, Noc2 approved these changes
Thanks for the quick reply. I'm generally happy to merge the RFP. But maybe you can also integrate these use cases into the RFP itself.

2023-02-21 09:16 UTC, semuelle requested changes

2023-02-21 10:49 UTC, semuelle reviewed
Getting (significant) changes merged into `apps` has proven difficult in the past. I think this RFP should either be standalone or contributed to some other established project.

2023-02-21 16:02 UTC, muddlebee commented
@semuelle my suggestion for this RFP was meant to be a standalone project as I have mentioned in the title of the project.
> Alternative javascript console for Polkadot JS API

Please let me know if I need to clarify more about the details in the RFP?

2023-02-21 16:03 UTC, Noc2 submitted a review, later dismissed

2023-02-21 16:16 UTC, muddlebee commented
@Noc2 I have mentioned the use cases towards the end of the RFP doc at the Deliverables section. Please let me know if I need to clarify more?

2023-02-21 18:42 UTC, semuelle approved these changes
Great, thanks.

2023-02-21 20:04 UTC, keeganquigley requested changes
Thanks for the submission @muddlebee, I made a few minor edit suggestions to clean up the language a bit.

2023-02-21 20:04 UTC, keeganquigley commented on docs/RFPs/Open/alternative-polkadot-js-api-console.md
> +A new polkadot js API playground with vs-code like configurations like save the code, workspace, keyboard shortcuts etc etc..
```suggestion
A new Polkadot-JS API playground with VS Code-like configurations like save the code, workspace, keyboard shortcuts, etc.
```

2023-02-21 20:04 UTC, keeganquigley commented on docs/RFPs/Open/alternative-polkadot-js-api-console.md
> +**Why alternative javascript console for for polkadot js API**
```suggestion
**Why alternative javascript console for Polkadot-JS API**?
```

2023-02-21 20:04 UTC, keeganquigley commented on docs/RFPs/Open/alternative-polkadot-js-api-console.md
> +    more features which makes the polkadot js experience productive and smoother are welcome
```suggestion
    Any additional features which make the Polkadot-JS experience more productive and smoother are welcome.
```

2023-02-21 21:02 UTC, randombishop submitted a review, later dismissed
LG

2023-02-22 03:43 UTC, muddlebee commented
@keeganquigley thank you for the suggestions. I have committed the changes as per the request 🎉

2023-02-22 10:47 UTC, semuelle approved these changes

2023-02-22 11:02 UTC, Noc2 approved these changes

2023-02-22 14:40 UTC, keeganquigley approved these changes

2023-02-22 14:55 UTC, merged