Solidity implementation of an on-chain accountable light client verifier
w3f/Grants-Program pull request #1546
Opened 2023-02-17 11:49 UTC by hackfisher

#### Project Abstract

One solidity implementation of an on-chain accountable light client verifier based on a recent [paper](https://eprint.iacr.org/2022/1205).

After reading the paper, we found it to be extremely valuable. It presents an efficient method for utilising SNARK to verify the aggregated public key of signers, while still holding those signers accountable. This approach greatly improves the speed and cost-effectiveness of proof generation.

This verifier will be implemented based on the BLS12-377 and BW6-761 elliptic curves, which is consistent with the implementation in the paper and [W3F's PoC implementation](https://github.com/w3f/apk-proofs).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@wuminzhe:matrix.org` (change the homeserver if you use a different one)

2023-02-17 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1546) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1546) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1546) it.</sub>

2023-02-21 11:49 UTC, AlistairStewart commented
Cool, I'm glad people are interested in this. Obvious question, BLS12-377 and BW6-761 do not have precompiles on Ethereum, but there are EIPs for them and Celo have an EVM with these precompiles. Are you going to write Solidity code assuming that the EVM has such precompiles? It's certainly feasible to have them for a substrate EVM. 

We are evaluating whether to use BLS12-381 instead of BLS12-377, ana that will be supported by Ethereum and most EVM chains sometime, but [the corresponding BW6 curve](https://ethresear.ch/t/bw6-over-bls12-381/10321) probably won't have precompiles.

2023-03-13 12:56 UTC, Noc2 requested changes
(requested changes in the private room)

2023-03-16 08:35 UTC, Noc2 approved these changes
Thanks for the update. I'm happy to go ahead with it.

2023-03-16 09:11 UTC, semuelle approved these changes
LGTM

2023-03-20 07:06 UTC, Noc2 submitted a review, later dismissed

2023-03-22 12:56 UTC, semuelle approved these changes

2023-03-23 00:33 UTC, randombishop approved these changes
Exciting project pushing the limits of light clients and making them lighter at the same time. 
Learnt a lot by reading this application and excited to see this kind of progress!

2023-03-28 08:01 UTC, takahser submitted a review, later dismissed

2023-03-29 07:05 UTC, Noc2 approved these changes

2023-03-29 07:09 UTC, randombishop approved these changes

2023-03-29 07:34 UTC, semuelle approved these changes

2023-03-29 13:36 UTC, keeganquigley approved these changes

2023-03-29 13:38 UTC, merged