Cyclops Grant Request
w3f/Grants-Program pull request #1549
Opened 2023-02-17 23:05 UTC by ArthurHoeke

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-02-17 23:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1549) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1549) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1549) it.</sub>

2023-02-18 00:30 UTC, keeganquigley requested changes
Hi @ArthurHoeke thanks for the application. I think this app could be very useful. Please see my initial review below:

- Can you specify which [payment method](https://github.com/w3f/Grants-Program#pencil-process) you are choosing [here](https://github.com/w3f/Grants-Program/pull/1549/files#diff-f7abfc747043301f2315a37ab6df6949fea9da212a19b0a89f3f3f0bca0a1c8dR4)? (USDC, DAI, etc.)
- I'm curious if you can give a bit of insight into the benefits of using PHP over something else?
- Why do you want to go with a traditional email/password login system? Personally I'm not in favor of supporting a typical OAuth setup unless there is an option to connect to an extension wallet instead. Is this necessary to get email notifications?

2023-02-18 10:11 UTC, ArthurHoeke commented
> Hi @ArthurHoeke thanks for the application. I think this app could be very useful. Please see my initial review below:
> 
> * Can you specify which [payment method](https://github.com/w3f/Grants-Program#pencil-process) you are choosing [here](https://github.com/w3f/Grants-Program/pull/1549/files#diff-f7abfc747043301f2315a37ab6df6949fea9da212a19b0a89f3f3f0bca0a1c8dR4)? (USDC, DAI, etc.)
> * I'm curious if you can give a bit of insight into the benefits of using PHP over something else?
> * Why do you want to go with a traditional email/password login system? Personally I'm not in favor of supporting a typical OAuth setup unless there is an option to connect to an extension wallet instead. Is this necessary to get email notifications?

Thanks for the quick initial review! I've updated the payment method.

The reason I have decided to use PHP over say a node REST API is because of the hosting benefits. The current PoC uses socketJS, which by all accounts works fine though I've found it to be rather over-kill seeing the dashboard data does not require to be updated by the second. Developing the middleware on PHP means that the entire dashboard can be hosted on a simple apache server, which cuts server costs and makes it a fair bit easier to setup. This way operators can easily self-host on their already existing webservers.

As for the traditional email/username/password OAuth, I've personally found it to be the easiest and most reliable UX. I have published an app version of our proof-of-concept on Android, and using a traditional login just keeps things simple and lightweight in my opinion. I'd be open to look into supporting wallet login in the future.

2023-02-19 20:08 UTC, keeganquigley commented
@ArthurHoeke thanks for the changes and insights! I will mark your application as ready for review and share with the committee.

2023-02-20 08:16 UTC, Noc2 requested changes
Thanks a lot for the application. This sounds like a useful project. I have just a couple of comments/ideas:

- It would be nice if you could also integrate some kind of tracking for era points. Usually, they are random, but if the setup of a company is, for example, very low hardware vise or the networking connections are bad, they receive fewer era points compared to others. Not sure if you mean this by “​​Income tracking.” 
- Also, it would be nice to see how often a validator was slashed in the past or reported offline. 
- Finally, it might be useful to list all the nominators of a certain validator, including the once that aren’t active.

2023-02-20 08:47 UTC, ArthurHoeke commented
> Thanks a lot for the application. This sounds like a useful project. I have just a couple of comments/ideas:
> 
> * It would be nice if you could also integrate some kind of tracking for era points. Usually, they are random, but if the setup of a company is, for example, very low hardware vise or the networking connections are bad, they receive fewer era points compared to others. Not sure if you mean this by “​​Income tracking.”
> * Also, it would be nice to see how often a validator was slashed in the past or reported offline.
> * Finally, it might be useful to list all the nominators of a certain validator, including the once that aren’t active.

Thanks for sharing your ideas! The middleware will use subscan's API to gather data, which means that for some functionality we're bound to which data / end-points subscan provides.

- Era point tracking is a great idea and shouldn't be an issue API-wise. Income tracking is reward tracking :)
- Tracking historic slash events is possible, offline events I'm not 100% certain on API-wise.
- Nominator list isn't a problem either.

2023-02-20 13:47 UTC, Noc2 commented
Thanks for the super quick reply. Would you be willing to integrate, for example, support for era points into the current application? If so, feel free to update the PR.

2023-02-20 14:41 UTC, ArthurHoeke commented
> Thanks for the super quick reply. Would you be willing to integrate, for example, support for era points into the current application? If so, feel free to update the PR.

Sure thing, I've included ERA point tracking into the application feature set. Nomination list & historic event tracking will be shelved for now until phase 3 has been completed.

2023-02-20 15:29 UTC, Noc2 approved these changes
Thanks for the update. I'm happy to go ahead with it.

2023-02-20 16:01 UTC, keeganquigley approved these changes
thanks @ArthurHoeke I think validators will find this tool useful, happy to approve it as well.

2023-02-20 17:29 UTC, gautamdhameja approved these changes

2023-02-20 18:42 UTC, merged