DeSci Platform - application to Grants Program
w3f/Grants-Program pull request #1564
Opened 2023-02-23 17:14 UTC by detechworld-dev

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-02-23 17:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1564) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1564) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: detechworld-dev<br/>:x: UladzislauVintsarevich<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1564) it.</sub>

2023-02-23 17:22 UTC, detechworld-dev commented
We would like to drive DeSci segment within the Polkadot ecosystem. We are focusing on delivering technology show-casing, co-creation, IP assessment and early stage research funding tools for the DeSci community and growing number of technological DAOs. It's the first application of DeTech.World to Grants Program.

2023-02-24 09:34 UTC, semuelle requested changes
Thank you for your application, @detechworld-dev. I have a couple of preliminary questions.

- Didn't (some of) you already do something very similar with DEIP? 
- Can you share how you verified the product/market fit? Are there established web3-based licensing platforms yet? 
- Can you expand on how your multi-chain strategy looks like? Will the data be "in sync" or parallel?
- I noticed that there are specifications for some of the deliverables in the roadmap doc you linked. The specification needs to be in this document, as it'll be part of the contract that would be signed. If you could add those here, that'd be great.

Generally speaking, this grant covers so much material that I'd suggest starting with a subset of the deliverables/milestones, perhaps with a proof of concept with a subset of features or pallets as the goal. There are very complex topics nested as one of several points under a single deliverable (e.g. `Crowdfunding pallet` as part of D4.1), that I would recommend expanding the list of deliverables to separate the pallets and include a thorough specification for each.

2023-02-27 18:57 UTC, detechworld-dev commented
[semuelle](https://github.com/semuelle) thank you for your questions!

- What is about comparison with DEIP: no, we have our own approach with unique insights on Decentralized Science (DeSci), tech DAOs and technology transfer process.
- On product/market fit, we’ve got feedback from pilots that our platform is the only native Web3 offering for the technology transfer segment, whereas the Web2 offering is rather segmented and mainly focuses on process automation or contract management. In fact, we offer a holistic approach (all-in-one) including process automation, contract management, tech show-casing, IP management, co-creation, assessment, funding, and licensing alongside true Web3 benefits (vs Web2): immutability, traceability, composability, plus economic layer with IP-NFTs and nested licensing. Plus, our business model is a true partnership mode implying only revenue sharing and no upfront, license, or subscription payments.
Currently, there are no established Web3 licensing platforms, one competitor is trying to issue NFTs linked to the existing patents with potential licensing. In our approach, we focus more on the early stage (pre-patent phase), where most of the promising tech discoveries die due to the so-called “valley of innovation death” phenomena, here we see the biggest potential for new tech breakthroughs. For sure, our IP-NFTs with bidirectional legal binding are fully applicable for the patents as well.
- In our multi-chain strategy design, we’ve been considering Polkadot multi-chain approach with XCM/XCMP vs Cosmos IBC which is a more general-purpose one. We see clear benefits of XCM/XCMP due to the cross-chain composability. Moreover, especially for XCM v3, the Programmability features are very interesting allowing to exchange of assets and NFTs between different consensus systems. Also, XCM v3 Bridging features are enabling transparency over bridges and multi-hops. Finally, a concept of the Universal location addressing for all consensus systems creates a very sound foundation for the multi-chain meta layer. Therefore, having realized our DeSci platform on the substrate, the utilization of the XCM/XCMP approach is our favorite option for the multi-chain strategy.
- The specification column of milestones section was updated: all deliverables were defined there according to recommendation above.

2023-02-28 17:02 UTC, semuelle commented
Thanks for the update, @detechworld-dev. I still think that a smaller initial grant would be preferable, but I am going to share your application with my colleagues to review, who might have other ideas.

2023-03-01 09:00 UTC, Noc2 requested changes
Thanks for the application: I have two initial questions: 

- How do you plan to handle privacy and potential legal problems (e.g., GDPR)? It looks like, at the moment, users will upload their personal data on-chain. 
- Could you explain a little bit more about how you plan to store the data as part of the milestone specification? For example, is the project information stored on-chain or on IPFS or something similar? How are you planning to integrate off-chain storage?

2023-03-02 10:29 UTC, detechworld-dev commented
[Noc2](https://github.com/Noc2) thank you for your questions, it's really a very important issue to address!

> Thanks for the application: I have two initial questions:
> 
> * How do you plan to handle privacy and potential legal problems (e.g., GDPR)? It looks like, at the moment, users will upload their personal data on-chain.
> * Could you explain a little bit more about how you plan to store the data as part of the milestone specification? For example, is the project information stored on-chain or on IPFS or something similar? How are you planning to integrate off-chain storage?

* To comply to EU GDPR for private data we will ask consent from individuals before collecting and storing their personal data. To enable capability to edit and delete, private data will be stored on the off-chain storage MangoDB located in EU. Ultimately, we target to integrate a fully-fledged SSI module on substrate. Please refer to the updated architecture description in application for details.

* Structure of the stored data: personal data, legal and other sensitive content -> encrypted on MangoDB, general  public project and technology data and references stored on ipfs/s3 and on-chain within related metadata. Please refer to the amended application for details.

2023-03-05 07:20 UTC, Noc2 requested changes
Thanks for the reply. You mean MongoDB, correct? In this case, how would you like to integrate this functionality? Do you plan to use off-chain workers? If the BIO pallet, for example, links to a centralized database, I would say there is no need to leverage a pallet in the first place since, ultimately, the database owner is in control.

2023-03-05 15:43 UTC, detechworld-dev commented
[Noc2](https://github.com/Noc2), previously, you asked to comply with the GDPR, which motivated selection of the MongoDB for the private data storage. At the same time some minimum of data related to ECI is put on-chain while minimizing used amount of data and pseudonymization it by replacing personal data with identifier, so that the data cannot be directly linked to an individual, also obtaining explicit consent for usage. For sure, compliance with GDPR while storing minimum data on-chain requires a careful balance between the data required for the services to function and data subjects' privacy rights, which ultimately can be solved by implementing a full SSI module, which is on our roadmap as well.

2023-03-09 13:07 UTC, detechworld-dev commented
[Noc2](https://github.com/Noc2), thanks a lot for your feedback! We are willing to learn from the world’s best domain experts and thus in terms of best-knowledge-sharing. We would really appreciate if you can specify an example of how to solve the dilemma of complying with GDPR and putting some private data on-chain in a more innovative way (except for SSI ZK approach). Thank you in advance!

2023-03-10 00:20 UTC, keeganquigley commented
Thanks for the application @detechworld-dev

- I agree with the other committee members that the price is a bit high for a team in which we don't have any experience with their work. Would you be willing to focus on a smaller scope for a level 1 or 2 PoC and then apply for follow-up grants?
- The GH profiles of your devs either don't have much activity or it is in private repos. Do you have any previous work examples you can link to?
- I see you were previously working with other blockchains such as Polygon and Near; can you give some insight on why you pivoted to building substrate pallets? Is there any proof of this concept working via smart contracts on other chains?
- Are you able to expand the technical information in the deliverable tables, for example, how will the functionalities for the Assessment pallet work? What structs will be built, what traits will be implemented, etc?
- You mention utilizing XCM but I don't see it in the deliverables. Can you explain how it will be used? Thanks!

2023-03-10 07:56 UTC, Noc2 commented
> [Noc2](https://github.com/Noc2), thanks a lot for your feedback! We are willing to learn from the world’s best domain experts and thus in terms of best-knowledge-sharing. We would really appreciate if you can specify an example of how to solve the dilemma of complying with GDPR and putting some private data on-chain in a more innovative way (except for SSI ZK approach). Thank you in advance!

Working with IPFS clusters instead of MongoDB might be a more decentralized solution that can still be GDPR compliant. Apart from this, there are a few initiatives that focus on decentralized databases that might be worth taking a look at, for example: https://tableland.xyz/

2023-03-10 10:44 UTC, detechworld-dev commented
[keeganquigley](https://github.com/keeganquigley), [Noc2](https://github.com/Noc2), thanks a lot for the insights. In fact, looking at GDPR compliance we’ve not considered decentralized storage clusters as IPFS, Arweave, etc due to 2 main reasons:
 1. GDPR requirement is to store private data locally in EU.
 2. Data to be deleted which might be a challenge on IPFS as well.
As for Tableland, a very nice SQL approach focused on EVMs. 
Thanks again for your insights!

2023-03-10 18:56 UTC, detechworld-dev commented
Thanks a lot for your feedback!
Our main target with this grant is to partner with Polkadot to open up a DeSci segment within an ecosystem. Multi-chain capability is an absolute MUST for our strategy and thus we see a compelling way towards this with Polka, mainly due to the XCM readiness and future-proof roadmap.

Therefore, following your advice we’ve reduced the application scope to the POC Level 2. Please refer to the amended application. We are confident to demonstrate our capabilities within this POC. So, let’s quickly finalize the application process and start building.

2023-03-14 15:24 UTC, Noc2 requested changes
Thanks a lot for the update and the reduced price. However, currently, you would only deliver two relatively simple pallets (all on-chain logic) as part of the grant, that probably won’t be useful for anyone else. Or are these pallets coming with some kind off-chain integration, e.g., for the upload or something similar? If so, could you please add this to the deliverables?

2023-03-15 10:12 UTC, semuelle commented
This application is now a Level 2, I have changed the PR text to reflect that.

2023-03-15 11:58 UTC, detechworld-dev commented
[Noc2](https://github.com/Noc2) thanks for your feedback, we amended the proposal according to your requirements: add integrations to deliverables.

2023-03-15 12:07 UTC, detechworld-dev commented
> Thanks a lot for the update and the reduced price. However, currently, you would only deliver two relatively simple pallets (all on-chain logic) as part of the grant, that probably won’t be useful for anyone else. Or are these pallets coming with some kind off-chain integration, e.g., for the upload or something similar? If so, could you please add this to the deliverables?

[Noc2](https://github.com/Noc2) thanks for your feedback, we amended the proposal according to your requirements: add integrations to deliverables.

2023-03-15 12:27 UTC, Noc2 requested changes
Thanks for the update. Could you add a few more technical details to the newly added deliveries? For example: What is the programming language/framework for the UI? Will the UI be based on the mock-ups? What exactly do you mean by "polkadot wallet integration"? Do you mean the UI will support the polkadot extension?

2023-03-15 13:22 UTC, detechworld-dev commented
[Noc2](https://github.com/Noc2), thanks for your feedback. Here the answers to your questions:
-UI will be based on React + React Query + GraphQL
-UI will be based on the POC level basic design 
-UI will support the polkadot wallet extension
The details about UI tech stack are amended to the application.

2023-03-21 07:29 UTC, detechworld reviewed
Add details about tech stack into application

2023-03-21 07:31 UTC, detechworld-dev commented
> Thanks for the update. Could you add a few more technical details to the newly added deliveries? For example: What is the programming language/framework for the UI? Will the UI be based on the mock-ups? What exactly do you mean by "polkadot wallet integration"? Do you mean the UI will support the polkadot extension?

2023-03-21 07:32 UTC, detechworld commented
> Thank you for your application, @detechworld-dev. I have a couple of preliminary questions.
> 
> * Didn't (some of) you already do something very similar with DEIP?
> * Can you share how you verified the product/market fit? Are there established web3-based licensing platforms yet?
> * Can you expand on how your multi-chain strategy looks like? Will the data be "in sync" or parallel?
> * I noticed that there are specifications for some of the deliverables in the roadmap doc you linked. The specification needs to be in this document, as it'll be part of the contract that would be signed. If you could add those here, that'd be great.
> 
> Generally speaking, this grant covers so much material that I'd suggest starting with a subset of the deliverables/milestones, perhaps with a proof of concept with a subset of features or pallets as the goal. There are very complex topics nested as one of several points under a single deliverable (e.g. `Crowdfunding pallet` as part of D4.1), that I would recommend expanding the list of deliverables to separate the pallets and include a thorough specification for each.

Updated application according to your recommendations.

2023-03-21 07:33 UTC, detechworld commented
> Thanks for the update. Could you add a few more technical details to the newly added deliveries? For example: What is the programming language/framework for the UI? Will the UI be based on the mock-ups? What exactly do you mean by "polkadot wallet integration"? Do you mean the UI will support the polkadot extension?

Added details to application - waiting for your feedback

2023-03-21 10:56 UTC, detechworld-dev commented
[semuelle](https://github.com/semuelle) 
Hello, we updated a week ago our application #1564 according to all your requests. When I try to re-request review and to return PR back on "Review required", I see a 404 error page. I tried to make quoted reply on your requests - it didn't help to fix an issue with "Re-request review" action. Therefore, could you please help us with the workflow of application review to ensure the right setting parameters  to move forward. Moreover, it would be also great to clarify what are the next steps in the process. Thank you in advance.

2023-03-23 11:09 UTC, semuelle commented
Thanks for the updates, @detechworld-dev. Did you answer @keeganquigley's questions from [his comment above](https://github.com/w3f/Grants-Program/pull/1564#issuecomment-1463026572)? Maybe I missed it, but I'd be interested to hear your replies (minus the scope and technical details questions, which you already addressed).

2023-03-23 13:10 UTC, detechworld-dev commented
> Thanks for the updates, @detechworld-dev. Did you answer @keeganquigley's questions from [his comment above](https://github.com/w3f/Grants-Program/pull/1564#issuecomment-1463026572)? Maybe I missed it, but I'd be interested to hear your replies (minus the scope and technical details questions, which you already addressed).

Dear @semuelle thank you for your feedback. Some questions have been answered with other comments, some have become not relevant after the scope changes. So, to be clear on this, I sum up the all changes below.
 1. Scope: the initial scope of proposal has been reduced to the POC according to your request, please refer to the details in the updated application.
 2. We’re fully committed to demonstrate our capabilities during the POC, if you like to look at our latest code, we added Keegan to the private repositories. @keeganquigley, please, check it.
 3. Currently, we don’t see the clear way towards multi-chain for Polygon and Near and thus we’d rather focus on Polka XCM methodology as a way forward. Multi-chain capabilities are fundamental for the execution of our long term DeSci strategy.
 4. Tech descriptions are extended according to the comments from reviewers, please refer to the application.
 5. XCM is not in scope of POC
 6. Stripe is not in scope of POC

2023-03-31 15:50 UTC, semuelle commented
Thanks for the updates, @detechworld-dev, but I think the pallets listed in your milestone are too specific to your use case to be useful to the greater ecosystem, so I'll abstain.

2023-04-05 17:19 UTC, dsm-w3f reviewed
Thank you for the application. I particularly think DeSci is a promising area, however I agree with the other members of the committee. Hardly this project will be a common good or something that can be reused for the community. For this reason I'll not approve it. I wish you luck in finding support for it.

2023-04-05 17:23 UTC, takahser reviewed
@detechworld-dev unfortunately I won't support this grant neither, for the following reasons:

-While your deliverables are quite specific, I'm concerned about their reusability and potential benefit for the broader community
- I noticed a reliance on centralized components, such as the backend, MongoDB, and S3 storage, which could limit the project's versatility and decentralization

Nevertheless, I appreciate your effort and the work you have put into the proposal and wish you the best of luck in your future endeavors.

2023-04-14 07:18 UTC, Noc2 commented
Thanks for all the effort that you put into this. However, the grants committee decided not to support your grant application. Therefore I’m closing the PR. Let me know if you have any questions, and feel free to apply again for another project or take a look at the other funding opportunities in our ecosystem: https://github.com/w3f/Grants-Program#rocket-alternative-funding-sources.

2023-04-14 07:18 UTC, closed without merging