Grant Management Webapp RFP
w3f/Grants-Program pull request #1575
Opened 2023-03-01 03:57 UTC by randombishop

RFP to build a frontend to render grants data for Web3 Foundation, or other grants programs who choose to adopt the same standard.

2023-03-01 13:42 UTC, Noc2 requested changes
Thanks for creating the RFP. Generally, it looks good, but could we make it more generic? Our grants program should ideally be just an example/first step. Ideally, such a tool (combining GitHub + website) can benefit other grant programs and on-chain treasuries. It might even make sense to integrate some long-term goals into the RFP, like, for example, some oracles/pallets for treasury integration or a decentralized Github alternative/hosting.

2023-03-01 13:42 UTC, 0xCaso commented on docs/RFPs/Open/grant_management_webapp.md
> +A quick an dirty prototype already exists for the application:
```suggestion
A quick and dirty prototype already exists for the application:
```

2023-03-01 13:42 UTC, 0xCaso commented on docs/RFPs/Open/grant_management_webapp.md
> +![screenshot_grants_page](./img/grants_page.png)
```suggestion
For example:

![screenshot_grants_page](./img/grants_page.png)
```

2023-03-01 13:42 UTC, 0xCaso commented on docs/RFPs/Open/grant_management_webapp.md
> +![screenshot_grants_details](./img/grants_details.png)
```suggestion
For example:

![screenshot_grants_details](./img/grants_details.png)
```

2023-03-01 13:50 UTC, 0xCaso commented on docs/RFPs/Open/grant_management_webapp.md
> +
```suggestion
- Shows current deliveries pending evaluation.
- Links to all relevant information and history.
- Status of the delivery, submission date, evaluator, and if it's on stale.
```

2023-03-02 01:36 UTC, randombishop commented
@0xCaso Thanks for the feedback and corrections!

2023-03-02 01:53 UTC, randombishop commented
@Noc2 
* What do you mean by more generic? Like applicable to a different github structure and process than current one used by w3f?
* +1 for long term goals, added your ideas as additional notes.
* There's already an indication that the specifics shown in the RFP are just examples to illustrate the product:
```
The features proposed above represent an opinion on what the grant management webapp should do and look like,
but are neither exhaustive nor strict requirements. Teams are welcome to propose their own design and vision for this product.
```
I am afraid if we don't provide concrete examples of what we mean, it will be hard to understand. Using github to manage grants is quite original and probably won't make sense to someone who never saw that process.

2023-03-07 22:08 UTC, keeganquigley commented on docs/RFPs/Open/grant_management_webapp.md
> +Therefore, the web application and the structure of our repositories can be re-used by other grant programs.
```suggestion
The Web3 Foundation Grants Program is unique in that everything is openly and transparently published on GitHub. As a result of this RFP, we hope the W3F Grants Program can set an example of how other grant programs can leverage a simple yet powerful process to manage their grants.
Therefore, the web application and the structure of our repositories can be re-used by other grant programs.
```

2023-03-07 22:08 UTC, keeganquigley commented on docs/RFPs/Open/grant_management_webapp.md
> +These are just a first experiment to test how the app could work, and are completely undocumented,
```suggestion
These examples are just an initial experiment to test how the app could work, and are completely undocumented, 
```

2023-03-07 22:08 UTC, keeganquigley commented on docs/RFPs/Open/grant_management_webapp.md
> +but please feel free to contact [randombishop](nabil@web3.foundation) if you need help trying them out or simply discuss.
Should we maybe add grants@web3.foundation here instead of just your personal?

2023-03-08 04:55 UTC, randombishop commented
Big thanks @keeganquigley, eagle eye for the details!

2023-03-08 12:48 UTC, Noc2 approved these changes
Looks good to me.

2023-03-08 14:17 UTC, keeganquigley approved these changes

2023-03-09 07:42 UTC, Noc2 commented
I'm going to merge it, since @randombishop counts as third approval.

2023-03-09 07:42 UTC, merged