Create Awesome-Polka.md
w3f/Grants-Program pull request #1587
Opened 2023-03-06 10:19 UTC by tolgayayci

#### Project Abstract

Awesome Polka - the ultimate social platform for discovering and exploring the most exciting projects in the Polkadot ecosystem!

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-03-08 11:05 UTC, tolgayayci commented
Hey @Noc2 

I wanted to check in about my application status and excitedly waiting for your suggestion about Awesome Polka

2023-03-08 12:24 UTC, Noc2 requested changes
Thanks for the application. In general, the application might be a better fit for the treasury since the key focus here is technical education or marketing, I would say, and less technical development. In any case, I will mark the application as ready for review so that others can take a look at it. 
Apart from this, my main questions would be:

- How is your solution different also from https://parachains.info/, which provides almost all of this information already? 
- And how do you want to convince the community actually to fill your side with information?

2023-03-08 17:09 UTC, tolgayayci commented
Thank you for your review, @Noc2 

Awesome Polka is comprised of three distinct parts: a frontend, project owner dashboard, and admin dashboard, each with its own unique components and design. With this in mind, I have prepared this proposal for the technical development of the platform.

As you noted, Awesome Polka is a social platform that aims to create a sustainable showcase for all actors involved, including technical education and marketing components. These factors are critical to achieving success for the platform.

To address your first question:

Although parachains.info is a great project, Awesome Polka differs in some aspects. Here are some different aspects of Awesome Polka:

**Authentication:** Awesome Polka uses web3 onboarding methods for authentication while user has option to choose just signin with their mail addresses and click the link that coming to their inbox, whereas parachains.info relies on web2 methods. This means that users can securely log in to Awesome Polka using their crypto wallets or just mail addresses by passwordless, without needing to create a separate username and password.

**Built-in articles editor:** Awesome Polka includes a built-in articles editor that allows users to publish articles directly on the platform, rather than just linking to external articles as parachains.info does. This feature is designed to increase engagement and participation within the Polkadot ecosystem and Awesome Polka.

**Admin dashboard:** Awesome Polka includes an admin dashboard that enables administrators to manage and moderate content on the site, including articles, projects, and other information. Admins can approve, reject or request to remove any harmful content on platform. This feature is designed to increase participation and ensure that the site remains up-to-date and relevant.

**Project owner dashboard:** Project owners can easily update their project pages all the time entering to their dashboard, as I can see on parachains.info there is a submission form but I am not sure how this system work

**Modules for project pages:** Awesome Polka includes more modules for project pages compared to parachains.info, and this will be further increased in future versions according to the needs of the Polkadot ecosystem. This means that project owners can showcase their projects more effectively, and users can find the information they need more easily.

**User Experience:** Awesome Polka offers a more user-friendly experience for users compared to parachains.info. This means that the platform is designed with ease-of-use in mind, ensuring that users can navigate the site and find the information they need quickly and intuitively.

These are some of the unique features that distinguish Awesome Polka from other platforms, such as parachains.info. 

Now, to address your last question:

Firstly, I will manually add projects to Awesome Polka and contact project owners to invite them to publish their projects on the platform.

Secondly, I will contact hackathons related to the Polkadot ecosystem and create special dashboards for them to publish their projects on Awesome Polka. This will help grow the user base organically.

Thirdly, I will engage with the community on Twitter by creating monthly update threads and real-time announcements. This will keep the community informed about new project releases, upcoming events, and other relevant news.

These are just a few of the ideas to engage the community, and I will work to generalize and expand on them after the development stage is completed. My ultimate goal is to make Awesome Polka truly awesome.

2023-03-09 08:44 UTC, tolgayayci commented
Thank you for you suggestions @Noc2 

As you may have noticed, I have mainly focused on developing the frontend for the platform and only need to make some small fixes. I am currently working on the project owner dashboard and integrating the backend. While I understand that you may have doubts about the platform's value to the ecosystem, as I have outlined in my project's problem statement, I believe that it can solve some significant issues and reach a wider audience.

To continue the project, I'm curious as to your ideas on narrowing the proposal down to level 1, which will only include the project owner control panel at milestone 2 and the current frontend. I will then focus on developing a proof of concept for this first phase.

Moving forward, I will reach out to project owners and invite them to add their projects to the platform, while also promoting the platform to a wider audience. If the platform experiences significant growth and attracts a substantial user base, I plan to apply for treasury funds to further develop the platform and invest in marketing efforts, backed up by detailed statistics.

I would appreciate your feedback on this approach. If you agree, I will revise my proposal accordingly.

2023-03-14 09:29 UTC, tolgayayci commented
Thanks for your support @Noc2,

I revised my proposal to level 1 and as I stated added project owner dashboard to Level 1. The project manager dashboard included a mobile application, but since I removed the admin dashboard, I had to delete it as well, users will be able to continue using it from the browser as mobile.

2023-03-14 13:00 UTC, Noc2 approved these changes
Thanks for the update. As I said before, I'm happy to go ahead with it now.

2023-03-14 17:25 UTC, semuelle approved these changes
Hi @tolgayayci. Thanks for the application. I am also happy to proceed. 
I haven't looked at the existing code yet, but based on your demo and screenshots I would like to express two wishes:
1. Allow more than one tag/category. Many projects include parachains but may also have their own wallet, for example.
2. Catalog/index parachains' pallets. It's currently quite difficult to find a parachain matching a sought set of pallets.

2023-03-14 17:25 UTC, merged