a-better-treasury-system
w3f/Grants-Program pull request #1593
Opened 2023-03-07 14:38 UTC by adrianloffredo

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-03-07 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1593) it.</sub>

2023-03-07 15:23 UTC, Noc2 requested changes
Thanks a lot for the application: I have one initial question: Would you also be willing to receive treasury funding for this? I personally think that it would be ideal if the treasury funded the improvement of the treasury ;-) This way, you also immediately come in contact with the treasury as well as the community.

2023-03-08 07:37 UTC, adrianloffredo commented
> Thanks a lot for the application: I have one initial question: Would you also be willing to receive treasury funding for this? I personally think that it would be ideal if the treasury funded the improvement of the treasury ;-) This way, you also immediately come in contact with the treasury as well as the community.

@Noc2 Yeah for sure that sounds Ideal. 

Are there any other implications that my team should be aware of? Other than where the funding is coming from and who we are working with?

2023-03-10 08:20 UTC, Noc2 commented
@adrianloffredo You would be paid in DOT or KSM by the on-chain treasury. You can find more about it here: https://github.com/w3f/Grants-Program#treasury But also here: https://wiki.polkadot.network/docs/learn-treasury. Let me know if you have any questions, and feel free to reach out to david@web3.foundation. We can potentially also schedule a call to discuss it. For now, I'm closing the application.

2023-03-10 08:20 UTC, closed without merging