Sirato (formerly Epirus) Substrate phase 3 grant application
w3f/Grants-Program pull request #1608
Opened 2023-03-10 19:31 UTC by conor10

#### Project Abstract

This is the third phase of the Sirato (formerly Epirus) block explorer for Substrate application.
During the first couple of phases a block explorer for ink! smart contracts was created along with a contract validation service allowing contract activities and events to be decoded on-chain.

This third phase includes adding Frontier EVM, block and extrinsics support. This will ensure that Sirato provides a high-quality open-source block explorer for the Substrate ecosystem.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-03-10 19:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1608) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1608) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1608) it.</sub>

2023-03-13 15:54 UTC, Noc2 requested changes
Thanks for the application. I have a few initial questions:

- Wasn’t Epirus initially an evm/solidity-focused block explorer? If so, will you be able to reuse some of your existing work (potentially, I am mixing something up here) 
- It might make sense to apply with this project to an evm focused grants program by a parachain team rather than our grants program, e.g., moonbeam grants: https://twitter.com/MoonbeamNetwork/status/1633128047342657539. We usually are not too keen on supporting solidity projects because it’s not our core expertise. 
- If you want to continue with this application, I recommend focusing on the unique technical details that make this explorer useful for the frontier pallet rather than another EVM implementation.

2023-03-13 17:12 UTC, conor10 commented
Hi @Noc2, thanks for the quick review. We'll update the application accordingly, but in the meantime wanted to provide some context to your questions:

- You are right, it was. However, when we commenced work on this project, we realised it would be too heavy a lift to take what we had and adapt it for Substrate. By making use of other projects such as Subsquid to assist with the ingestion we were able to create something faster than we would have had we adapted our existing technology for it. Our existing knowledge of EVM chains will make part of this grant simpler for the team, but the focus here is Frontier.
- One of the goals with Sirato is to have a high-quality OSS block explorer baseline that teams working with Substrate can use. Having frontier EVM support in addition to ink! will ensure the explorer will cover the two main smart contract languages teams use when they run up a Substrate network.
- We will provide additional specifics on this — the goal here is for great support for the Frontier pallet, not general EVM clients on this grant.

2023-03-21 23:12 UTC, keeganquigley commented
Thanks @conor10 feel free to ping us once the changes are made and we will have another look.

2023-03-27 16:42 UTC, conor10 commented
Having spent some time speaking to the team on this, we've added some specifics on how the work being proposed here for the EVM caters to just the `pallet-evm` component of Frontier. This is the preferred mechanism for teams who wish to support the EVM in Substrate to go about it.

We are not proposing `pallet-ethereum` support with this grant which would mean Ethereum RPC support which I appreciate is less aligned with the Substrate ecosystem.

We've also linked to an interesting recent discussion in the Polkadot forums on the need for a high-quality OSS blockchain explorer for Substrate networks.

I hope this provides more of the specific information that you would like to see @Noc2.

2023-03-31 07:52 UTC, Noc2 requested changes
Thanks for the update. I will mark the application as ready for review. I have two concerns here: 

- On the one hand, the application seems relatively expensive to me. Would you be willing to reduce the price? 
- On the other hand, I think it would be better if this initiative is funded by a team that actually leverages the frontier pallet in our ecosystem, like, for example, moonbeam. But I like to hear feedback from the rest of the committee on this.

2023-03-31 09:38 UTC, conor10 commented
Hi @Noc2,  on these points:
- While we're waiting on the grant application processing we've been commencing some work on this. We could reduce down from 4 months to 3 for a 25% reduction (keen to get this over the line). I've updated the application accordingly.
- Our primary target for the EVM work will be new teams bootstrapping Substrate networks so they have a free open-source explorer. Moonbeam and other established ones already have their explorer infrastructure, so I'm less sure what the appetite will be there.

2023-04-06 10:07 UTC, conor10 commented
@keeganquigley would be great to get your thoughts too.

2023-04-06 12:52 UTC, Noc2 requested changes
Thanks for the update here. I’m still not convinced here, especially about the second milestone and the value it brings to the ecosystem. But I would be happy to support the first milestone at this stage to develop an initial PoC that supports EVM + ink!. Apart from this, let’s see what other committee members say. It might take a little bit longer for them to reply also because of Eastern.

2023-04-12 19:09 UTC, dsm-w3f reviewed
Thank you for your application. I agree with David that the application looks expensive since Web3 Labs seems to have extensive experience with EVM chains and block explorers for EVM chains and probably some layers of code could be reused. Furthermore, Sirato is in a stage of being a [commercial product](https://www.web3labs.com/blockchain-explorer-sirato-plans), which usually we don't support as common good with grants.


The idea of EVM and substrate block explorers seems to be of interest to [other chains and grant programs](https://github.com/subquery/grants/issues/1) as well. I think the proposal would be more suitable for these chains/programs.


For these reasons, I'll not support this application. I wish you the best of luck in finding support for your project.


Maybe you have an interest in taking a look at these RFPs, which are suitable to be performed for block explorer providers:
[Analytics Website/Data Platform](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/analysis-website-and-data-platform.md)
[Data Analysis Tools for Substrate-based Blockchains](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/data_analysis_tools.md)

2023-04-18 16:05 UTC, semuelle reviewed
Hi @conor10. Sorry for the wait. 
I'd be happy to support M1 as well. I think the ability to execute ink! functions from the explorer would also be of great use. It might be easier to put this into a separate grant and stick to a Level 2, but I haven't done my research on the topic, so I'd leave it up to you.

2023-04-19 10:43 UTC, conor10 commented
Thanks @semuelle. I've updated the grant to just focus on M1 delivery. Hopefully, we can get this over the line now.

2023-04-19 14:44 UTC, keeganquigley submitted a review, later dismissed
Thanks again @conor10 for the nice call and for making the revisions. I'm happy to go forward with it. I updated the grant levels to mark it as a level 2 grant, which only needs three approvals.

2023-04-20 11:24 UTC, Noc2 requested changes
Sorry for the delay here. I'm happy to approve it. But could you update the level to a level 2 grant? Otherwise, it looks good to me.

2023-04-20 13:02 UTC, Noc2 approved these changes

2023-04-20 14:55 UTC, keeganquigley approved these changes

2023-04-21 09:02 UTC, conor10 commented
@semuelle please can I get your approval?

2023-04-24 11:11 UTC, merged