application: CILA - omnichain ifrastructure
w3f/Grants-Program pull request #1679
Opened 2023-04-18 08:14 UTC by AlexShkor

#### Project Abstract

The goal of this project is to implement an omnichain smart contract infrastructure support for Substrate framework. This will include the implementation of CQRS + Event Sourcing execution environment plus an example smart-contract. The implementation will be done using WASM and/or native Rust Substrate implementation as a pallet. The implementation will include implementing Protobuf support on-chain, serialization/deserialization, aggregated repository, event store, command/operations dispatcher, and events emitter.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-04-18 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1679) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1679) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1679) it.</sub>

2023-04-20 12:41 UTC, takahser requested changes
@AlexShkor thanks for submitting your grant proposal.
I've got a couple of questions:

- regarding "events relay" for cross-chain communication, what tech are you planning to use here? Protobuf?
- If yes, is there a reason not to use XCM here?
- Are you aiming to replace [Substrates' storage APIs](https://docs.substrate.io/build/runtime-storage/) with mongodb for the scope of your project?
- If yes, what's the reasoning behind that?
- What's your strategy on syncing the mongodb state with other blockchain nodes?
- Storing all event will make it much easier to interact with these smart contracts. However, this comes at a cost: loads of additional storage. Did you think of ways to ensure scalability here, when compared to the more "traditional" model where events are not necessarily persisted after their emittance?
- Why did you add NFTs to the architecture diagram? Are they that elementary to the architecture? I would have imagined them to be just one of many things you can implement through the smart contract.
- Regarding M2, we don't usually support deployment efforts. Feel free to remove it or to add some code deliveries, such as automated tests, fuzz tests or other code-related deliverables.
- Regarding M3, are you trying to reuse any existing NFT standards here? If not, why?

2023-04-20 12:41 UTC, takahser commented on applications/CILA-omnichain-infrastructure.md
> +The `Dispatcher` provides a simple and flexible way to handle commands/operations in the smart contract. By defining a set of command/operation handlers, developers can easily add new functionality t
```suggestion
The `Dispatcher` provides a simple and flexible way to handle commands/operations in the smart contract. By defining a set of command/operation handlers, developers can easily add new functionality to the smart contract without having to modify the `Dispatcher` class itself.
```

2023-04-20 12:41 UTC, takahser commented on applications/CILA-omnichain-infrastructure.md
> +Architcture Overview Diagramm
```suggestion
Architecture Overview Diagram
```

2023-04-20 12:41 UTC, takahser commented on applications/CILA-omnichain-infrastructure.md
> + | Application|       |   Router   |       |Execution Chain  |       |  Event Relay Node |       | Aggregation|
```suggestion
 | Application|       |   Router   |       | Execution Chain |       |  Event Relay Node |       | Aggregation|
```

2023-04-20 16:13 UTC, AlexShkor commented
@takahser 

`I imagine it to be quite expensive. Is the event emittance being paid for somehow by the contract owner or the person who calls a corresponding function that emits the event?`

yes, it will be paid by the original sender, the events will be batched with other smart contracts so it might help optimize the cost.

`By that, do you mean that it's a problem that an NFT can be part of a collection? Afaik there are both type of standards: Those which are part of a collection and those which aren't. If you seek funding for the NFT development it would be good to learn what additional value your implementation brings to the ecosystem and why it's not viable to just reuse an existing standard/implementation.`

Most probably we will reuse existing standards, I just wanted to mention here our approach to choosing a standard that we aim to reimplement in our omnichain format.

2023-04-20 18:54 UTC, takahser commented
Thanks for the updates, I'm generally open to support M1 and M2.

> Most probably we will reuse existing standards, I just wanted to mention here our approach to choosing a standard that we aim to reimplement in our omnichain format.

If you run your own standard, I'd expect you to justify why it's needed. On the other hand, if it's feasible to reuse an existing standard/implementation it would be the better option. However, in my personal opinion, it wouldn't really deliver any additional value to the ecosystem, and it's questionable if we should fund this. An alternative idea would be to deliver a market research report on existing NFT standards/implementations in the ecosystem as part of M3, which might help other teams in a similar situation to make a choice. In that case, I'd personally be open to support it.

2023-04-20 20:18 UTC, AlexShkor commented
@takahser Thank you, it's actually a good idea since we will be doing it anyway to select a proper standard for the omnichain implementation.

2023-04-21 12:01 UTC, takahser approved these changes
@AlexShkor thanks for the updates, I'm happy to vote in favor of your application now. I'm going to share it with the other committee members, please note that it may take some time before you'll receive their feedback as we have currently a lot of open applications that need to be reviewed. Thank you for your patience in advance.

2023-04-24 22:21 UTC, keeganquigley approved these changes
Thanks for the deep dive @takahser and for making the changes @AlexShkor CQRS sounds like interesting tech, and a good use case for an alternative WASM implementation. LGTM.

2023-04-25 14:06 UTC, Noc2 approved these changes
You clearly put a lot of effort into this. I'm happy to support it.

2023-04-25 14:07 UTC, merged