Application Profond
w3f/Grants-Program pull request #1682
Opened 2023-04-19 18:47 UTC by emarai

#### Project Abstract

[Profond.ai](http://profond.ai/) is web3 tools to help developers and creators to build, validate, and scale their dApps. We provide smart contract builder (NFT and token), analytic, and indexer. We will provide: 

1. Create smart contracts with no-code interface for Fungible Token and NFT
2. Analytic for smart contracts
3. Indexer (coming soon)
4. API Analytics.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-04-20 02:12 UTC, keeganquigley commented on applications/Profond.md
> +| 1. | Analytic Functionality | Add on-chain analytic for the smart contract. |
What exactly does "on-chain analytic" mean? Can you elaborate on this?

2023-04-20 02:12 UTC, keeganquigley commented on applications/Profond.md
> +| 4. | Go To Market | Onboard 20 project within a month after release. |
I'm not sure this is something that is covered by the grants program, you can probably remove the "go to market" part.

2023-04-20 02:12 UTC, keeganquigley commented on applications/Profond.md
> +| 2. | No Code Fungible Token Creation (ink!) | Allows users to create Fungible Token smart contract (PSP22) using ink! in one of WASM supported Parachains. |
Cool! Can you expand the technical details a bit in the deliverables? What technologies will you use to build this?

2023-04-20 02:15 UTC, keeganquigley commented
Thanks for the application @emarai please see my comments above to expand out the deliverables table. Also one additional question: will you integrate with any Polkadot wallets to sign in or is it strictly by email for now?

2023-04-21 06:29 UTC, ekkirinaldi commented on applications/Profond.md
> +| 1. | Analytic Functionality | Add on-chain analytic for the smart contract. |
It is data analytics for each contract in the project. Users can create a new contract on Profond or put in existing contracts.
Each contract created in Profond will come with analytics. Here's an example of on-chain data analytic for marketplace.paras.near. We're using Metabase for now. We will put this on the proposal.

<img width="1361" alt="CleanShot 2023-04-21 at 13 27 18@2x" src="https://user-images.githubusercontent.com/22832454/233557851-b37cb5ab-f740-4510-8250-d23ecba1545e.png">
<img width="1360" alt="CleanShot 2023-04-21 at 13 27 59@2x" src="https://user-images.githubusercontent.com/22832454/233557890-f3d849dd-b89c-474a-8cf0-61e804d58eef.png">

2023-04-21 07:53 UTC, emarai commented
> Thanks for the application @emarai please see my comments above to expand out the deliverables table. Also one additional question: will you integrate with any Polkadot wallets to sign in or is it strictly by email for now?

Yes, we will integrate Polkadot wallets (SubWallet, polkadot.js, Talisman) to sign in.

2023-04-21 07:53 UTC, emarai commented on applications/Profond.md
> +| 4. | Go To Market | Onboard 20 project within a month after release. |
Sure, removed this row.

2023-04-21 07:54 UTC, emarai commented on applications/Profond.md
> +| 2. | No Code Fungible Token Creation (ink!) | Allows users to create Fungible Token smart contract (PSP22) using ink! in one of WASM supported Parachains. |
Yep, I have updated the technical details inside the `Specification`.

2023-04-21 14:37 UTC, keeganquigley commented
Thanks for the changes @emarai the deliverables look better now. I'll go ahead and mark this application as ready for review and ping the rest of the committee. In the meantime, one more question:

Can you further define what the "indexer service" would look like in M2? Is there a reason you can't use an already existing solution for this?

2023-04-27 11:44 UTC, emarai commented
> Thanks for the changes @emarai the deliverables look better now. I'll go ahead and mark this application as ready for review and ping the rest of the committee. In the meantime, one more question:
> 
> Can you further define what the "indexer service" would look like in M2? Is there a reason you can't use an already existing solution for this?

Hey we were thinking of bringing what we know about indexer to polkadot. But, we have found this has been solved by subsquid, so we are removing it from the deliverables.

2023-04-27 17:20 UTC, keeganquigley commented
Thanks for the changes @emarai I'm happy to go forward with it.

2023-04-27 17:20 UTC, keeganquigley submitted a review, later dismissed

2023-05-03 08:23 UTC, Noc2 requested changes
Thanks for the application, and sorry for the delay here. I'm generally happy to go ahead with it, but could you add the default deliverables (license, tests, documentation etc.) also to the second milestone? Also, could you remove [Sui](https://sui.io/) from the application since we only support solutions for the Polkadot ecosystem?

2023-05-03 08:50 UTC, emarai commented
> Thanks for the application, and sorry for the delay here. I'm generally happy to go ahead with it, but could you add the default deliverables (license, tests, documentation etc.) also to the second milestone? Also, could you remove [Sui](https://sui.io/) from the application since we only support solutions for the Polkadot ecosystem?

Hi, thanks for the feedback. We have adjust the application to your comment, please check.

2023-05-03 19:20 UTC, Noc2 approved these changes
Thanks for the update. I'm happy to go ahead with it.

2023-05-04 01:30 UTC, randombishop approved these changes

2023-05-04 06:06 UTC, merged

2023-09-14 17:17 UTC, keeganquigley commented
Hi @emarai how is milestone 1 coming along?

2023-09-15 04:15 UTC, emarai commented
Hi @keeganquigley we are still working on it, it is taking us more time than our previous estimation. Our target would be to submit the result at the end of this month.