Skeezer Network - The Mental Health Blockchain
w3f/Grants-Program pull request #1724
Opened 2023-05-08 16:42 UTC by cleve02

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-05-08 16:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1724) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1724) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1724) it.</sub>

2023-05-08 21:20 UTC, keeganquigley commented
Thanks for the application @cleve02 a few initial comments:

- Typically we don't support the deployment of the actual parachain, as this is something that is more in line with treasury funding. The treasury might also be willing to fund the higher rates.
- Be aware that any amount over 100k would also need to be approved by the W3F council, which takes a lot more time. Most likely the rest of the committee will ask you to bring the price down.
- Considering the above, would you be willing to reduce the scope/price to a PoC of just the smart contracts?
- Can you explain the reason a full parachain is needed vs deploying the ink! contracts on an existing parachain?
- Not sure if you're planning on it, but please [note](https://github.com/w3f/Grants-Program#guidelines) that we don't fund the launch of a token sale.

2023-05-09 08:42 UTC, Noc2 requested changes
Thanks for your interest in our grants program. Something to be aware of is that we mostly focus on supporting open-source software development that can potentially be reused by others. We don't support the deployment of these tools via our grants program since it's only useful for your specific project. So, for example, we wouldn't support "deployment testing". Additionally, could you add more technical details to the deliveries? For example, what exactly do you plan to deliver with the test suites? Are these independent programs that can potentially be reused by others? Finally, for front-end-focused applications, we usually ask teams to share some initial mock-ups or designs with us.

2023-05-10 18:09 UTC, keeganquigley commented
Thanks for your answers @cleve02 a couple of follow-up questions:

- Your whitepaper mentions that calls are connected through a "bridging service", can you elaborate on this?
- Your FAQ notes that the project is "not a professional counseling or therapy platform and has no licensed therapists or mental health professionals". This sounds like it is essentially a text/video chat app that would be marketed towards the health industry? What benefits would your app have over existing open-source encrypted chat apps such as Element or Telegram?
- Can you explain what data would be stored on-chain vs IPFS? You mention "records, ratios, and processes" but I'm not sure what that means.
- How are rude caller sessions ended automatically?
- It's not clear to me how others would be able to re-use the smart contracts, for example the fungible token contract seems specific to your needs. Can you explain what benefits they provide?

2023-05-10 20:03 UTC, cleve02 commented
@keeganquigley 
Thanks. I’d refer to your points as 1 through 5 in ascending order

Points 1 and 4 are related in that the bridging service would essentially be Skeezer backend code that is automated to filter out offensive words and (when it is more cost effective for us) audio in conversation. This is does not mean monitoring of conversations as user data is automatically cleared when a conversation ends and users remain anonymous. This functionality already exists in most chat applications and would enable disconnection of obvious spam users.
On point 3, what would be stored on-chain would be essential token data as it would be less expensive this way. IPFS would mainly have information on voters belonging to the different tiers (records). 
We had initially planned on different tokens having different powers of vote (ratios) with for example a `tier_1` token having twice as much a vote as a `tier_2` token (2:1) but saw this would be very expensive on such a blockchain, such details however, we planned on storing on IPFS.
The “processes” is just description/code of how the above would work, should it be voted that it changes later on.
On point 5, I think there would be re-usablilty in cases where a smart contract requires the functionality we are planning. The tier system we envision will provide collective security were no one user especially in the early stages of a governance blockchain can maliciously hold a significant amount of tokens to control the direction of the network
Finally, on point 2, it does sound similar to the apps you mentioned but I’m sure as you do yourself, we all have different apps for different uses. 
Ours aims to built a rich community of compassionate listeners and users, not tied down by sign up processes etc., where they can go in and freely talk about the thoughts and experiences and hopefully get through when they’re going through - referring them to professionals if necessary.
In this regard, we are more likened to [7 cups of tea](https://www.7cups.com/) (200,000 + listeners) and [BuddyHelp](https://buddyhelp.org/)

2023-05-10 20:08 UTC, keeganquigley commented
Thanks for your replies @cleve02 I will go ahead and mark the application as ready for review so others can comment. Feel free to ping us once you have updated the mock-ups.

2023-05-11 09:02 UTC, semuelle reviewed
A volunteer support network is a noble idea. However, I don't see it benefiting from putting data on-chain or on IPFS much. The deliverables are also not technically novel, so it doesn't fit the grants program, and for that they are way too expensive.

2023-05-11 14:57 UTC, randombishop commented
Thank you for this application @cleve02 !

I disagree here with @semuelle and think this project could be a beneficial use case for blockchain: it empowers a well intentioned community to solve a problem without middle-men like `7 cups of tea`. Also, it seems like the community is to be kicked off in Kenya and Africa first, where very few can afford professional psychological help and I believe volunteers can fill the gap.

But with that I have the following suggestions to make the application more fit to our grants program:

- Reduce the scope and price to a level 2 under $30k to prove the concept first.

- Remove the following deliverables: 
    * `Initial Parachain Setup`: not really a deliverable as there are already multiple templates available open source.
    * `Fungible Token`: W3F generally doesn't fund tokenomic related work.
 
- Add mock-ups for how the front end will look like.
 
- Add a schema and more details on the data and transactions that will be supported by the blockchain.

2023-05-11 15:00 UTC, Noc2 requested changes
I agree with @semuelle that a lot of the current deliverables aren't helpful for others and are very specific (e.g. parachain setup, community research) to your project or rather small changes to existing contracts (fungible token). Could you potentially try to focus more on tools that can be reused by others (e.g. test suit, if it's possible to test other smart contracts with it, and you are not only referring to unit tests here) and reduce the price?

2023-05-11 17:47 UTC, takahser requested changes
@cleve02 I've taken a look and I tend to agree with @semuelle and @Noc2 here. I'd like to point out that we generally don't support market research (_1. Community Research_), deployments or setup efforts (_2. Initial Parachain Setup_, _6. IPFS setup_) and we'd expect testing to be part of any code deliveries (_4. Fungible Token_, _7. Test Suite 2_). For the _3. Fungible Token_ deliverable I currently don't see a reason why any of the existing implementations shouldn't be reused, but feel free to elaborate on this. So much for M1. Regarding M2, I think it's very closely tied to your use case and I question the reusability and added value in/to the ecosystem. Also, in my opinion the costs are way too high.

2023-05-11 22:29 UTC, cleve02 commented
Thanks for all the feedback. Your points were well taken. We’ll address the issues and get back in due time.

2023-05-24 11:09 UTC, cleve02 commented
Thanks for all the feedback. I’ve updated the request to a PoC with a level 2 budget.
The overall structure hasn’t changed drastically but we still believe there is a real use case in this project’s reusability and more importantly, contribution to an overall adaptation of an innovative blockchain solution in the real world.
We acknowledge that this, however, does not underscore the fact that this application is not as technical as the other projects that would fall into your consideration and in this, we would be happy to be guided in the right direction.
Some cases we would make for reusability are: 
The two-tier governance model implemented in the Skeezer project can be leveraged by other projects in the Polkadot ecosystem to establish a balanced and inclusive decision-making process. By adapting and customizing the tier composition, proposal types, and acceptance process, projects can benefit from a governance framework that incorporates expertise, community representation, and accountability. Reusing this model promotes consistency, interoperability, and collaboration within the Polkadot ecosystem while allowing projects to tailor the governance process to their specific needs.
The Test suites can in addition be reused on other smart contracts especially ones with a similar structure.

Finally, attached [here](https://www.figma.com/file/5oCWPYRdh4cSNcDSWLfNas/Skeezer-Blockchain-Network---Dashboard?type=design&node-id=0%3A1&t=kPGZdkn282t1kz3J-1) are design mockups for the network portal. And [here](https://skeezer.org/skeezer_design_assets.zip) are the corresponding assets.

Thank you again for all the time spent on this. We really appreciate it.

2023-05-29 10:30 UTC, cleve02 commented
@keeganquigley @randombishop @semuelle @Noc2 @takahser

2023-05-30 12:33 UTC, Noc2 requested changes
I'm sorry for not getting back to you sooner, and thanks for the update. I'm generally happy to go ahead with it. But could you add the programming language/frameworks that you will use to the specification of the milestone tables? Also, will you integrate/develop some kind of IPFS integration together with the data_management_smart_contract?

2023-05-31 12:30 UTC, cleve02 commented
@Noc2 
I’ve made the requested additions, on your second question, we do plan on writing some kind of IPFS integration to work with the data_management_smart_contract. This would be essential in keeping records on category tier of voters as well as other data that may be needed.

2023-06-01 08:05 UTC, Noc2 requested changes
Thanks for the update. Now, I have a follow-up question: You reduced the FTE and the duration with your latest update (https://github.com/w3f/Grants-Program/pull/1724/commits/68d00151c811c9ca2df53ce781db2018e0a1a830). Could you also reduce the price?

2023-06-07 01:52 UTC, randombishop approved these changes

2023-06-07 09:29 UTC, takahser requested changes
@cleve02 thanks for the updates and improvements. I still have a couple of points to make:

- The deliverable _1. Research & Data Collection_ still appears to be market research and closely tied to your business model to me. Hence, I wouldn't support it.
- I think the deliverables _3. Test Suite 1_ and _5. Test Suite 1_ should be incorporated into the deliverables _2. token_smart_contract_ and _4. data_management_smart_contract_ since we'd expect code to be tested anyway.
- I'm still confused about what data is stored on IPFS and what's stored on-chain.
- Also, it'd be good if you could describe the integration with IPFS in more detail. Currently you only mention IPFS as part of the tech stack.

2023-06-12 11:10 UTC, takahser requested changes
@cleve02 thanks for your answers.

> The first one I would assume you’re talking about would be the grant required one to cover functionality of the project in a dockerized container. This would be more case specific as we would be checking for processes & functions that we’ve written ourselves and more inward facing.

So basically unit tests?!

> The second more outward facing tests would be ported in a more popular language and would include use cases that may not be in our code but useful in testing & deploying similar tier based chains and their possible extended functionality based on the challenges we’ve solved in development.

Why do they need to be ported in a different language? Which language would you use here? I don't understand the reason to do that, could you explain? Also, I'm confused what you want to test since you're planning to "include use cases that may not be in our code". How do you want to test something that's not even coded? What exactly are you testing here?

> On IPFS, we plan on storing blockchain data that would be too expensive to live on the blockchain. This would mainly include wallets tiers and their voting strength and in extension, open source community information like proposals, profiles etc. would be stored there and only hash referenced on the data_management_smart_contract. This we believe would create a more transparent, well meaning community.

That appears to be still very vague for me. Please explain how you're going to integrate IPFS and your smart contract. Some diagrams would be useful here to see which requests are being done and how data flows between the different components. 

> Finally on research I agree its not a [typical research grant ](https://github.com/w3f/Grants-Program/blob/master/applications/tokenomics-survey-2022.md)format that w3f funds but the context would also not be strictly on Skeezer market research but include data on participants, professionals and ease of use and adaptability of such a blockchain for social mental health care, hence my thought process on having it as a deliverable for others who might need data when working on a similar community based project.

In my personal opinion it still sounds like it's very closely tied to your use case, rather than being useful for the wider ecosystem community. Hence, I'm (still) not willing to support the research part of your grant proposal.

2023-06-14 13:29 UTC, cleve02 commented
@takahser 
Thanks
Yes, I was referring to the required unit tests that are part of every grant application.
Like I said, the test suites would include functions and processes based on challenges solved in development that have may not necessarily have made it to our parachain implementation.
This may include scripts that test these same functions but some may be translated into a different language where possible (that can be used as reference/when developing similar tier based systems) as to be used in a wider variety of blockchains/solutions.

Here is a representation of data flow within the network.
![data_flow_skeezer_blockchain](https://github.com/w3f/Grants-Program/assets/35739047/3f43eb58-135c-460e-8431-a39b32e18acf)

2023-06-14 13:46 UTC, takahser commented
@cleve02 

> Like I said, the test suites would include functions and processes based on challenges solved in development that have may not necessarily have made it to our parachain implementation.

If they pose challenges to outdated code, I don't see any value in keeping the tests you wrote for it. Why would you have tests for outdated code? Also, I don't understand the value of translating them into different languages.

Regarding your diagram, do you imply that the `data_mgmt_sc` is not running on-chain?

2023-06-14 14:47 UTC, cleve02 commented
@takahser  
It may not be outdated code, but code that might be useful in other use cases or contexts different to ours. Translating our implementations we think can help a wider variety of blockchains/solutions.

No, the `data_mgmt_sc` would obviously be on-chain, but I was try to reflect that it would be the one closely in contact with IPFS

![dfsk](https://github.com/w3f/Grants-Program/assets/35739047/dc78a89a-8326-44ae-ae41-71e312780b10)

This may address that issue

2023-06-28 14:33 UTC, semuelle commented
pinging @cleve02

2023-06-28 14:52 UTC, cleve02 commented
Apologies for the late reply
@takahser Like I mentioned in different contexts earlier, the test suites can be used by solutions trying to create a tier based system similar to ours. The use cases can vary in this and can include, similar parachains, extensions etc. It depends of the solution and the developers.

Glad it made sense up-to that point. The diagram was meant to be a data flow diagram to and as you've said it represents data and functions associated between components. It was as a reply to your earlier question and I tried to make it as descriptive as possible.
If you could pin-point what exactly you don't understand and I could explain that specifically. I would otherwise think it is more or less straightforward.

2023-07-06 08:29 UTC, takahser commented
@cleve02, thank you for your response. However, I still have reservations about your architecture and the value your solution brings. Given the limited interest from other W3F grant committee members, I will be closing this application. I appreciate your interest in our grants program and invite you to consider reapplying in the future.

2023-07-06 08:29 UTC, closed without merging