Create Aequum_deOS.md
w3f/Grants-Program pull request #1749
Opened 2023-05-18 12:53 UTC by dsrdrk11a

#### Project Abstract

Aequum deOS is a blockchain-agnostic operating system for decentralized applications that transforms the established operational pattern and presents a new approach to accessing and developing dApps. Aequum deOS will connect dApps through a single framework. The new blockchain workspace will provide users with a single window of access to all their favorite dApps and a marketplace to explore new ones.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Statemint (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-05-19 19:35 UTC, keeganquigley requested changes
Thanks for the application @dsrdrk11a a couple of initial notes:

- Very cool idea, but the price is significantly more than we've given your team for previous grants and seems very expensive. Personally, I'd rather see a reduced scope to prove the concept first and then break down some of the milestones into follow-up grant(s).
- Be aware that any amount over 100k will need W3F council approval as well, which can take longer and would include a pitch call.
- Milestones 4 & 5 aren't related to substrate tech at all and I'm not sure how these parts could be re-used by the community. They seem to be specific to your app. Perhaps you could take these two out and reduce the scope/price?
- When I add up all six milestones, I get $208,000 as the total, rather than $218,000. Can you fix this?
- Under "Future Plans" you list an additional $172,000 for future milestones. Since this isn't part of the total costs and isn't in the scope of this grant, can you please remove it to make it clear that this part isn't being funded as part of this grant? You can keep the delivery table in if you'd like.

2023-05-25 12:13 UTC, dsrdrk11a commented
Hello, @keeganquigley 
Thank you very much for your notes and recommendations. We've splitted this project in more stages and found the opportunity to lower the estimation to facilitate the processing of the application. Also, I've added some base APIs to the 3rd milestone to clarify our intentions and contribution to the Polkadot. The "windos manager" is now moved to future plans, but I've also added more descrition to this deliverable.

2023-05-25 20:23 UTC, keeganquigley commented
Thanks for the changes @dsrdrk11a it's looking better now.

I love the idea of a decentralized OS but personally I won't approve it yet because I'm not sure if Milestone 1 is specific enough to the substrate ecosystem and overall it is quite expensive. That being said, I will mark the application as ready for review and ping the committee so others can comment.

2023-06-07 09:16 UTC, dsrdrk11a commented
Hi, @keeganquigley as there are no more reviews, maybe we have to change our milestones and budget estimation to proceed. We can not fully delete the first milestone, as the 2nd and 3rd milestones will fully depend on it and we won't be able to demonstrate a test app without deliverables from the first MS. Also we have reduced our budget last time simply by excluding development risks from the estimation. So I propose to move all deliverables from the 1st MS to the 2nd and return the previous estimation just for the 2nd MS, it will be 45K. As the 1st MS was previously estimated at 24K, we will find a way to allocate missing 19K from our own budget.

Summing this up:
There will be 2 Milestones: 45K + 34K and they will include all deliverables, that we have now in the application. Will that work?

2023-06-07 14:54 UTC, keeganquigley commented
Thanks @dsrdrk11a for the update. Regarding an acceptable price, it's hard to give an exact number that might be approved, since ultimately it is the committee decides whether to approve the application, and not just me of course.

That being said, personally I think that lowering the costs would help to improve the chances of getting it approved. My personal recommendation would be to go for an initial PoC that would fit into a level 2 grant, and then apply for a follow-up grant for the remaining milestones. That way you would only need three approvals instead of five.

Since we've seen some of your previous work, you could try lowering to the amount you mentioned first, but I'll leave that up to you. Feel free to ping me once you've made the changes and I will notify the committee again to take a look and comment.

2023-06-08 11:27 UTC, dsrdrk11a commented
Hello, @keeganquigley 
I've merged the 1st and the 2nd milestones and left the last shown price for the 2nd MS, so now we have just two milestones, but with all previously mentioned deliverables. We will find a way to develop the deOS loader and a bundle assembly tool fully on our budget and will deliver this code under open license as these features are needed to show the other functionality.
Please, pass this to the Cometee.

2023-06-08 15:52 UTC, keeganquigley commented
Thanks @dsrdrk11a I pinged the committee again. 

As I said previously, I think it's a cool idea, and was impressed with your previous work. However I still won't approve it yet as I feel that the milestones aren't really relevant to any substrate/Polkadot technology. The rust library and SDK might be helpful, but the rest of the deliverables are pretty specific to your use case. I might be willing to reconsider if you reduced the scope to a level 2 PoC. That being said, it's possible that other committee members may feel differently.

2023-06-14 09:30 UTC, Noc2 requested changes
Thanks a lot for the application. I have two big concerns here, why I won't approve the application at the moment and that I want to share with you: On the one hand, it seems that you rely mostly on grants for your funding.  However, the grant program is definitely not the right tool to develop a long-term successful business model around a project. On the other hand, your previous projects seem to be unmaintained at this stage, see [1](https://github.com/bsn-si/ocex-smartcontract/tree/main), [2](https://github.com/bsn-si/rubeus-smartcontract/tree/main).

2023-06-21 14:08 UTC, Noc2 commented
I wanted to let you know that I'm closing this because of inactivity. Let me know if I should reopen it.

2023-06-21 14:08 UTC, closed without merging