Add Orochi Network's proposal for research and development MPC ECDSA
w3f/Grants-Program pull request #1786
Opened 2023-06-05 07:43 UTC by chiro-hiro

#### Project Abstract

Orosign is a self-managing custodial Mobile App base on MPC and ECDSA to provide high security in digital assets/identity management that suits all demands of Web3.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@chiro-hiro:matrix.org` (change the homeserver if you use a different one)

2023-06-05 07:46 UTC, chiro-hiro commented
Hi @keeganquigley, the first part of our proposal moved here. After we complete the first part, I will provide the second part.

2023-06-06 17:14 UTC, keeganquigley commented
Thanks for the changes @chiro-hiro in addition to my minor corrections above, a few more questions:

- Can you explain a bit more about what questions you are looking to answer as part of the research milestone? And integrate this into the deliverables? Currently the M1 delivery tables seem a bit vague.
- With the Orosign app, are the MPC key shares stored on the physical device? I’ve read that signing a transaction needs direct access to the key shares, which could expose information from the device and render it vulnerable to hacks, creating a possible attack vector.
- Will you look into other attack vectors as part of your research?
- Can you elaborate on the [data correctness](https://docs.orochi.network/) section of your docs? What do you mean when you say that all data pipelines are stored in a black box?

Thanks!

2023-06-19 09:07 UTC, Noc2 requested changes
Thanks for the application and the updates so far. Let us know once we should take another look at it. Btw the link to your website as part of the PR doesn't work. Could you fix this? Something to be aware of is that we usually don't fund the initial research of teams to look into specific details of Polkadot, especially if they have their own business model. So your first milestone might be controversial for the team and you should try to point out how this is useful for everyone and if you have done upfront research on the topic already.

2023-06-20 10:15 UTC, chiro-hiro commented
Hi @keeganquigley, here is my answers, I will add to the proposal as well.

> * Can you explain a bit more about what questions you are looking to answer as part of the research milestone? And integrate this into the deliverables? Currently the M1 delivery tables seem a bit vague.

In this milestone, our team use cryptography to build a bridge from Digital Signature Algorithm (DSA especially ECDSA, EdDSA, Schnorr Signature) to Multi-Party Computation (MPC) allow the signing process to be performed without actual private key. There are 3 DSAs were used by Polkadot: `secp256k1`, `ed25519`, `sr25519`. Before we can build a MPC based DSA, we need to research the algorithm and figure out how we could fit MPC into it. You may notice that each curve have different parameters and different field, after the research we can specify how MPC should be implement without harm its security.

> * With the Orosign app, are the MPC key shares stored on the physical device? I’ve read that signing a transaction needs direct access to the key shares, which could expose information from the device and render it vulnerable to hacks, creating a possible attack vector.

We designed a threshold signature that required 3/5 to perform, here is how shares were distributed:
- 2 share on mobile device
- 1 backup share of users
- 2 share hold by Orochi Network server

If hacker get in to user's device he need to hack Orochi Network's server as well to collect enough share to perform the MPC. In this case the risk to be hacked still lower than other ordinary crypto wallet  since the ordinary crypto wallet access to private key directly.

> * Will you look into other attack vectors as part of your research?

Will do, I think it's nice to have.

> * Can you elaborate on the [data correctness](https://docs.orochi.network/) section of your docs? What do you mean when you say that all data pipelines are stored in a black box?

Right now all data pipelines are on centralized cloud services.

Thanks.

2023-06-20 10:27 UTC, chiro-hiro commented
Hi @Noc2 Thank for your feedback, I will do check.

> Something to be aware of is that we usually don't fund the initial research of teams to look into specific details of Polkadot, especially if they have their own business model. So your first milestone might be controversial for the team and you should try to point out how this is useful for everyone and if you have done upfront research on the topic already.

This research part is help other team understand our construction and trade-off in the implementation, any team can pick up our research and do the implement themselves, beside `ed25519` and `sr25519` aren't popular out there among existing blockchains. I hope our project could bring the security of Web3 for all retail users.

2023-06-21 16:07 UTC, keeganquigley commented
Thanks for the answers @chiro-hiro much appreciated. I am seeing that the website still doesn't work as David mentioned, are you planning to update this?

2023-06-22 02:08 UTC, chiro-hiro commented
Could you tell me which link?, I have no idea which one.

2023-06-22 13:57 UTC, keeganquigley commented
@chiro-hiro yep its http://www.orochi.network/

I remember it did work a couple weeks ago when I initially looked at your application.

2023-06-26 13:58 UTC, Noc2 requested changes
Thanks for the update here. In this case, I think you should only focus on the first milestone. I guess you don't know the exact implementation until you have researched it. Furthermore, one concern here I would have as a user is that I rely entirely on your solution. You control the app as well as 2 out of 5 keys by default, and [Orosign](https://github.com/orochi-network?q=Orosign&type=all&language=&sort=) doesn't seem to be open source. Correct me if I'm wrong. Additionally, could you please point out any previous relevant work that you have done and/or audits?

2023-06-27 04:29 UTC, chiro-hiro commented
> Thanks for the update here. In this case, I think you should only focus on the first milestone. I guess you don't know the exact implementation until you have researched it. Furthermore, one concern here I would have as a user is that I rely entirely on your solution. You control the app as well as 2 out of 5 keys by default, and [Orosign](https://github.com/orochi-network?q=Orosign&type=all&language=&sort=) doesn't seem to be open source. Correct me if I'm wrong. Additionally, could you please point out any previous relevant work that you have done and/or audits?

It's 3/5 to perform the transaction. The fact is, we can design tho make Orochi Network control 1 share instead of two shares. User will hold majority of shares in their device.

In this proposal, we supposed to implement an open-sourced crate in Rust (can be compiled to wasm) allow other team to reuse if they want to build a MPC solution for Polkadot. This grant is just focus on R&D on MPC DSA (ECDSA, EdDSA), it isn't include Orosign that's why we wasn't open-source it.

Here is our previous work in ERVRF https://github.com/orochi-network/orochimaru/tree/main/libecvrf

We do research in DKG and MPC ECDSA (`secp256k1`) https://docs.orochi.network/dkg/dkg-construction/dkg-construction.html. There is an technical report I could share via email. We want to expand to support `ed25519` and `sr25519`. Just to make it clear, everything was implemented by consuming Web3 Foundation grant will be licensed under `Apache-2.0` and `C00`.

2023-07-07 14:26 UTC, keeganquigley commented
Thanks for the update @chiro-hiro and sorry for the delay. So if I understand correctly, this grant is completely independent of Orosign and the R&D on the curves would benefit all substrate MPC wallet developers, is that correct?

I don't think that would be an issue policy-wise, but still might be worth mentioning that our guidelines state that not only must the code/research be open-sourced, but "also must not rely on closed-source software for full functionality". Just want to make sure we are on the same page here.

Regarding David's previous comment, I'm assuming this means you aren't willing to reduce the scope?

2023-07-07 14:51 UTC, keeganquigley commented on applications/orochi-network-orosign-part1.md
> +| **0d.** | Docker                                | We will publish an article that explains about Orosign's MPC wallet on curve `secp256k1`
I think you meant to change this milestone to "Article" instead of "Docker", can you fix this?

2023-07-07 14:51 UTC, keeganquigley commented on applications/orochi-network-orosign-part1.md
> +| **0d.** | Docker                              | We will provide a Dockerfile(s) that can be used to test all the functionality delivered with this milestone.
Is Docker needed for this milestone? If you don't think it is necessary you can go ahead and remove it.

2023-07-07 14:51 UTC, keeganquigley commented on applications/orochi-network-orosign-part1.md
> +| **4.**  | Research    | Researching MPC in `sr25519` and providing the document that describe how the MPC will be built and its security consideration                             |
I'd still love to see the research deliverables expanded more here. 

- What questions are you looking to find answers to? 
- What problems currently exist that you are looking to solve?
- Have you already consulted with other MPC projects in the substrate ecosystem to identify common pain points among devs?
- Have you looked for other research in this area to be sure it still needs to be done?
- Can you explain what a semi-retail user is?

I understand that MPC is the next generation of seed phrase abstraction, but I'm trying to understand what this research is attempting to accomplish and what will be produced as a result of it. Thanks!

2023-07-07 14:56 UTC, keeganquigley commented
Since the proposed research includes security considerations, I will also ping my colleague @bhargavbh who has more of an expertise in the area of security. If he has time, perhaps he can also comment on the usefulness of the research for the different curves.

2023-07-09 05:17 UTC, chiro-hiro commented
Hi @keeganquigley, thanks for your response.

> So if I understand correctly, this grant is completely independent of Orosign and the R&D on the curves would benefit all substrate MPC wallet developers, is that correct?

Yes, this research benefit the Polkadot ecosystem and all developers who aimed to build MPC wallet solution for Polkadot.

> What questions are you looking to find answers to?

In this milestone, our team use cryptography to build a bridge from Digital Signature Algorithm (DSA especially ECDSA, EdDSA, Schnorr Signature) to Multi-Party Computation (MPC) allow the signing process to be performed without actual private key. There are 3 DSAs were used by Polkadot: `secp256k1`, `ed25519`, `sr25519`. Before we can build a MPC based DSA, we need to research the algorithm and figure out how we could fit MPC into it. You may notice that each curve have different parameters and different field, after the research we can specify how MPC should be implement without harm its security.

2023-07-11 20:47 UTC, keeganquigley submitted a review, later dismissed
Thanks for the explanations @chiro-hiro it sounds like you have already put some effort into research, and I think it could be helpful to have more MPC projects in our ecosystem. I'm generally happy to go forward with it. I will mark your application as ready for review and ping the committee.

2023-07-12 07:44 UTC, Noc2 requested changes
I'm also generally happy to go ahead with it. But I still think it makes more sense to initially apply for a level 1 grant (10k) for milestone 1. Given @keeganquigley approval, this is something we could basically immediately go ahead with once you update the proposal. After this, once you deliver the first milestone, you could apply for a follow-up grant.

2023-07-19 12:12 UTC, Noc2 commented
@chiro-hiro, just to ping you here again. Would you be willing to reduce the scope to just the first milestone?

2023-07-24 05:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1786) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1786) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1786) it.</sub>

2023-07-24 05:27 UTC, chiro-hiro commented
Hi @keeganquigley @Noc2,

I changed the proposal to match your request, please review our proposal.

2023-07-24 06:50 UTC, Noc2 approved these changes
Thanks for the update. As promised, I'm happy to go ahead with it. Could you also sign our terms and conditions again? It looks like the bot was reset. We can only accept the agreement once the terms are signed.

2023-07-24 18:19 UTC, Noc2 commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1786) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1786) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1786) it.

@chiro-hiro could you please sign the terms (again)? I will merge the application once this is done.

2023-07-25 06:50 UTC, chiro-hiro commented
Hi @Noc2, sorry for being late. I signed please check!.

2023-07-25 07:12 UTC, Noc2 commented
Perfect. Thanks. I will merge the application.

2023-07-25 07:12 UTC, merged

2023-11-03 16:04 UTC, semuelle commented
@chiro-hiro, the postal address in the invoice does not match the one in the grant application. Could you modify one to match the other?

2023-11-04 03:35 UTC, chiro-hiro commented
Hi @semuelle, I'm aware of this issue and updated both the invoice  address and payment address. Please check the latest invoice. More details can be found here https://github.com/w3f/Grant-Milestone-Delivery/pull/1007