Add ISO-8553 implementation application
w3f/Grants-Program pull request #1809
Opened 2023-06-19 22:56 UTC by dastansam

#### Project Abstract

This application is in response to the [ISO-8583 RFP](https://github.com/w3f/Grants-Program/blob/master/rfps/open/ISO_8583.md).

In this project I aim to implement the proof of concept for the ISO-8583 standard in Substrate. The implementation will be based on the extensive research done by [Adit Patel](https://github.com/adit313) in the following [repository](https://github.com/adit313/ISO8583-Blockchain-Integration-Plan).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-06-20 05:54 UTC, Noc2 requested changes
Thanks for the application. In general, it looks really good. But your first milestone currently doesn't contain any Substrate-specific deliveries. Could you try to change this? Also, it would be nice to have some simple mock-ups or initial designs for the web app.

2023-06-20 08:21 UTC, dastansam commented
hey @Noc2,

thanks for the swift feedback. 

I addressed your feedback and here is the summary of what changed:

- Added more details for first milestone, specifically about how merchant app and PCIDSS Compliant Gateway will interact with the Substrate chain. PCIDSS Compliant Gateway is tightly coupled to offchain workers, in fact, the combination of both forms a centralized oracle mentioned in the research document. The gateway also does some of the expensive, repetitive tasks (by querying on-chain, basically) before the messages reach offchain workers, so that they only focus on validating and dispatching transactions.  I will also include some kind of cryptographic authorization to ensure only offchain workers are consuming messages from the message broker. I think this part of the milestone will be the most challenging and time consuming.
- Added mockups for merchant app. I won't be focusing a lot of my time on UI, but there will be a payment window page that provides both card and crypto payments.
- Generally added more documentation where it was lacking

2023-06-20 08:41 UTC, Noc2 approved these changes
Thanks for the super quick update here. I'm happy to go ahead with it and will share it with the rest of the team.

2023-06-20 09:13 UTC, gautamdhameja approved these changes

2023-06-20 17:02 UTC, keeganquigley approved these changes
Thanks @dastansam for wanting to work on this! I remember when I talked with Adit Patel, he agreed that the biggest problem here was how to implement chargebacks. I can imagine that other features like authorization holds might also be complex. Anyway, cool to see that you've already done some research on it. 

Happy to approve; also Adit [mentioned](https://github.com/w3f/Grants-Program/pull/1106#issuecomment-1414885174) that he's willing to help any team who wanted to work on it, so feel free to reach out to him.

2023-06-20 19:03 UTC, dastansam commented
Hey @keeganquigley,

thanks for your feedback!

I read Adit's comments and planning to personally reach out to him

2023-06-20 19:13 UTC, merged

2023-11-21 21:45 UTC, keeganquigley commented
Hi @dastansam how is milestone 2 coming along?

2023-11-30 23:47 UTC, keeganquigley commented
pinging @dastansam

2023-12-15 17:35 UTC, keeganquigley commented
Hi @dastansam are you still working on this grant? Would love to hear an update and find out if you've been having any difficulties.

2024-01-19 10:32 UTC, dastansam commented
hey @keeganquigley,

I lost access to my email for this account and didn't get the notification. I am still working on the grant and was planning on submitting the delivery soon. Is it possible to open this grant again?

2024-01-19 15:32 UTC, dastansam commented
PR for re-opening here: #2184 

> hey @keeganquigley,
> 
> I lost access to my email for this account and didn't get the notification. I am still working on the grant and was planning on submitting the delivery soon. Is it possible to open this grant again?

2024-01-19 16:14 UTC, keeganquigley commented
Thanks @dastansam glad you want to continue working on it, that's no problem.

2024-03-07 22:50 UTC, keeganquigley commented
Hi @dastansam how is it coming along are you still planning to submit this delivery soon?

2024-03-07 22:52 UTC, dastansam commented
> Hi @dastansam how is it coming along are you still planning to submit this delivery soon?

Hey, yes, hopefully by the end of this week. I'm preparing testing guidelines and docs. Thank you for your patience again!

2024-06-04 15:36 UTC, Polkadot-Forum commented
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-iso-20022-integration/8483/1

2024-06-05 04:27 UTC, Eldo420 commented
---

# Proposal for ISO-8583 PoC Implementation on Substrate Blockchain Framework

## 1. Introduction

### Project Title:
ISO-8583 PoC Implementation on Substrate Blockchain Framework

### Project Description:
This proposal aims to develop a proof of concept that integrates the ISO-8583 messaging standard with the innovative Substrate blockchain framework. ISO-8583 is a global standard protocol used by credit-card processing networks to enable transactions among different banks and financial institutions. Our goal is to build a prototype that demonstrates how ISO-8583 can be leveraged on a blockchain platform, enhancing security, transparency, and efficiency in financial transaction processing.

## 2. Objectives

### High-Level Objectives:
- **PoC Development**: Successfully implement a proof of concept that demonstrates the technical feasibility of integrating ISO-8583 with the Substrate blockchain framework. This includes basic functionalities such as transaction initiation, authorization, and confirmation.
- **Seamless Interoperability**: Ensure smooth and seamless communication between traditional financial systems utilizing ISO-8583 and the blockchain-based infrastructure built on Substrate.
- **Open Source Contribution**: Develop the PoC as an open-source project to foster innovation and collaboration within the community.
- **Comprehensive Documentation**: Produce extensive documentation to assist other developers and users in understanding and using the integration effectively.

## 3. Detailed Project Plan and Roadmap

### Milestone 1: Initial Research and Technical Design
- **Objective**: Conduct thorough research on both ISO-8583 messaging standards and the Substrate framework to lay a strong foundation for the technical design.
- **Tasks**:
  - Conduct an exhaustive literature review on ISO-8583 protocol types, data elements, and message flows.
  - Analyze the architecture of the Substrate blockchain framework with a focus on its extensibility and modular capabilities.
  - Design a technical strategy outlining how ISO-8583 messages will be mapped to Substrate transactions, including data flow diagrams and interaction models.
  - Create a project feasibility analysis to mitigate risks and forecast potential challenges.
- **Deliverables**: Comprehensive research report, technical design document, feasibility analysis.
- **Estimated Duration**: 1 month
- **Budget**: $5,000

### Milestone 2: Core Module Development
- **Objective**: Develop the core modules necessary for parsing, constructing, and validating ISO-8583 messages within the Substrate framework.
- **Tasks**:
  - Implement message parsers to decode ISO-8583 messages into a format that Substrate can handle.
  - Construct message formats to encode Substrate transaction data back into ISO-8583 messages.
  - Create core modules to handle various message types, such as financial transactions, account inquiries, and settlements.
  - Develop comprehensive unit tests to validate the functionality and accuracy of these modules.
- **Deliverables**: Functional module implementations, relevant unit tests, validation procedures.
- **Estimated Duration**: 2 months
- **Budget**: $10,000

### Milestone 3: Integration with Substrate
- **Objective**: Integrate the ISO-8583 modules with Substrate to enable end-to-end transaction workflows.
- **Tasks**:
  - Incorporate ISO-8583 message processing as Substrate runtime modules to facilitate transaction validations and state changes.
  - Develop APIs to allow external systems to interact with the Substrate-based blockchain using ISO-8583 formatted messages.
  - Conduct initial end-to-end testing to ensure the efficiency and correctness of the integration.
- **Deliverables**: Integrated modules with Substrate, initial end-to-end test results, API documentation.
- **Estimated Duration**: 3 months
- **Budget**: $15,000

### Milestone 4: Robust Testing and Refinements
- **Objective**: Perform detailed functional, performance, and security testing, followed by necessary refinements.
- **Tasks**:
  - Conduct extensive functional tests covering multiple transaction scenarios to ensure accuracy and reliability.
  - Perform performance testing to evaluate the scalability of the integration and identify any bottlenecks.
  - Analyze security risks and implement measures to safeguard transactions.
  - Make iterative refinements based on test results and performance metrics.
- **Deliverables**: Comprehensive testing reports, optimized and refined modules, security audit report.
- **Estimated Duration**: 2 months
- **Budget**: $10,000

### Milestone 5: Documentation and Community Engagement
- **Objective**: Generate thorough documentation and engage with the developer community to encourage widespread usage and further development.
- **Tasks**:
  - Prepare in-depth documentation, including architectural designs, setup guides, API references, and user manuals.
  - Develop user-friendly tutorials and how-to guides to simplify the adoption and implementation process.
  - Engage with community forums, host webinars, and post informative blog articles to promote the project.
- **Deliverables**: Detailed documentation, tutorial materials, community engagement initiatives.
- **Estimated Duration**: 1 month
- **Budget**: $5,000

## 4. Budget Breakdown

To ensure financial clarity and adherence to the milestones:
- **Total Estimated Cost**: $45,000
  - Milestone 1: $5,000
  - Milestone 2: $10,000
  - Milestone 3: $15,000
  - Milestone 4: $10,000
  - Milestone 5: $5,000

## 5. Technical Specifications

**Programming Languages**:
  - **Rust**: Primary language for developing Substrate modules.
  - **Python/JavaScript**: For testing, automation scripts, and tooling.

**Substrate Version**: Specify, e.g., "Substrate v3.0", for compatibility precision.

**Libraries and Dependencies**:
  - **parity-scale-codec**: Efficient data encoding and decoding.
  - **serde**: Handling serialization and deserialization.
  - **tokio**: Managing asynchronous operations.
  - Other ISO-8583 specific libraries as needed.

**Development Environment**:
  - **IDE**: Visual Studio Code with Rust plugins, IntelliJ IDEA.
  - **Docker**: For isolated, consistent development environments.

**Tools**:
  - **Version Control**: GitHub or GitLab for code repositories, issue tracking, and CI/CD setups.
  - **CI/CD**: Jenkins, CircleCI, or similar tools for continuous integration and deployment.

## 6. Team and Experience

**Team Members**:

- **Lead Developer**:
  - **Name**: John Doe
  - **Background**: Master’s in Computer Science with a decade’s experience in software development and 5 years focused on blockchain.
  - **Roles and Responsibilities**: Overseeing project implementation, coordinating the technical efforts.
  - **Skills**: Rust, Blockchain, Substrate.

- **Blockchain Specialist**:
  - **Name**: Jane Smith
  - **Background**: Bachelor’s in Information Technology, 8 years in blockchain, with notable contributions to open-source communities.
  - **Roles and Responsibilities**: Strategic technical input on blockchain design patterns and interoperability.
  - **Skills**: Substrate, Ethereum, Smart Contracts.

- **ISO-8583 Specialist**:
  - **Name**: Michael Brown
  - **Background**: Ph.D. in Financial Technology, 15 years specializing in financial transaction standards.
  - **Roles and Responsibilities**: Guiding ISO-8583 standards compliance and module development.
  - **Skills**: Financial transactions, ISO-8583 protocol expertise.

- **QA Engineer**:
  - **Name**: Emily White
  - **Background**: Bachelor’s in Software Engineering, 7 years in QA, particularly in fintech and blockchain projects.
  - **Roles and Responsibilities**: Leading testing efforts, ensuring robustness and reliability.
  - **Skills**: Automated testing, Performance testing, Security auditing.

**Previous Work**:
- Successful integration of ISO-20022 messaging for financial institutions.
- Development and deployment of smart cont [...]