Datagen proposal to amend payment for Milestone 2
w3f/Grants-Program pull request #1810
Opened 2023-06-20 14:57 UTC by Lord-Nymphis

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-06-20 15:18 UTC, Lord-Nymphis commented
Let me know your thoughts.

2023-06-20 18:53 UTC, keeganquigley commented on applications/Datagen_Project.md
> +For all the reasons above, I would like to ask an integration of the amount due for the M2 deliverable of 9K USDC (from 12K to 21K
Thanks @Lord-Nymphis I'm not sure what is meant here by "ask an integration of the amount due..." are you asking for us to pay for the milestone before it is completed? Or can you explain what you mean here?

Please note in our [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md), that we aren't able to pay for milestones before the delivery is evaluated and accepted.

2023-06-20 19:09 UTC, Noc2 requested changes
Thanks for the PR. Could you also update the [total costs](https://github.com/w3f/Grants-Program/blob/master/applications/Datagen_Project.md#overview-1) as well as the costs of the [milestone](https://github.com/w3f/Grants-Program/blob/master/applications/Datagen_Project.md#milestone-2--connecting-the-two-blockchains) as part of your PR?

2023-06-20 21:09 UTC, Lord-Nymphis commented on applications/Datagen_Project.md
> +For all the reasons above, I would like to ask an integration of the amount due for the M2 deliverable of 9K USDC (from 12K to 21K
@keeganquigley No, OfC I don't mean for the Milestone to be paid before is completed

2023-06-20 21:20 UTC, keeganquigley commented on applications/Datagen_Project.md
> +For all the reasons above, I would like to ask an integration of the amount due for the M2 deliverable of 9K USDC (from 12K to 21K
Thanks @Lord-Nymphis can you explain what you mean here?

2023-06-20 21:27 UTC, Lord-Nymphis commented on applications/Datagen_Project.md
> +For all the reasons above, I would like to ask an integration of the amount due for the M2 deliverable of 9K USDC (from 12K to 21K
@keeganquigley I mean that, given that the end goal of the Datagen project (not the Milestone, which concerns only the RPC communication, between a Parachain and a Solochain, and not the Grant, which is just a PoC) is to provide cloud computing also for validators; the sooner we develop, the sooner we can have a positive eternality for other projects, including projects in the Polkadot ecosystem.
Obviously it doesn't mean that once we have developed this milestone the Datagen network is operational, but it means that we are one step faster.

Meaning that, by developing faster, we can achieve the goal of having a positive effect on other projects.

2023-06-20 21:29 UTC, Lord-Nymphis commented
Ciao @Noc2 , I did their the you requested directly at the link you sent me (and in the abstract above). 
Let me know if it's ok.

2023-06-21 13:29 UTC, Noc2 commented
> Ciao @Noc2 , I did their the you requested directly at the link you sent me (and in the abstract above). Let me know if it's ok.

Could you please update it as part of this PR?

2023-06-21 13:36 UTC, Lord-Nymphis commented
ok, I think that now it is updated

2023-06-21 16:01 UTC, keeganquigley commented
Thanks for the changes @Lord-Nymphis I will mark it as ready for review and ping the rest of the committee.

2023-06-21 16:02 UTC, Lord-Nymphis commented
thanks @keeganquigley

2023-06-22 20:28 UTC, semuelle commented on applications/Datagen_Project.md
> +For all the reasons above, I would like to ask an integration of the amount due for the M2 deliverable of 9K USDC (from 12K to 21K
@keeganquigley, I think `integration` should be `increase`. Then it makes sense.

2023-06-23 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1810) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1810) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1810) it.</sub>

2023-06-23 09:11 UTC, Lord-Nymphis commented on applications/Datagen_Project.md
> +For all the reasons above, I would like to ask an integration of the amount due for the M2 deliverable of 9K USDC (from 12K to 21K
@semuelle Thanks, done. And corrected few other typos as well.

2023-06-26 14:18 UTC, Noc2 requested changes
Thanks for the PR. But after looking at it again. I'm personally not willing to accept the amendment. The main reason is that I think the grant is against our guidelines, specifically: 
- "We do not award grants for projects that have been the object of a successful token sale." 
- and "Applications must not mention a specific token". 

This was already highly controversial when you [applied](https://github.com/w3f/Grants-Program/pull/980#issuecomment-1180755311), but now you even publicly said that you paid your devs working on the project in the `native token allocation.`

2023-06-26 14:47 UTC, Lord-Nymphis commented
Hi @Noc2 

As said we tried to ask for the amendment because the guys from Parity told us it was worth a try. If you want to vote no or to close the pr is fine.

Just a clarification. I think you are referring to: _"....We thought we could count on @viac92 as an affordable dev. @viac92 was working at a much lower salary than the average substrate dev, both because he was involved in the project with a native token allocation and because he was very junior, and we paid him a salary during his formation in the substrate framework.  ...."_

I was not mentioning native token allocation for the milestone development. I already explained this fact, when we did the application, that devs already had done some previous work for the project (he developed the tokenomic smart contracts BEFORE the grant). For this reason, he had a pre-existing allocation in the project, as an early team member, and compounding the fact that he was an early team member with tokens (fact uncorrelated to the grant, as said in the original grant the tokens are used for other purposes that are not correlated to the object of the grant) and the fact that we paid him for months a salary in order to learn substrate (this being instead correlated to the grant) contributed to him accepting a lower salary than the benchmark. I never ever said that we paid him in native FOR the milestone or for the grant.

Businesses are complicated to run, devs do more than one thing for a company, there are many things going over, and it's not all black or white, my comment was just to give more context about the milestone development. BTW we both know which is a substrate dev salary, which is why I preferred to give more context.

As said, the scope of this amendment was to align the milestone with the real costs of the development.
I don't think in any way that the way in which we managed the dev payment is against the grant rules (we are an incorporated company, not an informal team just working on the grant and the relationship between devs and companies is complex), having said that, I'm fully aware that the process to accept amendments it's decentralized and it is fully within the rights of the commission members to accept or refuse our proposal for changes to what is already approved. We are totally on the same page on this, I just want to clarify eventual factual errors or misinterpretations.

2023-06-27 06:07 UTC, Noc2 requested changes
Thanks for the detailed answer. You are correct that the rule is somehow subjective and hard to define. So the rest of the team/committee might have a completely different opinion here and I will ping them again.

2023-06-28 19:46 UTC, keeganquigley commented
Hi @Lord-Nymphis it is my opinion that if additional development work is needed, it should be added into the application. Without an expansion in scope I find it hard to warrant an increase. Therefore I won't approve the amendment as it stands. Let's see if the rest of the committee has a different opinion.

2023-07-12 19:59 UTC, closed without merging