Tokeneconomics survey: Post approval changes
w3f/Grants-Program pull request #1812
Opened 2023-06-21 02:08 UTC by taqtiqa-mark

Following [Changes to a Grant after Approval instructions](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval):

This PR seeks approval for:
- Change in scope of the review
- Change in delivery timelines
- Change in project audience

### Change in scope of the review: Scope: Top-6
The existing literature was deeper than expected, but also much narrower than
expected. Unfortunately, this means there are not 10 articles that fit
the grant scope. It has also meant that distilling the analysis has taken
much more time than expected.  An example of a first draft annotation of the simplest article is included below.  Un-distilled annotated entries are 3-5 pages, and some annotated entries will likely run to multiple pages.
I have expanded the scope of published articles from
Dec 2022 to the current date in order to capture one article I judge to be
significant.
The current articles cover bubble-coins, dampened-coins,
breakable-coins and redeemable-coins.
These cover most, if not all, characteristics of existing coins.

### Change in delivery timelines
The existing literature was deeper than expected. This meant that distilling
the analysis has taken much more time than expected. I have also had
delays in setting up the legal entities through my accountant - its tax
season right now - hence the delay in submitting the details for the
Milestone payments.

### Change in project audience
Substrate is being merged into Polkadot and is now formally and
practically under the rubric of the 'Parity Polkadot SDK ...
(basically, that’s Substrate, Polkadot, Cumulus and XCM)'.

See: https://web.archive.org/web/20230621013047/https://forum.polkadot.network/t/psa-parity-is-currently-working-on-merging-the-polkadot-stack-repositories-into-one-single-repository/2883/13

Polkadot uses one specific coin model. 
This project envisions/contemplates token designs that improve on DOT or even
conflict with DOT.
These changes address that broader audience.

![Screenshot from 2023-06-21 11-58-27](https://github.com/w3f/Grants-Program/assets/1468258/07b32b8c-0470-49ad-9bde-a54b89e53a1d)

2023-06-23 00:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1812) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1812) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1812) it.</sub>

2023-06-23 00:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1812) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1812) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1812) it.</sub>

2023-06-23 11:25 UTC, semuelle requested changes
Thanks for the update, @taqtiqa-mark.

Why did you replace Substrate? The name change has not happened yet (and won't happen overnight) and open-web3-stack is not a particularly well-known name. IMO, the number of teams using open-web3-stack is sufficiently large to keep the name Substrate in this application.

Also, open-web3-stack has no affiliation with W3F. 

Other than that, LGTM.

2023-06-24 09:26 UTC, taqtiqa-mark commented
> Why did you replace Substrate? The name change has not happened yet (and won't happen overnight) and 

At the time of writing the application I, incorrectly, believed Substrate was the umbrella under which Polkadot sat as the first-mover/PoC of what you could do with Substrate.

 I believe the Parity leads were very clear in the forum post I linked to: Substrate serves Polkadot
To be fair to them, as I learned more, I now understand this has always been the case. 

I linked to TOW3S to cite some W3F project where users can follow-up, and hopefully find the example implementation I foreshadowed. Such an example does not fit naturally under Polkadot, where we may be exploring/experimenting with things that are considered flaws of Polkadot, and where we might also hope to attract projects that aim to compete with Polkadot, as well a projects that complement Polkadot.  

 I will remove the references, it doesn't impact the paper.

> open-web3-stack is not a particularly well-known name. 

True, right now.  This is a chicken-or-egg first problem. However, it does I believe have [critical mass](https://github.com/open-web3-stack/open-runtime-module-library#projects-using-orml).  As mentioned I'll remove references to any particular chain. If the example implementation goes ahead this can be revisited as part of that grant.

> IMO, the number of teams using open-web3-stack is sufficiently large to keep the name Substrate in this application.

 Such an example does not fit naturally under Polkadot for the reasons outlined.

> Also, open-web3-stack has no affiliation with W3F.

Ack. I'll remove those too.

2023-06-26 11:23 UTC, semuelle approved these changes
Thanks for the updates. Happy to proceed.

2023-06-28 16:11 UTC, Noc2 approved these changes

2023-06-28 16:12 UTC, merged