Amend milestone 3.
w3f/Grants-Program pull request #1859
Opened 2023-07-23 04:27 UTC by ethernomad

This pull request is an amendment for Milestone 3 for the Hybrid Block Explorer grant.
Milestones 1 & 2 have already been completed.

Enabling separate builds of the indexer for each chain (akin to how each chain is a separate build of Substrate) was a considerable amount of work and required writing Rust macros. This should now be the emphasis of Milestone 3.

New Rust app polkadot-indexer will enable indexing of polkadot, kusama, rococo & westend using hybrid-indexer.

The dapp will have an option to configure which chain is queried and will be hosted at https://hybridscan.app

There will be a blog post introducing the project instead of a video.

Let me know if there are any issues with these changes.

Once milestone 3 has been completed an application for grant 2 will be made including light client support in both the indexer and the front end.

2023-07-23 04:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1859) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1859) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1859) it.</sub>

2023-07-24 06:37 UTC, Noc2 approved these changes
Thanks for the update. I'm happy to go ahead with it and mark it as ready for review. But keep in mind usually we don't cover hosting costs as part of grants, so feel free to remove delivery number 4.

2023-07-24 09:29 UTC, takahser requested changes
@ethernomad I'm also willing to approve, given deliverable 4 is removed. 👍

2023-07-24 09:29 UTC, takahser commented on applications/hybrid.md
> +| 4. | Hosting | hybrid-dapp hosted at https://hybridscan.app supporting polkadot, kusama rococo & westend. |
```suggestion
```

2023-07-24 09:55 UTC, Noc2 approved these changes

2023-07-24 18:52 UTC, keeganquigley approved these changes

2023-07-25 07:56 UTC, merged