Amend Polkadart
w3f/Grants-Program pull request #1860
Opened 2023-07-24 09:26 UTC by Lohann

This amend adds a new milestone and update the value of the 3 milestone, we underestimated the effort required to support signed transactions, I detailed the new challenges bellow:

## 1. Lack of documentation and inconsistencies
Many important components necessary for implement signed extrinsics are not documented or have ambiguous implementations, one example is Substrate BIP-39, while the original [Bitcoin BIP39](https://en.bitcoin.it/wiki/BIP_0039) is well documented, substrate's BIP39 have no documentation at all, so we must rely on the code as reference, it is also fragmented between [substrate-bip39](https://github.com/paritytech/substrate-bip39) and [Substrate](https://github.com/paritytech/substrate/blob/master/primitives/core/src/crypto.rs#L925-L951) repos, and there's a lot of complexity and tiny details there, such as the usage of [magical strings](https://github.com/paritytech/substrate/blob/master/primitives/core/src/ed25519.rs#L374-L376) for key derivation, which is not documented anywhere besides the code. Another issue is that the implementation between [polkadot-api](https://github.com/polkadot-js/common/blob/v12.3.2/packages/util-crypto/src/key/DeriveJunction.ts#L20-L35) and [subkey](https://github.com/paritytech/substrate/blob/master/primitives/core/src/crypto.rs#L185-L206) are not consistent, example:
```javascript
import { Keyring } from '@polkadot/keyring';

const keyring = new Keyring({ type: 'sr25519', ss58Format: 42 });
const account = keyring.createFromUri("//18446744073709551616");
console.log(account.address);

// Output: 5FsxbdTHtNSLE5HCLzzGVB2oEzxZB6QJuakiHSoTNWEXD1qj
```

Now using Substrate's [Subkey](https://docs.substrate.io/reference/command-line-tools/subkey/):
```shell
$ subkey inspect --scheme=Sr25519 --network=substrate "//18446744073709551616"

Secret Key URI `//18446744073709551616` is account:
  Network ID:        substrate 
 Secret seed:       0xe95232125504305f665b8e8c891e1e1e87fcbb0b4eff38a9e100862207d2ce97
  Public key (hex):  0x11ea83f6705f1e3bd3b50695227a1c64dccd5c368648f17eb80f093695028daa
  Account ID:        0x11ea83f6705f1e3bd3b50695227a1c64dccd5c368648f17eb80f093695028daa
  Public key (SS58): 5CUCLVQzLh5oxNanu3699rqaxmkiQG4kNNd4WCDfJWiqwuYk
  SS58 Address:      5CUCLVQzLh5oxNanu3699rqaxmkiQG4kNNd4WCDfJWiqwuYk
```
Both generate different address when the path number have more than 64bits, who is right? We face similar issues with other modules too, like Ed25519 signatures (also use [magic strings](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/primitives/core/src/sr25519.rs#L58-L60)), Signed Extensions, etc...
I believe we are the only solution in the ecosystem besides Substrate that correctly implements the Substrate-BIP39 standard:
https://github.com/rankanizer/polkadart/tree/main/packages/substrate_bip39

## 2. No Libraries in Dart
Some cryptographic libraries like [schnorrkel](https://github.com/w3f/schnorrkel) only exists in Rust, as example Polkadot-api uses [native rust](https://github.com/polkadot-js/wasm/tree/v7.2.1/packages/wasm-crypto) compiled to wasm for signing transactions, we cannot do the same in dart because Flutter runs on web, mobile and desktop devices, we can't assume a native Wasm Runtime like the webbrowser, and creating [native bindings in flutter](https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings-c-tab) is not trivial either, it requires us to create one binding for each platform (iOS, Android, Windows, Web, MacOs, etc), which must be tested and included in our CI pipeline, it significantly increases the scope of this milestone. Another solution is rewrite the [schnorrkel](https://github.com/w3f/schnorrkel) in pure dart, we believe is the easiest and best approach, we included it in a new milestone.

## 3. Why we need more time
Given the polkadot-api code isn't equivalent to the Substrate code, we use the Substrate as reference implementation, the issue is that even we have a lot of talented Dart/Flutter developers working in this Project, just a few of them have the necessary experience and understanding of Substrate's codebase to effectively contribute to this milestone, this is one of the reasons why this milestone got delayed. I would like to highlight that Polkadart is as complex as [polkadot-api](https://github.com/polkadot-js/api) and [capi](https://docs.capi.dev/), to reflect the size of the project, I've update the value of the Milestone 3 and added a new Milestone for rewrite the [schnorrkel](https://github.com/w3f/schnorrkel) in dart and support sr25519 keypairs.

We are very proud of Polkadart, even without signed extrinsics, we already have external contributors and the project is being used in production already. Thanks to Polkadart many Flutter developers joined the Substrate ecosystem. We would love to keep supporting this project, count on us to get this done!

2023-07-24 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1860) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1860) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1860) it.</sub>

2023-07-26 03:59 UTC, Noc2 requested changes
Thanks for creating the amendment and the detailed explanation here. I'm generally happy to go ahead with it, but I have two questions/comments:
- Why did you change the FTE, and why did the cost per developer per month for the fourth milestone increase so much? 
- What's your cryptographic background/experience? I think in almost all cases it's better to use bindings for schnorrkel. Otherwise, it might also be necessary to audit the dart implementation.

2023-08-02 13:01 UTC, semuelle commented
pinging @Lohann

2023-08-09 13:27 UTC, semuelle commented
I am going to close this due to inactivity. Please let me know if I should reopen it, @Lohann.

2023-08-09 13:27 UTC, closed without merging