smartAudit project
w3f/Grants-Program pull request #1874
Opened 2023-07-30 02:47 UTC by ferasalsaab

#### Project Abstract

The smartAudit project aims to develop a comprehensive smart contract auditing platform for the Polkadot ecosystem. The platform will utilize both static and dynamic analysis techniques to identify vulnerabilities and security risks in smart contracts deployed on the Polkadot network. It will offer user-friendly interfaces, detailed vulnerability reports, and recommendations for contract improvements, empowering developers to build secure and reliable decentralized applications.

Grant Level: Level 2 (Up to $30,000, 3 approvals)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`smartAudit.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (BTC address: 0x1234567890abcdefg).
- [x] The software delivered for this grant will be released under the Apache 2.0 license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@ferasalsaab:matrix.org` (using the Element homeserver).

2023-07-30 02:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1874) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1874) it.</sub>

2023-07-31 11:49 UTC, Noc2 requested changes
Thanks for the application. However, we usually don't support a grant's initial "Project Planning and Architecture" phase and expect teams already to have a concrete technical plan. For example, could you add the programming language, the details of the static analysis, the smart contract language you want to support, etc., to the milestone deliverables? Additionally we usually don't support the deployment of the software but rather focus on the open source software development. Also, deliverables like "Bug Fixes and Optimization" could theoretically mean anything (e.g., add one line of code) and therefore need to be further specified. Let me know if you have any questions.

2023-08-09 13:25 UTC, takahser commented
@ferasalsaab on top of the points @Noc2 already has made, we'd usually ask for wireframes for any ui-based deliverables.

2023-08-11 14:52 UTC, semuelle commented
I'm closing this application due to inactivity. Please let me know if you want to continue working on it, @ferasalsaab.

2023-08-11 14:52 UTC, closed without merging