Rfp/security marketplace
w3f/Grants-Program pull request #1901
Opened 2023-08-10 11:03 UTC by ParthChaudhary31

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-08-10 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1901) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1901) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1901) it.</sub>

2023-08-14 05:18 UTC, ParthChaudhary31 commented
> Thanks @ParthChaudhary31 you mentioned that this would help save on development costs, does this mean there should be an adjustment in price as well? Or are these only contract deployment costs that aren't covered as part of the grant?

The latter actually, The cost-cutting would be on the front of :
#1) Deployment costs (Contract optimization by merging functionality into a single contract would require deploying fewer contracts).
#2) The Arbiters will not need to spend from their own pockets while voting. (Minimising gas fees Charges).

2023-08-14 14:51 UTC, keeganquigley approved these changes
Thanks for clarifying @ParthChaudhary31 LGTM

2023-08-24 05:44 UTC, ParthChaudhary31 commented
@semuelle ,
I understand your motives for keeping the Arbiter voting on-chain, The change is a suggestion that we believe would smoothen the onboarding process and encourage arbiters, however, we're perfectly fine with keeping it on-chain as well. If you can verify with the remaining team and give a final verdict on the changes, We'll be able to plan accordingly and start with the development.

2023-08-24 09:57 UTC, semuelle approved these changes
Thanks, @ParthChaudhary31. Sounds good to me. I will ping the rest of the committee again.

2023-08-24 09:57 UTC, semuelle requested changes
Thanks, @ParthChaudhary31. Sounds good to me. Could you integrate this into the document? I will ping the rest of the committee again.

2023-08-24 11:13 UTC, ParthChaudhary31 commented
@semuelle 
Sure, I've re-added the Arbiter's voting contract to milestone 1, We'll start working on it now and aim to finish this soon.

2023-08-24 11:14 UTC, ParthChaudhary31 commented
recheck

2023-08-24 11:14 UTC, ParthChaudhary31 commented
> recheck

recheck

2023-08-24 15:20 UTC, semuelle commented on applications/Security_Marketplace.md
> +20. The Arbiter's voting system will be hosted off chain to facilitate their transactions without any cost.
```suggestion

```

2023-08-25 15:56 UTC, keeganquigley approved these changes

2023-08-30 11:57 UTC, Noc2 approved these changes

2023-08-30 11:57 UTC, merged