EquiBloc Creative Ventures.md
w3f/Grants-Program pull request #1911
Opened 2023-08-16 15:05 UTC by Dazi01

PROJECT NAME:
EquiBloc Creative Ventures

Team Name: Sirius Africa 
Payment Address: (Ethereum) : 0xe07767abe76de87C1DbF7D9d281805d7678A0ce6
Level: 2

OVERVIEW
Tagline: Transforming Africa's Creative Landscape with Blockchain Innovation
Description: Sirius Africa is revolutionizing Africa's creative industry by providing a blockchain-powered platform that offers structured equity financing to content creators, bridging the existing funding gap. Our platform accumulates industry data to streamline the process and recommend strategic partnerships, enhancing the entire creative ecosystem.
Integration with Substrate / Polkadot / Kusama: Sirius Africa envisions integrating with the Substrate framework to leverage the scalability, interoperability, and security features it offers. This integration will enable us to create a robust and scalable blockchain infrastructure tailored to Africa's unique creative landscape.
Team's Interest: Our team is deeply motivated to address the lack of structured equity financing in Africa's creative industries. We see the transformative potential of blockchain technology in democratizing access to funding and catalyzing growth. With a decade-long commitment to enhancing digital and physical infrastructure in the creative sector, we are driven to pioneer this innovative solution and reshape Africa's creative landscape for the better.

Project Details

Our project's expected final state is a fully functional blockchain-powered platform that facilitates structured equity financing for Africa's creative industries. This platform will provide creatives with access to funding, streamline the equity financing process, and offer data-driven recommendations for strategic partnerships.

Patents and Share Screen Video Call:
Sirius Africa holds several patents poised to revolutionize the creative industry:
* Patent for novel methods of using blockchain technology to facilitate equity financing.
* Patent for innovative algorithms or techniques for evaluating and determining the value of equity stakes in creative projects.
* Patent for new methods of managing and distributing equity financing within a multi-channel network structure.
I am eager to discuss these patents in detail during a share screen video call session. Unfortunately, I am currently unable to share patent documents due to our ongoing state of development.
Transition to USDT and Project Deck:
Excitingly, we've recently embarked on a strategic journey by transitioning from E-naira to USDT, ensuring enhanced stability throughout our progress. To delve into the depth of our ongoing project, I encourage you to explore our current project deck: [Project Deck Link](https://drive.google.com/file/d/1KRadf5yp-LNQo0QOLrXkp9fLEofyrdlp/view).
Commitment to Industry Infrastructure:
For over a decade, we've dedicated ourselves to strengthening both digital and physical infrastructure within Africa's creative sectors. To witness a compilation of our initiatives and achievements, I invite you to explore our Data Room: [Data Room Link](https://drive.google.com/drive/u/0/folders/1RcNrptPDYAERe5EVstJNUpAH1SJfzgn_).
Your exploration of these resources will provide further insight into our vision and commitment to transforming Africa's creative landscape.

Relevant Submissions:

Data Models/API Specifications: We will provide detailed data models and API specifications outlining how user data, funding transactions, and industry data will be structured and interact within our platform.

Technology Stack: Our technology stack will include blockchain (Substrate), AI (machine learning models), web development frameworks, and cloud infrastructure.

Core Components/Protocols: We will deploy core components such as user authentication, smart contract-based funding, data analytics, and recommendation algorithms.

PoC/MVP: We will present a Proof of Concept (PoC) or Minimum Viable Product (MVP) showcasing essential features like user registration, funding transactions, data accumulation, and basic recommendation functionality.

Clarification on Limitations:

Our project will not provide traditional banking services or investment advice. While we facilitate equity financing, we will not engage in active fund management. Additionally, our platform will not guarantee financial outcomes for users, as investment returns are subject to market dynamics. We will not offer legal advisory services or professional design assistance, as we intend to leverage AI to assist content creators in these areas.

Ecosystem Fit:
Project Positioning:

Sirius Africa integrates into the Polkadot/Substrate/Kusama ecosystem as a blockchain-powered platform tailored for Africa's creative industry. Our innovative solution addresses the absence of structured equity financing in the continent's creative sectors. By leveraging blockchain technology, we aim to create a secure, transparent, and accessible ecosystem for funding creative projects.

Target Audience:

Our primary audience includes dApp developers, creators in Africa's creative industries, and potential investors seeking exposure to the region's creative scene. Additionally, our platform opens doors for UI/UX designers, as we emphasize user-friendly experiences for all participants in the ecosystem.

Meeting Key Needs:

Sirius Africa's project addresses the critical need for structured equity financing within Africa's creative sectors. By providing a blockchain-based platform, we empower creators to access funding opportunities that were previously scarce or unavailable. This bridges the gap between creators and investors, fostering growth and innovation within the industry.

Comparison to Similar Projects:

While there are existing projects in related ecosystems, such as blockchain-based financing platforms, there is a dearth of solutions catering specifically to Africa's creative industries. Sirius Africa stands out by focusing on this niche, combining blockchain and AI to transform an underserved sector. Our emphasis on equity financing, industry data accumulation, and tailored recommendations sets us apart.

Differences from Similar Projects:

Unlike projects in related ecosystems that may not be region-specific, Sirius Africa is uniquely poised to cater to Africa's creative landscape. We provide a holistic solution that encompasses equity financing, data-driven insights, and AI-powered recommendations. Our focus on enhancing local industries and addressing challenges specific to Africa sets us apart from more generalized solutions.

Team members
* Name of team leader - Dazi Ezekiel-Zang 
* Names of team members 

Contact
* Contact Name: Full name of the contact person in your team- Japheth Jonathan
* Contact Email: Contact email - japheth.jonathan@pglnigeria.com
* Website: https://siriusafrica.com/project/

Contact
* Contact Name: Full name of the contact person in your team-  Dazi Ezekiel-Zang
* Contact Email: Contact email - info#siriusafrica.com
* Website: https://siriusafrica.com/project/

Contact
* Contact Name: Full name of the contact person in your team-   Afam Ojemeni
* Contact Email: Contact email - afamoj@gmail.com
* Website: https://siriusafrica.com/project/

Contact
* Contact Name: Full name of the contact person in your team-   Wura Alake
* Contact Email: Contact email - wuraola007@gmail.com
* Website: https://siriusafrica.com/project/

Legal Structure
* Registered Address: 1 Ikota Road, Ajah, Lekki, Lagos State, Nigeria. 
* Registered Legal Entity: Sirius Africa InLtd. 

Team's Experience:

Our team is uniquely poised to drive the success of this innovation, bringing together a diverse range of expertise to ensure a seamless execution:

Japheth Jonathan, Chief Technology Officer:
Japheth is a seasoned expert in app, Web3, AI, and blockchain development. With an impressive track record of single-handedly engineering successful blockchain products, his hands-on approach and innovative mindset are instrumental in delivering cutting-edge solutions. Japhet [...]

2023-08-16 15:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1911) it.</sub>

2023-08-16 17:29 UTC, Noc2 requested changes
Thanks for your interest in our grants program. But could you add a new file with your application rather than directly changing our template? Also, we need concrete deliveries and see the mandatory default deliverables of the template.

2023-08-16 19:40 UTC, Dazi01 commented
[EquiBloc Creative Ventures.md.pdf](https://github.com/w3f/Grants-Program/files/12362955/EquiBloc.Creative.Ventures.md.pdf)

2023-08-16 19:42 UTC, Dazi01 commented
Hi David,

I wanted to let you know that we've uploaded a new file with our updated 
project details and concrete deliverables. We've also incorporated our 
entries into the default deliverables as you suggested. Thanks again for 
your guidance!

Best regards,
Dazi

On 2023-08-16 12:29, David Hawig wrote:
> @Noc2 requested changes on this pull request.
> 
> Thanks for your interest in our grants program. But could you add a
> new file with your application rather than directly changing our
> template? Also, we need concrete deliveries and see the mandatory
> default deliverables of the template.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
> 
> Links:
> ------
> [1] 
> https://github.com/w3f/Grants-Program/pull/1911#pullrequestreview-1581112433
> [2]
> https://github.com/notifications/unsubscribe-auth/BB56BINF4NK5RMO3X6Z7H53XVT7QXANCNFSM6AAAAAA3SV2AS4

2023-08-16 22:43 UTC, takahser requested changes
@Dazi01 Uploading a PDF is not what we're expecting here; could you push your proposal in the markdown format to the repo, while making sure it adheres to the application template?

2023-08-17 13:05 UTC, Dazi01 commented
> @Dazi01 please also revert the changes in the `application-template.md` doc.

Done.

2023-08-20 07:27 UTC, Noc2 requested changes
Thanks for the update. I have a few quick questions regarding the application itself. What exactly is the DataAccumulation module doing, and how is it storing the data? And what are equity financing contracts? Are these ink! smart contracts?

2023-08-20 11:44 UTC, Dazi01 commented
Thanks for your questions; these are very insightful.

The Data Accumulation module plays a pivotal role in our strategy to 
unleash the latent potential of the creative industry by aggregating 
essential data. It collects information about various aspects of funded 
creative projects, including expenses, collaborations, logistics, and 
affiliations with organizations. This data is then securely stored on 
the blockchain, ensuring its transparency and integrity.

Equity financing contracts are indeed ink! smart contracts. These 
contracts outline the conditions under which creative projects obtain 
funding through "cosmic credits." These credits serve as units of 
measurement for equity financing, not actual cryptocurrencies. To 
convert 'cosmic credits' into actual currency (USDT), a detailed project 
plan and robust data must be provided. These smart contracts not only 
facilitate fund disbursement but also stimulate data accumulation. When 
creatives decide to convert their cosmic credits to USDT, they must 
input intricate information about project plans, collaborators, 
expenses, and organizational specifics. This data, along with the cosmic 
credits, is recorded on the blockchain, creating a comprehensive and 
current repository of information.

The Data Accumulation module and equity financing contracts complement 
each other to ensure creatives receive funding while concurrently 
contributing data that enhances our understanding of the creative 
landscape. This data accumulation process aims to address the industry's 
data gap and establish us as a reliable source of information. By doing 
so, we bridge a significant void in equity financing within Africa's 
creative sector.


Best,
Dazi


On 2023-08-20 02:28, David Hawig wrote:
> @Noc2 requested changes on this pull request.
> 
> Thanks for the update. I have a few quick questions regarding the
> application itself. What exactly is the DataAccumulation module doing,
> and how is it storing the data? And what are equity financing
> contracts? Are these ink! smart contracts?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> 
> Links:
> ------
> [1] 
> https://github.com/w3f/Grants-Program/pull/1911#pullrequestreview-1585816132
> [2]
> https://github.com/notifications/unsubscribe-auth/BB56BIPIP4DNWEFVTRDUOY3XWG4ABANCNFSM6AAAAAA3SV2AS4

2023-08-20 11:54 UTC, Dazi01 commented
Thanks for your questions; these are very insightful.

The Data Accumulation module plays a pivotal role in our strategy to 
unleash the latent potential of the creative industry by aggregating 
essential data. It collects information about various aspects of funded 
creative projects, including expenses, collaborations, logistics, and 
affiliations with organizations. This data is then securely stored on 
the blockchain, ensuring its transparency and integrity.

Equity financing contracts are indeed ink! smart contracts. These 
contracts outline the conditions under which creative projects obtain 
funding through "cosmic credits." These credits serve as units of 
measurement for equity financing, not actual cryptocurrencies. To 
convert 'cosmic credits' into actual currency (USDT), a detailed project 
plan and robust data must be provided. These smart contracts not only 
facilitate fund disbursement but also stimulate data accumulation. When 
creatives decide to convert their cosmic credits to USDT, they must 
input intricate information about project plans, collaborators, 
expenses, and organizational specifics. This data, along with the cosmic 
credits, is recorded on the blockchain, creating a comprehensive and 
current repository of information.

The Data Accumulation module and equity financing contracts complement 
each other to ensure creatives receive funding while concurrently 
contributing data that enhances our understanding of the creative 
landscape. This data accumulation process aims to address the industry's 
data gap and establish us as a reliable source of information. By doing 
so, we bridge a significant void in equity financing within Africa's 
creative sector.


Best,
Dazi
On 2023-08-20 02:28, David Hawig wrote:
> @Noc2 requested changes on this pull request.
> 
> Thanks for the update. I have a few quick questions regarding the
> application itself. What exactly is the DataAccumulation module doing,
> and how is it storing the data? And what are equity financing
> contracts? Are these ink! smart contracts?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> 
> Links:
> ------
> [1] 
> https://github.com/w3f/Grants-Program/pull/1911#pullrequestreview-1585816132
> [2]
> https://github.com/notifications/unsubscribe-auth/BB56BIPIP4DNWEFVTRDUOY3XWG4ABANCNFSM6AAAAAA3SV2AS4

2023-08-21 17:22 UTC, Dazi01 commented
> Thanks for the update. I have a few quick questions regarding the application itself. What exactly is the DataAccumulation module doing, and how is it storing the data? And what are equity financing contracts? Are these ink! smart contracts?

Thanks for your questions; these are very insightful.

The Data Accumulation module plays a pivotal role in our strategy to
unleash the latent potential of the creative industry by aggregating
essential data. It collects information about various aspects of funded
creative projects, including expenses, collaborations, logistics, and
affiliations with organizations. This data is then securely stored on
the blockchain, ensuring its transparency and integrity.

Equity financing contracts are indeed ink! smart contracts. These
contracts outline the conditions under which creative projects obtain
funding through "cosmic credits." These credits serve as units of
measurement for equity financing, not actual cryptocurrencies. To
convert 'cosmic credits' into actual currency (USDT), a detailed project
plan and robust data must be provided. These smart contracts not only
facilitate fund disbursement but also stimulate data accumulation. When
creatives decide to convert their cosmic credits to USDT, they must
input intricate information about project plans, collaborators,
expenses, and organizational specifics. This data, along with the cosmic
credits, is recorded on the blockchain, creating a comprehensive and
current repository of information.

The Data Accumulation module and equity financing contracts complement
each other to ensure creatives receive funding while concurrently
contributing data that enhances our understanding of the creative
landscape. This data accumulation process aims to address the industry's
data gap and establish us as a reliable source of information. By doing
so, we bridge a significant void in equity financing within Africa's
creative sector.


Best,
Dazi

2023-08-21 21:46 UTC, takahser requested changes
@Dazi01 thanks for the update.

>• Total Costs: $40,000 USD

If the total price exceeds 30'000 USD you should change the grant level to 3.

> • Hiring developers and engineers for MVP creation: $10,000
> • Design and User Experience: $5,000
> • Quality Assurance and Testing: $3,000
> • Marketing and Initial User Engagement: $2,000
> • Strategic Partnerships and Software Development ($10,000):
> • Collaboration with Algo Coding Expert for advanced software: $6,000
> • Engaging Software Development Experts: $3,000
> • Software Development Planning: $1,000
> • Team Building and Technical Expertise Enhancement ($5,000): • Recruitment of Essential Team Members: $3,000
> • Training and Skill Enhancement: $2,000
> • Equity Financing Integration and Growth Strategy ($5,000):

Most of your costs seem to be not related to implementation of software. Please understand that our program is tailored to the development of relevant software, but not to other types of expenditure such as design, hiring, marketing, trainings efforts, etc.
Quote from our [README](https://github.com/w3f/Grants-Program/#wave-introduction):

> As part of our commitment to promoting the Web3 ecosystem, we offer a comprehensive grants program focused on funding software development and research efforts related to Polkadot and Kusama.

2023-08-23 09:34 UTC, semuelle commented
See our FAQ as well: https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund

2023-08-29 21:07 UTC, semuelle requested changes
To add to what David and Seraya already asked:

- What does "enabling the creation, management, and execution of equity financing contracts" mean, from a technical perspective? Please keep in mind that we are looking for technical novelty, so the deliverable specifications and the application as a whole should focus on what's new _technically_. 
- Why are you separating the functionality into pallets and smart contracts? Why both?
- Why would you run machine learning algorithms on-chain? They are computationally expensive, doing it on-chain doubly so.
- I don't understand the purpose of the DataAccumulation module. You can collect data much more effectively off-chain. Why would you want to decentralise this?

2023-09-06 13:32 UTC, takahser commented
@Dazi01 I'm closing this due to inactivity. LMK in case you'd like to improve the proposal, and we can reopen it.

2023-09-06 13:32 UTC, closed without merging