Tokenguard: Ultimate growth & data analytics tool for Substrate
w3f/Grants-Program pull request #1944
Opened 2023-08-30 13:24 UTC by caaaml

#### Project Abstract

Tokenguard responds to W3F Request for Proposal regarding creation of a comprehensive data analytics & insight discovery tool for the Substrate ecosystem. We believe that **delivering free of charge community analytics will further enhance growth** of the whole Polkadot & Kusama ecosystems.

Our solution focuses on making the **insight discovery process fun & easy for users** by perfecting the UX and making the data highly accessible.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-08-30 13:26 UTC, caaaml commented
I have read and hereby sign the Contributor License Agreement.

2023-08-31 12:00 UTC, Noc2 requested changes
Thanks a lot for the application. I have a few initial questions or concerns: We usually ask teams to create the UI/UX designs upfront and pay for the actual open-source development. Your initial milestone only mentions that you will create the designs. Also, what parts of your UI are currently open source? It seems you already have paying customers, and this grant seems mostly beneficial for you to expand in the Polkadot ecosystem and not necessarily helpful for anyone else.

2023-09-01 13:32 UTC, caaaml commented
Hey @Noc2, thanks for the questions! Let me answer these:

- Our milestones include a _“reusable frontend design”_ which includes Figma mockups and frontend designs consisting of the JS, HTML, CSS and design files. We can propose the mockups in the grant itself, judging from our experience though, they’re going to change in the final delivery. We always test mockups with users and usually the initial version is far from the final one. Let us know if the mockups are expected beforehand, we’re happy to present our ideas here! 

- Currently our UI is not open-source, however all the elements we work out while working on this grant will be open-source and reusable for any third party without our branding.

- Yes, our paying customers are web3 Substrate projects and as we understand, your [Guidelines](https://grants.web3.foundation/docs/Introduction/intro) consider this as a plus. Thanks to that, we’re able to create market-tested solutions, understand what’s needed and lastly - maintain it long-term. Of course, all the features mentioned in this grant will be free for users.

- We very much think that allowing community users to access the data & insights will be extremely beneficial for the whole ecosystem - that is exactly what W3F Request for Proposal asked for. So far we didn’t focus on community users and didn’t plan to due to monetization challenges. The grant would allow us to focus on such user-focused features and deliver them to community for free, creating a synergy between community and web3 projects (enhancing their growth).

We treat this grant as a separate set of features that will be able to operate independently and be reusable by the rest of the community.

2023-09-12 11:23 UTC, Noc2 requested changes
Sorry for the delay here, and thanks for pining. I will mark the application as ready for review and share it with the rest of the team. So that others can comment on it. 

But again, we usually don't fund UX / UI designs, and I personally think that a design development by somebody else isn't something that is super useful for others.  Unless you want to simply clone a project. It's great that you already have paying customers. However, the focus of this grants program is open-source software development and research. We don't for example subsidies certain services for the community. Also, keep in mind that we already received quite a lot of applications for the above RFP in the last few months.

2023-09-12 20:51 UTC, keeganquigley requested changes
Hi @caaaml thanks for all your efforts on this well-written application. I have the following comments:

- The current dashboards look and work great. But it seems that a lot of the UX/UI has already been built. Seeing as we don't fund existing software, can you specify what you would be creating for **2. Core Features UI** section of M1? (M2 is more explicit about the extra features.)
- You mentioned that your UI is not open-sourced. I understand that you plan to open-source everything for the grant, but if any of the work were to rely on closed-source React components, it may still violate our [guidelines](https://github.com/w3f/Grants-Program#guidelines) which state that "the project must not rely on closed-source software for full functionality".
- I agree that many teams have applied in response to this RFP, so I worry that some of the work may be redundant, especially the ETL infra.
- I agree with my colleague that we don't fund the design of the UI, and additionally, we also mostly focus on early-stage PoC and therefore don't fund CI/CD, hosting fees, or other costs in getting the software fully production ready.
- I would also argue that the maintenance costs could be taken out as well, as there is a separate process for [maintenance grants](https://github.com/w3f/Grants-Program#hammer_and_wrench-maintenance-grants).

2023-09-26 16:10 UTC, caaaml commented
Hi @keeganquigley , thanks for the reply! Let me answer your comments in the same order:

- Thanks! We've updated the proposal with mockups that we will transform into standalone designs which will be the deliverables for M1.
- All of the work delivered within the grant scope will be open-source. We don't rely on any closed-source libraries, all of them use either MIT or Apache 2.0 license.
- We've updated the proposal with additional explanation about the ETL processes needed to built a Dune-like tool with similar UX experience ("User data ETL"). Regarding "RAW data ETL" - we actually hope that we will be able to use other projects as a source of relay & parachain data as we're focused on working with end-user features so this would actually off-load a lot of work that doesn't fully align with our strategy.
- Affirmative! This grant only covers the cost of building frontend elements (not mockups but a standalone frontend) and creating a proper infrastructure behind it. CI/CD is not included here and hosting fees are going to be discussed with Parity Data Team and potentially put into a Maintenance Grant if decided together with W3F that it's the right solution to make it free for everyone. 
- As mentioned above, we treat this grant as a PoC that will allow us to actually calculate the maintenance cost of the final solution. Proper infrastructure design is extremely important in such solution as it defines the final UX for the user. 

We've updated the proposal with the above-mentioned changes.

2023-09-26 16:38 UTC, keeganquigley commented
Thanks for the changes @caaaml much appreciated. It sounds like you have a solid vision and I really like what has been built so far, but like my colleague, I still have reservations about how useful the code will be for others, and seeing that none of the code for the existing app is public, it's hard to judge your previous work. Therefore I will hold off on approving for now.

Also, I'm curious why there is no option to log in with a Polkadot wallet? Instead it's only the typical OAuth 2.0 email/password login.

2023-10-13 11:37 UTC, semuelle commented
pinging @caaaml

2023-10-13 12:15 UTC, caaaml commented
Hi @semuelle , thanks for heads up! :) We're currently reworking the grant and will be back with updates next week.

2023-11-13 17:09 UTC, keeganquigley approved these changes
Thanks @caaaml and thanks for reducing the scope. Looks good to me now, so mark as ready for review and ping the rest of the committee to take a look.

2023-11-21 16:46 UTC, semuelle approved these changes
Hey @caaaml, sorry for the long wait. On top of the many application, we also had the launch of the Decentralized Futures program, which brings about thoughts about the alignment of the grants program. As you know, we are keen on open source development, meaning that we have been happy to fund projects as long as they are open source. However, many of these projects have stalled or failed due to a lack of community, interest and/or long term vision. I'm worried that what you are building is too tightly coupled with your platform architecture to be useful by itself. Also, it is my impression that it requires a business model to maintain a data project/platform of this complexity long term. That being said, I am going to give my approval, in the hopes that your project will serve the community, bring new people and that you continue contributing to the ecosystem.

2023-11-21 16:50 UTC, Noc2 requested changes
(requested changes in the group)

2023-11-22 14:13 UTC, Noc2 approved these changes

2023-11-22 14:14 UTC, merged

2024-03-14 18:30 UTC, keeganquigley commented
Hi @caaaml are you able to provide an update on milestone 1?

2024-03-21 16:35 UTC, caaaml commented
Hey @keeganquigley, sorry for the delay - we wanted to make sure everything works well and you can access a live demo of the delivery to check it out. Tomorrow we will deliver both milestones with an additional demo instance.

2024-03-25 09:25 UTC, caaaml commented
Hey @keeganquigley,

We've delivered both milestones with an additional basic metric creation and metric catalogue features. You can access it here:
- Delivery: https://github.com/w3f/Grant-Milestone-Delivery/pull/1160
- Delivery instance on demo data:  https://demo-dc-app.tokenguard.io/

Let us know if you have any questions or comments!

Best,
Kamil