Create Plutonication.md
w3f/Grants-Program pull request #1947
Opened 2023-09-02 21:51 UTC by RostislavLitovkin

#### Project Abstract

- Communications protocol that enables seamless interactions between dApps and wallets across all platforms.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@rostislavlitovkin:matrix.org` (change the homeserver if you use a different one)

2023-09-02 22:02 UTC, RostislavLitovkin commented
I have read and hereby sign the Contributor License Agreement.

2023-09-04 07:32 UTC, Noc2 requested changes
Thanks a lot for the application. I have a couple of initial questions/comments:
- We usually don't pay for hosting costs. Could you remove this? 
- What do you mean by Mockups? 
- Are you aware of [SubConnect](https://github.com/Koniverse/SubConnect), [Tesseract](https://github.com/tesseract-one/Tesseract.rs) or [@talismn/connect](https://github.com/TalismanSociety/talisman-connect)?

2023-09-04 10:59 UTC, semuelle requested changes

2023-09-04 10:59 UTC, semuelle commented on applications/Plutonication.md
> +- **Registered Legal Entity:** None
Please provide at least an address. If you prefer not to do so publicly, feel free to [email us](mailto:grants@web3.foundation).

2023-09-18 20:15 UTC, semuelle requested changes
Please see my questions in the chat.

2023-09-26 09:06 UTC, RostislavLitovkin reviewed
Added all missing info

2023-10-05 20:06 UTC, keeganquigley commented on applications/Plutonication.md
> +> This document will be part of the terms and conditions of your agreement and therefore needs to contain all the required information about the project. Don't remove any of the mandatory parts prese
As the text states, this part can be removed. Feel free to take it out.

2023-10-05 20:06 UTC, keeganquigley commented on applications/Plutonication.md
> +Please describe the team's relevant experience. If your project involves development work, we would appreciate it if you singled out a few interesting projects or contributions made by team members i
Could you remove this template text as well?

2023-10-05 20:19 UTC, keeganquigley commented
Thanks for the application @RostislavLitovkin in addition to my above comments:

- Wallet Connect does have both a [Dapp integration guide](https://docs.walletconnect.com/advanced/multichain/polkadot/dapp-integration-guide) and a [wallet integration guide](https://docs.walletconnect.com/advanced/multichain/polkadot/wallet-integration-guide) for Polkadot. Can you compare to this and what is missing that your solution would provide?
- You point out that the only way to connect a mobile wallet to a Dapp is through Substrate Connect or Vault, but afaik mobile wallets such as Talisman and Fearless will also let you connect.
- How do you plan to get developers to use your solution?

2023-10-09 19:18 UTC, semuelle approved these changes

2023-10-09 21:40 UTC, keeganquigley approved these changes
Left comment in private channel.

2023-10-13 14:38 UTC, semuelle approved these changes

2023-10-24 15:28 UTC, nikw3f approved these changes
Happy to support

2023-10-24 15:49 UTC, merged