Add StorageHub Proposal
w3f/Grants-Program pull request #1970
Opened 2023-09-13 16:48 UTC by Cwilli30

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-09-13 18:41 UTC, Noc2 submitted a review, later dismissed
Thanks for the application. Based on my previous discussions with you and your team, I will approve the application, mark it as ready for review, and share it with the rest of the team. That said, both milestones currently contain very few concrete details, and the rest of the committee might complain about it. Potentially, for example, it might make sense to initially only apply for the initial research and follow up later with a more concrete PoC proposal. But let's see what the rest of the team thinks.

2023-09-14 04:58 UTC, nikw3f commented
I agree with @Noc2. Please add more concrete details in the milestones specifically the deliverables.

2023-09-14 16:19 UTC, keeganquigley requested changes
Thanks for the application @Cwilli30 I have a couple comments as well:

- For the "Research and Design" milestone 1, you can probably go ahead and remove the "infrastructure" deliverable since there isn't anything to evaluate there.
- M1 seems rather expensive to me for a single article. Could you perhaps integrate more technical details about what problems/issues you are looking to solve, the methodologies used, any analysis procedures used in producing the material, and how the knowledge will be useful for others?
- Regarding M2 "Testing & Guide", I understand that it's just a prototype and not production-ready, but would there still be some basic unit tests to evaluate?
- I agree that M2 could be expanded as well; for example what kind of limited features do you plan to implement?

2023-09-19 00:17 UTC, Cwilli30 commented
I have read and hereby sign the Contributor License Agreement.

2023-09-19 00:19 UTC, Cwilli30 commented
Grant team - The Moonsong Labs team spent the last week or so revising our Milestone deliverables for our grant application. Please review at your convenience. 

Thank you.

2023-09-19 09:50 UTC, Noc2 approved these changes
Thanks for the update. I'm still happy to go ahead with it and share it again with the rest of the team.

2023-09-19 10:19 UTC, semuelle requested changes
Hi @Cwilli30 and team,
I am happy to see a proposal being made on this topic. And I am happy with a prototype being included in this proposal already. Given that this is largely a research grant, I'm fine with the lack of technical specifications. Instead, I would like to see all the key questions and challenges you laid out to be directly addressed in your reports. Currently, it sounds like you are just focusing on delivering a solution ("The research & design document will include the gathered requirements and the list of researched solutions & features"), but the documentation of _how_ you came up with the requirements (calculations, interviews, comparisons) I think would be equally interesting and potentially useful down the road. If you could make this a bit more explicit in your deliverable specs, I would be happy to approve. 

One last thing: I don't understand the spec for deliverable `2.0g`. Are you saying you are going to write about the deliverables? Can you clarify what the difference between `2.0b` and `2.0g` is? I'm guessing one is the spec document and one is the project documentation, but it's not clear from the specification.

2023-09-19 11:17 UTC, Cwilli30 commented
Hi Semuelle - Thank you for the feedback. I added content in Milestone #1 (0b.) that reads, "The research & design document will include the gathered requirements and the list of researched solutions & features that could meet those requirements, as well as all supporting evidence and documentation that led to those proposed requirements and features. The document will also expand its research on the “Key Questions and Anticipated Challenges” section". Does that provide some additional clarity on what you were asking to see? 

With regards to your other comment "I don't understand the spec for deliverable 2.0g & Can you clarify what the difference between 2.0b and 2.0g". Deliverable (g) is simply calling out specifically what the deliverable is for Milestone #2. Milestone #2 is focused on providing follow on research applied to the v0.5 doc to get it to a v1.0 state, build some prototype code to begin to support the v1.0 doc, and provide a code tutorial so the code can be easily used by a user.

2023-09-19 16:45 UTC, notlesh commented
I have read and hereby sign the Contributor License Agreement.

2023-09-19 20:43 UTC, semuelle commented
> Does that provide some additional clarity on what you were asking to see?

Yep, that'd be great, thanks.

2023-09-20 02:23 UTC, Cwilli30 commented
@semuelle - Thank you for the feedback! I made the adjustment and submitted a PR. 

@keeganquigley & @nikw3f - I welcome your feedback or approval on the adjustments made from the last 2 PRs. 

Thank you in advance for your support we look forward to working on this project!

2023-09-20 06:54 UTC, Noc2 approved these changes

2023-09-20 11:02 UTC, semuelle approved these changes
Thank you for the update, @Cwilli30. Happy to approve.

2023-09-20 12:14 UTC, nikw3f approved these changes
Thanks. Good from my side.

2023-09-20 13:06 UTC, keeganquigley approved these changes
Thanks for the changes @Cwilli30 LGTM.

2023-09-20 13:12 UTC, Cwilli30 commented
Thank you all for the approvals. The Moonsong Labs team is super excited about this project. We are currently hiring to build the team to work on this. We have some high quality engineering candidates in the works. We look forward to rocking and rolling once they are in place!

2023-09-20 13:22 UTC, merged

2023-10-02 17:05 UTC, Cwilli30 commented
Hi W3F Team - Just wanted to provide an update. We just finalized the hiring process for the Principal Blockchain Engineer for this StorageHub project. We are really excited to have this individual (Facundo Farall) join our team. The candidate is extremely strong and was top of his class from Polkadot blockchain academy, with a perfect score! Facundo starts Monday, we plan to pair Facundo with one of our strong team members. Looking forward to really kicking this off!