Squashed all changes, ready for PR.
w3f/Grants-Program pull request #1986
Opened 2023-09-20 20:30 UTC by MatteoPerona

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@matteo-p:matrix.org` (change the homeserver if you use a different one)

2023-09-20 21:14 UTC, MatteoPerona commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md) before we can accept your contribution. Please submit the following text as a separate comment:
> 
> I have read and hereby sign the Contributor License Agreement.
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read and hereby sign the Contributor License Agreement.

2023-09-20 22:39 UTC, MatteoPerona commented
recheck

2023-09-21 20:19 UTC, MatteoPerona commented
I have read and hereby sign the Contributor License Agreement.

2023-09-21 20:19 UTC, MatteoPerona commented
Recheck

2023-09-21 20:20 UTC, MatteoPerona commented
recheck

2023-09-24 17:58 UTC, Noc2 requested changes
(changes requested in the private room)

2023-09-27 15:36 UTC, semuelle requested changes
Thanks for the application, @MatteoPerona. There are some things missing and not fitting, so I left a couple of comments below. Generally, I'd be curious to know if you are planning to deploy on Astar then, or possibly Watr?

2023-09-27 15:36 UTC, semuelle commented on applications/ssal-commods-dex.md
> +We built the original version of this project, Riso, on Substrate, but realized that architecting a fully fledged parachain goes out of scope for the purposes of our application. Our team is looking
The grants program doesn't fund traveling. Please see our [FAQ](https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund) and [application guidelines](https://grants.web3.foundation/docs/Introduction/intro) for details on what we fund.

2023-09-27 15:36 UTC, semuelle commented on applications/ssal-commods-dex.md
> +| 1. | Smart Contracts | We will write the requisite ink! smart contracts to create, buy, and sell commodities contracts, testing them on Shibuya testnet. |
Could you add more details about the design of the contracts? What data is required on-chain, which functions they will expose, how they interact, etc.

2023-10-01 20:25 UTC, MatteoPerona commented on applications/ssal-commods-dex.md
> +The lockup model adds a layer of security for buyers. It freezes the buyer's funds until a contract’s finality date, at which point, the buyer will either verify that the physical product exists, is
No, I will revise the wording in the document. We plan to implement a governance system to resolve disputes, but only after we have finished developing and proving the core technology.

2023-10-10 21:48 UTC, keeganquigley requested changes
Requested changes in private chat room.

2023-10-13 15:32 UTC, semuelle requested changes
I left a comment in the chat.

2023-11-01 14:40 UTC, keeganquigley commented
Thanks for the adjustments @MatteoPerona I will mark as ready for review and ping the rest of the committee.

2023-11-09 19:41 UTC, semuelle approved these changes

2023-11-09 20:17 UTC, keeganquigley submitted a review, later dismissed
Thanks for the changes @MatteoPerona LGTM.

2023-11-09 22:13 UTC, keeganquigley approved these changes

2023-11-15 13:58 UTC, semuelle approved these changes

2023-11-15 13:58 UTC, merged