Application for Dexel.md
w3f/Grants-Program pull request #2002
Opened 2023-09-25 18:24 UTC by itssravi

#### Project Abstract

Dexel is a a reimagined decentralised read-it-later reading experience built on the Polkadot network.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-09-25 19:34 UTC, Noc2 requested changes
Thanks for your interest in our grants program. Could you reuse the [table of the template for the milestone deliveries](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality) and also add the default deliverables?

2023-09-25 21:03 UTC, itssravi commented
Hey @Noc2 Thanks for pointing that out. I've updated our Development Roadmap to match the table format and included all the default deliverables. Let me know if it looks good now or if there's anything else I missed.

2023-10-04 17:50 UTC, itssravi commented
I have read and hereby signed the Contributor License Agreement.

2023-10-06 16:52 UTC, keeganquigley requested changes
Thanks for the application @itssravi I think this is a unique and novel idea.

- Can you integrate more technical details into the deliverables themselves? What main functions will each of the contracts have?
- Will there be unit tests for both the contracts and the UI? Can you list any test suites you will be using? As well as any additional tests (e2e, integration, etc.)

2023-10-11 22:34 UTC, keeganquigley commented
Thanks for the changes @itssravi I will mark your application as ready for review and ping the rest of the committee. In the meantime, in my opinion it seems a bit expensive for one dev. Would you be willing to lower your rate at all?

2023-10-12 21:18 UTC, SimonKraus commented
Hey guys and sorry for just chiming in @ w3f crew. 

I wanted to bring to your attention that the DotSama community was more then unsatisfied with previous deliveries like the Describedot project (dot content in hindi). 
Not only is most of it complete redos of years old w3f edu videos with just different language, also they just started it after my public allegations in the polkassembly comments https://kusama.polkassembly.io/referenda/27 
Keep in mind that this was awarded with about 60k $! 
Before that he got rewarded through the WAGmedia bounty...

Ravi also has a good track record of creating stuff nobody asked for and would ever use:
https://www.qnadot.com/
https://www.dotfordummies.com/
https://www.awesome-dot.com/
http://newtodot.xyz/

I don't see "Dexel" going any other route here. 

There was also another treasury proposal called "Dotrewards" (https://polkadot.polkassembly.io/post/1705) which was rejected by the community. 

Before rewarding this grant please carefully consider if the ecosystem NEEDS this project, if there are USERS, if it will gain TRACTION and if Ravi is the right person to execute on it given the already questioned high pricetag.

2023-10-13 15:26 UTC, semuelle requested changes
Thank you for the application, @itssravi. I'm afraid I have to disagree with your statement that "Dexel fills a niche yet essential gap in the Polkadot dApp landscape". Could you provide some insight into how you got to this conclusion? Are there similar, successful applications in other ecosystems? Are users of centralised "read it later" applications expressing desire for a decentralised version? The effort to put my bookmarks on-chain seems silly in comparison to what I gain.

2023-10-15 12:44 UTC, itssravi commented
> Thank you for the application, @itssravi. I'm afraid I have to disagree with your statement that "Dexel fills a niche yet essential gap in the Polkadot dApp landscape". Could you provide some insight into how you got to this conclusion? Are there similar, successful applications in other ecosystems? Are users of centralised "read it later" applications expressing desire for a decentralised version? The effort to put my bookmarks on-chain seems silly in comparison to what I gain.

Hi @semuelle ,

Thank you for your feedback. Here are some points addressing your concerns:

1. **Essential Gap in Polkadot dApp Landscape**: Beyond just bookmarking, Dexel emphasizes preserving the actual content. Centralized "read it later" services, while user-friendly, depend on the original data source. If that source vanishes, so does the saved content. With Dexel, the content remains accessible offline and searchable.

2. **Web3 Tools & Privacy Concerns**: 
Existing web2 tools, such as Pocket and Evernote Web Clipper, have questionable privacy policies and require unnecessary permissions. Demonstrating the advantages of a decentralized approach for everyday needs can significantly drive the adoption of Polkadot and the broader blockchain ecosystem.
   - [Pocket's](https://tosdr.org/en/service/384) questionable privacy policy and [list of trackers](https://reports.exodus-privacy.eu.org/en/reports/com.ideashower.readitlater.pro/latest/).
   - [Evernote's](https://tosdr.org/en/service/207) problematic policy and its [list of trackers](https://reports.exodus-privacy.eu.org/en/reports/com.evernote/latest/).

3. **Success in Other Ecosystems**: Tools like [Shiori](https://github.com/go-shiori/shiori), an offline version of Pocket with 8k stars, hint at existing demand. The [Awesome Privacy repo](https://github.com/pluja/awesome-privacy#bookmarking) also underscores the interest in privacy-centric bookmarking solutions.

4. **Need for Decentralized Storage and Identity**: Present solutions miss out on decentralized storage and identity, complicating cross-device setup and synchronization. Using cloud services like GDrive, Dropbox reverts to centralized dependency. Dexel combines decentralized storage and identity, offering private, secure, and smooth synchronization.

Building dApps that manifest the benefits of decentralization for common user needs can be pivotal for Polkadot's adoption. Our goal with Dexel isn't decentralization for its own sake, but to grant users genuine ownership, privacy, and redundancy.

I trust this sheds more light on Dexel's purpose and potential.

Warm regards,
Ravi

2023-10-15 12:51 UTC, itssravi commented
> Thanks for the changes @itssravi I will mark your application as ready for review and ping the rest of the committee. In the meantime, in my opinion it seems a bit expensive for one dev. Would you be willing to lower your rate at all?

Thank you @keeganquigley for reviewing the application and providing feedback. I understand your concerns regarding the costs. Given the scope of Dexel and the goal to build a good quality application, I  factored in potential expenses for additional developers/designers and other unforeseen costs.

However, acknowledging your feedback and our shared objective of making the Polkadot ecosystem better, I've adjusted the total cost and updated the numbers in the PR. I believe this revised amount will still allow us to maintain the quality and timely delivery of the project.

2023-10-18 21:56 UTC, keeganquigley commented
Thanks @itssravi for the updates and sorry for the delay.

- Thanks for comparing to the existing solutions. I do see value in having a privacy-focused bookmark app, especially with a smaller amount of permissions and the ability to login with a wallet in lieu of email/password. Though I do agree that it is questionable how much is gained by moving certain items on-chain, or whether it is truly needed.
- Are you planning to fork [Pocket](https://getpocket.com/en/) as well?
- For a small widget app I would personally be willing to support a level 1 PoC, but probably no more without first seeing it in action.
- A lot of your previously built websites are down and don't seem to work. How can we guarantee that this app would be maintained?

2023-10-18 23:45 UTC, itssravi commented
Hi @keeganquigley,

Thank you for recognizing the potential in Dexel.I know this looks like uncharted territory, but I belive pushing boundaries of what decentralized technologies can achieve beyond just financial applications can significantly help in mainstream adoption. Dexel represents an effort to showcase these benefits in everyday use cases.

- Regarding forking [Pocket](https://getpocket.com/), it's not feasible as it's closed source. If you meant [Shiori](https://github.com/go-shiori/shiori), I did consider forking it, but integrating all the blockchain features and decentralised identity stuff requires a ground-up approach.  We're still leveraging open-source libraries, like [Readability](https://github.com/mozilla/readability) for structured text extraction to ensure efficient development.

- I understand the budget concerns, but making sure we have reliable smart contracts would require us to hire Rust/Ink devs who charge hourly. Then there are some design flows not yet fully scoped that necessitate certain costs too. I'm okay with reducing it to a Level 1.5 (20K) but any lower and we'd have to compromise on the scope and quality of the project.

As for my previous projects, they are definitely operational. I bear the hosting, domain, and server costs out-of-pocket but occasionally, due to lack of funding, there might be short downtimes. I make sure address them promptly whenever that happens. With grant funding, I assure you of consistent uptime. To ensure this, we can integrate monitoring tools like Uptime Robot or Pingdom that'll alert and enable quick resolutions to any potential issues.

I'm committed to Dexel's success and ensuring its sustained operation and maintenance post-launch. Your support would significantly help in bringing it to life.

2023-10-25 17:18 UTC, nikw3f commented
Hey @itssravi can you discuss the measures taken to ensure the security and efficiency of the smart contracts that Dexel will utilize? Are there any particular design patterns or testing protocols employed to mitigate common risks or vulnerabilities?

2023-10-25 19:12 UTC, itssravi commented
Hey @nikw3f, thank you for the question. Security and efficiency are central to Dexel, and we're harnessing Polkadot's ecosystem to enhance these aspects:

1. **Comprehensive Testing:** We'll be adding extensive unit and integration tests, taking advantage of Polkadot's robust pre-deployment testing environment.
2. **Data Integrity:** We have strict data validations in place to make sure we provide role based access control to users.
3. **Efficient Design:** Our contracts would optimized for minimal computational overhead, utilizing Polkadot's high-throughput, low-fee infrastructure.
4. **Smart Resource Use:** We're optimizing on-chain storage, aligned with Polkadot's framework to ensure network efficiency.

By working with Polkadot, Dexel aims to achieve a balance of security and performance, critical for maintaining users' trust and seamless application functionality.

2023-10-25 23:10 UTC, keeganquigley reviewed
Thanks for your answers @itssravi would you be willing to reduce the scope to just milestone 1? Or do you prefer to keep M2 intact? I personally would be more apt to approve a PoC of the contracts and front-end.

2023-10-26 00:46 UTC, itssravi commented
Hey @keeganquigley Thank you for your thoughts and suggestions. I understand the importance of demonstrating a tangible proof of concept. We're open to focusing on Milestone 1 as it lays the foundational work and includes the initial setup, smart contract development, and basic frontend interface. This approach would provide a functional prototype and give us a solid ground to showcase the essential features of Dexel. We appreciate your willingness to consider this adjustment and are more than happy to proceed with Milestone 1. 

Could you guide me through the next steps in this process though? Should I modify the application to reflect these changes, or will it be handled internally during your review process?

2023-10-26 15:44 UTC, keeganquigley commented
Sure thing @itssravi thanks for being willing to reduce the scope. Yes you can go ahead and modify the current application and feel free to ping me when I should take another look. You can always apply for the second milestone in a follow-up grant after this one is evaluated. Thanks!

2023-10-27 22:21 UTC, itssravi commented
Hey @keeganquigley I've modified the milestones and subsequently updated the application to Level 1 based on the costs of the milestone. I've kept the second milestone in place just to make sure we have something to look at and move forward with after the evaluation. Let me know if there are any other changes.

Looking forward to the next steps where I can actually build this out.

2023-10-31 19:48 UTC, keeganquigley requested changes
Hi @itssravi thanks for the modifications, however the **Overall Costs** still say $25,000. Could you adjust this and move milestone 2 to the future plans section? And erase the cost for M2, this will make it clear that it is not part of the current grant. Thanks!

2023-10-31 23:15 UTC, itssravi commented
Hey @keeganquigley thank you for the clarification. I've updated the overall costs and also moved the milestones. Let me know if we need any other changes. Looking forward to the next steps.

2023-11-06 15:35 UTC, Noc2 requested changes
Thanks a lot for the application and all the effort you put into this. The grants committee decided today not to support your project. Partly because we don't see a lot of value in this project. Independent of it, we wish you all the best. Let us know if you have any questions.

2023-11-06 15:36 UTC, closed without merging