Polkadart amend
w3f/Grants-Program pull request #2004
Opened 2023-09-26 00:18 UTC by leonardocustodio

Lohann has done some amazing work into this lib but unfortunately he has not been able to dedicate the necessary time to continue with the works. 

As discussed in the Grant PR proposal https://github.com/w3f/Grants-Program/pull/1053#issuecomment-1720243331 to continue the development and finish this grant we opted to change the project owner as well as the milestone values and objectives.

We acknowledge we underestimated the effort required to finish the last two milestone. There were 5 engineers working on this but at this stage things got too complex and we remained with only 2 engineers with enough knowledge to finish the work.

Polkadart has been an amazing project and we have already have people using it in production environment. As Flutter together with React Native is one of the most popular mobile frameworks we are very sure that this project is a great contribution to our ecosystem allowing people to develop apps that support substrate based chains in any language they want.

2023-09-26 00:30 UTC, leonardocustodio commented
I have read and hereby sign the Contributor License Agreement.

2023-09-26 07:15 UTC, Noc2 requested changes
Thanks for the PR. Could you also update the total costs?

2023-09-27 08:58 UTC, semuelle commented
For reference, Lohann has given his approval [here](https://github.com/w3f/Grants-Program/pull/1053#issuecomment-1732368046).

2023-09-27 09:06 UTC, semuelle requested changes
Thanks for the amendment, @leonardocustodio. I'm generally happy to approve it. Could you clarify the timeline, though? You are, if I'm reading this right, planning to submit M3 in six months and requesting 40k for 2 full-time developers for the next ten months?

2023-09-27 09:06 UTC, semuelle commented on applications/Polkadart.md
> +| 3g.  | Statemint Signed Extensions | Support statemint's signed extensions |
```suggestion
| 3g.  | AssetHub Signed Extensions | Support AssetHub's signed extensions |
```

2023-09-27 11:44 UTC, leonardocustodio commented
Hello @semuelle,

Sure, milestone 3 is already halfway through I've increased it to 6 months to consider the time that was already spent and to have the project proposal updated with the whole time spent and the whole investment made. The delivery of milestone 3 should happen in 2 to 3 months. So I would say we "only" have about 6 months ahead to finish the whole project.

2023-09-27 15:38 UTC, semuelle approved these changes
Thanks. I think the added scope seems quite useful, so happy to approve.

2023-09-27 15:40 UTC, keeganquigley approved these changes
Thanks @leonardocustodio we appreciate it, LGTM.

2023-09-27 16:57 UTC, Noc2 approved these changes

2023-09-27 18:24 UTC, takahser approved these changes

2023-09-27 20:01 UTC, dsm-w3f approved these changes

2023-09-27 22:37 UTC, merged