Application for Sub-Consensus Mechanism
w3f/Grants-Program pull request #2007
Opened 2023-09-26 13:03 UTC by lawmeskiviahs

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-09-27 18:40 UTC, dsm-w3f requested changes
@lawmeskiviahs thank you for the grant application. There are some initial comments on it:

- The link for the RFP mentioned is broken, please use [this one](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/sub-consensus.md).
- Project details are missing. You say in the application that the proposed solution is " introducing a mechanism that allows parachain collators to achieve consensus among themselves on the "best" block faster than the existing process.". Could you explain how do you plan to develop this? 
- The overview doesn’t tell why your team is interested in creating this project.
- What are your future plans for this project?
- Milestones 1 and 2 need the Table with the Deliverables.
- It look like this is more a research grant proposal than a development one. If you don't know how to develop Milestone 2, I suggest you to remove it from the proposal. You can also try to use our [research template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template-research.md) if the grant is more for research than development.
- Your team has already developed some grants. You can put this and other information in Additional Information.

2023-10-02 11:55 UTC, Noc2 requested changes
@lawmeskiviahs, thanks a lot for the application. I agree with @ dsm-w3f that the application needs to have more details, but we are quite interested in someone looking into this. I will try to update the RFP in the coming days: https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/sub-consensus.md An (optimistic) finality method together with slashable collators and 1 second to under 200ms finality would be useful for a lot of applications or simple micro transactions. So let me know if you have any questions.

2023-10-03 12:18 UTC, lawmeskiviahs commented
Hi @dsm-w3f @Noc2 Sorry for the delay. I have updated the application with what we're exploring as solutions. More on the scope of work will be clear after researching more on this.

2023-10-03 15:06 UTC, dsm-w3f requested changes
@lawmeskiviahs thank you for the improvements in the application. As I understood from your deliverables, this grant proposal is more for initial research about the theme and to outline a solution. In this way, I think it is more appropriate to apply using our [research grant template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template-research.md). Furthermore, could you please outline the experience of the team in designing and developing consensus algorithms or core parts of decentralized systems?

2023-10-09 06:57 UTC, lawmeskiviahs commented
Hi @dsm-w3f sorry for the late reply. I was not well last week so wasn't active. I have updated the application. About the Proof-of_Concept, that will be a follow up grant to this. I had made the POC milestone 2 in this grant earlier but now I think it will be better to do this in two phases. Our experience is already mentioned in the application. Kindly let me know if there is anything else.

2023-10-11 17:32 UTC, dsm-w3f requested changes
@lawmeskiviahs thank you for the improvements. I think we have more details now and it is almost ready for the review from the committee. I would like to ask one more thing. Please notice in our research template that the results of the steps needed to perform the research are listed as deliverables. In this way, we can check and verify if each step of the methodology was followed and if the results are good. Please add the results of each step of the methodology proposed as deliverables in the milestone table. Feel free to split them into more than one milestone if you want. After that, let me know to check it again and make this application ready for review.

2023-10-13 13:50 UTC, lawmeskiviahs commented
Thankyou @dsm-w3f for your comment. I have added deliverables and I think I have better clarity on how to proceed with the deliverables. I feel that the deliverables will be more clear once we get deeper into the research, I have a basic idea of what we might do but I refrain from writing anything uncertain into the application.

2023-10-16 21:52 UTC, dsm-w3f requested changes
@lawmeskiviahs thank you for the improvements. I think the deliverables in the milestone table are still unclear. I noticed that you just copied the default description from our template, we expect a more clear description of each result to be able to check it as deliverable. We need this specification in the deliverables table. I'll make the application ready to review, but I personally won't approve it since it is not possible to check the deliverables in the way it is described.

2023-10-25 07:30 UTC, arunjot12 commented
.

2023-10-25 13:53 UTC, Noc2 requested changes
Thanks a lot for the application and all the effort you put into this. However, the grants committee decided against supporting your project. Part of the reason is, for example, that there are currently no "academic papers regarding finality in parachain ecosystem." There is only one paper on GRANDPA. Independent of it, we wish you all the best for your project, and let us know if you have any questions.

2023-10-25 13:53 UTC, closed without merging