Treasury Tracker - Level 2 Request
w3f/Grants-Program pull request #2063
Opened 2023-10-20 22:05 UTC by senseless

#### Project Abstract

Stake Plus Inc is developing TreasuryTracker, a platform aimed at enhancing transparency and engagement in the Polkadot and Kusama ecosystems by offering in-depth analytics on treasury funding and governance. Built on NodeJS, CakePHP, and MySQL/MariaDB, the project focuses on data visualization, comprehensive analytics, and real-time chain statuses. The team seeks a Level 2 Web3 Foundation grant to transition from a proof of concept to a fully-realized, market-ready product.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@stakeplus:matrix.org` (change the homeserver if you use a different one)

2023-10-20 22:08 UTC, senseless commented
I have read and hereby sign the Contributor License Agreement.

2023-10-24 22:52 UTC, keeganquigley requested changes
Thanks for the application @senseless have you looked into going for treasury funding for this? In my opinion the treasury should be funding its budgeting tools. I wouldn't be opposed to funding milestone 1 to help bootstrap the project, but milestone 2 seems like mostly maintenance work that could be funded by the community/users. Would you consider reducing the scope?

2023-10-25 12:59 UTC, senseless commented
> Thanks for the application @senseless have you looked into going for treasury funding for this? In my opinion the treasury should be funding its budgeting tools. But based on your previous work I wouldn't be opposed to funding milestone 1 to help bootstrap the project, but milestone 2 seems like mostly maintenance work that could be funded by the community/users. Would you consider reducing the scope?

I would be ok with that. The governance 1 part and importing the historical data (as well as supporting all paras still operating gov1) is a big thing that I'd like to have done prior to going to treasury. I'm a bit concerned by Ivy due to comments left on the recent OpenSquare proposal. Ivy seems to be picking winners. But if we put in some effort on revamping design prior and putting in a lower ask, we may be able to find support in treasury.

2023-10-25 13:48 UTC, keeganquigley commented
Thanks @senseless for your response, and yes I know there are currently some issues with trying to get funds from the treasury so that's also why I'm willing to support a reduced scope. Sounds good, feel free to ping me once changes are made and I will have another look.

2023-10-25 15:56 UTC, senseless commented
> Thanks @senseless for your response, and yes I know there are currently some issues with trying to get funds from the treasury so that's also why I'm willing to support a reduced scope. Sounds good, feel free to ping me once changes are made and I will have another look.

I have removed the second milestone and left the first milestone in-tact.

2023-10-25 16:03 UTC, keeganquigley requested changes
Thanks @senseless looks good except for it looks like the Overview section is missing above the milestone. Could you add it in per [this example](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1)? Thanks!

2023-10-25 16:14 UTC, senseless commented
> Thanks @senseless looks good except for it looks like the Overview section is missing above the milestone. Could you add it in per [this example](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1)? Thanks!

I have added an Overview section under the Milestones section

2023-10-25 16:40 UTC, keeganquigley approved these changes
Thanks for the changes @senseless you can always apply for a follow-up grant for M2 in the future if treasury funding doesn't work out. Happy to go forward with it, and I will mark it as ready for review so the rest of the committee can take a look.

2023-10-25 18:21 UTC, senseless commented
> Thanks for the changes @senseless you can always apply for a follow-up grant for M2 in the future if treasury funding doesn't work out. Happy to go forward with it, and I will mark it as ready for review so the rest of the committee can take a look.

It appears as if this application is marked for 5 approvals instead of the normal 3 for level 2. Is that intended? Thanks

2023-10-25 19:09 UTC, keeganquigley commented
Thanks @senseless yes that's normal, it will be manually merged after 3 approvals.

2023-10-26 07:16 UTC, Noc2 requested changes
I added a comment in the private channel.

2023-10-26 13:35 UTC, senseless commented
Closing this PR for now. We will proceed to a Treasury request and see how things go. 

Thanks!

2023-10-26 13:35 UTC, closed without merging