Nighthawk Grant application
w3f/Grants-Program pull request #2106
Opened 2023-11-13 12:36 UTC by vav12

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2023-11-13 13:00 UTC, vav12 commented
I have read and hereby sign the Contributor License Agreement.

2023-11-22 15:43 UTC, takahser requested changes
@vav12 thanks, I've taken a look and believe that it's not a good match for our program. The main reasons are:

- most deliverables are non-technical (e.g. Talent acquisition, data collection, etc.), while we focus on technical projects
- the deliverables are also mostly vague and not very specific (e.g. 
_2. | Research | Conduct a final research on set of rules to start off with_)
- your plans for auto-classification using LLMs lack detail
- I feel like the added benefit for the community around Substrate and the Polkadot network is very limited

Hence, I've come to the decision not to approve this proposal. Nevertheless, I wish you good luck for the future of your project and wish you're going to be successful.

2023-11-22 16:49 UTC, keeganquigley commented
Thanks for the application @vav12 While I appreciate all the work that PhishFort does for our ecosystem, I agree with the others that this project isn't really the best fit for the grants program, because most of the deliverables can't be re-used by others, and they aren't really specific to substrate or Polkadot tech. Also, I see that the Nighthawk [public beta](https://chrome.google.com/webstore/detail/nighthawk-by-phishfort/bdiohckpogchppdldbckcdjlklanhkfc) has already been released, so it seems that the initial PoC has already been built.

I know you guys are in touch with the W3F anti-scam team so I would recommend discussing with them about what the community wants out of this project, perhaps opening a discussion on the Polkadot forum, and then possibly going for treasury funding since the Discord community is already familiar with the tool.

2023-11-22 16:49 UTC, closed without merging

2023-11-27 09:22 UTC, vav12 commented
Thanks for the review and your suggestions.