Change the Payment address
w3f/Grants-Program pull request #2126
Opened 2023-11-28 09:15 UTC by hgergov

The initial application contains an incorrect payment address. Please use the following accurate payment address: 0x050801be60d8535f433d5c15db3129276cc1cc6a (USDT on Ethereum Mainnet)

2023-11-28 09:56 UTC, Noc2 requested changes
Could you change this to a Polkadot address on [AssetHub](https://wiki.polkadot.network/docs/learn-assets) or fiat? see https://github.com/w3f/Grants-Program#pencil-process

2023-11-29 07:24 UTC, hgergov commented
> Could you change this to a Polkadot address on [AssetHub](https://wiki.polkadot.network/docs/learn-assets) or fiat? see https://github.com/w3f/Grants-Program#pencil-process

Hey David and thanks for the feedback. We changed the payment address to an address on the asset hub. Apologies for the confusion.

2023-11-29 07:55 UTC, Noc2 approved these changes
Perfect. Thanks

2023-11-29 08:03 UTC, semuelle approved these changes

2023-11-29 08:22 UTC, laboon approved these changes

2023-11-29 08:44 UTC, SBalaguer approved these changes

2023-11-29 18:03 UTC, keeganquigley approved these changes

2023-11-29 19:29 UTC, merged