Logos Network PoC part-one web3-grant-application
w3f/Grants-Program pull request #2186
Opened 2024-01-21 18:56 UTC by h3rak1it

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [ ] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2024-01-21 18:58 UTC, h3rak1it commented
I have read and hereby sign the Contributor License Agreement.

2024-01-22 15:06 UTC, PieWol commented
hey @h3rak1it thanks for the application,

I wonder what you mean by "sub0layer". You mention that you will develop a parachain which means you are going to rely on a relay chain which you say suffers from false decentralization as most nodes are hosted on big cloud providers and thus are vulnerable to these players. 

Do you think a parachain would fix the problems you are trying to overcome? I'm struggling to understand how this proposal will be a solution while still having the very same problems in its underlying layers. I would appreciate you clarifying on this topic.

2024-01-22 20:33 UTC, h3rak1it commented
Hi @PieWol  , thanks for the quick feedback.

The sub0layer (computational layer) will be the outcome of the Logos network.
The Logos network basically consists of three components, including the Logos Chain (parachain).
The Logos chain will be used to create and secure the sub0layer utilizing Smart Contract Logic.
We could develop the Logos Chain as an independent chain which then has its own decentralization and security and is not dependent on the Relay Chain.
However, there are reasons why we have decided to use a parachain approach and are not developing a standalone chain.
Polkadot's ecosystem has many advantages (shared security, scalability, upgradeability, heterogeneity, community-driven governance, ecosystem diversity, ...) and the technology is already very well developed, so the approach is not to build everything from scratch.

We see Polkadot's method (relay or system chains and parachains) as the right technological approach for the future of Web3, so we want to support the Polkadot ecosystem by creating the possibility that the relay chain nodes and all parachains (blockchain nodes) can benefit from the Logos network or the sub0layer that is created by it.
With the Polkadot's new approach with system chains, our parachain could perhaps also be called a "system chain" in the future.

As you have indicated, it will only make sense if the relay chain is also executed on the sub0layer, which is our approach after the PoC is completed.
Since we want to develop in Polkadot ecosystem ourselves and we should act as parachain, the sub0layer should be made available for Polkadot first.
If we assume that the Polkadot infrastructure nodes will be executed on the sub0layer after the Logos network has been established, then we have no concerns about our parachain.
It is clear that the relay chain is secure and decentralized today, but we want to improve it with our approach and also reduce the computational cost of running blockchain nodes.

Visualization: (concept: Figure 1: Overview of a Web2 approach in comparison to Web3 and Web3 with a new security and compute layer and how the Logos network can enhance the Web3 infrastructure.)

![image](https://github.com/w3f/Grants-Program/assets/80841554/7fd9ff78-e885-4ce9-a37f-34bb72f76b2b)

So why Parachain, because of the Polkadot philosophy, technology and many other advantages, we want to develop in this ecosystem and let it benefit from the sub0layer.
With the sub0layer (computational layer) we want to make Polkadot and the rest of the Web3 more decentralized and let the community run the computation.

If more details are needed, please let me know

2024-01-23 11:04 UTC, PieWol requested changes
thanks for elaborating @h3rak1it ,

To make this application ready for review please complete the information about your legal structure. You need to provide a registered address and a registered legal entity.

2024-01-23 12:29 UTC, semuelle commented
> To make this application ready for review please complete the information about your legal structure. You need to provide a registered address and a registered legal entity.

If you prefer not to disclose the registered address, @h3rak1it, please send this information to us via [email](grants@web3.foundation).

2024-01-23 14:38 UTC, h3rak1it commented
Hello @PieWol  and @semuelle  thanks for the remarks.

A legal entity has not yet been registered.
If possible, we would like to register an entity after the PoC phase one and two are completed.
In the application template in the Legal Structure section, "if available" is specified, but if absolutely necessary, this can be accomplished in the coming weeks.

![image](https://github.com/w3f/Grants-Program/assets/80841554/7359f676-e565-4ead-ab4f-656346d5e6d8)

Please let me know if this is required or if you need further information.

2024-01-23 14:52 UTC, semuelle commented
> Please let me know if this is required or if you need further information.

Hey @h3rak1it. This information is required to make clear who the benefactors of the grant are. The foundation is required to KYC all benefactors of a grant, and this is _usually_ done through an entity. But it's perfectly acceptable to list individuals if you haven't established an entity yet.

2024-01-23 17:05 UTC, h3rak1it commented
Hi @semuelle  thanks for the clarification.

The data has been sent via email.

From: e.s@logoslabs.io
To: grants@web3.foundation
Subject: Legal structure data: Logos Network - PoC (part one)
Date: Tue, 23 Jan 2024 17:57:39 +0100 (CET)

2024-01-23 20:04 UTC, PieWol commented
Thanks for sending the information. We have received it. The application is now ready for review.

2024-01-24 14:09 UTC, Noc2 requested changes
Thanks a lot for the application and all the effort that you put into this. However, the grants committee decided not to go ahead with the project at this stage. Feel free to apply again if you have more technical details and a specification regarding the exact integration. Also, let us know if you have any questions.

2024-01-24 14:09 UTC, closed without merging