Submit DigiTrust proposal
w3f/Grants-Program pull request #2219
Opened 2024-02-15 02:19 UTC by phamdat721101

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [ ] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2024-02-15 02:30 UTC, phamdat721101 commented
I have read and hereby sign the Contributor License Agreement.

Phạm Quốc Đạt

Mobile phone: 0977705810



Vào Th 5, 15 thg 2, 2024 vào lúc 09:19 github-actions[bot] <
***@***.***> đã viết:

> *CLA Assistant Lite bot:* Thank you for your submission, we really
> appreciate it. Like many open source projects, we ask that you sign our Contributor
> License Agreement
> <https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md>
> before we can accept your contribution. Please submit the following text as
> a separate comment:
> ------------------------------
>
> I have read and hereby sign the Contributor License Agreement.
> ------------------------------
>
> *phamdat* seems not to be a GitHub user. You need a GitHub account to be
> able to sign the CLA. If you have already a GitHub account, please add
> the email address used for this commit to your account
> <https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user>
> .
> You can retrigger this bot by commenting *recheck* in this Pull Request
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Grants-Program/pull/2219#issuecomment-1945261253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH37MBJSDPDL5V7UMHEGJE3YTVWDJAVCNFSM6AAAAABDJOTRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBVGI3DCMRVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-16 17:32 UTC, keeganquigley requested changes
Hi @phamdat721101 thanks for the application. I have the following initial comments:

- Milestone 2 is missing delivery tables. Could you add these in?
- We typically only focus on the PoC and therefore aren't able to fund gathering feedback or beta testing. Could you remove deliverable 5?
- We don't support Solidity development, would you be willing to write them in ink! instead?

2024-02-16 17:33 UTC, keeganquigley commented on applications/DigiTrust.md
> +### Milestone 2 Example — Additional features
```suggestion
### Milestone 2 — Additional features
```

2024-02-17 01:48 UTC, phamdat721101 commented
Hi Keegan,
Thanks for your comments
I already updated my proposal, and opened a pull request. Please help me to
check it again
Thank you so much.

Phạm Quốc Đạt

Mobile phone: 0977705810



Vào Th 7, 17 thg 2, 2024 vào lúc 00:32 Keegan | W3F <
***@***.***> đã viết:

> ***@***.**** requested changes on this pull request.
>
> Hi @phamdat721101 <https://github.com/phamdat721101> thanks for the
> application. I have the following initial comments:
>
>    - Milestone 2 is missing delivery tables. Could you add these in?
>    - We typically only focus on the PoC and therefore aren't able to fund
>    gathering feedback or beta testing. Could you remove deliverable 5?
>    - We don't support Solidity development, would you be willing to write
>    them in ink! instead?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Grants-Program/pull/2219#pullrequestreview-1885660114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH37MBK5LPHWZ722EYABXXLYT6J4RAVCNFSM6AAAAABDJOTRZ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBVGY3DAMJRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-17 02:09 UTC, keeganquigley commented
Thanks @phamdat721101 we usually require mandatory deliverables for all milestones, could you also add those in for M2 as well?

2024-02-17 02:32 UTC, phamdat721101 commented
Sure I did it

Phạm Quốc Đạt

Mobile phone: 0977705810



Vào Th 7, 17 thg 2, 2024 vào lúc 09:09 Keegan | W3F <
***@***.***> đã viết:

> Thanks @phamdat721101 <https://github.com/phamdat721101> we usually
> require mandatory deliverables for all milestones, could you also add those
> in for M2 as well?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Grants-Program/pull/2219#issuecomment-1949602900>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH37MBIPQDV46T2H4AGWP73YUAGOVAVCNFSM6AAAAABDJOTRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBZGYYDEOJQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-19 16:37 UTC, keeganquigley requested changes
Thanks @phamdat721101 however I'm still not seeing deliverables 0a. - 0e. present in M2. 

1. Can you add these in? You can skip the Docker deliverable if it doesn't apply; also just one article for M2 is fine.

2. We usually ask for mockups to be provided upfront for UI focused milestones, even if they are rough.

3. For M2, its not clear to me how the notifications are being built.

4. Curious why you want to use traditional email/password login? Seems like a wallet login would be sufficient seeing as its dealing with assets.

2024-02-20 13:59 UTC, phamdat721101 commented
Hi @keeganquigley,
I already updated the proposal:
 1 - I updated the Docker deliverable in M1 and M2
 2 - I already attached link to our mockups website, and you can check our
figma design (wireframe link) in project details
 3 - I updated more detail about how to build automatic funding
allocation and notification in milestone 2
 4 - In the first-version, we target to convert web2 users to web3
industry, so we want to use traditional login firstly, then we will update
to zk-login after having good traffic.

Please help me to check it.
Thank you.

Phạm Quốc Đạt

Mobile phone: 0977705810



Vào Th 2, 19 thg 2, 2024 vào lúc 23:38 Keegan | W3F <
***@***.***> đã viết:

> ***@***.**** requested changes on this pull request.
>
> Thanks @phamdat721101 <https://github.com/phamdat721101> however I'm
> still not seeing deliverables 0a. - 0e. present in M2.
>
>    1.
>
>    Can you add these in? You can skip the Docker deliverable if it
>    doesn't apply; also just one article for M2 is fine.
>    2.
>
>    We usually ask for mockups to be provided upfront for UI focused
>    milestones, even if they are rough.
>    3.
>
>    For M2, its not clear to me how the notifications are being built.
>    4.
>
>    Curious why you want to use traditional email/password login? Seems
>    like a wallet login would be sufficient seeing as its dealing with assets.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Grants-Program/pull/2219#pullrequestreview-1888848074>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH37MBPTDIYAONYWHPPVLYDYUN5W7AVCNFSM6AAAAABDJOTRZ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBYHA2DQMBXGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-22 02:38 UTC, phamdat721101 commented
Thank you so much @Keegan

Phạm Quốc Đạt

Mobile phone: 0977705810



Vào Th 5, 22 thg 2, 2024 vào lúc 03:55 Keegan | W3F <
***@***.***> đã viết:

> Thanks for the changes @phamdat721101 <https://github.com/phamdat721101>
> I'm still not seeing that the M2 Market News section has been elaborated
> upon. That being said, I will go ahead and mark your application as ready
> for review.
>
> But I'm personally not convinced about it seeing as you list only EVM DeFi
> protocols in the tech stack and your team doesn't have much Rust/ink!
> expertise. Also this is a DeFi focused app that could be more appropriately
> funded via a VC or one of the DeFi parachain grant programs
> <https://github.com/w3f/Grants-Program?tab=readme-ov-file#other-grant-or-bounty-programs>
> or even a community treasury, given the social aspect of it.
>
> Therefore I won't personally approve it but I will open it up for other
> committee members to comment.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Grants-Program/pull/2219#issuecomment-1957900157>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH37MBMOWLBG35YWPOSO5R3YUZNLZAVCNFSM6AAAAABDJOTRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJXHEYDAMJVG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-22 12:37 UTC, Noc2 requested changes
Thanks for the application. But why do you need to "Integrate blockchain technology" to track portfolio data? For this kind of solution no smart contract or anything similar should be needed, at least if the portfolio is based on digital assets. What kind of smart contracts have you deployed as part of your MVP?

2024-03-03 06:15 UTC, Luckygirl3289 commented on applications/DigiTrust.md
> +**Blockchain Integration:** Smart contracts have been deployed to testnet, providing users with transparent and tamper-resistant asset management.
Blockchain testnet

2024-03-04 20:36 UTC, keeganquigley commented
pinging @phamdat721101

2024-03-06 02:49 UTC, phamdat721101 commented
> Thanks for the application. But why do you need to "Integrate blockchain technology" to track portfolio data? For this kind of solution no smart contract or anything similar should be needed, at least if the portfolio is based on digital assets. What kind of smart contracts have you deployed as part of your MVP?

2024-03-06 03:21 UTC, phamdat721101 commented on applications/DigiTrust.md
> +**Blockchain Integration:** Smart contracts have been deployed to testnet, providing users with transparent and tamper-resistant asset management.
1 - DigiTrust targets to deploy on **Statemint** parachain
2 - We are starting to work with Ink! and Substrate now, and we will migrate system from solidity base
3 - These are extra features in the second milestone, and we will explain more detail after having traffic from first-version for building portfolio management 
4 - DigiTrust is deployed in Klaytn-testnet : 0xa39c2b7957496d28cd6b3fd005b4a1584abe0c30

2024-03-06 03:32 UTC, phamdat721101 commented
> Thanks for the application. But why do you need to "Integrate blockchain technology" to track portfolio data? For this kind of solution no smart contract or anything similar should be needed, at least if the portfolio is based on digital assets. What kind of smart contracts have you deployed as part of your MVP?

Hi, DigiTrust target to track portfolio data as the post content for decentralized social network feature, which can support investors or managers to share their performance, 
We already deployed test-version in Klaytn-testnet in 0xa39c2b7957496d28cd6b3fd005b4a1584abe0c30

2024-03-07 00:22 UTC, keeganquigley commented
Hi @phamdat721101 thank you for all the time and effort you put into the application and for your communication during the process. 

Unfortunately, the committee unanimously decided today not to move forward with the application. This is mainly due to the concerns listed above. Since you already have all the smart contracts built and it is meant to integrate with popular EVM DeFi apps, it might make more sense to migrate the contracts to an EVM-compatible chain like Moonbeam or Astar instead of re-writing them all.

Either way, I appreciate your interest in the W3F grants program and wish you the best of luck in finding funding.

2024-03-07 00:22 UTC, closed without merging

2024-03-07 01:59 UTC, phamdat721101 commented
No worries, thanks for the update!

Phạm Quốc Đạt

Mobile phone: 0977705810



Vào Th 5, 7 thg 3, 2024 vào lúc 07:22 Keegan | W3F <
***@***.***> đã viết:

> Hi @phamdat721101 <https://github.com/phamdat721101> thank you for all
> the time and effort you put into the application and for your communication
> during the process.
>
> Unfortunately, the committee unanimously decided today not to move forward
> with the application. This is mainly due to the concerns listed above.
> Since you already have all the smart contracts built and it is meant to
> integrate with popular EVM DeFi apps, it might make more sense to migrate
> the contracts to an EVM-compatible chain like Moonbeam or Astar instead of
> re-writing them all.
>
> Either way, I appreciate your interest in the W3F grants program and wish
> you the best of luck in finding funding.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Grants-Program/pull/2219#issuecomment-1982099511>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH37MBJACAWRHQD54WA7Q4LYW6XMTAVCNFSM6AAAAABDJOTRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBSGA4TSNJRGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>