Create PyreBrowser.md
w3f/Grants-Program pull request #2434
Opened 2024-10-24 08:48 UTC by DamianRavi

#### Project Abstract

Pyre Browser is a Decentralized P2P browser that liberates the world from predatory markets.

It is a normal HTTPS browser (thats 44% faster than Firefox) but also has a secondary P2P internet. If I type in polkadot.com it will go to the main website. If I type in "polkadot" it will take you to a 404 page where you can purchase the domain. At current prices its $2500 for a 8 letter domain. After the site is purchased you can upload a folder and save the checksum to the blockchain. Every time a user searches for your domain their client will look for a 7z folder with the same checksum as noted on the blockchain and download it from peers. If you want to change the website you just upload the new folder and save again (It costs 0.1 cent in Glimmer to do this). Each user is then prompted to download the new version from peers.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2024-10-24 09:06 UTC, DamianRavi commented
I have read and hereby sign the Contributor License Agreement.

2024-10-24 10:55 UTC, DamianRavi commented
> Thanks for the application, @DamianRavi, but please review our guidelines and FAQ on what projects and information we look for in an application. In particular, please note that we do not fund projects that actively encourage gambling.
> 
>     * FAQ: https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund
> 
>     * Guidelines: https://grants.web3.foundation/docs/Introduction/intro

There is no gambling - I will remove the charity casino from the roadmap

2024-10-24 10:57 UTC, DamianRavi commented
> Thank you for submitting a grant application. We've assessed your submission and have found that it requires a higher level of technical detail in order to be considered for review. We encourage you to expand on it by providing a more precise specification/technical details. The [section on project details](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#project-details) in the application template is a good reference as to what type of information we expect applicants to provide, and these [category-specific requirements](https://grants.web3.foundation/docs/Support%20Docs/grant_guidelines_per_category) contain more precise guidelines depending on what type of software you're building. An area of the application that we often find to be insufficiently elaborated are the milestone deliverables. At a minimum, please indicate what languages/technologies you will be using to implement each deliverable, and provide a technical summary of its expected functionality. Note that deliverables should be tangible, reusable by other teams and in most cases not already present in the ecosystem. If they are, you will need to provide a comparison to existing implementations and explain why it makes sense to fund your approach. Also see our [FAQ](https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund) for a breakdown of what we fund and what we don't. Let us know as soon as you're done with your changes, and we'll give your application another look!

I have included all tech used (There is not much beyond Electron and NodeJS)

2024-10-24 11:41 UTC, semuelle requested changes
Please also fix the development roadmap as per our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). There are default deliverables that are required. Also, all deliverables should be verifiable and reusable (see guidelines and FAQ mentioned above) and specifications as precise as possible to avoid any misunderstandings.

2024-10-24 13:08 UTC, DamianRavi commented
> Please also fix the development roadmap as per our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). There are default deliverables that are required. Also, all deliverables should be verifiable and reusable (see guidelines and FAQ mentioned above) and specifications as precise as possible to avoid any misunderstandings.

I've included this now and converted it to one milestone. I'm weary of realeasing source code before we have any users as it can be copied and rebranded within 1 hour. Either it is released when we have around 100 active websites or by June 2025 as a hard deadline. Hopefully this is ok!

2024-10-24 14:01 UTC, keeganquigley requested changes
Hi @DamianRavi we do require any code written for the grant to be open-source, (and not rely on any closed-source components) but the code doesn't have to be public until the milestone delivery. Would you be willing to open-source all the code upon delivery of the first milestone? See more details in our [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md).

2024-10-24 14:28 UTC, DamianRavi commented
> Hi @DamianRavi we do require any code written for the grant to be open-source, (and not rely on any closed-source components) but the code doesn't have to be public until the milestone delivery. Would you be willing to open-source all the code upon delivery of the first milestone? See more details in our [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md).

Yes, of course! I want it to be opensource ASAP. I combined both milestones and set the deadline to 8 months. So by 06/2025 it needs to be open source but hopefully it gains traction before then and I can release the code earlier.

2024-10-26 08:37 UTC, DamianRavi commented
![gaia](https://github.com/user-attachments/assets/cd605558-6b5f-4fea-a8db-f3810c1b7729)
And here is what Gaia Source will look like soon. A cybernetic system that allows anyone in the world to see global production and purchases and plan their life correctly based on real world data. A true vision of the 1960s cyberneticists mixed with the dreams of free market thinkers of the 1800s! A true free market paradise with the Earth in mind

2024-11-04 16:44 UTC, DamianRavi commented
![chart-orange](https://github.com/user-attachments/assets/dcc4bd73-71b8-4993-9b15-abfca12accc7)
Just finishing up PyreCharts - its 95% smaller than Trading Views library and does most of the same things. Just working on the last feature - you can draw lines to buy/sell against those lines in real-time.

Eventually I want to add tools to prospect commodity markets. So a rice farmer will be able to check what crop to switch to based on projected trends and buying volumes.

2024-11-10 17:10 UTC, DamianRavi commented
![pyrepassalert](https://github.com/user-attachments/assets/9d7cb055-2254-4c99-b8be-0d6a33a79981)

Next update users will be able to highlight and add any EVM address to their address book! Theres a couple of issues with favicons and address bar focusing that will be fixed also. Updating probably tomorrow or the day after

2024-11-12 20:12 UTC, keeganquigley commented
Thanks for the additional info @DamianRavi the tech is neat, but to be honest, I don't think this is the best fit for a W3F grant. Mainly because of these points:
- The product is already completed, launched and in production. Unfortunately we don't offer retroactive funding.
- You mentioned that you mainly need "design, branding, and marketing help" but the grants program doesn't cover any of these areas. For example, we can't fund "the hiring of a community manager" deliverable.
- I think you are underestimating the hosting costs; they might be small now but not if you intend to scale the app for a million users. I think to effectively compete with the other browser giants you will need some VC funding. Since the PoC has already been built, I don't think we're an appropriate avenue for funding.

Additionally, this is just my opinion, but why bring advertising back into the browser? Personally I love the ad block features in Brave, and I don't love ad trackers. The beauty of Web3 and decentralization is that you can get rid of advertising as a revenue model. When you add it back in as a built-in feature, I don't see the benefits over using a regular Web2 browser. 

Before closing, I will mark your application as ready for review to give other committee members a chance to comment.

2024-11-14 15:53 UTC, keeganquigley requested changes
Thanks for your response @DamianRavi just to make it clear, this is only my opinion, its possible other committee members will think differently. I will reiterate though that section **1. Marketing** "hiring of a community manager" would need to be removed from the deliverables in order for the grant to be considered for acceptance. Let us know if you are willing to make these changes.

2024-11-14 16:30 UTC, DamianRavi commented
"Revamp of the main website and innovating good marketing ploys (twitter referal programs, social media linked faucet (for 1 GLMR anyone can create a multitude of things - so just giving someone 20 cents in crypto is a huge boon to the network))"

I have modified and excluded that. I actually spent years generating weird referal programs and marketing ploys for crypto games so I can manage on my own. We had an entire Indonesian village game a monetary system in a dapp at some point!

2024-11-14 16:38 UTC, keeganquigley commented
Thanks for the changes @DamianRavi I will mark as ready for review again.

2024-11-20 13:03 UTC, semuelle reviewed
Thanks for the application, @DamianRavi. However, I have to agree with my colleague here that this application is not a good fit for the Grants Program for the reasons mentioned.

Also, not to rain on your parade, but there are some _very_ steep claims in your application that make me wonder how familiar you are with the complexities of running a Gmail or AWS-type service. I tried finding out more about the project and what you shared here, but most links on your website are broken or nonexistent, including the community, blog, team, Reddit and help links. I will therefore also not support this application.

2024-11-20 16:30 UTC, closed without merging

2024-11-20 16:30 UTC, keeganquigley commented
Thanks for all your time and efforts in submitting the application @DamianRavi, unfortunately the proposal was unable to gain the necessary support from the committee. Therefore I will close it. Thanks again for your prompt answers, and we wish you the best of luck in securing funding for the project.