docs(cyferio-hub): grant application for Cyferio Hub
w3f/Grants-Program pull request #2462
Opened 2024-12-07 09:59 UTC by moven0831

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2024-12-07 10:00 UTC, moven0831 commented
I have read and hereby sign the Contributor License Agreement.

2024-12-09 10:44 UTC, keeganquigley requested changes
Hi @moven0831 thanks for the application. Nice to see that you were already a winner in two hackathons. A couple of initial questions:

- The link to the [Cyferio SDK](https://github.com/cyferio-labs/tmc) gives a 404 error. Is this hosted in a different location now?
- On the Cyferio [website](https://github.com/cyferio-labs/tmc), the docs and demo links don't seem to point anywhere.
- What is the expected latency and throughput of the FHE rollups, and how will they compare to traditional rollups?
- What mechanisms will be in place to prevent malicious actors from exploiting vulnerabilities in the cross-chain communication protocols?
- How will the integration with DragonflyDB improve the scalability and performance of Cyferio Hub, especially in terms of transaction throughput and latency?
- What are the expected limits on the size and complexity of confidential computations that can be performed on the platform?

2024-12-18 14:07 UTC, semuelle commented
pinging @moven0831

2024-12-19 09:57 UTC, moven0831 commented
Hi @keeganquigley and @semuelle , thanks for the nice questions and reminders (sorry for missing the message). Our team have done some research and here are the responses to the best of our knowledge. Looking forward to your feedback!

## Repo
we have refactored our github repo recently and are ready to open-sourced them. please check them on
- org page: https://github.com/cyferio-labs
- Cyferio Hub: https://github.com/cyferio-labs/cyferio-hub-node
- Cyferio SDK: https://github.com/cyferio-labs/cyferio-sdk (prev. [tmc](https://github.com/cyferio-labs/tmc))

## Website
the website is currently under construction. we will update it as soon as possible.
- Draft Web: https://cyferio.com
- Demo (Youtube): https://www.youtube.com/@cyferio

## Benchmarks on the size, complexity, latency and throughput of confidential transactions that can be performed on the FHE rollups created by Cyferio SDK

We have done some benchmarks on confidential token transfers. This is done on single sequencer node and a consumer-grade machine. Notice that with production-grade hardware and increasing the number of sequencer nodes, the performance can be further improved.

- Machine Info
  - CPU: Apple M3
  - cores: 8
  - Memory: 24GB
- Single confidential transaction size: 75 KB (the transfer amount is a FHE ciphertext)
  | **Operation**       | **Time Taken (seconds)** |
  |----------------------|--------------------------|
  | Token creation       | 4.906156                |
  | Token minting        | 9.091760                |
  | Token transfer       | 5.951537                |
- Maximum confidential transactions in a batch: 4 Token transfers, or 75 KB * 4 = 300 KB size of transactions.

The details of the benchmarks are available here: https://github.com/cyferio-labs/cyferio-sdk/blob/d3a4601fa4d9f13301ce54a9144614e9cc796871/benchmarks/log_20241219.txt


Moreover, we want to highlight that Zama has done some benchmarks on the confidential token transfers. They have done it on production-grade hardware and the results shows that the performance of confidential transactions can be dramatically improved. With advancements in FHE algorithms and hardware such as GPUs and ASICs, we strongly believe confidential transactions will continue to improve in size, complexity, and speed, eventually reaching mass adoption.

Machine Info for Zama's benchmarks:
- CPU benchmarks: AMD EPYC 9R14 server with 192 cores
- GPU benchmarks: NVIDIA 2xH100

**Table: Encrypted ERC20 transfers benchmarks**
| Hardware | Latency (ms) | Throughput (tx/s) |
|----------|--------------|-------------------|
| CPU      | 325          | 12                |
| GPU      | 99           | 37                |


The details of Zama's benchmarks are available here: https://github.com/zama-ai/fhevm/blob/main/fhevm-whitepaper-v2.pdf

### Comparison with traditional rollups

Compared to FHE Rollups, Optimistic Rollups have the following advantages:
- Lower gas cost (the transaction is relatively simple)
- Higher throughput: 10x to 100x of L1's throughput. e.g. 16 TPS on Ethereum Mainnet vs ~1000 TPS on Optimistic Rollups (reference: https://ethereum.org/en/developers/docs/scaling/optimistic-rollups)

Nonetheless, again, FHE Rollup is one of the most feasible solutions to have confidential applications achieve mass adoption without the need of upgrading the mainstream blockchains. On the other hand, the FHE Coprocessor approach is better suited for simpler applications, as it results in high latency and gas fees for more complex uses. And it's the only viable way to build comprehensive privacy-preserving dApps such as Confidential DEX, Confidentail DID and Governance since Cyferio SDK is highly modularized and can be easily customized for the needs of different scenarios to lower the cost of development.

## Future mechanisms to prevent malicious actors from exploiting vulnerabilities in the cross-chain communication protocols.

We understand the concerns of the community and are actively working on developing mechanisms to ensure the security of the cross-chain communication. One way is to collaborate with a mature cross-chain communication protocol, such as those utilized within the Polkadot ecosystem, the team can leverage proven security measures (from Polkadot's shared security model) and established best practices that have been vetted by a broader community of parachains and relay chains.

Moreover, other feasible solutions are also being considered, such as diversified validator sets, robust smart contract audits, and secure key management are also in our roadmap.

## Integration with DragonflyDB will improve the scalability and performance of Cyferio Hub in terms of transaction throughput and latency

### Scenario 1 (FHE Ciphertext Transactions):
We leverage DragonflyDB to efficiently handle computationally intensive tasks. Specifically, in dealing with FHE ciphertexts and operations among them, its optimized memory management mitigates the high ciphertext blow-up rate (typically 100x to 1000x), reducing TPS and ensuring consistent latency. This enables Cyferio Hub to confidently scale encrypted transaction loads from FHE rollups.

### Scenario 2 (Ordinary Transactions):
In terms of StateDB, compared directly to RocksDB that we've used for now, DragonflyDB's benchmarks show a superior QPS (queries-per-second), more efficient resource utilization with in-memory data store, all of which ensure that as transaction volume increases, performance remains stable and users experience minimal delays.

2025-01-04 06:54 UTC, moven0831 commented
Hi @keeganquigley and @semuelle , looking forward to your feedback!

2025-01-04 06:55 UTC, moven0831 reviewed
Hi @keeganquigley and @semuelle , looking forward to your feedback!

2025-01-13 23:22 UTC, keeganquigley requested changes
Thanks @moven0831 I just have a few additional non-technical questions:

- The applications mentions parachain and appchain developers as the target audience. What is the marketing strategy for attracting them to Cyferio?
- Will any of the JAM integration deliverables potentially change down the line depending on development choices?

2025-01-14 14:58 UTC, moven0831 commented
> * The applications mentions parachain and appchain developers as the target audience. What is the marketing strategy for attracting them to Cyferio?

Our vision is to unlock a new generation of fully confidential and interoperable on-chain applications. With Cyferio Hub:

- Empowering Innovation: We’ll publish in-depth tutorials showcasing how privacy-focused modular rollups can power confidential DID, prediction market(like an encrypted Polymarket), and even on-chain games where logic remains hidden yet verifiable.

- Ecosystem Engagement: We plan to team up with Polkadot community events, hackathons, and accelerator programs. We’ll also offer grants and pitch sessions, ensuring that talented teams can bring their confidential dApps to life on Cyferio.

- Incubation & Support: We are about to launch a dedicated builder program, we’ll offer mentorship, collaborative marketing, and funding resources to projects that choose Cyferio for their confidentiality needs. This helps us grow privacy-preserving ideas into confidential dApps ecosystems.

so the overall path is: demo the potential of confidential applications → attract developers → ecosystem support (grants, workshops) → provide incentives (grant support for participating in Polkadot's hackathon with privacy dApps)

2025-01-14 14:59 UTC, moven0831 commented
> * Will any of the JAM integration deliverables potentially change down the line depending on development choices?

While our long-term goal of integrating JAM to enable privacy-focused rollups remains, individual deliverables may adjust as we refine the architecture alongside with JAM’s updates (e.g. synchronous calls between services during the accumulate phase).

At our core, we believe that the combination of Cyferio's confidential rollups and routing capabilities, along with JAM's scalability and performance, will be a powerful force in the advancement of the Polkadot network and nurture top confidential applications. Also, our modular approach lets us pivot quickly without compromising existing functionality.

2025-01-14 16:44 UTC, keeganquigley requested changes
Thanks for your thorough answers @moven0831 I will mark the application as ready for review and ping the other committee members. In the meantime, would you be willing to reduce the scope to a level 2 PoC, and then follow-up with subsequent grants? $100k is a lot to ask for a team we haven't worked with before, and this would give us a chance to see some of your work before committing to further milestones.

With a level 2 grant, you would also only need three approvals instead of five, in addition to approval by the W3F council, which could be much harder to get. Perhaps you could remove M3 for now. Let us know if you would consider this option.

2025-01-15 06:49 UTC, moven0831 commented
thanks for your feedback @keeganquigley. After discussing this internally with our team, we agree that your suggestion makes sense and will also give us more time to further explore our integration with JAM. We've updated the grant level to 2 and adjusted our milestones and future plans accordingly. Looking forward to ship this and bring on-chain privacy to Polkadot ecosystem!

2025-01-15 17:50 UTC, keeganquigley approved these changes
Thanks @moven0831 much appreciated. Happy to see the reduced scope, and also given the integration with Zama, I'm willing to support it. Will ping the rest of the committee again.

2025-01-15 17:54 UTC, keeganquigley commented
Could you please also submit [KYC verification](https://in.sumsub.com/idensic/l/#/uni_mjcB05gJZfh8dbr7)? Or [KYB verification](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO) if you have a legal entity you'd like to use.

2025-01-17 01:37 UTC, moven0831 commented
@keeganquigley  It's nice to know we will have your support! Also, I've completed the KYC using this email (moven0831@gmail.com). Looking forward to the other commitee's review.

2025-01-17 17:25 UTC, keeganquigley commented
Thanks @moven0831 it's no problem to not have a legal entity, but in that case could you have the other team members complete KYC also? Sorry for the inconvenience.

2025-01-18 11:10 UTC, moven0831 commented
@keeganquigley sure thing! here's our KYC info

- @moven0831 (moven0831@gmail.com)
- @Zombieliu (zombiesliu@gmail.com)
- @vladilen11 (vladilenaksana@gmail.com)
- @web3olalala (web3bob.dev@gmail.com)

Let me know if you need any additional info from us

2025-01-28 21:15 UTC, keeganquigley commented
Thanks @moven0831 KYC is all good to go; I emailed you separately with some additional questions.

2025-01-30 05:23 UTC, moven0831 commented
close this PR for major adjustments

2025-01-30 05:23 UTC, closed without merging