Submit Transactions Agent Pallet proposal
w3f/Grants-Program pull request #2467
Opened 2024-12-16 06:46 UTC by OIyoung

#### Project Abstract

The Transactions Agent Pallet is designed to provide a proxy signing tool for the Substrate ecosystem, aiming to enhance the user interaction experience on Substrate chains. It includes signer accounts and proxy accounts, allowing a user’s wallet address (signer account) to perform on-chain transactions via a token-holding wallet address (proxy account) even without holding tokens.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

2024-12-16 06:59 UTC, OIyoung commented
I have read and hereby sign the Contributor License Agreement.

2024-12-16 07:12 UTC, OIyoung commented
recheck in this Pull Request

2024-12-20 21:38 UTC, keeganquigley requested changes
Thanks for the application @OIyoung we don't pay to ETH mainnet addresses anymore, please see our [payment options](https://github.com/w3f/grants-program?tab=readme-ov-file#pencil-process) and let us know if you are willing to be paid in 50% vested DOT?

- The system you're describing sounds very similar to [pure proxies](https://wiki.polkadot.network/docs/learn-proxies-pure). What are the differences? Are you hearing from others that there is a great need in the ecosystem for this? 
- What advantages does a system like this have over using the existing [proxy pallet](https://wiki.polkadot.network/docs/learn-proxies)?

2024-12-23 07:33 UTC, OIyoung commented
> Thanks for the application @OIyoung we don't pay to ETH mainnet addresses anymore, please see our [payment options](https://github.com/w3f/grants-program?tab=readme-ov-file#pencil-process) and let us know if you are willing to be paid in 50% vested DOT?
> 
> * The system you're describing sounds very similar to [pure proxies](https://wiki.polkadot.network/docs/learn-proxies-pure). What are the differences? Are you hearing from others that there is a great need in the ecosystem for this?
> * What advantages does a system like this have over using the existing [proxy pallet](https://wiki.polkadot.network/docs/learn-proxies)?

We are willing to change the payment method and accept 50% vested DOT.



In fact, we have used **pure proxies** before, and it is indeed a great feature. Although **Transactions Agent Pallet**, **pure proxies**, and **proxy pallet** may sound similar, they serve different functions and aim to achieve different goals.



**Their differences are as follows:**

​	1.	**Problems They Solve**

​	•	**Pure proxies** reduce the exposure of the primary account’s private key.

​	•	**Transactions Agent Pallet** improves the conversion rate from acquiring users to user registration by allowing users to use Substrate applications without needing tokens.

​	2.	**Functions of Accounts**

​	•	**Pure proxies** are new accounts created (not assigned) by a primary account. The primary account acts as a proxy on behalf of the pure proxy. Pure proxies are keyless, non-deterministic accounts, meaning they do not have private keys but possess randomly generated addresses.

​	•	The proxy accounts in the **Transactions Agent Pallet** are controlled accounts with private keys. Their primary tasks include not only signing transactions on behalf of others but also paying gas fees for the signed accounts and implementing various payment strategies.

​	3.	**User Entry Barriers**

​	•	**Proxy pallet** requires users to pay at least one transaction’s gas fee for authorization.

​	•	**Transactions Agent Pallet** is barrier-free for users, allowing them to make calls without gas.



**In simple terms:**

​	•	**Pure proxies** enhance the security of the primary account’s signature, serving as a security tool that allows users to interact with DAPPs more safely.

​	•	**Proxy pallet** addresses the issue of gas fees during transactions but has an entry barrier requiring authorization.

​	•	**Transactions Agent Pallet** is a tool designed for operational purposes, enabling more users to utilize DAPPs.



These features are not mutually exclusive; they can even complement each other. For instance, a sub-key can be generated via **pure proxies**, and **Transactions Agent Pallet** can then be used to call the **proxy pallet** for authorized transactions.



**Regarding the project’s advantages:**



We are aware that the Substrate ecosystem has many proposals aimed at solving technical and security issues. However, few consider where the users are and how to acquire them. **Transactions Agent Pallet** provides a marketing tool for the Substrate ecosystem, attracting more users and converting a higher proportion of them into paying users.

2025-01-14 02:28 UTC, OIyoung commented
Hello @semuelle , Thanks for your reply. Our response to these questions is as follows:

- How does the user control the proxy account? Is it assumed that the user has an account in a wallet with native token?

  Users cannot control the proxy account, the proxy account is created by developers. The Transactions Agent Pallet is designed to address situations where the user has no tokens, which prevents them from using the DApp and may lead to user abandonment.

- How is the proxy gas fee calculated and paid for? Can you provide a sequence or architecture diagram to clarify the work being done?

  No proxy gas fee. The gas fee for transactions is paid by the proxy account, and token for this account come from developers. The reason the developer pays the gas fee for users is that they want users to try their DApp without any barriers, allowing the DApp to gain more users.

  Below is a sequence:

  ![sequence](https://github.com/OIyoung/Transactions-Agent/blob/main/static/image3.png)

- Can you provide any evidence of you or your team having experience in the ecosystem and in developing and maintaining open source software?

  Sure. Can we prove our team’s experience in a non-public manner? Because in some projects, we have committed to keeping our identities confidential.

- Have you talked to any parachain teams that would be interested in integrating this?

  Yes, there have been some informal discussions since this is still just an idea. From the perspective of user conversion in marketing, we are confident that this feature will be highly beneficial for parachain user conversion.

If these questions haven’t been explained clearly, please feel free to let me know.

2025-01-14 12:03 UTC, semuelle commented
> * Sure. Can we prove our team’s experience in a non-public manner? Because in some projects, we have committed to keeping our identities confidential.

Yes, please send an email to grants@web3.foundation with a reference to this pull request. Thanks.

2025-01-15 03:08 UTC, OIyoung commented
> Yes, please send an email to [grants@web3.foundation](mailto:grants@web3.foundation) with a reference to this pull request. Thanks.

@semuelle Thank you very much! We have sent the team introduction to your email. Please let me know if you need any more information.

2025-01-31 17:20 UTC, keeganquigley commented
Thanks @OIyoung see my email reply - I asked a few more team related questions.

2025-02-05 16:56 UTC, semuelle reviewed
Sorry for the late reply, @OIyoung. Could you expand on how the system would work from a parachain perspective? Would every proxy account receive an allowance until it's depleted? And what does the security check look like? Is it possible to ensure that a user is not simply calling a smart contract that burns the whole allowance?

Lastly, not sure if it applies here, but there seems to be an issue with native feeless transactions and missing existential deposits: https://github.com/paritytech/polkadot-sdk/issues/3991. You didn't provide a development status section in your application; have you verified this idea beforehand?

2025-02-10 03:41 UTC, OIyoung commented
Hello @semuelle , Thanks for your reply.
1. Could you expand on how the system would work from a parachain perspective?

   First, when developers add the Transactions Agent Pallet to their chain, they also need to transfer an initial amount of funds to the proxy account of this Pallet. This fund is used to pay the transaction fees for the signing accounts. The role of the proxy account is to bear the transaction fees on behalf of the actual users, and it is generated from the PalletId.

2. Would every proxy account receive an allowance until it's depleted?


   If the balance of the proxy account is insufficient, developers need to manually recharge it; otherwise, the proxy account will not function properly, resulting in users being unable to transact normally.

3. And what does the security check look like? 


   The security checks include the following aspects:

   - The most basic check is to verify user inputs, such as whether the transaction summary format is correct and whether the signature is valid.

   - For the nonce verification, since the unsigned transaction does not include the nonce format, we envision adding this parameter when formulating the transaction and setting up a StorageMap to store the nonce for each account.


   - Calculate gas using the methods provided by `pallet_transaction_payment` and check whether the proxy account has sufficient balance.

   - Estimate the maximum weight consumption and calculate the transaction priority based on the weight, using the transaction priority to reasonably create a `ValidTransactionBuilder`.

4.  Is it possible to ensure that a user is not simply calling a smart contract that burns the whole allowance?


    Theoretically, because we check the weight in the security checks, malicious users cannot consume the entire balance of the proxy account in a single transaction. However, to prevent this situation, we can set a maximum limit for the amount a proxy account can consume in a single transaction (which is typically used for all normal transactions). Alternatively, we can also restrict malicious user behavior by setting up whitelists or blacklists.

5. Lastly, not sure if it applies here, but there seems to be an issue with native feeless transactions and missing existential deposits:


   It seems that this issue is related to our envisioned security check for the nonce value. We plan to manage the mapping of each account's nonce value through a StorageMap to ensure the safety of funds.

6. You didn't provide a development status section in your application; have you verified this idea beforehand?

    The project has not yet entered the formal implementation phase, but we have conducted a thorough viability assessment of the required deliverables. Based on our extensive experience and proven track record in contributing to other open-source projects, the majority of the infrastructure deliverables fall well within our domain of expertise. This positions us strongly to ensure their successful implementation with minimal risk.

2025-02-10 03:44 UTC, OIyoung commented
Hello @keeganquigley . We have responded to your question about the team in the email, please confirm.

2025-02-19 17:07 UTC, semuelle reviewed
Thank you for providing information via email, and sorry for the long wait, @OIyoung. 
After careful review, I have decided not to support the application for the sole reason that grants for building pallets without a parachain team behind it have a bad track record. As our guidelines state, we look for evidence that "the project will be maintained after completion of the grant, be it through an obvious commitment to the technology from your side, additional funding sources, or an existing business model". It is notoriously difficult for external teams to make significant contributions to parachains, so this to no fault of your own.

That being said, I will notify the rest of the committee, who might disagree with me.

2025-02-20 02:00 UTC, OIyoung commented
Thank you for your reply @semuelle , we will continue to work on it. Finally we will close this issue.

2025-02-20 02:00 UTC, closed without merging

2025-02-20 17:09 UTC, keeganquigley commented
Thanks @OIyoung for all your time and efforts here. I won't approve it either because I think there are already solutions being built in this area, such as the upcoming Polkadot app, or tools like [Multix](https://multix.chainsafe.io/?network=polkadot) and [Signet](https://talisman.xyz/signet) which allows enterprises to create proxy accounts with a lot of abstraction already in place. Also things like keyless wallets will help with the problems you describe.

I also don't think that enough proof was provided to demonstrate that your team has experience in this area. So we will leave it closed, but thank you for the application and I hope you are able to secure funding for the project.