GVM Bridge.md
w3f/Grants-Program pull request #445
Opened 2021-06-05 22:19 UTC by steve1588

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-06-05 22:31 UTC, steve1588 commented
hi, everyone. This is an interesting basic project, please support it. Thanks in advance.

2021-06-07 07:50 UTC, mmagician commented
@steve1588 It looks like an interesting idea indeed.
I realise there has been some delay with the evaluation of the first milestone of your previous grant - apologies for this, I'll double check that one for you today and make sure we move forward. Regardless of M1, before we proceed with this proposal, could you let us know whether you're planning to complete the previous grant and what stage are you at with M2?

With very few exceptions, we generally don't award multiple grants in parallel ([we're making this more explicit](https://github.com/w3f/Open-Grants-Program/pull/446)), but rather ask teams to complete any outstanding milestones for earlier grants. If you no longer wish to work on the previous project, please let us know ASAP - in that case we'd terminate the previous one and open this proposal for review, although that might also affect the committee's willingness to support the new project. 

I'll wait for your response and in the meantime put this PR on hold.

2021-06-07 12:17 UTC, steve1588 commented
> @steve1588 It looks like an interesting idea indeed.
> I realise there has been some delay with the evaluation of the first milestone of your previous grant - apologies for this, I'll double check that one for you today and make sure we move forward. Regardless of M1, before we proceed with this proposal, could you let us know whether you're planning to complete the previous grant and what stage are you at with M2?
> 
> With very few exceptions, we generally don't award multiple grants in parallel ([we're making this more explicit](https://github.com/w3f/Open-Grants-Program/pull/446)), but rather ask teams to complete any outstanding milestones for earlier grants. If you no longer wish to work on the previous project, please let us know ASAP - in that case we'd terminate the previous one and open this proposal for review, although that might also affect the committee's willingness to support the new project.
> 
> I'll wait for your response and in the meantime put this PR on hold.

We are glad to get your attention.

The ELC project is a very important project for the Cycan team. We will definitely continue to complete it. In order to make the project even better, we are putting more resources and time in the ELC project. Please rest assured that the M2 is currently undergoing development and testing, and the original plan was to deliver M2 in the near future. 

But in order for the whole project to be more robust, we want to ensure that the sercurity audit of ELC project to de done, and then certain features will be optimized and updated as necessary.After completion of these tasks, we will merge and release them with M2. To do so, we may need a few more weeks for the M2 delivery.

In addition, it needs to be explained that the development of the ELC and GVM Bridge projects have been carried on by two different tech groups from our team,, and the parallel development of the two projects will actually have no conflict with each other. Our goal is to make GVM Bridge a public basic project of Polkadot and strive to become a public welfare basic module in Substrate that can be cited by various project teams. In fact, we started the coding work of the GVM Bridge project a month ago. The progress is going well.

Please evaluate the above situation and hope you give us extra support on both of the two projects. Thank you very much!

2021-06-07 13:53 UTC, mmagician commented
We will evaluate your case on an individual basis. I'll get back to you on this.

2021-06-17 11:12 UTC, mmagician commented
I think the idea in this proposal is very interesting and I would like to support it. However, I'm still evaluating the previous milestone and I am getting the impression that the delivery is a little messy and perhaps git management isn't best either. I would be wary in accepting a parallel grant at this stage, but this is just my opinion and I'll let other members of the Grants team decide.

Anyway, before I share it with the rest of the team and to better understand the current proposal, I would like to ask you to expand on the specifications of M1 & M2. I don't fully understand what scope you're planning to cover. For example, first you write:
> The Framework V0.2 will contain WASM-Proxy pallet, EVM-Proxy pallet, Trans4WABI and Trans4EABI.

But then in the future plans section you mention that there you'll complete the functions for the above modules. Therefore, my question is: how much are you going to deliver for the proposed milestones, and what is not covered? It would be great if you could outline all the functionality that is & isn't covered by your current proposal.

2021-06-21 17:34 UTC, steve1588 commented
> I think the idea in this proposal is very interesting and I would like to support it. However, I'm still evaluating the previous milestone and I am getting the impression that the delivery is a little messy and perhaps git management isn't best either. I would be wary in accepting a parallel grant at this stage, but this is just my opinion and I'll let other members of the Grants team decide.
> 
> Anyway, before I share it with the rest of the team and to better understand the current proposal, I would like to ask you to expand on the specifications of M1 & M2. I don't fully understand what scope you're planning to cover. For example, first you write:
> 
> > The Framework V0.2 will contain WASM-Proxy pallet, EVM-Proxy pallet, Trans4WABI and Trans4EABI.
> 
> But then in the future plans section you mention that there you'll complete the functions for the above modules. Therefore, my question is: how much are you going to deliver for the proposed milestones, and what is not covered? It would be great if you could outline all the functionality that is & isn't covered by your current proposal.

2021-06-21 17:35 UTC, steve1588 commented
> > I think the idea in this proposal is very interesting and I would like to support it. However, I'm still evaluating the previous milestone and I am getting the impression that the delivery is a little messy and perhaps git management isn't best either. I would be wary in accepting a parallel grant at this stage, but this is just my opinion and I'll let other members of the Grants team decide.
> > Anyway, before I share it with the rest of the team and to better understand the current proposal, I would like to ask you to expand on the specifications of M1 & M2. I don't fully understand what scope you're planning to cover. For example, first you write:
> > > The Framework V0.2 will contain WASM-Proxy pallet, EVM-Proxy pallet, Trans4WABI and Trans4EABI.
> > 
> > 
> > But then in the future plans section you mention that there you'll complete the functions for the above modules. Therefore, my question is: how much are you going to deliver for the proposed milestones, and what is not covered? It would be great if you could outline all the functionality that is & isn't covered by your current proposal.

Thank you very much for your support. I just saw your message. We will update it as soon as possible.

2021-06-25 02:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=445) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=445) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: steve1588<br/>:x: derrickf87<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=445) it.</sub>

2021-06-29 07:52 UTC, Noc2 requested changes
Thanks for the application. In general this is something in which we are quite interested in. But I have a few questions: What exactly would be the scope of M1 (programming language)? Why did you choose pallets instead of smart contracts for the connection? Could you integrate an example as part of the deliveries? Why did you increase the price so significantly compared to https://github.com/w3f/Open-Grants-Program/pull/277 and how do you plan to increase the quality compared to your previous delivery: https://github.com/w3f/Grant-Milestone-Delivery/pull/157

2021-06-30 08:17 UTC, steve1588 commented
> Thanks for the application. In general this is something in which we are quite interested in. But I have a few questions: What exactly would be the scope of M1 (programming language)? Why did you choose pallets instead of smart contracts for the connection? Could you integrate an example as part of the deliveries? Why did you increase the price so significantly compared to #277 and how do you plan to increase the quality compared to your previous delivery: [w3f/Grant-Milestone-Delivery#157](https://github.com/w3f/Grant-Milestone-Delivery/pull/157)

Hi, David
Thank you for your attention to the GVM bridge project.
The programming language range of the M1 is in Rust. 
Since smart contracts need to call ERC20 contracts on other types of virtual machines through the pallets, they cannot be called directly. We will have an example of calling other types of virtual machine ERC20 contracts as part of the M1 delivery.

First of all, compared with #277, the positioning of the GVM bridge project is a basic non-profit public project, while the #277 project is a commercial project.

Therefore, our considerations of cost calculation when applying for the Grant are completely different. The GVM bridge project is quoted to ensure that the actual development cost is covered.
We completely ignored the actual development cost when we apply for #277. At that time, it only applied for a grant in order to obtain recognition and did not consider the actual amount from the Grant.

Secondly, we attach great importance to the GVM bridge project, because it is one of the infrastructures related to ecological migration. If it can finally be widely adopted, we will be very honored.

For these reasons, we have specially assigned the team's most senior developer to take charge of the project, who has more than 20 years of experience in development.

Therefore, please rest assured in terms of the delivery quality of the GVM bridge project. The GVM bridge team is completely transcended the #277 primary team in terms of engineering capability or quality management requirements.

As a result, the GVM bridge project will also cause the development cost to be much higher than the #277 project.

Thank you again for your attention and support!

2021-06-30 08:24 UTC, steve1588 commented
By the way, let’s talk about the problem of #277: As I mentioned before, our audit team has recently audited the development of the #277 project team. According to the audit result, we are also quite dissatisfied with the current situation. There are many necessary optimizations on design and transformation. We have made a decision: we plan to reorganize the #277 project team, and according to the schedule, we will start to optimize and partially refactor the code of the #277 project not later than late July. Please continue to pay attention to the #277 project. Thank you very much in advance  @Noc2 @mmagician

2021-06-30 11:48 UTC, mmagician commented
Is there any code or github repos that your team members involved in **this** project can demonstrate?

Regardless of the previous project's quality: could you explain how the sequence of calls will look like under the hood?
Do I understand correctly that in order to be able to use the GVM capabilities, a chain needs to have 4 pallets deployed to it: pallet-contracts, evm-pallet and both EVM-proxy & WASM-proxy pallets, right?

When creating a smart contract, say in `ink!`, how would I actually make a call to another EVM contract? Do you have any examples of how this would look like (i.e. code mock-up)? And what would happen under the hood, i.e. the interaction between pallets/calls/extrinsics?

2021-07-01 16:09 UTC, steve1588 commented
> Is there any code or github repos that your team members involved in **this** project can demonstrate?
> 
> Regardless of the previous project's quality: could you explain how the sequence of calls will look like under the hood?
> Do I understand correctly that in order to be able to use the GVM capabilities, a chain needs to have 4 pallets deployed to it: pallet-contracts, evm-pallet and both EVM-proxy & WASM-proxy pallets, right?
> 
> When creating a smart contract, say in `ink!`, how would I actually make a call to another EVM contract? Do you have any examples of how this would look like (i.e. code mock-up)? And what would happen under the hood, i.e. the interaction between pallets/calls/extrinsics?

The core engineers involved in the project have participated in the research and development of commercial projects that are closed source for more time in the past, and generally have confidentiality agreements, so it is not convenient to display their past project code information here. Please understand.
Let's talk directly about the behind-the-scenes work of the GVM bridge:

The project is mainly divided into 5 pallets and some auxiliary codes: wasm contract pallet, EVM-pallet, and EVM proxy pallet, WASM proxy pallet, and gvm_bridge pallet (The M1 version will temporarily merge EVM proxy pallet and WASM proxy pallet into gvm_bridage pallet), Other auxiliary codes are EVM-precompile code, WASM's ChainExtention code.

When creating a smart contract, take ink! as an example, in order to call another EVM contract, the steps are:
1. Organize appropriate parameters in the ink! code.
2. Call the ChainExtention code in ink!.
3. ChainExtention code calls the WASM proxy pallet. 
4. The WASM proxy pallet decodes the parameters and calls the gvm-bridge pallet. 
5. The gvm_bridge pallet will call the EVM proxy pallet according to the parameters. 
6. The EVM proxy pallet encodes the parameters and calls the EVM contract. 
7. After the result is returned, the EVM proxy pallet decodes the parameters and returns them to the gvm_bridge pallet. 
8. The decoded parameters return to the WASM proxy pallet. 
9. After the WASM proxy pallet encodes the returned parameters, it returns to the ChainExtention code again.
10. The ChainExtention code returns to the ink! contract to complete the whole invoke process.

For the EVM contract to call the ink! contract, the first step is to call the EVM-precompile code for the EVM contract organization parameters, and the subsequent process is similar to that of the ink! contract calling the EVM contract.

2021-07-02 08:39 UTC, mmagician commented
I see, thanks for the explanation.
I'm sorry to say that I won't be supporting this project.
First of all, we have no insight into who's going to be working on the project and their experience. I find it suspicious that you can't even share github profiles of the members and that **all of them** have **absolutely zero** public github activity.
Second, the quality of previous delivery wasn't up to our standards as already mentioned.
Lastly, the above described process makes conceptual sense, but it seems extremely cumbersome to use this structure.

Perhaps I would be more willing to re-consider the application once you've demonstrated the ability to deliver on the promise for the previous grant. Other Grants Committee members can still have a look and take a different approach.

2021-07-02 09:14 UTC, steve1588 commented
> I see, thanks for the explanation.
> I'm sorry to say that I won't be supporting this project.
> First of all, we have no insight into who's going to be working on the project and their experience. I find it suspicious that you can't even share github profiles of the members and that **all of them** have **absolutely zero** public github activity.
> Second, the quality of previous delivery wasn't up to our standards as already mentioned.
> Lastly, the above described process makes conceptual sense, but it seems extremely cumbersome to use this structure.
> 
> Perhaps I would be more willing to re-consider the application once you've demonstrated the ability to deliver on the promise for the previous grant. Other Grants Committee members can still have a look and take a different approach.

Regarding your opinion, let me express my personal opinion:
First of all, for you, there is actually no upfront expenditure, so there is no loss or risk. Moreover, for the M1 content of the GMV bridge project, we are almost finished developing it, and we are testing it. You can directly understand the results of the current stage in advance to test the capabilities of the GVM bridge development team.
Secondly, you think the above-mentioned behind-the-scenes steps of virtual machine intermodulation seem more complicated, but this is only the procedure behind the scenes operation. In fact, for contract developers who use the GMV bridge, it is very simple to use.
If you have thoroughly studied the intermodulation between different virtual machines, you will think this is a good solution. Or, do you have a better and simpler solution? Welcome to discuss.

2021-07-02 09:29 UTC, mmagician commented
> First of all, for you, there is actually no upfront expenditure, so there is no loss or risk

We try our best to understand the code in-depth and ensure quality when looking at milestone deliveries. If we accept projects which have delivered poorly in the past, poses an opportunity cost and a risk of allocating our resources inefficiently.

There have been [some discussions](https://github.com/paritytech/ink/issues?q=is%3Aissue+solidity) in the `ink!` repo regarding calling solidity methods. To my eye, it doesn't look resolved yet, but it seems at least theoretically possible to do this directly without hopping through intermediate pallets.

2021-07-02 09:44 UTC, alxs commented
Hey @steve1588, I'm afraid I won't support this application either.

Regardless of whether it makes sense to invest effort into this in the first place or whether your approach is technically sound, I'm also wary of awarding any grant to a team with no verifiable experience. The only point of reference we'd have is the last delivery, which even if it was made by a different team, was poor enough to be rejected.

Seeing as you've apparently almost finished M1, feel free to already share some code if you want, but I'm unlikely to change my mind.

2021-07-02 10:24 UTC, steve1588 commented
> > First of all, for you, there is actually no upfront expenditure, so there is no loss or risk
> 
> We try our best to understand the code in-depth and ensure quality when looking at milestone deliveries. If we accept projects which have delivered poorly in the past, poses an opportunity cost and a risk of allocating our resources inefficiently.
> 
> There have been [some discussions](https://github.com/paritytech/ink/issues?q=is%3Aissue+solidity) in the `ink!` repo regarding calling solidity methods. To my eye, it doesn't look resolved yet, but it seems at least theoretically possible to do this directly without hopping through intermediate pallets.



> > First of all, for you, there is actually no upfront expenditure, so there is no loss or risk
> 
> We try our best to understand the code in-depth and ensure quality when looking at milestone deliveries. If we accept projects which have delivered poorly in the past, poses an opportunity cost and a risk of allocating our resources inefficiently.
> 
> There have been [some discussions](https://github.com/paritytech/ink/issues?q=is%3Aissue+solidity) in the `ink!` repo regarding calling solidity methods. To my eye, it doesn't look resolved yet, but it seems at least theoretically possible to do this directly without hopping through intermediate pallets.

For the existing solutions you mentioned, as far as we know, the idea is to put the code directly in chain extensions. We think their scheme is not general enough and the structure is not good enough.

Here are a few specific points:

1. It is inconvenient to add new virtual machine support. ChainExtension needs to change the ChainExtention node code; and bridge only needs to add proxy.

2. The bridge structure is clear, the codec is placed in the corresponding Proxy, and the ChainExtention is not clear in the node.

3. When the intermodulation support is added, the bridge only needs Runtime update, and if the ChainExtention is changed, the node execution program needs to be replaced.

Finally, we can refer to the "network seven-layer protocol" to look at this problem. If anyway, as long as the application layer is written directly on the network card, data can be transmitted, then why do we need a seven-layer protocol?

2021-07-02 10:54 UTC, steve1588 commented
> Hey @steve1588, I'm afraid I won't support this application either.
> 
> Regardless of whether it makes sense to invest effort into this in the first place or whether your approach is technically sound, I'm also wary of awarding any grant to a team with no verifiable experience. The only point of reference we'd have is the last delivery, which even if it was made by a different team, was poor enough to be rejected.
> 
> Seeing as you've apparently almost finished M1, feel free to already share some code if you want, but I'm unlikely to change my mind.

hi @alxs, I am sorry to see your comment.
I have kept explaining that this is the work being done by two completely different working groups within ours.
We can evaluate the GVM bridge project more directly, objectively, and independently.
If you are willing to give it a try, we are happy to share the current results of the GVM bridge.
Maybe you can think about it this way. What if we used another account to apply for the project in the first place? Will these unacceptable thoughts still be triggered? This may be unfair to the GVM bridge project, and it is easy to bury some excellent projects.

If possible, please reconsider.

2021-07-02 11:15 UTC, steve1588 commented
> Perhaps I would be more willing to re-consider the application once you've demonstrated the ability to deliver on the promise for the previous grant. 

@mmagician 
I think your proposal is also possible. As I mentioned before, we will definitely honor our previous promises and even update and optimize the original technical design. For this reason, we will invest regardless of cost and finally deliver a complete result, please rest assured. It is currently on the timetable and needs to start in late July.

However, I also hope that the original project will not affect the GVM bridge project as much as possible. Please understand. Thank you.

2021-07-02 17:19 UTC, alxs commented
This is not only about your previous delivery having being rejected, as we've said, the fact that all team members for this project have no verifiable experience also makes it hard for us to accept it.

Feel free to share existing code with us.

2021-07-08 10:38 UTC, steve1588 commented
> This is not only about your previous delivery having being rejected, as we've said, the fact that all team members for this project have no verifiable experience also makes it hard for us to accept it.
> 
> Feel free to share existing code with us.

hi @alxs , we have updated part of the current code to GitHub ( https://github.com/CycanTech/GVM-Bridge ), but it has not yet reached the complete state of version 0.1. We are still debugging some tests and sample code, and we don’t expect to upload them to GitHub until next week. In addition, in order to facilitate the pre-publication of the code, we temporarily use a dual LICENSE (BSL+APACHE2) for the GMV project, which has been explained in the Readme file, but this does not affect the subsequent change of the GMV project to fully use the APACHE2 license. Please also understand. Also welcome to make suggestions at any time. Thank you in advance.

2021-07-08 15:55 UTC, alxs commented
Thanks @steve1588. I personally won't support the application, but it will remain open for another week and may still be accepted by other members of the committee.

2021-07-09 08:59 UTC, Noc2 commented
@steve1588  It’s nice to see that you [are already working on this](https://github.com/CycanTech/GVM-Bridge), but I’m currently unable to compile it. If you integrate some initial documentation and bring it to a stage where people can test your POC, maybe including some unit tests, etc. I would be interested in supporting the rest of your project. At the moment, I have the same concerns as my colleagues.

2021-07-13 20:33 UTC, steve1588 commented
> @steve1588 It’s nice to see that you [are already working on this](https://github.com/CycanTech/GVM-Bridge), but I’m currently unable to compile it. If you integrate some initial documentation and bring it to a stage where people can test your POC, maybe including some unit tests, etc. I would be interested in supporting the rest of your project. At the moment, I have the same concerns as my colleagues.

hi @Noc2  Thank you very much for your support, it makes me ignite hope. We will update it as soon as possible in the next few days based on your comments.

2021-07-26 13:13 UTC, mmagician commented
Closing due to inactivity. Since there haven't been any explicit approvals from the committee so far, my suggestion would be to re-open the PR only once either the first grant has been resolved, or you've provided a working PoC for your current project.

2021-07-26 13:13 UTC, closed without merging