Create Valibre PLIP grant application
w3f/Grants-Program pull request #520
Opened 2021-07-23 10:17 UTC by olanod

# Grant Application

## Abstract

This is the application for the implementation of the People Local Interactions Protocol(PLIP) for the Valibre Network(VLN) testnet that allows transacting with local(off-chain) assets and crypto(on-chain) assets, effectively becoming the ecosystem's bridge to the fiat world. 

## Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-07-23 10:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=520) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=520) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=520) it.</sub>

2021-07-23 12:18 UTC, Noc2 requested changes
Thanks for the application. This sounds like an interesting project. 

- Something to be aware of is that we usually don’t support deployment or hosting via the grants program (regarding your delivery 1 and 2 of your first milestone). We rather focus on the parts that are potentially useful for others in our ecosystem, so feel free to remove these from the deliverables. 
- Regarding Summa, could you provide more details? Will it work with kusama/polkadot/substrate?  
- In general could you provide more technical information (e.g. programming language) for the deliverables or link to existing code?  
- Regarding the Escrow & Rates pallet, what are you going to implemented as part of the grant, which wasn’t implemented as part of the Substrate builders program? 
- Why do you want to compile Valor to wasm? Do you want to integrate it into off-chain workers?

2021-07-23 14:35 UTC, olanod commented
Thanks for the feedback @Noc2 I will update the application regarding the infrastructure related topics.  
I will also include answers to your questions in the proposal but answering here as well ...

- [**Summa**](https://github.com/valibre-org/summa) is more of an initiative to group everything related to integrate Substrate and Matrix, in the future you can expect a multitude of libraries and tools grouped in the same repository but for our initial rollout of the testnet and as part of the deliverables we would start with a simple version of the "summa wallet"(built with the help of our [libwallet](https://github.com/valibre-org/libwallet) abstraction) that leverages the fact that matrix clients already handle cross device signing and the mapping of those device keys to a Matrix user ID which in turn will have a corresponding substrate account  ID. And yes, your matrix login would give you a wallet in any Substrate based chain ;)
- I'll link each repository of each tool/library individually but the whole "PLIP stack" is found under our [Github organization](https://github.com/valibre-org). Due to our focus in portability and performance, specially for web clients, everything is being written in **Rust** with big focus on supporting WASM compilation and remaining lightweight.
- The current version of the Escrow and Rates pallets developed with the builders program is basic, more of a PoC for the initial permissioned needs of Valiu. Moving forward we will be making sure it's robust for everyone to use in a permission-less way.
- For a bit more of context trying to not extend myself too much, [**Valor**](https://github.com/valibre-org/valor) needs to compile to WASM since its our bet to achieve **progessive decentralization**(inspired by the progressive enhancement concept of web development). As a general purpose plugin system that allows creating HTTP APIs it would allow users to run plugins, i.e. one based on [**Sube**](https://github.com/valibre-org/sube) that enables talking to a chain similar to how the parity sidecar API works(but better 😛), on top of that more plugins can be integrated and composed together(e.g. a bank API integration that listens to chain events) but it wouldn't end there, it's not only about having a more convenient way to develop APIs but being able to run said APIs in user's devices completely decentralized without having to change the client application code. Imagine the simplest of the web applications, one that gets data and uses some simple forms to submit data via HTTP to a Valor based server, the experience is simple and fast but centralized, to "progressively decentralize" the app, if Valor is included as a "script" in the web app, after a while the same HTTP requests could be served not from a server but from the user device itself thanks to the use of service workers, we can go a step further if for example we hot-swap the Sube plugin used to talk to the chain via HTTP or WebSockets for one that embeds a Smoldot based light node that was downloaded in the background. This whole time the front-end didn't change a line of code and didn't realized when the app went from centralized to fully decentralized. Also front-end devs never had to deal with learning anything blockchain related which is why not only Valiu but other teams are getting interested in building on top of this technology 😄  So no, not related to off-chain workers.

2021-07-25 13:29 UTC, Noc2 requested changes
Thanks for the quick and detailed reply. I have a few follow-up comments: 

- Could you integrate unit tests into the deliverables, see  our template https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules At least for milestone 1, I think this makes a lot of sense. 
- And could you also add rustdoc support to your first milestone?  
- The last milestone currently focuses on things (Dev Workshops, Social media), which we usually don’t support via the grants program. Also because it’s hard to evaluate or isn’t really beneficial for others. Could you potentially just integrate the documentation and video tutorials into the other milestones? It will probably also help us with the evaluation of the milestones.

2021-07-26 09:43 UTC, olanod commented
- Unit tests will definitely be there, it's so natural that didn't think of adding it explicitly 😅 
- Sure no problem with having rustdocs there, it's also pretty standard. Are we expected to host the generated docs and have them public somewhere? We'd do our best to publish at least the pallets to crates.io but developing on the edge also means having git dependencies that won't allow the publishing and therefore the freely available docs.
- What about we make milestone 3 less general and not mention things like workshops and social media, but since what we are building is more of a developer ecosystem and infrastructure, a website with more extensive documentation and guides for teams to build with our technology is quite important and takes time of its own that would go beyond the scope of simpler documentation in the code of previous milestones. So basically it would be about a developer portal(e.g. `dev.plip.community`), if that kind of development is outside the scope of the grants program then no problem we would leave it outside(but develop it anyway since teams already demand it).

2021-07-26 10:50 UTC, Noc2 commented
No need to host the rust docs yourself. It’s just useful for everyone, who might want to take a look at your code (or later audits). Regarding milestone 3, my recommendation would still be to integrate this into the previous milestone (feel free to also increase the price of these milestones a little bit). Alternatively you could add maybe also some additional development work/improvements to the third milestone.

2021-07-27 07:24 UTC, Noc2 commented
Let me know once I should take another look at the application.

2021-07-27 07:40 UTC, olanod commented
Let me know if the changes make sense :)

2021-07-27 08:47 UTC, Noc2 approved these changes
Looks good. I will share the application with the rest of the team.

2021-07-27 13:00 UTC, semuelle commented
Hi @olanod, thanks for the application. Just some minor comments/questions from my side:

- I'm getting a 524 on [the Valibre whitepaper](https://valibre.org/PLIP.pdf). Do you have a copy elsewhere? It'd be useful to know how you decentralise fiat transactions. 
- The Wificoin grant has been [terminated due to inactivity](https://github.com/w3f/Grants-Program/pull/69#issuecomment-855371207). Of course that doesn't necessarily mean they might not be working on the project anymore.
- You mention abstracting away complexities of blockchain a lot, but that brings its own risks. Users might not know that their device potentially carries significant value or that they might have to protect it. Have you thought about how to minimize the risk?

2021-07-27 16:36 UTC, olanod commented
Hi @semuelle

The "whitepaper" is still a work in progress(still it should show up 🤔) but glad to clarify a bit more the approach here in the meantime... The current design is the result of exploring different approaches to do Fiat to Fiat transfers based on previous experience with a remittances company, hopefully this explanation is detailed enough but feel free to ask if there's need to dig deeper in any topic :)  
The initial main idea of the protocol is to enable decentralized on&off ramps for local communities, meaning _fiat to crypto_ and _crypto to fiat_ **swaps**.  First using the Rates pallet users that act as liquidity providers express their commitment to trade a local or crypto currency with a deposit for an amount they consider equivalent to be payed with their medium of preference, when a swap is created by a user they get to select(or their app selects) which liquidity provider they want to trade with based on their payment preferences, then the swap is conducted by locking crypto funds inside an escrow that are released only after the party receiving the Fiat is convinced the transfer was made. Optionally a trusted third-party can join the swap to resolve disputes.

Unlike a [previous design](https://user-images.githubusercontent.com/1329925/115689673-99f1a000-a35c-11eb-9678-4a2ac137b755.png) where the swaps and all the interactions were happening on-chain creating a poor user experience as every update to the swap's state was a signed transaction(with fees), now the highlight of the protocol is building on top of two core decentralized technologies(therefore the sum of both is also decentralized?), on one side as expected a Substrate based blockchain keeps the state of consensus critical data only(balances, rates, escrows), and on the other side Matrix end-to-end encrypted chat rooms serve as a decentralized(enough) encrypted message storage where users can keep track of the swap state or any other interaction like saying hi! or uploading and re-uploading proofs of the off-chain transactions like photos or documents. As the rooms are encrypted messages remain private and the information left on-chain is very basic providing good level of anonymity.

![swap_flow](https://user-images.githubusercontent.com/1329925/127184696-797998d3-c073-41bd-9a43-3989e0ec107b.png)

Experienced users can host their own home servers and interact with the system directly with existing Matrix clients, or application builders can completely abstract the concept of the chat rooms (ab)using Matrix as a general purpose store for their users and community private&public data.  

Most of the complexity abstraction we mention comes from this integration of Substrate and Matrix, specially the Summa wallet that would allow transacting with users only knowing their MatrixID. Matrix has several mechanism already built for friendly handling private keys, like cross signing and trusting devices, backups etc. meaning Matrix users are allowed to lose their devices and still recover their chat history, when translating this to Substrate there are several paths to take but we can for example have each device key be converted to Substrate accounts that in turn control an anonymous proxy that is the actual main account of a user.

2021-07-27 17:58 UTC, semuelle commented
Thanks for the quick reply. The whitepaper being unavailable was a temporary issue with Cloudflare, apparently. 

This all sounds pretty good. Can you, just briefly, talk a bit about trusted third parties and disputes? What is the liquidity providers motivation to remain honest?

2021-07-28 00:32 UTC, BenWhiteJam approved these changes

2021-07-28 12:02 UTC, gautamdhameja approved these changes

2021-07-28 12:05 UTC, merged

2021-08-23 09:33 UTC, olanod commented
Following the suggestion of the good bot here, we might need an extra week of work for the first milestone since the holiday season took some productivity time away form us.

2021-08-23 09:50 UTC, semuelle commented
Thanks for the update, @olanod. No issue here. Keep us in the loop.

2021-11-27 13:05 UTC, alxs commented
@olanod could you give us an update on your progress? Note that since the first milestone is already very delayed and we previously asked you for an update, if we don't hear from you in the next 2 weeks we will assume you're no longer interested and terminate the agreement.

2021-11-29 11:19 UTC, olanod commented
I'm very sorry, somehow I missed the previous notice.  
We are very interested in continuing the agreement as we believe the **Virto.Network** and all our tools will be a great addition to the ecosystem, but perhaps we'll need a change of scope since some tasks were not well estimated and there have been lots of updates within the team and the protocol since the PLIP proposal. I just haven't reached out on purpose since we wanted to first get somethings right, like a formal description of **LIP**(Local Incentives Protocol), building the right team and in general have a good looking and compelling value proposition.

As the new white paper is still in the making and the whole implementation of the protocol is something large to accomplish in one single proposal, I would like to leave for consideration to have a our first grant proposal be about the implementation of the [**payments pallet**](https://github.com/virto-network/virto-node/tree/master/pallets/payment)(previously the escrow system) that has seen several changes in its design and development to fit the grand picture of what LIP is trying to accomplish. Lots of work has been put in the pallet already with only a few issues left to be solved, it is something concise enough to deliver in a timely manner and is general enough that can also benefit other projects in the Dotsama ecosystem.

2021-12-13 09:25 UTC, semuelle commented
Hey @olanod, sorry for the late reply. 
I cannot gauge from your description if the existing grant could be adapted to fit your new scope, but I think you should submit an amendment. You can rearrange and adapt the milestones. You will have to explain the changes and what let to them, and the grants committee will have to re-approve it, but if the changes are well explained and the scope doesn't change dramatically, it should be straightforward.

2021-12-13 09:43 UTC, olanod commented
I'll be submitting a new PR that supersedes this one explaining the changes and the updated scope.

2021-12-29 09:31 UTC, olanod commented
https://github.com/w3f/Grants-Program/pull/756 Here is the grant application for the **payments pallet**.