add hazelword.md
w3f/Grants-Program pull request #538
Opened 2021-07-28 08:11 UTC by ydong3

Project Name：Hazelword 
add add hazelword.md forW3F Grant Proposal

2021-07-28 08:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=538) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=538) it.</sub>

2021-07-28 11:46 UTC, Noc2 requested changes
Thanks for the grant application. However, we usually don’t support the development of solidity smart contracts via our grant program. On the one hand we are no experts when it comes to solidity, on the other hand there is a high chance that a similar contract already exists. Furthermore your deliverables are currently really unspecific. For example, what exactly do you mean with “TEE module”. The deliverables and the specification are basically the requirements of our contract and need to have enough details so that we are able to evaluate these deliverables.

2021-08-02 15:11 UTC, semuelle commented
@ydong3, @ywdlucking needs to sign the CLA, because they are the one that committed the file to your repo.

2021-08-03 02:55 UTC, ydong3 commented
Due to our reasons, it cannot be updated at #538, so keep to #551

2021-08-03 02:55 UTC, closed without merging