Update JuniDB.md
w3f/Grants-Program pull request #580
Opened 2021-08-17 15:30 UTC by andskur

https://github.com/w3f/Grants-Program/pull/466

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

2021-08-17 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=580) it.</sub>

2021-08-17 15:47 UTC, mmagician commented
@andskur You removed the key deliverable of Milestone 1. It looks like your milestone now only includes *forking* substrate, I don't see how we would pay $7,000 for this.

2021-08-17 16:12 UTC, alxs commented
@mmagician I think the purpose is to update [offchain::ipfs](https://github.com/rs-ipfs/substrate) to Substrate v3, or at least that's what I read from [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/254/files#diff-9fee4ec1fe0f082883f36b07b01dd6fe9b0d8804be9c694a35ce5c5820a53f4cR20). But @andskur I would first clarify that the team behind offchain::ips is ok with that (they may want to do this themselves soon) and I'd argue that your work should be merged into offchain::ipfs as part of the milestone instead of it just living in a separate fork.

2021-08-17 20:14 UTC, mmagician submitted a review, later dismissed
My bad @andskur @MikeMS-sys, I have somehow missed the connection between the delivery and this amendment. Makes absolute sense and as I had written before, I'm totally supportive of rejuvenating the offchain::ipfs repo.

2021-08-18 07:02 UTC, Noc2 submitted a review, later dismissed
Makes sense and https://equilibrium.co/ so far didn’t send us anything. So, I think they are busy doing other things.

2021-08-18 07:04 UTC, Noc2 commented
@andskur Btw. it looks like you still need to sign the terms and conditions.

2021-08-18 07:08 UTC, alxs requested changes

2021-08-18 07:08 UTC, alxs commented on applications/JuniDB.md
> +| 1. | Substrate fork | Substrate last version fork with fully updated version of offchain::ipfs. |
Sounds good. Could you mention this explicitly? 

```suggestion
| 1. | Update [offchain::ipfs](https://github.com/rs-ipfs/substrate) | We will coordinate with equilibrium.co to update offchain::ipfs to the latest Substrate version via PR to the existing repository |
```

2021-08-18 07:11 UTC, alxs commented
And could you please update the total cost and duration too?

2021-08-18 11:33 UTC, alxs approved these changes

2021-08-18 11:36 UTC, MikeMS-sys commented
Hi all,

@mmagician  It's ok )
@Noc2 Fixed it.
@alxs Made changes.

2021-08-18 11:58 UTC, mmagician approved these changes

2021-08-18 12:59 UTC, Noc2 approved these changes

2021-08-18 12:59 UTC, merged