Maintenance Grant Application Template
w3f/Grants-Program pull request #669
Opened 2021-11-01 16:58 UTC by enfipy

### Maintenance Grant Application Template

This is an example of the Maintenance Grant Application. Feel free to update or add any information to this template file.

Also, maybe we want to change the Development Roadmap example. I think it's a subject of change for most Projects that will apply for Maintenance Grant. Will highly appreciate any feedback.

2021-11-02 18:55 UTC, alxs requested changes
Thanks @enfipy, this is amazing.

My only suggestions would be that levels shouldn't apply to maintenance grants and also the development roadmap should probably be worded/structured a bit differently as this type of grant is meant to cover project maintenance in the stricter meaning (see #671, and also apologies as this was really not clear before).

Feel free to let us take care of the changes, I'm OOO until next week but maybe someone else will pick it up.

2021-11-03 08:23 UTC, Noc2 requested changes
Just an additional note here, also once @alxs is back. He can work on it: The development roadmap should mention that all code is published under an open source license during the maintenance period.

2021-11-03 12:43 UTC, enfipy commented
@alxs and @Noc2, thanks for clarifying these things! As you requested, I changed some parts and if you want to change something else - let me know :)

2021-11-03 15:11 UTC, semuelle commented on maintenance/application-template.md
> +Below we provide an **maintenance responsibilities**.
```suggestion
Below we provide **example maintenance responsibilities**.
```

2021-11-04 07:44 UTC, Noc2 approved these changes
Looks good to me. Thanks for all the work!

2021-11-04 10:37 UTC, semuelle approved these changes

2021-11-04 11:21 UTC, mmagician approved these changes

2021-11-04 11:22 UTC, merged