Add Venice Finance
w3f/Grants-Program pull request #752
Opened 2021-12-21 22:29 UTC by oliver-venice

### Project Abstract

Venice is a next-generation, Zero-Knowledge powered decentralized exchange, primarily focused on privacy preservation, front-running resistance, and cross-chain liquidity aggregation.
Venice utilizes advanced cryptography algorithms like Bulletproofs and Turbo-PLONKS to protect users from value extracting players and other malicious exploits while providing lightning-fast trades, minimal slippage, and maximum liquidity efficiency (Uniswap’s market making algorithm is implemented in V0 with future upgrades planned)

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

2021-12-21 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=752) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=752) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=752) it.</sub>

2021-12-22 19:14 UTC, semuelle commented
Thank you for your application, Oliver! We will look into it as soon as possible.

I noticed that your only milestone is named "Example" and the total cost and cost of the milestone(s) don't match. I assume that wasn't on purpose?

2021-12-22 19:54 UTC, oliver-venice commented
> Thank you for your application, Oliver! We will look into it as soon as possible.
> 
> I noticed that your only milestone is named "Example" and the total cost and cost of the milestone(s) don't match. I assume that wasn't on purpose?

Thank you. I correct these errors in our new commit. :)

2021-12-27 07:20 UTC, Noc2 requested changes
Thanks for the application. It seems to me that you are using findora for almost everything, which you describe in your application. Could you try to explain the substrate specific part a little bit more detailed? The way I understand it at the moment, is that you want to implement atomic swaps to your network and some kind of staking. Is this correct? How exactly do your atomic swaps work (off-chain, how will the substrate part be implemented, etc)?

2022-01-26 18:55 UTC, alxs commented
Closing due to inactivity. Feel free to reopen the PR if you're still interested.

2022-01-26 18:55 UTC, closed without merging