Grant application for Mixer RFP - Webb Technologies
w3f/Grants-Program pull request #830
Opened 2022-02-16 22:32 UTC by dutterbutter

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

2022-02-16 22:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=830) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=830) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=830) it.</sub>

2022-02-17 10:07 UTC, Noc2 requested changes
Thanks a lot for the application @dutterbutter. It's nice to see that you are still working inside the ecosystem. Given that the grant is above 100k. I suggest that we schedule a call. What’s your new email address or feel free to reach out to me via email.

2022-02-18 09:28 UTC, alxs commented
On hold pending pitch call and evaluation of the previous grant's last milestone.

2022-03-29 09:28 UTC, Noc2 commented
I’m going to close the application. If I remember correctly, the goal was to get this supported via the SBP. Let me know if I should reopen it.

2022-03-29 09:28 UTC, closed without merging