Application: Polkadot Collator Setup
w3f/Grants-Program pull request #905
Opened 2022-04-11 11:05 UTC by rharink

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

2022-04-11 11:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=905) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=905) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=905) it.</sub>

2022-04-11 11:06 UTC, rharink commented
Hi, I and some co-workers would like to apply for this grant. We only have a couple of questions/assumptions and want to check if these are correct.

- Can we assume that every parachain uses cumulus for its collator implementation? And if so may we assume the command-line arguments are the same for each of them?
- What are the preferred operating systems to run on? Should the Ansible playbooks be written in a cross-OS fashion?

2022-04-12 11:30 UTC, rharink commented
@takahser Thanks for the quick response.

> @rharink it seems like you copied the application template but didn't actually fill it with your information, is that correct?

Yes, correct, we'll update the information as soon as possible.

> Which Ansible playbooks are you referring to here?

The ones that we'll be writing for this grant. If we look at existing playbooks in the [polkadot-validator-setup](https://github.com/w3f/polkadot-validator-setup) repo. We see the assumption is a Debian variant (according to the usage of `apt`). Is support for Debian, Redhat, CentOS, etc. required? (because requirements might be different per parachain).

This would also mean Terraform templates could also vary per parachain. Should we take this into account when preparing for a PoC?

2022-04-13 14:48 UTC, takahser commented
@rharink atm I don't really understand, what you're planning to build, but it sounds a bit like this project: https://github.com/Nexus2k/polkadot-ansible. 
Also, the https://github.com/w3f/polkadot-validator-setup repo isn't actively [maintained](https://github.com/w3f/polkadot-validator-setup/blob/master/README.md).
Maybe it'd be helpful to elaborate a bit more on what you're planning to build, so I can get a better understanding.

2022-04-13 14:49 UTC, takahser requested changes
See my comment above ⬆️

2022-04-13 15:02 UTC, rharink commented
@takahser Oh, we're responding to the RFP: https://github.com/w3f/Grants-Program/blob/master/rfps/polkadot-collator-setup.md. I should have mentioned the link earlier 😅 sorry! We're figuring out what the prerequisites are before writing the actual proposal application. Is the RFP still relevant?

2022-04-20 09:16 UTC, mmagician commented
The RPF was written when not too many parachains had any collators running and would mostly run a minimally modified version of the substrate node.
It **might** still be relevant, although you'd need to do research of at least the most popular parachains to find out what their setups are, and whether they are somewhat compatible to be bundled into the same library, e.g.:
https://dev.kilt.io/docs/chain/collator/
https://wiki.acala.network/integrate/integration-1/collator

Ideally the project would involve collaborating with the projects themselves to figure out the exact requirements and whether they'd even benefit from such an effort. In case you decide to go down route, the support that the Grant Program can give you will likely be much higher than in the RFP.

2022-05-10 18:56 UTC, semuelle commented
Given the state of the application, I am going to convert this PR into a draft until it is properly filled out. Let us know if you need any input from our side, @rharink.

2022-05-11 11:40 UTC, rharink commented
Hey @semuelle, ok. I've been very busy lately 😅. I'll pick this up again soon. Thanks

2022-06-17 09:12 UTC, Noc2 commented
I’m closing this application due to inactivity. Let me know if I should reopen it.

2022-06-17 09:12 UTC, closed without merging