On-chain-cash amendment
w3f/Grants-Program pull request #907
Opened 2022-04-11 19:52 UTC by dsrdrk11a

### Project Abstract

While applying for the grant we've significantly corrected all the milestones and did not check the compliance of fields 0d-0e with the scope of work that was finally left in the milestone 1.
In Milestone 1 we don't deliver any executable files so there's no need in the docker file (0d line) as we see it. But we will provide a docker file in milestone 2. As for the 0e (article) - firstly it was only in the 3rd Milestone and when it was deleted we mistakenly added it to all left milestones, but we planned to write an overall article on the whole project.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

[#803]

2022-04-11 19:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=907) it.</sub>

2022-04-12 07:45 UTC, Noc2 requested changes
Looks good. But it looks like you still need to sign the latest CLA.

2022-04-13 08:47 UTC, dsrdrk11a commented
@Noc2 I'm confused how to do that. On the CLA-assistant page it shows me that I've already agreed to the CLA, but this sign doesn't appear here. I've even tried to delete my february's sign and make a new one, it appears in the list of my signed CLAs, but still a pending status here. Waited the whole day yeasterday - no updates.

<img width="876" alt="CLA signed" src="https://user-images.githubusercontent.com/98888366/163137244-4391c0ab-f499-4ae8-a250-c8732f5aa92c.png">
<img width="793" alt="Signed CLAs" src="https://user-images.githubusercontent.com/98888366/163137284-6ebdeb4d-be2b-4fdc-b9f0-f28483d4c99a.png">

2022-04-13 12:02 UTC, Noc2 approved these changes
Perfect. Thanks. I’m happy to go ahead with it.

2022-04-13 12:21 UTC, takahser approved these changes

2022-04-14 11:16 UTC, rrtti approved these changes

2022-04-14 12:19 UTC, merged