Fudge
w3f/Grants-Program pull request #917
Opened 2022-04-22 10:39 UTC by mustermeiszer

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

2022-04-22 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=917) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=917) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=917) it.</sub>

2022-04-27 08:00 UTC, Noc2 requested changes
Thanks for the interest in our grant program. This sounds like an interesting grant application. Let us know once we should take a look at it.

2022-04-28 21:16 UTC, mustermeiszer commented
> Thanks for the interest in our grant program. This sounds like an interesting grant application. Let us know once we should take a look at it.

@Noc2 We are still thinking whether to apply for w3f grant or on-chain treasury. Furthermore, I will be off for 2-3 months. are you fine with having this draft around here for that long? Otherwise, I will close it and re-open once this can progress faster.

2022-04-29 06:47 UTC, Noc2 commented
@mustermeiszer Thanks for the update. In this case, I will close it and you can ping me any time to reopen it.

2022-04-29 06:47 UTC, closed without merging