relation graph
w3f/Grants-Program pull request #920
Opened 2022-04-28 09:34 UTC by relationlabs

### Project Abstract

> `Rlation Graph` is a substrate pallet that allows anyone to use GraphDB in [Substrate platform](https://substrate.io/).
`Rlation Graph` provides organizations with ready-to-use GraphDB service for successfully running Dapps on the Substrate.  using `Rlation Graph` Dapps builders can focus on bussiness logic by removing the complexities of Substrate.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

2022-04-28 09:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=920) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=920) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=920) it.</sub>

2022-04-29 04:24 UTC, bornel approved these changes
checked，looks well

2022-04-29 04:46 UTC, shadow-001 approved these changes

2022-04-29 04:49 UTC, Notopponent approved these changes

2022-04-29 05:06 UTC, icp123 approved these changes

2022-04-29 05:06 UTC, icp123 commented on applications/Relation-Graph.md
> +`Rlation Graph` is a substrate pallet that allows anyone to use GraphDB in [Substrate platform](https://substrate.io/).
ok

2022-04-29 06:57 UTC, Noc2 requested changes
Thanks for the application. Sounds like an interesting project.  Something to be aware of, deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are mandatory for all milestones. Additionally you should add your actual deliverables as number 1 and following to this table and not only as headlines. Could you update this? Also are you aware of any similar projects?

2022-04-29 06:59 UTC, Noc2 commented
Btw. only [committee members](https://github.com/w3f/Grants-Program#w3f-grants-committee) can approve applications.

2022-05-06 13:09 UTC, closed without merging