Create phishfort_nighthawk.md
w3f/Grants-Program pull request #935
Opened 2022-05-10 10:42 UTC by tehnlulz

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

2022-05-10 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=935) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=935) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=935) it.</sub>

2022-05-10 15:31 UTC, Noc2 requested changes
Thanks for the application. To quickly already give you some feedback: We mostly fund open source software development as part of our grants program. The deliverables should therefore focus on technical deliverables that we can actually evaluate as part of the delivery process, see https://github.com/w3f/Grant-Milestone-Delivery These are basically the requirements of the contract and the specification should contain as many technical details as possible (e.g. programming language). We usually don’t support things like talent acquisition or launch marketing as part of our grants program. However, this is something the treasury potentially could fund, once you developed an MVP as part of grants. Also something to be aware of: the deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/pull/935) are usually mandatory for all milestones, and deliverable 0e at least for the last one.  Could you update this and let me know if you have any questions.

2022-05-11 07:31 UTC, tehnlulz commented
Hi @semuelle & @Noc2 - thanks very much for the feedback. Well noted and will clarify further and remove relevant areas that fall outside of the grants program. PhishFort is contributing to this financially too, so I will reduce the ask accordingly and make it work our end on the areas that aren't eligible for support.

2022-06-17 09:10 UTC, Noc2 commented
@tehnlulz what’s the status of this? Are you still planning to work on it and update the application? For now I’m going to close it due to inactivity, but let me know if I should reopen it.

2022-06-17 09:10 UTC, closed without merging