Add Keysafe application
w3f/Grants-Program pull request #947
Opened 2022-05-14 16:52 UTC by yyd106

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

2022-05-16 13:39 UTC, semuelle commented
Hey @yyd106. Thank you for your application! Your element handle seems to be missing your [homeserver](https://matrix.org/faq/#what-is-a-mxid%3F). Can you check?

2022-05-16 16:41 UTC, yyd106 commented
> 

@semuelle Thanks for reminding, it's fixed now.

2022-05-17 13:13 UTC, Noc2 requested changes
Thanks for the grant application. Could you make sure that both milestones contain the deliverables 0a-0d of the template. These are usually mandatory for all milestones, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Apart from this are you aware of Gluon (http://www.gluonwallet.com/#/), if I remember correctly, they were planning to do something similar. Also see https://github.com/w3f/Grants-Program/blob/master/applications/Gluon_decentralized_hardware_crypto_wallet_services.md

2022-05-18 13:51 UTC, Noc2 requested changes
Requested some additional changes on elements

2022-05-18 15:29 UTC, gautamdhameja approved these changes

2022-05-18 16:56 UTC, merged

2022-11-03 11:33 UTC, alxs commented
Hey @yyd106, any updates on the first milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

2022-11-24 17:08 UTC, alxs commented
@yyd106 friendly reminder

2023-03-13 03:33 UTC, yyd106 commented
> Hi @yyd106 how is milestone 2 coming along?

Hi @keeganquigley , Under the trend of Account Abstraction, a number of wallets and Dapps are planned to offer Social login, including the Clover wallet and zCloak in Polkadot ecosystem.

Instead of providing another social login wallet, our technology is more suitable as a generic protocol to provide a private and decentralized social login authentication for all the AA wallets and DApps.

Therefore we want to shift the milestone 2 goals to provide a privacy social login SDK. And have cooperation with Clover and zCloak.

2023-03-13 11:32 UTC, yyd106 commented
> Hi @yyd106 how is milestone 2 coming along?

BTW @Noc2 I saw the element group chat is disconnected. We you help to recover my connection?

2023-03-13 12:13 UTC, Noc2 commented
If you have a new account, feel free to contact me: @david:web3.foundation and I can add you to the group again.

2023-03-23 20:01 UTC, keeganquigley commented
Thanks for the updates @yyd106 do you plan to submit an amendment?

2023-03-24 02:36 UTC, yyd106 commented
> 

Yes we have this requirement. @keeganquigley

2023-04-17 20:05 UTC, semuelle commented
> Hi @yyd106 do you still plan to submit an amendment for milestone 2?

This grant was replaced by DAuth Network (see Element discussion). So we can probably cancel it now.

2023-04-17 21:53 UTC, keeganquigley commented
@semuelle ah thanks I see the conversation now, I will file the PR.