Stardust Algorithmic Stablecoin Proposal
w3f/Grants-Program pull request #967
Opened 2022-05-25 02:10 UTC by adit313

### Project Abstract

This is a follow on to our [stablecoin research project](https://github.com/w3f/Grants-Program/pull/865). After analyzing the failure modes of extant solutions and the collapse of Terra, we've identified the key weaknesses of those models. Specifically the inability to manage demand contractions and susceptibility to runs on the network that leads to a "death spiral" ultimately inflating the currency to nothing. In order to solve these weaknesses we have developed a new structure that tightly integrates the operations of the stablecoin with the market to redirect seigniorage profits into a treasury and then uses the stable cashflow coming out of the automatic investing operations of the treasury to compensate the bond token holders who ultimately underwrite the stability risk. This ultimately creates a stable demand and allows us to disincentive runs by allowing users to exit only by surrendering access to these future cash flows. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [x] Other: Previous Grant Recipient

2022-06-02 10:30 UTC, alxs commented
Hey @adit313, thanks for the interesting proposal and great research so far! I have a few questions about this approach, I hope it's fine if I challenge it:

- Do I understand it correctly that the entire supply is issued in response to heightened demand and sold in DEXs?
- Don't you think doing so plays against the stability of the price by creating sell-side pressure, since arbitrageurs can no longer speculate on the price increasing above 1 and can only profitably trade in below value, "de-pegged" ranges - hence decreasing liquidity around the peg?
- Also, you will be competing with arbitrageurs.
- What do you mean by the treasury's "dynamic APR rate"?
- Assuming the answer to 1) is yes, the supply will be backed solely by a basket of crypto-assets, which are highly volatile and correlated. It is very likely that at some point, the market value of these assets drops by more than the excess size + interest pool. What happens then? What really prevents a death spiral in all this? If the stablecoin de-pegs, everyone tries to redeem it for bondcoins and immediately sells those bondcoins, how won't you end up with 6 trillion worthless bondcoins? As soon as the market value of the assets in the reserves drops below the stablecoin market cap, a death spiral can still happen - it will just be delayed.
- Doesn't the treasury entirely depend on the assets it contains appreciating, apart from the small lending interest in the long run? How else can it reach the excess size?

2022-06-02 11:58 UTC, takahser commented on applications/algo_stablecoin_proposal.md
> +This proposal is in response to an RFP for an Algorithmic Uncollateralized Stablecoin (Specifically: https://github.com/w3f/Grants-Program/blob/master/rfps/uncollateralized-stablecoin.md).
```suggestion
This proposal is in response to an RFP for an Algorithmic Uncollateralized Stablecoin Research (Specifically: https://github.com/w3f/Grants-Program/blob/master/rfps/under_development/uncollateralized-stablecoin-research.md).
```

2022-06-02 11:58 UTC, takahser commented on applications/algo_stablecoin_proposal.md
> +This proposal is in response to an RFP for an Algorithmic Uncollateralized Stablecoin (Specifically: https://github.com/w3f/Grants-Program/blob/master/rfps/uncollateralized-stablecoin.md).
Note: We recently restructured the RFP directory which is why this link is outdated.

2022-06-02 15:27 UTC, takahser requested changes
@adit313 usually we [require](https://github.com/w3f/Grants-Program/tree/aab24bcf0cfce2e045c8fbc72b51ec35268bb17b#1-application) grantees to deliver the [Deliverables 0a-0d](https://github.com/w3f/Grants-Program/blob/aab24bcf0cfce2e045c8fbc72b51ec35268bb17b/applications/application-template.md#development-roadmap-nut_and_bolt) for each milestone, unless there is a specific reason not to do it. Your previous grant was exempt from that, since it was solely research-focused. The same goes for M1 of the current grant application, however with M2 and M3 to my understanding the main deliverables are code. Hence (unless I'm missing something) I think it makes sense to add these deliveries to M2 and M3.

2022-06-02 18:14 UTC, lamafab commented
Hey

Thanks for this proposal. I took a look at it and I'm trying to understand it, so the following comments are not mean to be critical but rather help clarify how your proposal works exactly.

***

The Open Market Operations lack quite a bit of detail. I'm not sure if it's a good idea to integrate with (existing) DEXes, instead of having the treasury put out offers that traders/arbitrageurs can buy directly (i.e. deposit assets in exchange for newly printed stablecoins, probably at a premium). But maybe this is meant here, I'm not certain. If it's the former, you must expand on:

* How the treasury deals with a liquidation crisis. Meaning: what happens if not enough assets can be bought.
  * (This somewhat also applies to the later)
* How the treasury deals with slippage.
* How the fees are managed.
  * It will require a consistent amount of funding to pay for gas.
  * What issues could occur during unusual/high trading activities (such as gas wars).
* How the DEXes are managed, whether those are fixed or can be modified via some sort of governance mechanism.

The lending part seems to imply that the treasury will lend out its stable assets to buyers directly, which has full control over the APR and adjusts it until all reserves have been deployed (collateralized, hopefully). Is there some sort of interval on how often the APR is increased? What decisions does the treasury make to set the APR?

Lastly, in case the stablecoins drops below the peg: you say that stablecoins can be burned in exchange for bonds, so I assume those bonds are newly printed. For this to work and not to scare off current bond holders, you must make sure that the treasury has enough stable asset reserves to cover the newly printed bonds + interest (is this were the "excess size" comes into play?). You describe:

> Not illustrated: The treasury, if it falls below the excess, claws back assets from the interest pool. The treasury has the ability to make uncollateralized, interest free loans from the stablecoin smart contract, which it can then loan out at a fixed interest rate. This functionality is not designed for long-term use, but more as a tool if the system needs to perform an emergency liquidity injection into the market for very short-term demand. (Note this is VERY complex economically and designed to function primarily as a way to control the interest rate of the stablecoin currency, similar to how central banks control overall USD interest rates. Due to its complexity, it must be a carefully managed process that is entrusted to the bondholders as it cannot be automated.)

I'm not quite sure I understand this part, it does not clarify what kind of uncollateralized, interest free loans the treasury takes from the stablecoin contract... I hope not _newly printed_ stablecoins while the price of the stablecoin is _below_ the peg? You're basically trying to give out newly printed stablecoins in exchange for stable assets while trying to convince (potential) bond buyers to burn their stablecoins in exchange for bonds, so now you have to create new loans of newly printed stablecoins in exchange for stable assets and the cycle continues... is this correct? This _VERY complex economically and designed function_ should be explained further.

In summary, please expand on:
* How the Open Market Operations will work exactly, respectively with whom the treasury will/should interact with.
* The lending mechanism.
  * How often and by how much does the treasury hike the APR?
 * Where this "excess interest" comes from.
* **Most importantly**: Explicit description of the asset type every time it's mentioned: stablecoin, bond or "stable asset" (DOT/ETH). While reading the proposal it was kind of hard to decipher what kind of asset type you're referring to in each section or sentence.

Also:

> Bondcoin supply can be burned at anytime for an equal % of the interest.

Principal + interest, you mean?

Maybe in general, a list of assumptions that you make for this system to work might be useful.

2022-06-02 23:43 UTC, adit313 commented
Hi Alexio, all good questions. They are all things we've put a ton of thought behind and we're happy to explain it in detail. Also, I appreciate you playing devil's advocate to every single one of our ideas and appreciate being challenged and having to prove the stability of the idea especially during contractions. The last thing I'd want to do is introduce risks for the general public and we need to deliver a solution that has been rigorously challenged and tested.

_Do I understand it correctly that the entire supply is issued in response to heightened demand and sold in DEXs?_
Exactly, we're trying to integrate it tightly with real financial infrastructure (DEXs) and perform the stabilization through open market operations so that it is transparent, automatic, and quickly reacts to real world market changes. One of our learnings with extant algo coins is that there was rapid and sizable appreciation in the price of Luna tokens because you could gain access to the minting arbitrage opportunity. However, that's a double edged sword that unwinds just as fast, characterized by the classic "death spiral" as users rush to the exit. We are redirecting these seigniorage profits into an automated treasury that can perform market stabilizing functions automatically instead of relying on the bond holders or the price of the token itself to insure that.  

_Don't you think doing so plays against the stability of the price by creating sell-side pressure, since arbitrageurs can no longer speculate on the price increasing above 1 and can only profitably trade in below value, "de-pegged" ranges - hence decreasing liquidity around the peg?_
You are correct that it creates less incentives for arbitrageurs (aka our bond token holders) as there is no immediate upside benefit like there was with Terra or still is with Waves. This is a purposeful choice. The primary design challenge of an algorithmic coin, in our opinion, is on the downside during market contractions. Printing money is easy, burning supply is the real challenge. Instead of realizing an immediate profit from seigniorage, our bond token holders instead realize a long-term, profit from excess investment interest from treasury operations, a process they are responsible for managing. 

In essence, the bondholders don't get the seigniorage profits immediately, and instead need to properly manage the treasury to continue to profit off the interest, a much slower process. In full transparency, I don't really have a good understanding for how bond holders value this tradeoff or if it will be sufficiently attractive. Obviously, most users prefer the immediate profit of seigniorage tokens, but the recent collapse of Terra demonstrates the converse risks of that strategy. Directing seigniorage profits to a smart contract controlled treasury allows our proposal to offer a fundamental utility of a profit stream to bond holders that could one day be several multiples of the immediate seigniorage profit, if they do a good job managing the network and hedging risk.

_Also, you will be competing with arbitrageurs._
Sort of, the treasury is designed to step in and issue new tokens when there is an overall imbalance in supply and demand at a market level. It's not planned to be implemented in such a way that the treasury is going to be trying to find opportunities for every pair where the price is >$1.00 USD generally. In the current design it is supposed to watch a few highly liquid, specific pools. A good hypothetical example would be something like 3Pool on Curve, but that choice of what pools it watches is ultimately down to the bondholders. Pool choice is important because it determines the makeup of the treasury, and as such should be carefully managed by the bondholders. All of the traditional arbitrage opportunities and movements across the 100,000s of other pools would be left to searchers on the market, it's not something the treasury is planning to compete with. Ultimately, if there is a consistent supply/demand imbalance, it should also show up in the largest pools where it will be caught by the treasury. If arbitragers can keep the price in large, liquid pools at $1.00, then there really isn't a need for any market operations.

_What do you mean by the treasury's "dynamic APR rate"?_
The treasury is by far the most complex construct. I used to be a banking analyst, and I know first hand the difficulty and time-consuming nature of making investing decisions. Deploying the funds of the treasury efficiently is a non-trivial task, and is difficult to do without any form of centralization. We could try to leave the process up to the bond holders, as they have a vested interest in making the most efficient allocations, but it needs to be highly streamlined as it would quickly become a full time job and become a very expensive process if investment decisions were made on-chain.

In order to solve this, the treasury itself needs to be smart enough to make investment decisions. I stole the logic of AMMs for this, but the treasury responds to market forces of supply/demand. Similar to other borrowing protocols, anyone can borrow treasury assets provided they post collateral. The APR they pay for this is dynamic and adjusts based on how far off the treasury is from a target deployment threshold set by the bondholders. This is very similar to how a traditional bank aims to deploy most of its funds at the highest APR it can manage. US banks are legally required to hold 10% capital in reserve, so let's say the bond holders set a similar 90% deployment ratio. The treasury dynamically changes APR based on how much of its capital is deployed. If it is failing to find borrowers and only 70% of its capital is borrowed, it automatically drops borrowing rates. If it has 95% of its capital deployed, it increases borrowing rates until 5% of capital is retuned. Bond holders are responsible for setting a target deployment ratio through a vote.

(This is primarily because we want to keep this automatic, decentralized, and algorithmically driven. This process can also be managed by a DAO that's takes charge of treasury deployment. Though there is a large trade-off in terms of centralization and autonomy.)

_Assuming the answer to 1) is yes, the supply will be backed solely by a basket of crypto-assets, which are highly volatile and correlated. It is very likely that at some point, the market value of these assets drops by more than the excess size + interest pool. What happens then? What really prevents a death spiral in all this? If the stablecoin de-pegs, everyone tries to redeem it for bondcoins and immediately sells those bondcoins, how won't you end up with 6 trillion worthless bondcoins? As soon as the market value of the assets in the reserves drops below the stablecoin market cap, a death spiral can still happen - it will just be delayed._

These are very good points and you are exactly right, the treasury will ultimately hold some basket of crypto-assets. I'm going to separate the death spiral and then address the real failure mode. First off, as far as we're concerned, death spirals are THE major problem of algorithmic stablecoins. Everything needs to be built to manage a recession or demand contractions. Our hope, is that by leaving the allocation of this crypto-asset basket up to the bond holders and only paying out interest to the bond holders if the treasury is above excess size, bond token holders will be able to manage it and respond to market dynamics with a better understanding of then-current market conditions than any pre-built algorithm can or we can set in the present. This however is not assumed, we assumed that at some point, perhaps consistently, they will fail to maintain the peg.

This proposal is primarily designed to manage what would be the ensuing run of a depeg through several separate mechanisms. Crypto-assets are notoriously volatile and can lose 20%+ overnight. Even slight volatility in stablecoin p [...]

2022-06-03 03:26 UTC, adit313 commented
Hi Fabio, don't feel bad, this model needs to stand up to intense scrutiny and it should be well thought out and have very defendable design decisions.

**_The Open Market Operations lack quite a bit of detail. I'm not sure if it's a good idea to integrate with (existing) DEXes, instead of having the treasury put out offers that traders/arbitrageurs can buy directly (i.e. deposit assets in exchange for newly printed stablecoins, probably at a premium). But maybe this is meant here, I'm not certain. If it's the former, you must expand on:_**

Yes, it's an equally valid idea to have a bidding system that offers out newly minted stablecoins that traders can buy directly, [in fact it's how the US treasury injects new supply](https://www.treasurydirect.gov/instit/auctfund/work/work.htm). The challenge in implementing a bidding model for us, is knowing how much stablecoin supply to inject. The US government has a flexible inflation target so it doesn't need the accuracy of our system, which is trying to anchor very closely to a peg. With a bidding or offer model, it is very difficult to figure out exactly how much supply to offer, and who should hold that decision power. Performing the operation on a DEX, you can look at the imbalance in the pool and calculate the size of the injection needed to bring the AMM back to parity. With the bidding system, it has a lot of room for error in the lot size, unless you offer unlimited stablecoins at a slight premium and let the market sort it out. However, if you went that route, the only time anyone would buy these tokens is when there is an arbitrage opportunity on the open market and they can turn around and inject it themselves into these pools for a profit. In which case you've distributed away some of your seigniorage profits to no advantage. 

I might be misunderstanding your model, or I've overlooked something. I'd love to hear what you were recommending in terms of a bidding or offering model, and what hesitations you have about integrating with existing DEXs. There are always oversights we haven't thought of. 

**_How the treasury deals with a liquidation crisis. Meaning: what happens if not enough assets can be bought._**

From our side, this isn't a real crisis as not being able to purchase enough assets simply inflates the price of the coin above $1. At that point, the bond holders would simply have to add new pools to be tracked for newly minted stablecoin, which would have the added advantage of diversifying its assets. Generally, if the price temporarily exceeds $1, it isn't really a major issue in this design as it is trivial to print more coins and issue them on the market, have the bond holders vote to just add a few more asset pairs and it'll figure it out. 

I'm reading deeper into your question and assuming it is, what is the threshold at which the open market operation causes too much slippage and buys tokens for far too high a price and how do you stop that. That's related to your next question.

**_How the treasury deals with slippage._**

When the smart contract mints new stablecoins and buys tokens on the DEX, it's only going to do so up until it hits parity with $1 USD. As an example, if the pool was our stablecoin:ETH on Uniswap, it would first query the Chainlink oracle to get the price of ETH:USD. Let's say it's $2,000 USD. It would then get the actual coins and liquidity in the watched pool and construct a trade such that the final coin of the order transacts at 2,000 Stablecoins for 1 ETH token. [We can look into the pool on Uniswap](https://ethereum.stackexchange.com/questions/83701/how-to-infer-token-price-from-ethereum-blockchain-uniswap-data) (Note: I'm aware there are some complications here if you are using V3 because it has smart routing, but I'm ignoring that for this quick example) and figure out the exact order size to bring it to parity and execute that amount. Obviously the transaction would be failed if that price was not possible. 

**_How the fees are managed. It will require a consistent amount of funding to pay for gas. What issues could occur during unusual/high trading activities (such as gas wars)._**

Our current implementation has the fees paid for by the initiator of the process. The bond holders are strongly incentivized to maximize the size of the treasury since this increases the interest flows, so they'll be responsible for initiating the process. If successful and over a sufficient proceed size the smart contract can refund the gas costs using some of the proceeds, otherwise the bond holder pays it as a penalty for a false initiation. By proportioning the "sufficient size" to the gas used hopefully the bond holders smartly manage unusual/high trading timeframes. 

**_How the DEXes are managed, whether those are fixed or can be modified via some sort of governance mechanism._**

The choice of DEXes, or more specifically the particular pools is left to the bond holders to decide. This has a major impact on the composition of treasury assets, and as such is up to the bond holders to manage and sequence in terms of priority. It's their job to manage and ensure the stability of the treasury and one of the primary ways to ensure that is to craft a well diversified portfolio of assets. 

**_The lending part seems to imply that the treasury will lend out its stable assets to buyers directly, which has full control over the APR and adjusts it until all reserves have been deployed (collateralized, hopefully). Is there some sort of interval on how often the APR is increased? What decisions does the treasury make to set the APR?_**

Investing decisions are very complex and can't be managed by the bond holders efficiently. Instead the bond holders set a "target deployment ratio". This is the targeted ratio of capital that should be deployed. The treasury updates a dynamic APR every fixed period, likely 8 hours based on perpetual best practices, in order to maintain this ratio. Too little capital deployed and it drops the APR, too much capital deployed and it increases it. In order to borrow the assets, users have to post collateral. APR changes work similarly to an AMM where it is an exponential curve based on how far from the target deployment ratio the current deployment ratio is. 

Also, depending on what the bond holders have decided, none, some, or all of this collateral must be denominated in the stablecoin itself. This gives the bond holders a tool to quickly increase demand for the stablecoin and lock it up, [similar to how central banks use the reserve ratio at banks](https://www.investopedia.com/terms/r/reserveratio.asp). Note: I personally would not advise keeping any requirement during normal market conditions as that would create artificial demand for the token, but ultimate control rests with the bond token holders.

**_Lastly, in case the stablecoins drops below the peg: you say that stablecoins can be burned in exchange for bonds, so I assume those bonds are newly printed. For this to work and not to scare off current bond holders, you must make sure that the treasury has enough stable asset reserves to cover the newly printed bonds + interest (is this were the "excess size" comes into play?). You describe:_**

"Scaring off" current bond holders is purposeful design decision. In extant solutions, these tokens had no utility and as such,  bankrupting current bond holders was seen to be a negative. In our solution, being a bond holder confers a responsibility to manage the treasury and ensure that it is well diversified and generating stable returns. In exchange for efficiently managing the network and fulfilling their obligations, they have the potential to receive a revenue stream. If they fail to properly discharge their duties, they lose their investment and will be quickly replaced by the newly minted bond holders. This is a know design feature and serves to ensure that the risk ultimately land on those with the ultimate responsibility.

> Not illust [...]

2022-06-03 03:27 UTC, adit313 commented
@takahser 

Our mistake, I just copied our old submission without thinking. We'll add those back in. :)

2022-06-03 08:47 UTC, lamafab commented
@adit313 Thank you for the quick response!

> A question for you on this is that a lot of these questions are very detailed and are more things we were planning to put into the design docs with pictures, charts and references instead of trying to squeeze it all into our proposal. Would you prefer that we go into this level of detail in the actual grant proposal? We thought it would be better in the design docs as there we can use diagrams and go into the full depth of the model.

I'm generally not involved in grant proposal, I was asked to take a look at this. So whether this information is sufficient I don't know. While I do remain highly skeptical of this proposal, I'm quite interested on where it might go. I'd fully support having you write a more enhanced design document and a working proof-of-concept/implementation.

> As this is still an experimental architecture and invites a ton of questions, we're also happy to pull together a presentation and jump on a call. It might be faster to cover it in 30 minutes with diagrams and talk through any potential oversights or limitations you see.

I'd happily join the talk, assuming we want to do that.

2022-06-03 09:23 UTC, alxs commented
On hold pending legal approval.

2022-06-03 18:07 UTC, adit313 commented
Hi Alexio, just saw the hold for legal approval. We obviously understand that uncollateralized algorithmically managed stablecoins are a highly sensitive space at the moment. In light of those sensitivities, do you think it makes more sense to pare back this proposal to just milestone 1 as a level 1 grant, with a very explicit caveat that it is a purely exploratory analysis being performed for research purposes? Dropping the code deliverables would help make it explicit that this is just a research exercise, and not a real attempt to actually build a stablecoin.

I obviously don't know what your legal team's specific sensitivities are, but we're happy to accommodate any concerns they have to the best of our ability. We're glad they are being brought in early in the process as we also feel that it's a politically sensitive space currently.

2022-06-05 10:04 UTC, takahser commented
@adit313 personally I do think that your suggestion to drop M2 and M3 could indeed increase the chances for this grant application to be considered compliant by our legal team. However, that's just my personal opinion and I'm definitely not a legal expert. For now, I think the best approach is to wait for our legal team's feedback and plan the next steps from there.

2022-06-07 16:36 UTC, adit313 commented
Sounds good, we'll be on the lookout for any updates.

2022-06-13 17:06 UTC, adit313 commented
@alxs, @takahser Hey there, any updates?

2022-06-14 08:45 UTC, takahser commented
@adit313 legal is still working on it, we'll get back to you as soon as we have an answer.

2022-06-23 09:02 UTC, takahser commented
@adit313 sorry for the delay here. I just received feedback from the legal team.

I'm quoting [your earlier comment](https://github.com/w3f/Grants-Program/pull/967#issuecomment-1146230591) here:

> (...) do you think it makes more sense to pare back this proposal to just milestone 1 as a level 1 grant, with a very explicit caveat that it is a purely exploratory analysis being performed for research purposes?

From a legal perspective, there's no problem with M1. Hence, limiting the grant to M1 and converting it into a level 1 grant would be the recommended way forward. Of course, you'd still need to reach a sufficient number (=2) of approvals from the grants committee to get the grant accepted.

2022-06-23 09:03 UTC, takahser commented on applications/algo_stablecoin_proposal.md
> +This proposal is in response to an RFP for an Algorithmic Uncollateralized Stablecoin (Specifically: https://github.com/w3f/Grants-Program/blob/master/rfps/uncollateralized-stablecoin.md).
@adit313 feel free to accept my fix :D

2022-06-24 16:27 UTC, alxs commented
@adit313 thanks a lot for the elaborate reply. That's quite a lot to dive into. In general, I have to say like Fabio I remain sceptical. I've highlighted a few passages where I see potential issues below, I'm trying to explain why I'm not convinced so please understand if I'm critical. I really enjoyed thinking about this and in principle, I like the idea.

> We are redirecting these seigniorage profits into an automated treasury that can perform market stabilizing functions automatically instead of relying on the bond holders or the price of the token itself to insure that.

These aren't "profits" in the first place - you'll likely be buying assets at, basically, market price and then you indeed don't rely on the price of your token to insure that, but on that of some third-party assets.

>  bond token holders instead realize a long-term, profit from excess investment interest from treasury operations, a process they are responsible for managing.

It's unclear to me where you intend for this capital to be invested - you talk about investment interest and a "diversified treasury portfolio", but you also clearly describe effectively launching your own lending platform later on ("similar to other borrowing protocols, anyone can borrow treasury assets provided they post collateral"). This would be an unrelated product whose risk stablecoin users would also need to carry. However that is, there will always be a risk involved, and I'm not sure the treasury would be able to generate enough interest to not only attract users but also make up for the risk of the entire thing.

> In essence, the bondholders don't get the seigniorage profits immediately, and instead need to properly manage the treasury to continue to profit off the interest, a much slower process.

Again, the treasury's performance will largely depend on the performance of a few selected crypto assets, not on the interest. The way it's currently described in the proposal, the profits in case these assets appreciate would also overflow into the interest pool and render the actual interest returns irrelevant once the excess size is reached. You also claim that "the treasury, if it falls below the excess, claws back assets from the interest pool", which means effectively these two pools are one and the same, and the whole system is a bet on one external variable, the market.

> The best way to increase that %, is to be the LAST person to burn your tokens when the peg has slipped the furthest, this would give you the largest proportion of interest bearing tokens.

Assuming they can only periodically be redeemed? Because otherwise, the last person to arrive may get the largest share of all tokens in the interest pool at the time they redeem, but by then it will have been reduced to pennies. And if they can only periodically be redeemed, that doesn't stop people from selling them in the open market until their market cap matches the value of the interest pool, which may even be empty if the treasury has "clawed back" the returns. You mention in your application that being able to exchange bond tokens for a share of the treasury pool "gives the bond tokens a material non-zero intrinsic value at any given moment", but that value seems to 1) not necessarily be non-zero and 2) be largely dependent on external factors, i.e. again the market.

> We've tried to break the incentive to run by instead using the interest payments to create a strong incentive to wait when the price depegs, as that will maximize the profits of a stablecoin holder. 
> In the long-run, the system attempts to close any deficit between treasury assets and the market cap of the stable coin through continued investing operations.

Again, that's not a strong incentive, and it will certainly not maximise the profits if it depegs, which would be the most natural outcome in case the assets in the treasury drop below the market cap. Liquidating these assets will cause them to drop further in value, exacerbating the problem, and only absorb sell pressure until they've been completely liquidated and the remaining stablecoin supply is unbacked, which is very much death-spiraly. By then, any long-run attempts by the system to "close any deficit" will not matter in the least.

> This is correct. Integral to the foundation of this proposal, is the assumption that the overall cryptocurrency industry will at a minimum shrink slower than the risk-free interest rate.

So if you'd launched half a year ago, the project would most certainly have ended in a death spiral? I don't understand how you can claim the project is "death-spiral resistant" and at the same time depend on an assumption that simply doesn't hold in the real world.

Even though I would certainly like to support an algorithmic stablecoin which eventually succeeds, and it is clear to me there's a lot of work behind this proposal apart from it certainly being novel approach, looking at this objectively I can't support any of the current milestones. However, I really enjoyed your previous research deliveries and I'd be more than happy to support more work along those lines, or if you'd like to implement something maybe you could work on something with less inherent risk? Feel free to pick a slot so we can chat [here](https://calendly.com/aleixo/grant-sync) or let me know if those don't work for you.

2022-07-02 20:08 UTC, adit313 commented
Hi Alexio, you are perfectly right, because the basket is only of crypto currencies, you'd never really be able to hedge against gross movements in the industry. All non-custodied stablecoins expereince this issue in their collateral pools. most solve it like MakerDAO does with PSM and USDC and allow for 1:1 redemption for a custodied stablecoin, but at that point, you haven't really solved any issues. That's the one thing we found during our state of the stablecoin report is that most of these projects have collateral from other projects until you get down to the two main collateral sources USDC or USDT. 

It's really hard to create a diversified portfolio with only crypto assets today without centralizing which is what we are trying to avoid. You are completely right, a crypto-only asset portfolio wouldn't work because every crypto asset is ultimately STRONGLY correlated to Bitcoin. 

One of the solutions we were thinking of is: can one diversify the portfolio with off-chain assets using synthetic products, kind of like what Mirror and Synthetix were attempting to do. This would allow you to bring things like bonds and stocks on chain, and ideally synthetic treasury bonds from multiple countries which would form a strong backbone of stability. We actually went to ETHGlobal NYC this past weekend and met with the founder of Sythetix and got some feedback on that idea. Ultimately, the issue becomes the collateral required to cover any movements in the price of crypto. The amount quickl becomes untenable and capital inefficient unless the collateral is in stablecoins with low collateral margins. There are a lot of open questions with that idea as even Synthetix haven't really made it work, and this would be highly experimental in a soon to be heavily regulated space, so we understand the hesitancy to pursue it at this time.

We'd love to follow up on future research projects with the team. After the hackathon, I had 2 weeks of weddings, but I should be free sometime the week of July 11th. I'll book some time later this upcoming week once I talk to Theresa and coordinate some mutual availability.

2022-07-05 09:42 UTC, alxs commented
Thanks for offering your perspective, I completely agree with your points. I also think that's an interesting approach to consider but also quite complex and not at all straightforward to implement. Sounds good, I'll put the application on hold for now.

2022-07-18 15:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=967) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=967) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=967) it.</sub>

2022-07-20 19:09 UTC, adit313 commented
Sounds good, just booked time for this Friday, let me know if that time suits, otherwise I can move it.

2022-08-03 08:40 UTC, alxs commented
@adit313 was great chatting with you last time, I hope all is well.

Here are again the two RFPs I shared during our call:

https://github.com/w3f/Grants-Program/blob/master/rfps/open/ISO_8583.md
https://github.com/w3f/Grants-Program/blob/master/rfps/open/ISO_20022.md

As I mentioned, we'd be interested in supporting research and/or implementation on how to integrate with these payment standards in Substrate. I think you'd be a great fit for these, but let us know in case you're still interested in pursuing the Stardust project instead or something else.

2022-08-03 16:19 UTC, adit313 commented
Hi Alexio, happy to help with the ISO-8583 and ISO-20022 RFPs. I've taken a look at the open source tools and projects that can help integrate them into Substrate. I have an early-stage implementation plan that integrates the JS open-source libraries for ISO-8583 into substrate as JS and Rust have good inter-compatibility. 

There is major issue though, Blockchains can't actually conform to ISO-8583. One of the most notorious and important events in a credit card is transaction reversals, colloquially called "chargebacks". The bane of every card accepting merchant, issuing banks and the networks themselves have full power to reverse transactions unilaterally. This kind of centralized control and authority doesn't exist within blockchains as finality is incredibly important to the consensus mechanism. [Satoshi himself was really against chargebacks, and instead prefered escrow accounts.](https://www.bitcoin.com/satoshi-archive/emails/mike-hearn/8/) 

Reversals are a HUGE part of ISO-8583. The 400 codes are all for reversals and that's a bigger strategic question of how the team would like to see those implemented. (Questions like "Do users have the ability to reverse transactions", "How long is the dispute window") Obviously, you can design a new token standard that is ISO-8583 compatible, but there are a lot of strategic questions. The strategic questions are really the hard part. In terms of coding, you'd just literally build a bridge from Rust to the [open-source JS implementation](https://github.com/zemuldo/iso_8583), no sense in reinventing the wheel when the users most likely to use this pallet will already be familiar with the JS implementation anyway.

The closer traditional financial analogue to blockchains are things like wire transfers, which are irreversible. [Those conform to ISO-15022 which seems like what is really being deprecated in favor of ISO-20022](https://www.redbridgedta.com/us/market-intelligence/swift-mx-migration/).

ISO-20022 is more broad and designed to work for generic financial exchanges including wire transfers, so it should be applicable to DLT and blockchains. However, even though I was just an analyst and didn't touch the tech stack at the bank, I completely agree with the ISO-8583 RFP language of "it might take some time before it’s actually fully replaced". There's no reason to "upgrade" to ISO-20022 for an institution for card payments or Mastercard/Visa and there is no deadline. As far as I've seen, the ISO-20022 is only really relevant for large European bank wires.

In terms of ISO-20022 compatibility, [none of the major blockchain players seem to be there](https://www.cryptopolitan.com/iso-20022-compliant-crypto-list/). I've taken a surface level look at their implementations, and it's seems to be a strategic decision because things like Ripple and Stellar are aiming to be at the interface of fiat and crypto, but everyone on the list is not exactly a traditional blockchain. [Impel recently "made bitcoin ISO-20022 compliant"
](https://www.yahoo.com/now/impel-adds-bitcoin-iso-20022-130000050.html) but it seems like more of a marketing stunt to get you to use the XDC network than anything material. Basically wrapped BTC tokens can be attached to ISO-20022 messages that are already on their XDC network. 

I really don't think their implementation makes sense, it seems like it's the equivalent of if I just made my own Substrate chain but the transaction objects were ISO-20022 compliant XMLs instead of the normal Substrate transaction objects. ISO-20022 isn't optimized for message size or retrieval so it would really impact performance. A far better solution is to just have an API you call when you need to convert a Substrate transaction to an ISO-20022 compliant XML for external use or vice-versa. The problem becomes blockchains like Polkadot can't support all ISO-20022 transactions [as there are reversals there as well.](http://www.iotafinance.com/en/SWIFT-ISO20022-Message-pain-007-001-Customer-Payment-Reversal.html)

If the team is open to it, I'm happy to pull together a deep dive for both as milestone 1. For ISO-20022 there is enough material for an in-depth summary on how competitors have integrated the standard, their limitations and what's likely to be the best implementation based on their experience. For ISO-8583, I can provide a summary of the strategic tradeoffs of implementing ISO-8583 in Substrate and a summary of the high-level decision you'd have to make regarding dispute windows, chargebacks, etc to create a compliant token standard.

2022-08-03 17:23 UTC, alxs commented
Thanks Adit, that was a fascinating read and it's clear you have a lot to contribute in this area. Regarding the reversals issue, leaving aside the philosophical aspect, it shouldn't be a problem to implement this on Substrate, as you say, as a new token standard using [ink!](https://ink.substrate.io/) or even as a pallet enabling a parachain to support transactions which are compliant with one of these standards.

I can't speak for the entire team, but as far as I'm concerned I'd be more than happy to support such a grant and if other team members have any feedback they can share it with you once you've submitted the application.

In the meantime, I'll go ahead and close this one. Feel free to reach out if you have any questions.

2022-08-03 17:23 UTC, closed without merging

2022-08-04 15:37 UTC, adit313 commented
Sounds good, I'll start by submitting a proposal for ISO-8583. Let me know if you'd prefer I start with ISO-20022 first.

2022-08-04 15:59 UTC, alxs commented
Great! I thought you meant both in one grant - however you prefer.

2022-08-04 16:33 UTC, adit313 commented
I can make them into one giant proposal, but the logistics of it are probably more complicated than I think you are expecting when you wrote the RFP. As an example, one of the super complicated aspects of it is going to be making it PCI-DSS compliant, ISO-8583 messages contain PAN numbers, i.e. your credit card numbers. You can't exactly store those on a publicly accessible blockchain ledger... or at least I personally wouldn't want my credit card numbers on a peer to peer blockchain. PCI-DSS compliance is currently voluntary compliance in EU and the US on a Federal level, but [states like Minnesota require you to delete the information within 48 hours.](https://www.revisor.mn.gov/statutes/cite/325E.64) 

I was thinking Milestone 1 for ISO-8583 was going to be work to identify and summarize all of these open challenges, and then research into how to logistically manage these requirements on the blockchain. Security/Reversals/Authority, the list goes on, and there are a lot of open questions that need some research to start making this work with decentralized ledgers. For example you could solve that privacy issue of revealing PAN numbers [with one time use virtual cards.](https://www.nerdwallet.com/article/credit-cards/what-is-a-virtual-credit-card-number) Or you can centralize, or maybe there is a decentralized solution. Obviously Visa/Mastercard/Baking just lock down the networks so only analysts can access the data with plenty of oversight, that's not quite going to work for blockchains.

ISO-20022 has some of the same issues, but it's not just credit card information so you'll have other things to worry about. That's why I think it makes sense to systematically approach this one at a time.

2022-08-04 18:17 UTC, alxs commented
That does sound like quite the rabbit hole. Makes sense, in that case I fully agree it's a better idea to focus on one thing at a time.

2025-02-03 21:20 UTC, adit313 commented
Reviving an old thread, hope you guys have been well. I was wondering if there was any renewed interest in pursuing this stablecoin idea? I've been working for the past 2 years under a National Science Foundation MEV-related research grant in distributed ledgers. Based on everything going on inside the government under the new administration, stablecoins are going to have strong legislative support and it seems like a great time to pursue this again. 

We had paused last time as Terra/Luna had collapsed and stablecoins were in a regulatory grey-zone. I think a fully decentralised stablecoin is going to be a great opportunity to pursue in 2025.