Datagen_Project
w3f/Grants-Program pull request #980
Opened 2022-06-06 10:23 UTC by Lord-Nymphis

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [ ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

2022-06-06 10:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Grants-Program?pullRequest=980) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=980) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=980) it.</sub>

2022-06-07 17:32 UTC, Lord-Nymphis commented
Well'll revert back ASAP in the next few days.
We'll have an answer also for milestone 1 and 2 (clarifications about the implementation of randomness traits and further implementations for milestone 2 VS reducing the milestone grant amount)
 Regarding the mockup we'll speak with our designers. You mean a simple FIGMA or similar, no front end code, right?

2022-06-08 14:19 UTC, viac92 commented
Hi @Noc2 Datagen developer here!

For the Milestone 1 we want to develop a pallet to manage the random selection of the nodes that have to check if the computational work (from other random selected nodes) has been done correctly.

So I think we need a custom pallet to manage the logic for this mechanism, maybe we could start with the babe pallet and modify it.

Let me know if it makes sense to you.

2022-06-09 11:12 UTC, Noc2 requested changes
Thanks for the quick reply. Yes, you need to develop your own pallet for this. You should probably take a look at 
https://docs.substrate.io/how-to-guides/v3/pallet-design/randomness/ 
https://github.com/paritytech/substrate/blob/master/frame/babe/src/randomness.rs 

I was mostly referring to the fact that the pallet at the moment seems to have only a single function according to the milestone, correct? And therefore it seems relatively expensive, so I would recommend either adding additional details to the delivery or reduce the price a little bit.

2022-06-27 07:39 UTC, Lord-Nymphis commented
Noc, you asked us to create a mock-up. It required some days. We also updated the Milestones as requested. We were waiting to have the mock-up to update all in one shot. OF COURSE you should reopen it.

2022-06-27 08:53 UTC, Noc2 commented
Got it. I wasn’t sure you are working on it, since you didn’t reply for 18 days. I will reopen the PR.

2022-06-27 08:58 UTC, Lord-Nymphis commented
Thank you very much @Noc2 , yea, sorry for not answering, we directly went back to work ... for us was implied that we were going to answer once we had updated the grant proposal, taking into account of all your suggestions. Sorry for not notifying that to you. :)

2022-07-01 09:23 UTC, viac92 commented
Hi @Noc2!

For milestones 1 and 2  we add more functionalities and explain them more in depth.
For milestone 3 we add a mock-up of the dapp.

If there are more things to change let us know :)

2022-07-01 11:41 UTC, Noc2 approved these changes
Thanks for the update. @viac92 could you also sign the CLA? All contributors need to sign it. Apart from this, I’m happy to support the project.

2022-07-07 15:03 UTC, Noc2 commented
Yes, correct. We changed the levels, but everyone who applied before the github commit, still needs the same number of approvals as before. So in your case 3 approvals.

2022-07-07 15:12 UTC, Lord-Nymphis commented
Thank you for the clarification @Noc2 , glad to hear it.

So we don't have to worry about the fact that in the right-upper part of the screen I see: "At least 5 approving reviews are required to merge this pull request."

As so, once we have three approvals the proposal is passed?

Do want us to remember you to do that manually if we have the three approvals (since is different from the general status of new applications)?

2022-07-07 15:16 UTC, Noc2 commented
Yes, you don’t need to worry about the 5 approvals. This is just because the github branch protection works like this. We will merge the application after three approvals.

2022-07-07 15:18 UTC, Lord-Nymphis commented
Grazie mille.

2022-07-07 17:11 UTC, semuelle requested changes
Thanks for the application, @Lord-Nymphis. Could you please replace the screenshots in the specifications under M3 with a list of functions or functionalities, so it's less ambiguous what is being delivered?

2022-07-07 17:15 UTC, Lord-Nymphis commented
Hi @semuelle . I think that would possible to add a brief description / comment of the functionalities below each screenshot.
( The screenshots represent the mock-up requested in the comments above by @Noc2 ).

2022-07-08 09:40 UTC, viac92 commented
Hi everyone, @semuelle I just push a new version for milestone 3 with a list of functionalities for every page of the dapp/explorer. 

Let me know if it's ok.

2022-07-08 09:43 UTC, viac92 commented
Also @Noc2 please check the new version :)

2022-07-11 06:48 UTC, Noc2 approved these changes

2022-07-11 15:49 UTC, cruikshankss commented
Good day @viac92,

I just reviewed your application. Forgive me if this is a dumb question but I have not yet studied any decentralized cloud computing projects. How is your proposal interoperable/related to IPFS standards? How is this interoperable/related to wasm standards? I know you are not storage, but rather processing. I'm just trying to understand how this all fits together big picture ideally in an ideal future web3 tech stack. Thanks!

2022-07-11 18:17 UTC, Noc2 requested changes
Sorry, I previously overlooked that you already did a token sale or you are in the process of doing one on BSC (https://www.b-datagray.com/token-sale). How is the purpose of this funding different from the grant? We generally want to ensure that teams are not getting funding for the exact same work twice, see [our guidelines](https://github.com/w3f/Grants-Program#guidelines) “We do not award grants for projects that have been the object of a successful token sale.”

2022-07-11 18:21 UTC, Lord-Nymphis commented
@semuelle @cruikshankss we'll answer tomorrow

2022-07-11 18:57 UTC, Lord-Nymphis commented
@Noc2 the token sale is relative to the Datagen token, that will be used as native token of the Datagen infrastructure. The grant is relative just to building the PoC. Token sales proceeds are being used for long term marketing programs, listing, etc. While the proceeds from the grants are being used to pay devs and team salaries.

Anyway we didn't have public sales, just private sales for our telegram community and a vested sale for some angels, VCs and SAFT.

The grant is being used to pay the devs to develop the PoC.

@Noc2  we had like 5 calls with your management, including Rohan, Surag, Santiago, etc...
 (after having some emails with Gavin, that looped in Bjorn, that didn't answered, so Gavin looped in Surag, that looped Santiago, that said us to do the Substrate Builders Program, than said us to apply to a grant, so that we can start building something with Substrate and later have a natural access way for the Substrate Builders Program and then to see the following steps).

It took 5 months to for the Parity team to give us the right instructions.

We have been super super clear that our main goal in approaching the Polkadot stack was to have a technical and strategical partnership and not for the money.

And @SBalaguer told us that starting with a grant was the right approach.

When you asked us to do the MockUp we had to anticipate 1K to our graphic designers (that work for us part time). It's ok, since is all good work for the project, but, please, try to take our work seriously.

We find very difficult to work in this way.

The fact that we have a utility token minted on BSC is clearly specified in the grant, when we have also said that our smart contracts are minted and audited.

B-Datagray is an incorporated company, with a full time team operating in the blockchain industry. Is so unreasonable that we have minted a token? 
How do you think that we pay our salaries.

Our main goal is with the grant is to open a part for a collaboration with the Polkadot stack. I get that is a tough moment. Do you want us to develop the object of our grant without receiving the grant money? 
Is not impossible.

Sorry @Noc2 if I am so direct, but please speak with @SBalaguer or others with whom we had calls, I find almost impossible to navigate the programs of you stack if you have a short circuit of communications between the members of your team.

Sorry again for being so direct, but we waited 3 months to be able to arrange a call with Sureg and Rohan, that took another month to direct us to Santiago, telling us that the right thing for our project was the Substrate Builders program. Santiago told us to do the grant. We had our devs and designers (and myself working on this), sorry and I hope that I don't feel rude to you @Noc2. I get that your applications are compartmentalized. But it becomes impossible to find a way to partner with the Polkadot stack, the impression is to be trapped in a giant bureaucratic machine, like applying to the motorization or something. 

Again, @Noc2, please don't take it as a personal attack, I have the maximum respect for your work and I immensely appreciate the attention that all the people of both the W3F and Parity Technologies are giving to our project and I think that I can speak for our whole team saying that we are all grateful for this, but I think that there is a serious short circuit in your communications. Again, not your fault, @Noc2 , but our first emails with @gavofyork have been in October 2021 and not even have been able to unravel the skein.

We are not playing. This is our project and our lifework and again, the token sales proceeds and the grant proceeds are used for a different scope.

To be legalistic, the #DG token is the utility token sale is the utility token of the functional infrastructure; while the grant is related to a local bc, a PoC, that will be open source, that will be available at benefit of the whole substrate community, and as a local bc, of course will be a different product from the mature Datagen infrastructure to whom the DataGen token is related. Consider the PoC (object of the grant) as a research program, more than the development of our Datagen infrastructure. Of course for us is useful research for our infrastructure, but the pallets that we are going to develop can be useful for a plethora of project in the Substrate community.

2022-07-11 19:37 UTC, Noc2 approved these changes
Thanks for the quick reply. I’m sorry to hear that you previously had a bad experience with some of Parity’s employees, potential miscommunication and/or responsiveness. But when it comes to the grants program, I merely try to focus on the technical scope (= milestones) of the project and the guidelines (e.g. preventing double funding of the exact same work) of the grants program and see if the open source software development as part of the grant could be useful for others. In this case, I’m still happy to support this research/development of the polkadot PoC.  

Just to clarify:
- No one can ensure that you get a grant. Not even me, since it’s up to the grants committee (in case this was previously miscommunicated). 
- Web3 Foundation doesn’t partner with anyone and a decentralised network like polkadot hasn’t partnered with anyone so far.

2022-07-12 10:25 UTC, viac92 commented
> Good day @viac92,
> 
> I just reviewed your application. Forgive me if this is a dumb question but I have not yet studied any decentralized cloud computing projects. How is your proposal interoperable/related to IPFS standards? How is this interoperable/related to wasm standards? I know you are not storage, but rather processing. I'm just trying to understand how this all fits together big picture ideally in an ideal future web3 tech stack. Thanks!

Hi @cruikshankss I think there aren't dumb questions (if you ask to learn something) but only dumb answers.

Actually we are in a very initial phase of our project and many things will be more define in the next future also with the support of the web3 developer community.

As you say, we wont to be a storage service so for the IPFS I think we might develop an API to interact with our service of cloud computing and the IPFS standards to work smoothly.

About wasm maybe I don't really get what you mean, sure for us the wasm runtime of the node is a big opportunity for developing fast and upgradable computational node and make easier interactions with blockchain and dapp.

Hope it isn't a dumb answer, let me know if you need more info!

2022-07-12 12:00 UTC, Noc2 commented
> BTW, @Noc2 having specified the difference between the development of the Datagen infrastructure and of the Substrate PoC that will be at the availability of the whole Polkadot community, do you still think that the existence of our #DG token would be invalidating for our grant proposal or (given the different scope of the infrastructure and of the PoC and having explained the specific role of the DataGen token, that is not a security token used to fund the development of the PoC, but the utility token that will be used to settle payments inside the Datagen infrastructure and that, only incidentally, is part of our revenue stream, but that is not it's reason to be) do you think that we can proceed?
> 
> Thank you for the clarifications.

I’m still willing to go ahead, otherwise I wouldn’t have accepted the PR. But this is just my personal opinion and others might disagree.

2022-07-12 12:43 UTC, Lord-Nymphis commented
> > BTW, @Noc2 having specified the difference between the development of the Datagen infrastructure and of the Substrate PoC that will be at the availability of the whole Polkadot community, do you still think that the existence of our #DG token would be invalidating for our grant proposal or (given the different scope of the infrastructure and of the PoC and having explained the specific role of the DataGen token, that is not a security token used to fund the development of the PoC, but the utility token that will be used to settle payments inside the Datagen infrastructure and that, only incidentally, is part of our revenue stream, but that is not it's reason to be) do you think that we can proceed?
> > Thank you for the clarifications.
> 
> I’m still willing to go ahead, otherwise I wouldn’t have accepted the PR. But this is just my personal opinion and others might disagree.

Sure, I understand. Thank you @Noc2

2022-07-13 00:24 UTC, cruikshankss commented
@viac92 Thank you for your response! Unless I'm misunderstanding, I don't see why wasm _wouldn't_ be a core part of your stack. I probably won't approve your application without you using wasm for the cloud computing, unless you convince me otherwise. Always happy to learn about a better way!

2022-07-13 05:42 UTC, viac92 commented
@cruikshankss yes we use wasm for cloud computing because we run cloud computing on chain on the node.

Sorry I thought it was clear in the application description.

2022-07-13 14:08 UTC, cruikshankss commented
> @cruikshankss yes we use wasm for cloud computing because we run cloud computing on chain on the node.
> 
> Sorry I thought it was clear in the application description.

That's why I said forgive me because this might be a dumb question. XD ... You didn't mention wasm or WebAssembly in your application (unless I'm wrong) and I thought it would be a very important and certainly noteworthy topic since imo wasm == the simplest form / the standard of cloud computing. My team just educated me that of course wasm is used natively in a substrate-based chain. Sorry for the dumb question!

2022-07-13 16:26 UTC, Lord-Nymphis commented
> > @cruikshankss don't worry I understand the misunderstanding and you are right too, maybe we need to make more explicit this part in the proposal, what do you think?
> 
> Thanks for understanding. I think in general, the more detailed the technical and business plan, the better. I personally look for details of deep technical expertise in proposals. For a cloud computing project, I'd ideally want to make sure you could easily integrate with cloud storage (IPFS), since that will be a common use-case that people will want to compute, then store. Also I evaluate the general feasibility of business strategy. Perhaps the most important consideration is how directly valuable the milestones would be to the larger open-source Polka ecosystem and the hypothetical ideal web 3.0 tech stack. If I see the milestones and business plan are more related to the success of an individual project rather than contributing to the collective, then I'm less inclined to approve. And please keep in mind I only represent one approval of this decentralized collective. :)

Thank you for the review @cruikshankss . I totally get your point about cloud storage being a very important product in pairing to cloud computing. However, cloud computing and cloud storage have different hardware requirements (for example performative GPU and CPU capacity VS drive space), as so, while interoperability in the offer of cloud storage and cloud computing services can be easily pursued by most traditional providers (Azure, AWS, Google VM or Stadia), that can easily reroute the user from servers optimized to storage to the ones optimized for GPU/CPU cloud computing, the same can't be done by networks that wish to decentralize the same services and do so with critical in-chain computing function. There are many reasons for this, but the main one is that decentralized cloud computing already suffers the lack of scale economy and efficiency of the sheer scale of AWS server farms (meaning that you need to work hard to provide additional value, to keep the computational inefficiency to a minimum and to aid the affordability with a reasonable token economic). If you add to this disadvantage (that can be overcome) the one of requiring to validators to have machines both performant in storage and in computing functions, basically you are digging a very deep grave for your network (either it becomes super expansive for the user or not profitable for the validator).

There is a reason why Web3 projects have focused either almost exclusively on cloud storage (see Filecoin) or on either almost exclusively cloud computing (see Golem or Akash). Is not like saying that you can't do both, but it's just not efficient.
Having said that, we think that a more viable solution for the Datagen network would be to have an API to integrate standards like IPFS and possibly partner with existing cloud storage projects (that are, on the opposite, are focusing Only on cloud storage and Not on cloud computing); sometimes, instead than trying to do everything in a mediocre way, is better to focus just on something, trying to do it in a good way and partner with possible complementary projects that are doing in a very good way things that you aren't.

@cruikshankss  We don't also exclude categorically that our stack will never ever host some integrated storage solution, we just say that is presently outside of the scope for the creation of the Datagen infrastructure. If we ever were to create a "Storagen" -I just came up with the world :)- we could salvage some R&D done for the Datagen infrastructure, but it would for almost for sure be a different stack, with a different set of validators and a different consensus protocol, albeit similar and integrated to the Datagen one.

I also must underline that the development of the mature Datagen infrastructure (and the go to market, user-base-building strategy) is outside the scope of the of the grant, that is just related to the construction of a local bc and the front end to test the correct functioning of the randomized consensus protocol operated by the customized substrate pallets that we'll create and  give to the opens source substrate community, hoping that they can be helpful to other projects, besides our own (maybe for uses different from the one we imagined for them: if this journey is teaching something to us is that learning and progress, both individual and collective comes from the ingenuity in the use of already existing stuff  and the willingness to see it with curious eyes).
The fact that we don't have all the answers about the characteristics of our mature infrastructure doesn't mean that we are walking in the darkness of ignorance, but just that we are aware that we have a ponderous quantity of R&D to do to build the Datagen network; Note, in the Years, not the Months to come. It would be a trivialization of the work that we still have to do, also, inevitably, of the work of people that still have to join our team if, just to give you the answer that we think you would like to hear, we were to answer you, with false certainty "we'll do this" or "we'll do that, for sure". I think that the future has the same dignity of the past and we need to give it the respect it deserves. Including the respect that our team must give to the work that we still must do. (As I bet you know, building a stack from scratch is not easy).

@cruikshankss I say these things not to try to change your mind, because I respect your professional opinion, but I also think that is my duty to show also our point of view on the matter. Of course we could be wrong about our stance on cloud storage, but it comes after observation and reflection, not out of ignorance or lack of reflection, so is important to give you the full picture of our point of view on the better.

Have a good day.

2022-07-13 17:27 UTC, cruikshankss approved these changes
@Lord-Nymphis Thank you for providing so much technical explanation of the problems you've conceptualized solving in the cloud-computing space and your future technological vision! I am approving this (one additional approval). I find I have to understand a project pretty deeply in order to have the confidence to approve the proposal, so thank you for answering my Qs. 

By the way, I am so sorry to make you type out so much, but thank you regardless! 

> a more viable solution for the Datagen network would be to have an API to integrate standards like IPFS

I believe this would be sufficient and I'm glad it's in your longer-term plan! I think an API to integrate IPFS standards is in line with [the w3f ideals mentioned here](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#i-am-starting-a-company-that--i-want-to-use-polkadotkusamasubstrate-to-build-a-blockchainparachain-and-connect--would-i-be-eligible-for-a-grant), perhaps for a follow-up grant if this application/grant is successful. 

Btw, also what took me a long time to think through was if your $BG token has true utility, but thank you very much for the explanation you gave @Noc2. I find it more complicated to assess applications when they include a native token and the tokenomics of course. :)

Additionally worth mentioning, I anticipate there may be some additional complexity in this potential grant & milestones with wasm, and so I would have liked to see more details about wasm in your milestones, but I realize it may be irrelevant, so I'm happy to approve the application as is! If you run into additional complexity, you can always attempt to amend your application with additional costs and technical details. ;-)

2022-07-13 17:38 UTC, Lord-Nymphis commented
> @Lord-Nymphis Thank you for providing so much technical explanation of the problems you've conceptualized solving in the cloud-computing space and your future technological vision! I am approving this (one additional approval). I find I have to understand a project pretty deeply in order to have the confidence to approve the proposal, so thank you for answering my Qs.
> 
> By the way, I am so sorry to make you type out so much, but thank you regardless!
> 
> > a more viable solution for the Datagen network would be to have an API to integrate standards like IPFS
> 
> I believe this would be sufficient and I'm glad it's in your longer-term plan! I think an API to integrate IPFS standards is in line with [the w3f ideals mentioned here](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#i-am-starting-a-company-that--i-want-to-use-polkadotkusamasubstrate-to-build-a-blockchainparachain-and-connect--would-i-be-eligible-for-a-grant), perhaps for a follow-up grant if this application/grant is successful.
> 
> Btw, also what took me a long time to think through was if your $BG token has true utility, but thank you very much for the explanation you gave @Noc2. I find it more complicated to assess applications when they include a native token and the tokenomics of course. :)
> 
> Additionally worth mentioning, I anticipate there may be some additional complexity in this potential grant & milestones with wasm, and so I would have liked to see more details about wasm in your milestones, but I realize it may be irrelevant, so I'm happy to approve the application as is! If you run into additional complexity, you can always attempt to amend your application with additional costs and technical details. ;-)

Np, @cruikshankss always a pleasure to have a mindful conversation. Thank you for the vote and for the tips. :)

2022-07-15 07:55 UTC, laboon approved these changes

2022-07-15 08:04 UTC, Noc2 approved these changes

2022-07-15 08:04 UTC, merged

2023-01-26 19:37 UTC, keeganquigley commented
Hi @Lord-Nymphis how is milestone 2 coming along?

2023-01-26 19:54 UTC, Lord-Nymphis commented
Hi  @keeganquigley , thanks for checking out!
We lost some weeks along the way because @viac92 , the dev that had done most of the work for Milestone 1 left us stranded after the end of M1 (he got an offer from a bigger company). Consequently, we lost a good part of December to find a new dev and he needed some weeks to get familiarity with the project. Now there is a new dev @cuteolaf (GitHub profile). Presently we are keeping work on a private repo. I think that we should put some work into our public grant repo in 2-3 weeks.

2023-01-26 20:40 UTC, keeganquigley commented
thanks @Lord-Nymphis delays generally aren't a problem, but if you think it will take longer than 2 weeks please submit an amendment to update the timeline. Thanks!

2023-01-27 10:30 UTC, Lord-Nymphis commented
You are welcome @keeganquigley. I think that two weeks is a little bit too tight in terms of the timeline for the final delivery of Milestone 2 (it could be not so much longer, but a little more, if we don't encounter particularly difficult problems).

What is the correct way to do the amendment? Directly in the grant proposal? Or somewhere else?

2023-01-30 17:41 UTC, cuteolaf commented
@keeganquigley Nice to e-meet you.

2023-01-30 18:05 UTC, keeganquigley commented
Thanks @Lord-Nymphis thanks for the update! I don't think that's an issue if it's just a week or so longer. But if you think it can't be delivered by the end of February I would recommend creating the amendment to take the pressure off.

Yep you can do this by creating a PR from the original grant proposal and then modifying the timelines (you can title it something like Amend Datagen). While you are at it you can also add @cuteolaf as a contributor to the team list. Hope that helps!

2023-01-30 19:02 UTC, Lord-Nymphis commented
https://github.com/w3f/Grants-Program/pull/1491 @Noc2 @keeganquigley I opened the pull request adding @cuteolaf as a contributor, as for the timeline update, I think that by late February we should be able to deliver Milestone 2. If we see within two weeks that February is not anymore a viable timeline we'll update also the timeline, with a new PR, what do you think about it?

2023-01-31 09:16 UTC, Noc2 commented
Sounds good.

2023-01-31 11:07 UTC, Lord-Nymphis commented
Ah, @Noc2 , I see that the pending Pull request needs 5 approvals, but, if you remember, our grant lev2 was approved with 3 approvals, with the old rules, we already discussed about this: https://github.com/w3f/Grants-Program/pull/980#issuecomment-1177775863

2023-01-31 12:32 UTC, Noc2 commented
See my last reply ;-) You don't need to worry about the number of approvals. GitHub doesn't allow us to set this up in a different way.

2023-02-07 20:00 UTC, cuteolaf commented
@Noc2 @cruikshankss 
I need your technical help for M2.
As you can see in the application, the main deliverables of M2 are the RPC methods and cross-chain communication between HB(heavy blockchain - parachain) and FB(fast blockchain - solochain).

After starting work on this project, I took a look at the application and did some research.

Me and @Lord-Nymphis agreed that 
- we will store the historical record of computational works done by FB nodes in the runtime storage of HB
  Of course, it's not recommended to store a growing list of data in the runtime storage, but for the demonstration purposes of M2, we believe it's understandable.
- implement RPC methods in the heavy blockchain
    Those will include
    - generate data for a check (a maths problem, the node to be checked, 3 checker nodes)
    - check if a node is reliable or not.
    - get historical records of computational works done by each FB node

And we have three types of messages between HB and FB.
- FB -> HB     list of computational works and their results
- HB -> FB     data for a check
- FB -> HB     results of computational works requested by FB

The problem is, how to implement the communication between HB and FB.

We now have two options - [Darwinia Bridge](https://github.com/darwinia-network/bridger) and Parity's [Para-solo bridge](https://github.com/paritytech/solo-para-bridge-poc)

If I have understood everything correctly, bridges are off-chain workers at their core, isn't it?

So could you please help us decide which repo to use or let us know another repo for implementing the communication between two substrate chains?

I had a chat with @NukeManDan and he told me that he is not aware of such projects so far.

Any tips or advice on this problem would be really appreciated.

2023-02-09 14:56 UTC, Noc2 commented
Thanks for reaching out. In general, it's up to you and depends on your use case and on things I might not be fully aware of. But I personally would probably reuse [parity's work and code](https://github.com/paritytech/parity-bridges-common). Given that there are plans for a bridge between polkadot and kusama and the code will highly likely be audited as well as maintained, etc.  Additionally, XCM will be supported, and BEEFY will be integrated for efficient verification. And finally, my main reason is that I simply know more about it the parity code than Darwinia's project. But from a quick look at it, it seems Darwina is definitely also something that you could use.

2023-02-10 19:12 UTC, Lord-Nymphis commented
Thank you @Noc2

2023-02-13 16:23 UTC, Lord-Nymphis commented
Hi guys ( @keeganquigley @Noc2 )!
 I think that a feasible deadline for us (Milestone2) is the 5th of  March, in the worst case 15th of March. 

Should we update the timeline in the grant proposal?

We shouldn't be very far from the end of February, but we may be a few days short.

2023-02-13 16:57 UTC, keeganquigley commented
Thanks for the update @Lord-Nymphis; In this case, I would recommend updating the timeline by submitting an amendment PR, since I'm assuming your third milestone will be delayed as well. This way you can extend it for both M2 & M3 and that will remove any added pressure for completing M3 as well (since technically M3 is due this month as well). I hope that helps!

2023-02-13 18:34 UTC, Lord-Nymphis commented
Thanks @keeganquigley for you recommendation. 
I just submitted a PR.
(date is march 15th for second milestone, just to be sure).

The timeline change is in the "Overview" paragraph of the grant application. 

https://github.com/Datagen-Project/Grants-Program/blob/Update-timeline/applications/Datagen_Project.md

2023-04-21 18:21 UTC, keeganquigley commented
Hi @Lord-Nymphis just checking in to see how M2 is coming along?

2023-04-24 10:04 UTC, Lord-Nymphis commented
Hi @keeganquigley , how are you?
Thanks for checking out. 
Unfortunately @cuteolaf can't handle the job and we are in the process of scouting new devs, again.

I can't give you a timeline until this is sorted out.
Timeline will mostly depend whether we can find a full time dev. Given the past two experiences we think that at this point for us is mandatory to work with a senior substrate dev for the milestone. As you know there is a shortage of substrate devs and is very difficult to find a senior substrate dev willing to work full time for just one month. We already found quite senior substrate devs that are willing to work on this, but, as you can imagine, being Senior Substrate Devs they already have a full time employment, they will be able to work on the milestone only part time and this would stretch a bit the timeline. We are currently seeing if we can shortcut it with a senior full time, otherwise we'll need to work with part time dev.

Probably by the end of the week we can understand if we are working with part time devs, in case we'll add him/them with a PR to the grant application

Thanks for checking on us regularly and for the patience. The last months haven't been easy on anyone in the industry, specially on smaller/ younger start ups.

2023-05-22 14:25 UTC, Lord-Nymphis commented
Hi @Noc2 and @keeganquigley . 

In the last few days we had a conversation with some of your colleagues of Parity (between them Coleman Maher) for the Parity VC introduction program; given the hardships that we are having with budget they also inquired whether was opportune for us to increase the W3F Milestone2 deliverable amount, by explaining that we underestimated the costs and adding more detail to the deliverables.

 Before eventually embarking in the procedure and eventually submitting a PR, I would like to inquire the concerning rules. 

If you remember, @Noc2 , I ask you in different occasions ( https://github.com/w3f/Grants-Program/pull/980#issuecomment-1177769588 ; https://github.com/w3f/Grants-Program/pull/980#issuecomment-1410164871 ) ;  whether for our 44K grant applied the old grant rules (up to 50K for a Lev.2 Grant) or the new ones (up to 30K for a Lev.2 grant) and you always answered that the old ones applied, given at the time of our applications ( https://github.com/w3f/Grants-Program/pull/980#issuecomment-1177775863 ; https://github.com/w3f/Grants-Program/pull/980#issuecomment-1410266476 ). In fact our grant was approved with the old rules.

You colleagues of Parity suggested that in case we were to ask for an integration of the second milestone of the grant, our grant would shift to a Lev.3, with all the implied consequences. 

So, questions:

1)Given that the total of our grant is actually 44K. If we were to ask an amount bigger than 6K, so exceeding the amount of 50K for the whole grant, would it need the approvals required for a level3?

2) Given the same premises, what happens if we were to ask an integration lower than 6K (for example, 5.990 USDC). Would it automatically shift to a Lev3 grant under the new rules, or would it be still considered a Lev.2, given that the cap of Lev.2 at the time of the application was 50K?

In case you say that everything shifts to lev.3 probably we will stick to the actual deliberated amount, even if we miscalculated the costs, because I imagine that shifting to lev3 would be too difficult. 

Looking forward and thank you for the support

2023-05-24 16:03 UTC, keeganquigley commented
Hi @Lord-Nymphis thanks for your patience while I confirmed the answers to your questions.

Essentially, any amendment PR asking for a change in price would fall under the new rules, since it is being filed after the change took place. Therefore:

1. An adjustment for an amount bigger than 50k would fall under level 3 according to the old rules as well as the new ones.
2. An adjustment for an amount under 50k would fall under the new rules, which would still bump it to a level 3, needing 5 approvals from the committee. 

If you defend your position with clear details about the changes in scope and costs, it's possible that the committee will agree and approve the PR. But as you mentioned, there is also the chance that the PR doesn't get approved by 5 members. I'll leave it up to you to decide whether or not you want to file the PR. I hope this helps to clarify!

2023-06-20 15:02 UTC, Lord-Nymphis commented
OfC, I created a pull request https://github.com/w3f/Grants-Program/pull/1810 

I leave above the text of the proposed amendment just for discussion purposes.

2023-09-28 21:32 UTC, keeganquigley commented
Hi @Lord-Nymphis do you think you will still be able to finish the grant?

2023-09-28 23:51 UTC, Lord-Nymphis commented
HI @keeganquigley . Yes, sure. 
The milestone delivery is almost completed. We just need to finish some work on the heavy chain client and then run the complete set up to see if the messages are running smoothly. Plus all the cosmetic stuff like the medium and the testing guide.

We took a very long time after we resumed the development in May, but must be said that many of the substrate dependencies we needed to use weren't up to date with the v1.0.0 and we couldn't really do much until someone in the Parity team fixed that. In fact we had also to be quite proactive and our lead dev @ysfkel in some cases had to directly propose some changes to some Parity repos and we had been in contact with different devs maintaining of those repos themselves. I could bore you to death with all the details, but I will not.
The important thing is that is almost finished.
If you want to take a preliminary look below we have the two repos in which we push most of the code for the grant.

https://github.com/Datagen-Project/Datagen-Substrate-Grant ; https://github.com/Datagen-Project/parity-bridges-common

2023-09-29 14:13 UTC, keeganquigley commented
Thanks for the update @Lord-Nymphis much appreciated! Sure I'll take a look.

2023-11-09 21:48 UTC, keeganquigley commented
Hi @Lord-Nymphis are you still planning on submitting a delivery soon?

2023-11-10 10:09 UTC, Lord-Nymphis commented
Hi @keeganquigley , we are planning to deliver soon, by mid December. The bridge setup is completed, we are finishing to complete the RPC methods.

2024-01-11 19:54 UTC, keeganquigley commented
Hi @Lord-Nymphis any updates you can provide?

2024-01-12 10:52 UTC, Lord-Nymphis commented
Ciao @keeganquigley , someone in the Parity team had the wonderful idea of discontinuing ( https://github.com/paritytech/parity-bridges-common/issues/2538 ) the Rialto Millau bridge repo, over which we had built the core functionalities of our solochain to parachain bridge. Thanks to that, we throw away a couple hundred hours of development and we had to refactor the entirety of our core functionalities (shifting to Westend - Rococo), which we are finishing to do.
If we didn't had to refactor we would have delivered the overall milestone by mid to second half of December.

Most of the refactoring had been done, but we are still getting some error when running the setup. We are working to fix everything.

2024-01-12 15:22 UTC, keeganquigley commented
Thanks for the update @Lord-Nymphis I appreciate you informing us on the situation. I will take note of this and consult with the team, perhaps we should create a new RFP to find a team who is willing to take over and maintain this repo. LMK if that is something your team would be interested in.

2024-01-12 15:25 UTC, Lord-Nymphis commented
Thanks. BTW our dev heard one of Parity devs that worked on the Rialto repo and told us it would have been outdated with the new SDK. Now we already refactored  almost everything.

2024-02-08 16:44 UTC, keeganquigley commented
Hi @Lord-Nymphis how did the refactoring go? Can you provide any updates?

2024-02-09 10:29 UTC, Lord-Nymphis commented
Hi @keeganquigley , thank you for asking!

The part concerning the heavy chain's refactoring is done and the blockchain is compiling, the part concerning the fast chain is still missing some features for some dependencies concerning the runtime, but they could potentially be fixed by the end of this weekend. 

After that the refactoring is done, with of course the bridge implementation to be done after that.

2024-03-07 20:53 UTC, keeganquigley commented
Hi @Lord-Nymphis any updates? I see that the two grant repos mentioned above haven't had any commits in around 6 months.

2024-03-08 09:48 UTC, Lord-Nymphis commented
Hi @keeganquigley . Yep. 

I think you have been looking into some old branches. The last update is two days ago. Here the most updated code branch https://github.com/Datagen-Project/Datagen-Substrate-Grant/tree/ln-update-testing-bridge

2024-03-08 15:48 UTC, keeganquigley commented
Thanks for the update @Lord-Nymphis does this mean a delivery will be submitted soon?

2024-03-21 19:15 UTC, keeganquigley commented
pinging @Lord-Nymphis

2024-03-22 11:12 UTC, Lord-Nymphis commented
Hi @keeganquigley 

Yes. Sorry for not answering, the message slipped through.
Yes, the answer is yes. As Soon As Possible.

2024-04-11 15:50 UTC, keeganquigley commented
Hi @Lord-Nymphis seeing as the delivery date keeps getting pushed, and there has been no delivery for a year and half, it's probably best to go ahead and close it at this point, and it can potentially be re-opened in the future should you wish to submit a delivery. This helps us for administrative & budgeting purposes. Let me know if this works, otherwise we'll close it in a few days. Thanks!

2024-04-11 16:14 UTC, Lord-Nymphis commented
Hi @keeganquigley , as previously explained, the company had budget constraints during the bear market and we had to change a few dev. There had been also the matter of Parity  discontinuing the support for the Rialto-Millau bridge repositories in November 2023 for the new SDK, meaning that we had to do everything from scratch starting from that date using the Rococo-Westend bridges.

Happy to help you with your administrative budgeting as long as this doesn't require going again through the approval procedure from the grant commission. 
We are actively working on the milestone and we have also already committed the payment to the dev working on it.

Let me know the best way to go ahead with this.

2024-04-11 16:25 UTC, keeganquigley commented
Thanks @Lord-Nymphis for the update. Is this dev already listed on the application as part of the team? Usually for core contributors we ask for any personnel changes to be amended on the original document.

2024-04-12 09:57 UTC, Lord-Nymphis commented
@keeganquigley No, he is not. The dev is the one that made the most recent contributions in this repo's branch https://github.com/Datagen-Project/Datagen-Substrate-Grant/tree/ln-update-testing-bridge

Now he is on leave for personal reasons. He should come back in 8 days.

What do you think, could we directly update the application document right before pushing the code for the milestone?

We also had another dev making some small contributions in December and we don't exclude to have others helping the current one with other contributions; to avoid updating the document multiple times and to have something more complete in terms of contributors, we could update right before submitting the Milestone code.

2024-04-12 13:40 UTC, keeganquigley commented
Sounds good, thanks @Lord-Nymphis let me consult with the team and will get back to you!

2024-04-17 16:55 UTC, keeganquigley commented
Hi @Lord-Nymphis thanks for your patience while we discussed internally; unfortunately the committee has unanimously decided to cancel the grant, mainly for the following reasons:

- No deliveries in 1.5 years
- M3 would likely be further delayed
- Many delays with not much progress other than minor fixes/updates
- Undocumented changes in scope
- Many personnel changes over the course of the project
- Changes would require another amendment which is not likely to be approved at this point

That being said, we thank you for all the time & effort you've put into this project and we wish you the best of luck in finding funding moving forward.

2024-04-17 17:04 UTC, Lord-Nymphis commented
Hi @keeganquigley 

We would like to know the procedure to reapply for the milestone delivery once delivered. Thanks

2024-04-17 17:10 UTC, keeganquigley commented
Sure thing @Lord-Nymphis yes it can always potentially be re-opened in the future should you have a delivery ready for submission. The procedure would essentially be the same as the regular application process, but in your case you would submit a PR to amend the contract to remove the terminated status. I hope that helps!

2024-04-17 17:11 UTC, Lord-Nymphis commented
@keeganquigley so basically it's like the milestone it's in standby?

2024-04-17 17:12 UTC, Lord-Nymphis commented
We would need to submit only the delivery or the application?

2024-04-17 17:18 UTC, keeganquigley commented
Yes, in this scenario you would need to submit two PRs, one for the application and one for the delivery. However it probably wouldn't be necessary to submit another application entirely, as [the current one](https://github.com/w3f/Grants-Program/blob/master/applications/Datagen_Project.md) will stay in our files, but with the added status. So you would just submit a PR amendment to change the status.

2024-04-17 17:22 UTC, Lord-Nymphis commented
So I will basically submit a pull request where I submit the Milestone (as per deliverable of the closed grant) and the request to reopen the Grant and approve the Milestone, all in the sam PR?

2024-04-18 18:06 UTC, Lord-Nymphis commented
@keeganquigley Yes, it's clear we don't have to submit the delivery in the milestone repo, but that the right procedure is to submit the application to the grant repo. 

 What I meant (ofc I have clear that the procedure requires the voting of the commission) is that, exactly because there had been delays with the delivery of the second milestone of the closed grant, it's pretty obvious that if we submit the application proposal without any code it would be rejected (I can't read in the committee's members' minds, ofc, but I presume it would be only logical), as so we would like to submit the application to the grant repo (requesting to re-open) together with the complete delivery of the second milestone of the previously closed grant, in good faith (understanding that then 1. the committee would have to update the grant status 2. only subsequently to the eventual acceptance of the status the milestone delivery could be approved).

2024-04-18 18:13 UTC, Lord-Nymphis commented
@keeganquigley 

Regarding https://github.com/w3f/Grants-Program/pull/980#issuecomment-2061764807

While we acknowledge that you are 100% right about us being late and we take full responsibility on this specific matter, and I understand that this point alone is sufficient for you to change the grant status, I would also like to underline that there has been NO undocumented scope in the grant deliveries. This is a factual error, which I would like to challenge (if I am mistaken, I would like to know in what regard).

2024-04-18 18:59 UTC, Lord-Nymphis commented
Also regarding this specific comment in the post https://github.com/w3f/Grants-Program/pull/980#issuecomment-2061764807 

> * Many delays with not much progress other than minor fixes/updates

I would like to underline that this is another factual error, given that our most recent code branch https://github.com/Datagen-Project/Datagen-Substrate-Grant/tree/ln-update-testing-bridge/heavy_blockchain/node/src
has 184 code commits and ≈5000 lines of code, EXCLUDING dependencies.

It's clear that we had deeply underestimated the task when submitting the grant proposal.
We also underlined above in the conversation that we thought that the original proposal was deeply below the budget, but continued to implement it nonetheless, considering that the original mistake was ours (but, as anyone who does development knows, sometimes you don't know how much work development will require until you really start doing it, especially for something as experimental as we are doing).
The market cost of a senior substrate developer is typically between 50 and 100 USD$. We had someone woking on this part time (20h week) for at least 1 year = 1000h of development, which means that the real cost to develop ONLY Milestone2 is between 50K and 100K USD. 
This is math, it's not my opinion.
We never asked for the full amount and we took the expense on ourselves, yet apparently the Web3 Foundation thinks that  it's possible to develop under budget AND in time AND without changing any personnel AND that 184 commits + 5000 lines of code are "minor-fixes / updates".
About 50% of our code commits had been unnecessary, given that we spent 6 months working with the Rialto-Millau Repo's, just to have the support for those suddenly cancelled by Parity in November (event totally outside of our control), and 0 help and 0 clarifications from Parity when asked how projects already working with those repos' had to behave. Meaning that we had to refactor everything and that of the 13 months of delay at least 5 or 6 are because of this issue.

I understand that you have a variety of problems with the restructuring of Parity and the W3F, but, at the same time, you can't expect small project to do the impossible and take the scorn.


I understand that you had already voted on the matter and that clearly for the W3F moving 12K from one row of the balance sheet to another is more important that retaining projects and having development for Substrate, so I don't expect you to reconsider.

I also understand that this isn't your fault, but that this is the policy of the W3F.

I only hope that these considerations will be taken into account when we will submit the PR (together with the code) in good faith.


Have a good day